### ISSUE TITLE
Support for installing repos without a package.json

### ISSUE THREAD

**Issue by johans** [yarnpkg/yarn#1011]
In npm there is this helper package napa (https://www.npmjs.com/package/napa) which enables one to install repos without a package.json file. Is this something you would consider adding support for in yarn?

**Comment by bestander** [comment]
Will be implemented in #2651.

**Comment by bestander** [comment]
duplicate #2621

**Comment by joshxyzhimself** [comment]
Hi, why is #1011 and #2621 reopened after #2651 got merged?

Thank you.

**Comment by joshxyzhimself** [comment]
Possible edge case.

This one below doesn't work, where `tradingview/charting_library` is a private repo, gets stuck on a continuous download (as seen in System Monitor, on Ubuntu Focal Fossa). Repo zipped is just `2.5 MB`, yet the download never ends.

```
yarn add ssh://git@github.com:tradingview/charting_library.git
```

---

However, this one below from a private fork works, after I added the `package.json` with the following contents; total download time is fast (as what is expected for a `2.5 MB` repo zipped)

```
{
  "name": "charting_library",
  "version": "0.0.0",
  "repository": "git@github.com:joshxyzhimself/charting_library.git"
}
```

```
yarn add ssh://git@github.com:tradingview/charting_library.git
```

**Comment by floviolleau** [comment]
Hi,

Sorry to comment an old issue but it seems to not be possible to do it with yarn v3.

```
Manifest not found
    at Function.find (/home/.yarn/releases/yarn-3.3.1.cjs:390:29961)
    at async /home/.yarn/releases/yarn-3.3.1.cjs:593:12212
    at async Object.Gbe (/home/.yarn/releases/yarn-3.3.1.cjs:390:8896)
    at async fQ.resolve (/home/.yarn/releases/yarn-3.3.1.cjs:593:12173)
    at async zf.resolve (/home/.yarn/releases/yarn-3.3.1.cjs:391:1400)
    at async zf.resolve (/home/.yarn/releases/yarn-3.3.1.cjs:391:1400)
    at async /home/.yarn/releases/yarn-3.3.1.cjs:439:6346
    at async Ff (/home/.yarn/releases/yarn-3.3.1.cjs:390:8959)
    at async Z (/home/.yarn/releases/yarn-3.3.1.cjs:439:6328)
```

Any ideas?
Thanks

**Comment by SKYBITDev3** [comment]
I updated yarn to v3.6.1 and got "Manifest not found" error. Please fix it ASAP.
