### ISSUE TITLE
yarn team ls throws an error if you don't specify a team name

### ISSUE THREAD

**Issue by danielmcgraw** [yarnpkg/yarn#1018]
Yarn throws an error do team ls without giving a team name. I would have expected a helpful message letting you know your missing a team name and possibly even how to add a team.

```
$ yarn team ls

error TypeError: Cannot read property 'split' of undefined
    at explodeScopeTeam (~/.npm-packages/lib/node_modules/yarn/lib/cli/commands/team.js:41:23)
    at ~/.npm-packages/lib/node_modules/yarn/lib/cli/commands/team.js:68:21
    at next (native)
    at step (~/.npm-packages/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at ~/.npm-packages/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at Promise.F (~/.npm-packages/lib/node_modules/yarn/node_modules/core-js/library/modules/_export.js:35:28)
    at ~/.npm-packages/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at ~/.npm-packages/lib/node_modules/yarn/lib/cli/commands/team.js:87:19
    at Object.<anonymous> (~/.npm-packages/lib/node_modules/yarn/lib/cli/commands/_build-sub-commands.js:20:27)
    at next (native)
```

**Comment by nik-john** [comment]
This is not true anymore in version 0.15.1

```
yarn team
yarn team v0.15.1
error Usage:
error yarn team team create <scope:team>
error yarn team team destroy <scope:team>
error yarn team team add <scope:team> <user>
error yarn team team rm <scope:team> <user>
error yarn team team ls <scope>|<scope:team>
error Invalid subcommand. Try "create, destroy, add, rm, ls"
info Visit http://yarnpkg.com/en/docs/cli/team for documentation about this command.
```

**Comment by wyze** [comment]
After investigating a little further, it looks like this error is thrown for any `yarn team` command when then first argument isn't provided after the command you want to run. I have a PR incoming in a few minutes that will address the error.
