### ISSUE TITLE
Is cafile config ignored in .npmrc ?

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [yarnpkg/yarn#1041]
nodejs v4.4.7

My .npmrc file have `cafile=/cert/file/path.crt`
But Yarn seem to ignore it.

refer the below error log

```
yarn add v0.15.1
info No lockfile found.
[1/4] Resolving packages...
error unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1017:38)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:582:8)
    at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:424:38)
info Visit http://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by FLGMwt** [comment]
Which .npmrc file? Can you run `yarn config list` and dump the output?

**Comment by kittens** [comment]
We don't currently support `cafile`. We have #736 open that should be merged soon.
