### ISSUE TITLE
TypeError: uid must be an unsigned int

### ISSUE THREAD

**Issue by danieljoppi** [yarnpkg/yarn#1056]
This error happen when I just install Yarn

``` bash
sudo npm install -g yarn
```

```
npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.7.0/bin/node" "/usr/local/bin/npm" "install" "-g" "yarn"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
```

see the `npm-debug.log`

```
12050 verbose stack TypeError: uid must be an unsigned int
12050 verbose stack     at TypeError (native)
12050 verbose stack     at Object.fs.chown (fs.js:1190:11)
12050 verbose stack     at Object.chown (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:231:17)
12050 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
12050 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
12050 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
12050 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:211:18
12050 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
12051 verbose cwd /Users/daniel.joppi/Documents/
12052 error Darwin 15.6.0
12053 error argv "/usr/local/Cellar/node/6.7.0/bin/node" "/usr/local/bin/npm" "install" "-g" "yarn"
12054 error node v6.7.0
12055 error npm  v3.10.8
12056 error uid must be an unsigned int
```

**Comment by sandaemc** [comment]
Any workaround?
