### ISSUE TITLE
Empty license Field in package.json causes failure

### ISSUE THREAD

**Issue by kkerr1** [yarnpkg/yarn#1070]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Run `yarn` command on a project that has an empty string `"license": ""` in it's package.json. The following error is returned. Removing the the `"licence"` property entirely or changing it to a non-empty string solves the problem. 

```
error TypeError: speedtest-intelligence-client@0.0.1: Cannot read property 'toUpperCase' of undefined
    at Array.<anonymous> (/Users/kevinkerr/.nvm/versions/node/v6.8.0/lib/node_modules/yarn/node_modules/spdx-correct/index.js:82:23)
    at validTransformation (/Users/kevinkerr/.nvm/versions/node/v6.8.0/lib/node_modules/yarn/node_modules/spdx-correct/index.js:173:36)
    at module.exports (/Users/kevinkerr/.nvm/versions/node/v6.8.0/lib/node_modules/yarn/node_modules/spdx-correct/index.js:215:21)
    at module.exports (/Users/kevinkerr/.nvm/versions/node/v6.8.0/lib/node_modules/yarn/node_modules/validate-npm-package-license/index.js:60:23)
    at isValidLicense (/Users/kevinkerr/.nvm/versions/node/v6.8.0/lib/node_modules/yarn/lib/util/normalize-manifest/util.js:16:10)
    at exports.default (/Users/kevinkerr/.nvm/versions/node/v6.8.0/lib/node_modules/yarn/lib/util/normalize-manifest/validate.js:53:55)
    at /Users/kevinkerr/.nvm/versions/node/v6.8.0/lib/node_modules/yarn/lib/util/normalize-manifest/index.js:56:51
    at next (native)
    at step (/Users/kevinkerr/.nvm/versions/node/v6.8.0/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/kevinkerr/.nvm/versions/node/v6.8.0/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Run `yarn` command on a project that has an empty string `"license": ""` in it's package.json

**What is the expected behavior?**

Yarn will install dependencies. 

**Please mention your node.js, yarn and operating system version.**

Node 6.8, Yarn v0.15.1, MacOS Sierra, 10.12

**Comment by samccone** [comment]
Dup of #646 thanks for the report!
