### ISSUE TITLE
Getting error installing a global package.

### ISSUE THREAD

**Issue by hamzatrq** [yarnpkg/yarn#1075]
I am using yarn 0.15.0 on Ubuntu 16.04.1.
While trying to install angular-cli beta 17 (latest - as of today), I am getting this error. I have tried it a few times but got this error each time. npm works fine.

`yarn global add angular-cli@latest`

`error https://registry.yarnpkg.com/connect-history-api-fallback: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at TLSSocket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)
info Visit http://yarnpkg.com/en/docs/cli/global for documentation about this command.
`

**Comment by bestander** [comment]
This is probably fixed now.
Could you reproduce on latest version of Yarn please?
