### ISSUE TITLE
Install has error with Ubuntu 16.04

### ISSUE THREAD

**Issue by TianyiLi** [yarnpkg/yarn#1155]
I tried to install the modules with yarn on my Ubuntu 16.04.
Then after the command "yarn install" , it appears the error to me.

```
error SyntaxError: ~/.yarn-cache/npm-supports-color-2.0.0/.yarn-metadata.json: Unexpected end of JSON input                                         
    at Object.parse (native)                                                                                                                                   
    at Object.<anonymous> (/usr/local/lib/node_modules/yarn/lib/util/fs.js:260:54)                                                                             
    at next (native)                                                                                                                                           
    at step (/usr/local/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)                                                    
    at /usr/local/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
```

And the environment info

node 6.7.0
yarn 0.15.1
Ubuntu 16.04

**Comment by TianyiLi** [comment]
OK I think I got a authority problem....
