### ISSUE TITLE
Error: EPERM: operation not permitted, rename 'C:\Users\user\.config\configstore\typings.json, typings install error, Command: C:\Windows\system32\cmd.exe Arguments: /d /s /c typings install broken Administrator privileges

### ISSUE THREAD

**Issue by carmelone** [yarnpkg/yarn#1240]
**Do you want to request a *feature* or report a *bug*?**
bug (I think)

**What is the current behavior?**
After `yarn` command I have many packages that need many typings, so in every package I have a "postinstall": "typings install". But I got this:

```
[4/10] ⢀ my-package-with-typings
error C:\Users\user\Desktop\Temp\node_modules\my-other-package\node_modules\my-package-with-typings: Command failed.
Exit code: 1
Command: C:\Windows\system32\cmd.exe
Arguments: /d /s /c typings install
Output:
C:\Users\user\AppData\Roaming\npm\node_modules\typings\node_modules\configstore\index.js:70
                                throw err;
                                ^

Error: EPERM: operation not permitted, rename 'C:\Users\user\.config\configstore\typings.json.3579867660' -> 'C:\Users\user\.config\configstore\typings.json'
    at Error (native)
    at Object.fs.renameSync (fs.js:809:18)
    at Function.writeFileSync [as sync] (C:\Users\user\AppData\Roaming\npm\node_modules\typings\node_modules\write-file-atomic\index.js:81:8)
    at Object.set (C:\Users\user\AppData\Roaming\npm\node_modules\typings\node_modules\configstore\index.js:63:21)
    at Object.Configstore (C:\Users\user\AppData\Roaming\npm\node_modules\typings\node_modules\configstore\index.js:28:11)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\typings\node_modules\typings-core\dist\utils\store.js:5:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**What is the expected behavior?**

yarn should install everything good as If I go with `npm i`

**Please mention your node.js, yarn and operating system version.**

node 6.9.0
npm 3.10.8
yarn 0.16.0 (latest now)

**Comment by no-more** [comment]
I have the same issue on windows 10, not sure if it's related.
Do you have any workaround ?

Thanks

**Comment by leobeta** [comment]
I have the same with win 10, Windows sucks badly!

**Comment by Preethy77** [comment]
I am having the same issue when I am trying to install typings on my windows 10 . Is there any solution to this?

**Comment by Karl-Gustav** [comment]
According to this bug in the [typings](https://github.com/typings/typings/) repository the `C:\Users\<user>\.config\configstore\` folder might be set to "read only" on Windows: https://github.com/typings/typings/issues/530

**Comment by Naved-Biz4** [comment]
Thanks @Karl-Gustav. `C:\Users\<user>\.config\configstore\` was set to read only somehow. Deselecting the checkbox and applying changes has solve my issue.

**Comment by deveras** [comment]
Hello, as per local security policies i do not have rights to remove the read only, would it be possible to use a temporary folder?

**Comment by bliotti** [comment]
I have the same issue as  @deveras
