### ISSUE TITLE
Cannot use 'in' operator to search for '^4.14.34' in undefined

### ISSUE THREAD

**Issue by VsLoureiro** [yarnpkg/yarn#1241]
Do you want to request a feature or report a bug?

Bug

What is the current behavior?

Doesn't add packages.

If the current behavior is a bug, please provide the steps to reproduce.

Run $ yarn

What is the expected behavior?

Should install all my dependencies in package.config

Please mention your node.js, yarn and operating system version.
node.js: v4.6.0
npm: 3.10.8
yarn: 0.16.0
Windows: 7

Log:

Trace: 
  TypeError: Cannot use 'in' operator to search for '^4.14.34' in undefined
      at C:\Users\vloureiro\AppData\Roaming\npm\node_modules\yarn\lib-legacy\resolvers\registries\npm-resolver.js:74:24
      at next (native)
      at step (C:\Users\vloureiro\AppData\Roaming\npm\node_modules\yarn\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
      at C:\Users\vloureiro\AppData\Roaming\npm\node_modules\yarn\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14
      at new Promise (C:\Users\vloureiro\AppData\Roaming\npm\node_modules\yarn\node_modules\core-js\library\modules\es6.promise.js:191:7)
      at C:\Users\vloureiro\AppData\Roaming\npm\node_modules\yarn\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12
      at Function.findVersionInRegistryResponse (C:\Users\vloureiro\AppData\Roaming\npm\node_modules\yarn\lib-legacy\resolvers\registries\npm-resolver.js:84:7)
      at C:\Users\vloureiro\AppData\Roaming\npm\node_modules\yarn\lib-legacy\resolvers\registries\npm-resolver.js:101:34
      at next (native)
      at step (C:\Users\vloureiro\AppData\Roaming\npm\node_modules\yarn\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)

This happens when I try to install dependencies from @types/xxxx all the others work ok
This particular the dependency was @types/lodash

**Comment by ecozoic** [comment]
I'm getting this issue when installing @angular/xxx packages.

```TypeError: Cannot use 'in' operator to search for '2.1.0' in undefined```

**Comment by wyze** [comment]
Solved by #1356.
