### ISSUE TITLE
Error installing scoped packages

### ISSUE THREAD

**Issue by montogeek** [yarnpkg/yarn#1245]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
While trying to install `"@kadira/storybook": "2.2.1"`, installation fails
**If the current behavior is a bug, please provide the steps to reproduce.**
Add `"@kadira/storybook": "2.2.1",` to dependencies
Run `yarn`
**What is the expected behavior?**
Install `kadira/storybook`
**Please mention your node.js, yarn and operating system version.**
Yarn version:
  0.16.0

Node version:
  5.3.0

Platform:
  darwin x64

**Stack trace**
<details>
```
yarn manifest:
  No manifest

bower manifest:
  No manifest

Lockfile:
  No lockfile

Trace:
  Error: https://registry.npmjs.org/@kadira%2fstorybook: Could not authenticate montogeek
      at Request.params.callback [as _callback] (/Users/montogeek/.nvm/versions/v5.3.0/lib/node_modules/yarn/lib/util/request-manager.js:294:18)
      at Request.self.callback (/Users/montogeek/.nvm/versions/v5.3.0/lib/node_modules/yarn/node_modules/request/request.js:187:22)
      at emitTwo (events.js:87:13)
      at Request.emit (events.js:172:7)
      at Request.<anonymous> (/Users/montogeek/.nvm/versions/v5.3.0/lib/node_modules/yarn/node_modules/request/request.js:1048:10)
      at emitOne (events.js:77:13)
      at Request.emit (events.js:169:7)
      at IncomingMessage.<anonymous> (/Users/montogeek/.nvm/versions/v5.3.0/lib/node_modules/yarn/node_modules/request/request.js:969:12)
      at emitNone (events.js:72:20)
      at IncomingMessage.emit (events.js:166:7)
```
</details>

**Comment by Tapppi** [comment]
It's an authentication error, if that helps you at all `Could not authenticate montogeek`. Are you correctly authenticated?

**Comment by montogeek** [comment]
Authenticated against npm or GH?

**Comment by montogeek** [comment]
Thanks @Tapppi 
I changed my Node version with nvm, so, I had to login again :)

**Comment by ingro** [comment]
Sorry to write here, I'm correctly authenticated both with npm and yarn but I get the same error while trying to install storybook. How do you fixed it @montogeek, if I may ask?

**Comment by montogeek** [comment]
@ingro `npm login`, that was it :)

**Comment by ingro** [comment]
Well thanks, but didn't work for me, maybe I should open another issue?
