### ISSUE TITLE
Looking for package on the proxy server which doesn't exist when installing a yarn pack file

### ISSUE THREAD

**Issue by KennyLindahl** [yarnpkg/yarn#1249]
Yarn version: 0.16.0 (currently latest)

Additional info: I have a npm proxy server (Sinopia) where i store some private npm packages.

**Steps to reproduce**

1. Ran `yarn package hello` in my package directory
2. Ran `yarn add hello -g` 
3. Got the following error in my yarn-error.log:

`Trace: 
Error: https://npm.my-internal-proxy-domain.com/tagen: no such package available
   at Request.params.callback [as _callback] (/Users/kenny/.npm-global/lib/node_modules/yarn/lib/util/request-manager.js:294:18)
   at Request.self.callback (/Users/kenny/.npm-global/lib/node_modules/yarn/node_modules/request/request.js:187:22)
   at emitTwo (events.js:106:13)
   at Request.emit (events.js:191:7)
   at Request.<anonymous> (/Users/kenny/.npm-global/lib/node_modules/yarn/node_modules/request/request.js:1048:10)
   at emitOne (events.js:96:13)
   at Request.emit (events.js:188:7)
   at IncomingMessage.<anonymous> (/Users/kenny/.npm-global/lib/node_modules/yarn/node_modules/request/request.js:969:12)
   at emitNone (events.js:91:20)
   at IncomingMessage.emit (events.js:185:7)
`

**Expected outcome**

Yarn should not look for the tagen package on the proxy server as it doesn't exist there, it should go to the original npm server and download it.

**Question**

Is proxy servers for NPM not supported by Yarn?

**Comment by KennyLindahl** [comment]
Need to have a second look at this myself before someone else investigates this, closing for now.
