### ISSUE TITLE
Can't install hello.tgz after a yarn pack

### ISSUE THREAD

**Issue by KennyLindahl** [yarnpkg/yarn#1253]
- _Node version:_ v6.8.1
- _Yarn version:_ 0.16.0
- _OS version:_ Mac OS Sierra 10.12

_Steps to reproduce_
1. `yarn pack --filename hello.tgz`
2. `yarn add hello.tgz -g`

From yarn-error.log:
`
  Error: invalid tar file
      at Extract.Parse._startEntry (/Users/kenny/.npm-global/lib/node_modules/yarn/node_modules/tar/lib/parse.js:149:13)
      at Extract.Parse._process (/Users/kenny/.npm-global/lib/node_modules/yarn/node_modules/tar/lib/parse.js:131:12)
      at BlockStream.<anonymous> (/Users/kenny/.npm-global/lib/node_modules/yarn/node_modules/tar/lib/parse.js:47:8)
      at emitOne (events.js:96:13)
      at BlockStream.emit (events.js:188:7)
      at BlockStream._emitChunk (/Users/kenny/.npm-global/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:145:10)
      at BlockStream.resume (/Users/kenny/.npm-global/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:58:15)
      at Extract.Reader.resume (/Users/kenny/.npm-global/lib/node_modules/yarn/node_modules/fstream/lib/reader.js:249:34)
      at Entry.<anonymous> (/Users/kenny/.npm-global/lib/node_modules/yarn/node_modules/tar/lib/parse.js:261:8)
      at emitNone (events.js:86:13)
      at Entry.emit (events.js:185:7)
`

I can unpack the hello.tgz without any problems using the inbuilt uncompressor in Mac.

**Comment by bestander** [comment]
I don't think add API works like that.
You can do `yarn add <resolvable dependency>` but not a local .tgz file.
Though it could be a good feature

**Comment by KennyLindahl** [comment]
@bestander So what is the purpose of the `yarn pack` command then?
I can do this in npm and i would expect yarn to be able to do it as well.

In npm i can do the following:
1. npm pack
> my-package-3.6.1.tgz
2. npm install my-package-3.6.1.tgz -g

**Comment by bestander** [comment]
This feature is just not implemented yet.
Feel free to send a PR.

**Comment by thejameskyle** [comment]
Side note: It's `yarn global add` not `yarn add -g`

**Comment by KennyLindahl** [comment]
I can try to explain my use case as well.

Basically i would like to see what the package is going to look like if i publish it before i actually publish it.
This is what i did with npm after doing the shrinkwrap stuff to see what it would be like to install it without actually having to publish it and unpublish it.

**Comment by t-richards** [comment]
@KennyLindahl The `yarn add <local tarball>` command does, in fact, work as expected (v0.18.0). The real issue here is that `yarn pack` produces an invalid tarball. Use `npm pack` to pack your tarball and then you'll be able to successfully add it to your project (via local file or remote URL) using `yarn`.

**Comment by KennyLindahl** [comment]
@t-richards Thanks, that's great news. However it doesn't look like Yarn 0.18.0 is published to NPM yet (currently on 0.17.10). Do you happen to know when this will be released or where i can find more information about it?

**Comment by torifat** [comment]
@KennyLindahl It works with `0.17.10` too. Can you check please?

**Comment by KennyLindahl** [comment]
I can confirm that this is now working in Yarn 0.18.1. Closing this.
