### ISSUE TITLE
lib/util/git.js - TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by vjpr** [yarnpkg/yarn#1287]
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

`yarn install` with an existing lock file.

```
Trace: 
  TypeError: Cannot read property 'split' of undefined
      at Function.parseRefs (/usr/local/Cellar/yarn/0.16.0/libexec/lib/node_modules/yarn/lib/util/git.js:439:20)
      at /usr/local/Cellar/yarn/0.16.0/libexec/lib/node_modules/yarn/lib/resolvers/exotics/hosted-git-resolver.js:138:50
      at next (native)
      at step (/usr/local/Cellar/yarn/0.16.0/libexec/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /usr/local/Cellar/yarn/0.16.0/libexec/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Please mention your node.js, yarn and operating system version.**

macOS, yarn 0.16.0

**Comment by vjpr** [comment]
`yarn/src/resolvers/exotics/hosted-git-resolver.js:84`

```
    let out = await this.config.requestManager.request({
      url: `${url}/info/refs?service=git-upload-pack`,
      queue: this.resolver.fetchingQueue,
    });
```

`out` returns `Repository not found`.

This needs to be handled.

**Comment by joezcool02** [comment]
Having the same issue here

**Comment by rsumilang** [comment]
Same issue here :(

**Comment by samccone** [comment]
can someone please provide a minimal lock file to reproduce?

**Comment by derimagia** [comment]
Taken from a separate package.json (Works in npm, not yarn)

```sh
yarn add 'thinktandem/grunt-nwjs-builder.git'

**Comment by derimagia** [comment]
Relevant package npm uses: https://github.com/npm/npm-package-arg

**Comment by ravishivt** [comment]
Just a note for future reference, this error can still come up when you have an invalid package version like `"ckeditor": "#full/4.5.10"`, which was migrated from a valid bower version.

On yarn install, it gives the same `Cannot read property 'split' of undefined` in yarn-error.log:
<details>
```
Trace:
  TypeError: Cannot read property 'split' of undefined
      at Function.parseRefs (/Users/rmehra/.npm-packages/lib/node_modules/yarn/lib/util/git.js:462:20)
      at /Users/rmehra/.npm-packages/lib/node_modules/yarn/lib/resolvers/exotics/hosted-git-resolver.js:138:50
      at Generator.next (<anonymous>)
      at step (/Users/rmehra/.npm-packages/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /Users/rmehra/.npm-packages/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
      at process._tickCallback (internal/process/next_tick.js:103:7)
```
</details>
<br/>

Doing npm install gives a bit more helpful error message:
<details>
```
npm ERR! git clone --template=/Users/rmehra/.npm/_git-remotes/_templates --mirror git@github.com:/%7Bproject%7D.git /Users/rmehra/.npm/_git-remotes/git-github-com-7Bproject-7D-gi
t-full-4-5-10-ba8cfb60: Cloning into bare repository '/Users/rmehra/.npm/_git-remotes/git-github-com-7Bproject-7D-git-full-4-5-10-ba8cfb60'...
npm ERR! git clone --template=/Users/rmehra/.npm/_git-remotes/_templates --mirror git@github.com:/%7Bproject%7D.git /Users/rmehra/.npm/_git-remotes/git-github-com-7Bproject-7D-gi
t-full-4-5-10-ba8cfb60: fatal: remote error:
npm ERR! git clone --template=/Users/rmehra/.npm/_git-remotes/_templates --mirror git@github.com:/%7Bproject%7D.git /Users/rmehra/.npm/_git-remotes/git-github-com-7Bproject-7D-gi
t-full-4-5-10-ba8cfb60:    is not a valid repository name
npm ERR! git clone --template=/Users/rmehra/.npm/_git-remotes/_templates --mirror git@github.com:/%7Bproject%7D.git /Users/rmehra/.npm/_git-remotes/git-github-com-7Bproject-7D-gi
t-full-4-5-10-ba8cfb60:   Email support@github.com for help
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/rmehra/.npm/_git-remotes/_templates --mirror git@github.com:/%7Bproject%7D.git /Users/rmehra/.npm/_git-remotes/git-github-com
-7Bproject-7D-git-full-4-5-10-ba8cfb60
npm ERR! Cloning into bare repository '/Users/rmehra/.npm/_git-remotes/git-github-com-7Bproject-7D-git-full-4-5-10-ba8cfb60'...
npm ERR! fatal: remote error:
npm ERR!    is not a valid repository name
npm ERR!   Email support@github.com for help
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rmehra/esupport/code/ase_v1/public/npm-debug.log
```
</details>
