### ISSUE TITLE
Yarn install Error

### ISSUE THREAD

**Issue by luanmuniz** [yarnpkg/yarn#1338]
```
Arguments: 
/Users/luanmuniz/.nvm/versions/node/v6.9.0/bin/node /usr/local/bin/yarn install --production

PATH: 
/Users/luanmuniz/.nvm/versions/node/v6.9.0/bin:/usr/local/bin:/usr/local/heroku/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin

Yarn version: 0.16.0
Node version: 6.9.0
Platform: darwin x64

npm manifest: 
  {
    "name": "api",
    "version": "0.0.1",
    "private": true,
    "bugs": "###",
    "scripts": {
      "start": "node index.js",
      "nodemon": "nodemon index.js",
      "postinstall": "cp ../lib ./lib",
      "test": "./node_modules/grunt-cli/bin/grunt -v test"
    },
    "engines": {
      "node": ">=4.*"
    },
    "dependencies": {
      "body-parser": "^1.10.2",
      "compression": "^1.3.0",
      "csurf": "^1.6.5",
      "deep-extend": "^0.4.1",
      "express": "^4.11.1",
      "express-params": "0.0.3",
      "helmet": "^0.15.0",
      "joi": "^9.0.4",
      "lodash": "^3.6.0",
      "marked": "^0.3.3",
      "method-override": "^2.3.1",
      "moment": "^2.15.0",
      "mysql": "^2.5.4",
      "newrelic": "^1.30.3",
      "universal-event-tracker": "^2.1.8",
      "uuid": "^2.0.1"
    },
    "devDependencies": {
      "grunt": "^0.4.5",
      "grunt-cli": "^0.1.13",
      "grunt-contrib-jshint": "^0.11.0",
      "grunt-david": "^0.4.0",
      "grunt-env": "^0.4.4",
      "grunt-execute": "^0.2.2",
      "grunt-jscs": "^2.3.0",
      "grunt-mocha-test": "^0.12.7",
      "load-grunt-tasks": "^3.1.0",
      "mocha": "^2.2.4",
      "should": "^7.0.1",
      "sinon": "^1.14.1",
      "supertest": "^1.0.1",
      "time-grunt": "^1.0.0"
    }
  }

yarn manifest: 
  No manifest

bower manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  TypeError: Cannot use 'in' operator to search for '1.3.0' in undefined
      at /usr/local/Cellar/yarn/0.16.0/libexec/lib/node_modules/yarn/lib/resolvers/registries/npm-resolver.js:62:24
      at next (native)
      at step (/usr/local/Cellar/yarn/0.16.0/libexec/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /usr/local/Cellar/yarn/0.16.0/libexec/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
      at Promise.F (/usr/local/Cellar/yarn/0.16.0/libexec/lib/node_modules/yarn/node_modules/core-js/library/modules/_export.js:35:28)
      at /usr/local/Cellar/yarn/0.16.0/libexec/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
      at Function.findVersionInRegistryResponse (/usr/local/Cellar/yarn/0.16.0/libexec/lib/node_modules/yarn/lib/resolvers/registries/npm-resolver.js:72:7)
      at /usr/local/Cellar/yarn/0.16.0/libexec/lib/node_modules/yarn/lib/resolvers/registries/npm-resolver.js:89:34
      at next (native)
      at step (/usr/local/Cellar/yarn/0.16.0/libexec/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
```

**Comment by wyze** [comment]
Possibly fixed by #1281. There are other issues in the PR that are all similar.

**Comment by thejameskyle** [comment]
Yeah, Dyn has been getting DDoS'd all day:

- http://status.npmjs.org/
- https://status.github.com/

**Comment by thejameskyle** [comment]
registry.yarnpkg.com is now bypassing npm's DNS by pointing directly to it's IP address so there should not be anymore problems.

**Comment by jas99** [comment]
@thejameskyle All of sudden yarn stoped working

can't connect to 104.16.59.173 (cloudflare seems to block it)
I am from india and using internet connection **reliance jio**(4g); my bsnl broadband is down today(never had problem). This is not first time I had issue using yarn with my 4g connection. 

Thx

**Comment by jas99** [comment]
@thejameskyle 
`Error: connect ECONNREFUSED 104.16.59.173:443
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
`

**Comment by SuhairZain** [comment]
@thejameskyle
Same issue here. I have the same issue with another service provider (Airtel). Were you able to find a solution for this?

**Comment by jas99** [comment]
@SuhairZain I kinna started working for me again after a while.
