### ISSUE TITLE
 `yarn info . engines` fails

### ISSUE THREAD

**Issue by paulirish** [yarnpkg/yarn#1347]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`yarn info . engines` fails.

From 0.15.1:
```sh
▸ yarn info . engines
yarn info v0.15.1
error TypeError: Invalid attempt to destructure non-iterable instance
    at /Users/paulirish/.homebrew/lib/node_modules/yarnpkg/node_modules/babel-runtime/helpers/slicedToArray.js:48:13
    at parsePackageName (/Users/paulirish/.homebrew/lib/node_modules/yarnpkg/lib/util/parse-package-name.js:22:81)
    at Object.<anonymous> (/Users/paulirish/.homebrew/lib/node_modules/yarnpkg/lib/cli/commands/info.js:23:90)
    at next (native)
    at step (/Users/paulirish/.homebrew/lib/node_modules/yarnpkg/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/paulirish/.homebrew/lib/node_modules/yarnpkg/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at Promise.F (/Users/paulirish/.homebrew/lib/node_modules/yarnpkg/node_modules/core-js/library/modules/_export.js:35:28)
    at Object.<anonymous> (/Users/paulirish/.homebrew/lib/node_modules/yarnpkg/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at Object.run (/Users/paulirish/.homebrew/lib/node_modules/yarnpkg/lib/cli/commands/info.js:52:17)
    at run (/Users/paulirish/.homebrew/lib/node_modules/yarnpkg/lib/cli/index.js:237:18)
info Visit http://yarnpkg.com/en/docs/cli/info for documentation about this command.

```

And from `master`:

```sh
▸ yarn info . engines
yarn info v0.16.2
error An unexpected error occurred, please open a bug report with the information provided in "/Users/paulirish/code/lighthouse/lighthouse-cli/yarn-error.log".
```

```sh
Trace: 
  TypeError: Cannot convert undefined or null to object
      at Object.<anonymous> (/Users/paulirish/code/yarn/lib/cli/commands/info.js:39:30)
      at next (native)
      at step (/Users/paulirish/code/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /Users/paulirish/code/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
      at process._tickCallback (internal/process/next_tick.js:103:7)
 ```

**If the current behavior is a bug, please provide the steps to reproduce.**
run `yarn info . engines` in pretty much any repo. can repro in yarn's one.

**What is the expected behavior?**
```sh
▸ npm info . engines
{ node: '>=5' }
```

yarn: 0.15.1 and master (0ad1ec6781a6c8bc00fabb31777dfce6971a7d04)
osx: 10.11.6 
node: v6.6.0

**Comment by paulirish** [comment]
IMO this is a super minor issue, so feel free to bounce it to low priority.

**Comment by thejameskyle** [comment]
I don't understand what the `.` is in the `yarn info . engines`

**Comment by paulirish** [comment]
it's if you want to run `yarn info` on the module that's in CWD rather than a module in the registry.

**Comment by tudorgergely** [comment]
Hi, I would like to work on this if possible.

I know where the issue is and I guess it can get me started onto more complex pull requests. This if there is nobody else already working on it.

Thanks!

**Comment by thejameskyle** [comment]
@tudorgergely go for it

**Comment by samccone** [comment]
👍 if someone wants to implement this :)

**Comment by samccone** [comment]
got it 🐐
