### ISSUE TITLE
Error while installing babel-preset-es2015

### ISSUE THREAD

**Issue by JiDai** [yarnpkg/yarn#1368]
Hi,
I just install Yarn with Brew on OSX Sierra.
I got an error when I try to install only one dependency `babel-preset-es2015`
`error An unexpected error occured, please open a bug report with the information provided in "/Users/jordid/GitHome/test-yarn/yarn-error.log".`
I tried to install another dependency and it worked.

Step to reproduce : 
Run `mkdir test-yarn`
Run `cd test-yarn`
Run `yarn init` (keep all defaults)
Add in `package.json` :

```
  "dependencies": {
    "babel-preset-es2015": "6.9.0"
  }
```

Run `yarn`

Here is the last line of error.log : 

```
Trace: 
  SyntaxError: /Users/jordid/.yarn-cache/npm-babel-plugin-transform-es2015-for-of-6.8.0/.yarn-metadata.json: Unexpected end of JSON input
      at Object.parse (native)
      at /usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/lib/util/fs.js:271:57
      at next (native)
      at step (/usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
```

The `.yarn-metadata.json` file is empty

Thanks
## 

OSX Sierra 
node v6.9.1
yarn 0.16.1

**Comment by math1761** [comment]
Me too I have exactly the same problem with another babel dependency and the same configuration as yours..

`Trace:
  SyntaxError: /Users/mathieu/.yarn-cache/npm-babel-template-6.16.0/.\
yarn-metadata.json: Unexpected end of JSON input
      at Object.parse (native)
      at /usr/local/lib/node_modules/yarn/lib/util/fs.js:271:57`

**Comment by Daniel15** [comment]
I'm seeing the same thing when I try to run `yarn install` on [babel-standalone](https://github.com/Daniel15/babel-standalone).
```
  SyntaxError: C:\Users\Daniel\AppData\Local\Yarn\cache\npm-array-union-1.0.2\.yarn-metadata.json: Unexpected end of JSON input
      at Object.parse (native)
      at c:\Program Files (x86)\Yarn\lib\util\fs.js:271:57
      at next (native)
      at step (c:\Program Files (x86)\Yarn\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
      at c:\Program Files (x86)\Yarn\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:20
```

**Comment by dflock** [comment]
I think I just encountered this, or a very similar issue. I ran this and got this output:

```console
 ➜ yarn install
yarn install v0.16.1
info No lockfile found.
error An unexpected error occured, please open a bug report with the information provided in "/home/duncan/dev/vuejs-test-from-scratch/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

this is the contents of the `yarn-error.log`:

```
Arguments: 
  /usr/bin/nodejs /usr/share/yarn/bin/yarn.js install

PATH: 
  /home/duncan/.cabal/bin:./node_modules/.bin:/home/duncan/.yarn-config/global/bin:~/.npm-packages/bin:/home/duncan/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-7-oracle/bin:/usr/lib/jvm/java-7-oracle/db/bin:/usr/lib/jvm/java-7-oracle/jre/bin:/var/data/phemi/utils

Yarn version: 
  0.16.1

Node version: 
  6.9.1

Platform: 
  linux x64

npm manifest: 
  {
    "name": "myapp",
    "version": "0.0.1",
    "description": "My app",
    "private": true,
    "dependencies": {
    },
    "devDependencies": {
      "babel-core": "^6.1.2",
      "babel-loader": "^6.1.0",
      "babel-plugin-transform-runtime": "^6.1.2",
      "babel-preset-es2015": "^6.1.2",
      "babel-preset-stage-0": "^6.1.2",
      "babel-runtime": "^5.8.0",
      "webpack": "^1.12.2",
    },
    "author": "Duncan Lock <dlock@phemi.com>"
  }

yarn manifest: 
  No manifest

bower manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  SyntaxError: /home/duncan/dev/vuejs-test-from-scratch/package.json: Unexpected token } in JSON at position 377
      at Object.parse (native)
      at /usr/share/yarn/lib/util/fs.js:271:57
      at next (native)
      at step (/usr/share/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /usr/share/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
```

**Comment by kaylieEB** [comment]
closing this due to inactivity and outdated version of yarn (can't verify on latest release)
