### ISSUE TITLE
Debian package needs to depend on / recommend ca-certificates to avoid "unable to get local issuer certificate" error

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#1390]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Installing `yarn` without having `ca-certificates` installed produces this error:
```
+ yarn add react
yarn add v0.16.0
info No lockfile found.
[1/4] Resolving packages...
error An unexpected error occured, please open a bug report with the information provided in "/tmp/yarntest/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

```
root@291a7c28dd47:/data# cat /tmp/yarntest/yarn-error.log
Arguments:
  /usr/bin/nodejs /usr/share/yarn/bin/yarn.js add react

PATH:
  /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Yarn version:
  0.16.0

Node version:
  4.2.6

Platform:
  linux x64

npm manifest:
  No manifest

yarn manifest:
  No manifest

bower manifest:
  No manifest

Lockfile:
  No lockfile

Trace:
  Error: unable to get local issuer certificate
      at Error (native)
      at TLSSocket.<anonymous> (_tls_wrap.js:1016:38)
      at emitNone (events.js:67:13)
      at TLSSocket.emit (events.js:166:7)
      at TLSSocket._finishInit (_tls_wrap.js:585:8)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
```
docker run -it ubuntu:16.04
```

Then inside Docker container:
```
apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
echo "deb http://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list
apt-get update -y
apt-get install yarn -y
cd /tmp
mkdir yarntest
cd yarntest
yarn add react
```

**What is the expected behavior?**
`apt-get install yarn` should also install `ca-certificates`.

**Comment by Daniel15** [comment]
Filed https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=841980 and https://github.com/nodesource/distributions/issues/376 for updating the Node.js packages to recommend `ca-certificates`.

**Comment by BYK** [comment]
@Daniel15 is this still a thing?

**Comment by Daniel15** [comment]
The Debian package was fixed (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=841981), but I don't think NodeSource's one was fixed (https://github.com/nodesource/distributions/issues/376) so we probably still need to add this. It should just be a simple change.

**Comment by simevo** [comment]
now `ca-certificates` is recommended, but users can still choose to not install it; this often happens in docker containers where one wants to squeeze the container footprint invoking apt with `--no-install-recommends` option
also see: https://bugs.debian.org/952656
