### ISSUE TITLE
FR: auto build on npm link/post install on dev.

### ISSUE THREAD

**Issue by hemanth** [yarnpkg/yarn#1416]
**Do you want to request a *feature* or report a *bug*?**
Feature 

**What is the current behavior?**

`git clone` and `npm link` results in:

```sh
$ yarn install
module.js:339
    throw err;
    ^

Error: Cannot find module '../lib-legacy/constants'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/hemanth/labs/yarn/bin/yarn.js:9:17)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
```

After 

```
npm run build
```

It works fine.

It would be nice to have a post install, `run build` ?

**Please mention your node.js, yarn and operating system version.**

* os : `Darwin`
* version : `v4.2.1`
* nvm : `2.14.7`

**Comment by samccone** [comment]
Mind opening this here:
https://github.com/yarnpkg/rfcs

Thanks

**Comment by hemanth** [comment]
RFC! I see, nice.
