### ISSUE TITLE
yarn --version after installation gives error on Windows 10

### ISSUE THREAD

**Issue by wvandeneede** [yarnpkg/yarn#1507]
OS Version: Windows 10 Enterprise

Installed yarn using the msi here: https://yarnpkg.com/en/docs/install
Tried to verify the version using: yarn --version
The following error shows:

C:\>yarn --version
C:\Program Files (x86)\Yarn\lib-legacy\constants.js:7
const userHome = require('user-home');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Program Files (x86)\Yarn\bin\yarn.js:9:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by csvan** [comment]
What is your node version?

**Comment by csvan** [comment]
This sounds like a Node version issue. Any 6.x release should not have problems like this. For example, try running a file with the following:

```
'use strict';
const apa = 'bepa';
console.log(apa);
```

So either your version of Node is outdated, or the one bundled in the MSI (if any)

**Comment by wvandeneede** [comment]
It is indeed a node version issue, I had 2 versions of node installed the latest being v.6.9.1 (installed under C:\Program Files\nodejs).  
But the path environment variable was still point to an old version of node v.0.12.2 (installed under C:\Program Files (x86)\nodejs).

Pointing the environment variable to the latest node version, solved the issue.

Thanks a million!

**Comment by csvan** [comment]
Glad it worked!
