### ISSUE TITLE
Bad error message for not found scoped packages

### ISSUE THREAD

**Issue by justinfagnani** [yarnpkg/yarn#1513]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`yarn add @types/flimmflamm` (@types/flimflam does not exist)
results in:

`error An unexpected error occured...`

Trace:

```
Trace: 
  Error: https://registry.yarnpkg.com/@types%2fflimflam: Not found
      at Request.params.callback [as _callback] (/Users/justinfagnani/.nvm/versions/node/v7.0.0/lib/node_modules/yarn/lib/util/request-manager.js:294:18)
      at Request.self.callback (/Users/justinfagnani/.nvm/versions/node/v7.0.0/lib/node_modules/yarn/node_modules/request/request.js:186:22)
      at emitTwo (events.js:106:13)
      at Request.emit (events.js:191:7)
      at Request.<anonymous> (/Users/justinfagnani/.nvm/versions/node/v7.0.0/lib/node_modules/yarn/node_modules/request/request.js:1060:10)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:188:7)
      at IncomingMessage.<anonymous> (/Users/justinfagnani/.nvm/versions/node/v7.0.0/lib/node_modules/yarn/node_modules/request/request.js:980:12)
      at IncomingMessage.g (events.js:291:16)
      at emitNone (events.js:91:20)
```

**What is the expected behavior?**

`error Couldn't find package "flimmflamm" on the "npm" registry.`

**Please mention your node.js, yarn and operating system version.**
node 7.0, yarn 0.16.1, OS X

**Comment by samccone** [comment]
This is fixed on master :)
