### ISSUE TITLE
yarn outdated - crashes due to 404 for @angular/http package

### ISSUE THREAD

**Issue by JohannesRudolph** [yarnpkg/yarn#1535]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`yarn outdated` crashes on my project with the following error: 

```
Trace: 
  Error: https://registry.yarnpkg.com/@angular/http: Not found
      at Request.params.callback [as _callback] (/usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/lib/util/request-manager.js:294:18)
      at Request.self.callback (/usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/node_modules/request/request.js:187:22)
      at emitTwo (events.js:106:13)
      at Request.emit (events.js:191:7)
      at Request.<anonymous> (/usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/node_modules/request/request.js:1048:10)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:188:7)
      at IncomingMessage.<anonymous> (/usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/node_modules/request/request.js:969:12)
      at emitNone (events.js:91:20)
      at IncomingMessage.emit (events.js:185:7)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Run `yarn outdated` on a project that installs the `@angular/http` projects. I suspects this issue is very similar to https://github.com/yarnpkg/yarn/issues/1510

Might be a configuration issue on the yarnpkg.com registry...

**What is the expected behavior?**
It should work without crashing :-) 

**Please mention your node.js, yarn and operating system version.**
node 6.3, OS X 11 El Capitan, yarn 0.16.1 (via homebrew)

**Comment by dylanparry** [comment]
Hi, this is a duplicated of #620, which has been fixed by #1276. It should be included in the next release :)
