### ISSUE TITLE
yarn corrupts phantomjs binary on reinstall

### ISSUE THREAD

**Issue by aaronjensen** [yarnpkg/yarn#1607]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Yarn appears to occasionally corrupt the native portion of phantomjs-prebuild, especially when used within docker.

This manifests like this:

```
# ./node_modules/.bin/phantomjs --version
internal/child_process.js:289
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:289:26)
    at exports.spawn (child_process.js:380:9)
    at Object.<anonymous> (/the-link/node_modules/phantomjs-prebuilt/bin/phantomjs:22:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Our repro is fairly complicated and involves blowing way the yarn cache (though it still seems to happen for us even without the yarn cache being taken away).

See this repo for repro steps: https://github.com/aaronjensen/yarn-repro

Some notes about this repo:

* Because the container is new for each step, the yarn-cache is empty in both steps.
* Deleting the `.yarn-integrity` is meant to simulate the `yarn.lock` changing in any way. We typically see this behavior when the `yarn.lock` changes.
* I've been able to "fix" this when attempting to repro sometimes by adding `--cache-folder .yarn-cache` to both `yarn` commands, but in our real world scenario this does not seem to consistently help.

**What is the expected behavior?**

Yarn would not corrupt phantomjs's binary ever, even if the yarn-cache was gone.

**Please mention your node.js, yarn and operating system version.**

Node 6.5.0
yarn 0.16.1
Debian 8 (jessie)

**Comment by Ky6uk** [comment]
Yarn `v0.17.2` still broken on it. NPM installs it correctly.

**Comment by mheimschild** [comment]
yarn unlike npm does not install phantomjs binary only script relying on it. 
As a workaround I downloaded phantomjs binary a set PHANTOMJS_BIN env variable pointing to it.

**Comment by RSO** [comment]
Another fix for this is to run `rm -rf node_modules/` and re-run `yarn`. I'll see if I can investigate this issue a little further.

**Comment by msteitle** [comment]
Thanks, @RSO. Worked for me.
