### ISSUE TITLE
appveyor build failing when installing native dep w/ yarn

### ISSUE THREAD

**Issue by jamesdixon** [yarnpkg/yarn#1693]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Appveyor build is failing when building `node-zopfli` (native dep). The build does not fail when using NPM .

Build output:

```
Build started
git config --global core.autocrlf true
git clone -q --branch=env/staging git@bitbucket.org:scoutforpets/app-business.git C:\projects\app-business
git checkout -qf 9c3b78ea9dce08024787c3f8233010d7ffd585f0
Restoring build cache
Cache 'node_modules' - Restored
Cache 'bower_components' - Restored
Running Install scripts
Install-Product node $env:nodejs_version
Uninstalling node 4.6.1 (x86)...
Installing node 6.9.1 (x86)...
yarn global add bower ember-cli
yarn global v0.16.1
[1/4] Resolving packages...
warning ember-cli > broccoli-babel-transpiler > babel-core > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning ember-cli > npm > node-gyp > minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning ember-cli > npm > node-gyp > glob > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning ember-cli > npm > request > tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed bower@1.7.9 with binaries:
      - bower
success Installed ember-cli@2.9.1 with binaries:
      - ember
Done in 39.60s.
yarn install
yarn install v0.16.1
[1/4] Resolving packages...
[2/4] Fetching packages...
warning ember-truth-helpers@1.2.0: The engine "ember-cli-app-version" appears to be invalid.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error C:\projects\app-business\node_modules\node-zopfli: Command failed.
Exit code: 1
Command: C:\windows\system32\cmd.exe
Arguments: /d /s /c node-pre-gyp install --fallback-to-build
Directory: C:\projects\app-business\node_modules\node-zopfli
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.31
node-pre-gyp info using node@6.9.1 | win32 | ia32
node-pre-gyp info check checked for "C:\projects\app-business\node_modules\node-zopfli\lib\binding\node-v48-win32-ia32\zopfli.node" (not found)
node-pre-gyp http GET https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.1-node-v48-win32-ia32.tar.gz
node-pre-gyp http 403 https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.1-node-v48-win32-ia32.tar.gz
node-pre-gyp ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.1-node-v48-win32-ia32.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.1 and node@6.9.1 (node-v48 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 403 status code downloading tarball https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.1-node-v48-win32-ia32.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@6.9.1 | win32 | ia32
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@6.9.1 | win32 | ia32
gyp http GET https://nodejs.org/download/release/v6.9.1/node-v6.9.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v6.9.1/node-v6.9.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v6.9.1/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v6.9.1/win-x86/node.lib
gyp http GET https://nodejs.org/download/release/v6.9.1/win-x64/node.lib
gyp http 200 https://nodejs.org/download/release/v6.9.1/win-x86/node.lib
gyp http 200 https://nodejs.org/download/release/v6.9.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v6.9.1/win-x64/node.lib
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\projects\\app-business\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\projects\\app-business\\node_modules\\node-zopfli\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\projects\\app-business\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\appveyor\\.node-gyp\\6.9.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\appveyor\\.node-gyp\\6.9.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\projects\\app-business\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\projects\\app-business\\node_modules\\node-zopfli',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\projects\\app-business\\node_modules\\node-zopfli\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@6.9.1 | win32 | ia32
gyp info spawn msbuild
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  zopfli-binding.cc
  zopflipng.cc
  zopflipng_lib.cc
  lodepng.cpp
  lodepng_util.cpp
  blocksplitter.c
  cache.c
..\zopfli\src\zopfli\cache.c(70): warning C4267: '=': conversion from 'size_t' to 'unsigned char', possible loss of data [C:\projects\app-business\node_modules\node-zopfli\build\zopfli.vcxproj]
  deflate.c
  gzip_container.c
..\zopfli\src\zopfli\deflate.c(638): warning C4267: '=': conversion from 'size_t' to 'unsigned short', possible loss of data [C:\projects\app-business\node_modules\node-zopfli\build\zopfli.vcxproj]
  hash.c
  katajainen.c
..\zopfli\src\zopfli\hash.c(53): warning C4267: '=': conversion from 'size_t' to 'unsigned short', possible loss of data [C:\projects\app-business\node_modules\node-zopfli\build\zopfli.vcxproj]
  lz77.c
..\zopfli\src\zopfli\hash.c(69): warning C4267: '=': conversion from 'size_t' to 'unsigned short', possible loss of data [C:\projects\app-business\node_modules\node-zopfli\build\zopfli.vcxproj]
..\zopfli\src\zopfli\hash.c(125): warning C4267: '=': conversion from 'size_t' to 'unsigned short', possible loss of data [C:\projects\app-business\node_modules\node-zopfli\build\zopfli.vcxproj]
  squeeze.c
..\zopfli\src\zopfli\lz77.c(360): warning C4267: '=': conversion from 'size_t' to 'unsigned short', possible loss of data [C:\projects\app-business\node_modules\node-zopfli\build\zopfli.vcxproj]
..\zopfli\src\zopfli\lz77.c(486): warning C4267: '=': conversion from 'size_t' to 'unsigned short', possible loss of data [C:\projects\app-business\node_modules\node-zopfli\build\zopfli.vcxproj]
..\zopfli\src\zopfli\squeeze.c(243): warning C4305: '=': truncation from 'double' to 'float' [C:\projects\app-business\node_modules\node-zopfli\build\zopfli.vcxproj]
..\zopfli\src\zopfli\squeeze.c(264): warning C4244: '=': conversion from 'double' to 'float', possible loss of data [C:\projects\app-business\node_modules\node-zopfli\build\zopfli.vcxproj]
..\zopfli\src\zopfli\squeeze.c(281): warning C4244: '=': conversion from 'double' to 'float', possible loss of data [C:\projects\app-business\node_modules\node-zopfli\build\zopfli.vcxproj]
..\zopfli\src\zopfli\squeeze.c(299): warning C4244: '=': conversion from 'double' to 'float', possible loss of data [C:\projects\app-business\node_modules\node-zopfli\build\zopfli.vcxproj]
..\zopfli\src\zopfli\squeeze.c(300): warning C4267: '=': conversion from 'size_t' to 'unsigned short', possible loss of data [C:\projects\app-business\node_modules\node-zopfli\build\zopfli.vcxproj]
  tree.c
  util.c
  zlib_container.c
  zopfli_lib.c
  win_delay_load_hook.c
C:\projects\app-business\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition; different type modifiers [C:\projects\app-business\node_modules\node-zopfli\build\zopfli.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNotifyHook2'
gyp ERR! build error 
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\projects\app-business\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\projects\\app-business\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\projects\\app-business\\node_modules\\node-zopfli\\lib\\binding\\node-v48-win32-ia32\\zopfli.node" "--module_name=zopfli" "--module_path=C:\\projects\\app-business\\node_modules\\node-zopfli\\lib\\binding\\node-v48-win32-ia32"
gyp ERR! cwd C:\projects\app-business\node_modules\node-zopfli
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\projects\app-business\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\projects\app-business\node_modules\node-zopfli\lib\binding\node-v48-win32-ia32\zopfli.node --module_name=zopfli --module_path=C:\projects\app-business\node_modules\node-zopfli\lib\binding\node-v48-win32-ia32' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\projects\app-business\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\projects\\app-business\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\projects\app-business\node_modules\node-zopfli
node-pre-gyp ERR! node -v v6.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok 
Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\projects\app-business\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\projects\app-business\node_modules\node-zopfli\lib\binding\node-v48-win32-ia32\zopfli.node --module_name=zopfli --module_path=C:\projects\app-business\node_modules\node-zopfli\lib\binding\node-v48-win32-ia32' (1)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Command exited with code 1
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Running Appveyor using the following config:

```yaml
  environment:
    nodejs_version: "6"

  # Don't actually build.
  build: off

  # Cache NPM modules unless package.json changes
  cache:
    - node_modules -> package.json
    - bower_components -> bower.json
    - "%LOCALAPPDATA%/Yarn"

  test: off

  # Install scripts
  install:
    # Get the latest stable version of Node.js or io.js
    - ps: Install-Product node $env:nodejs_version
    # Install Ember CLI & Bower
    - yarn global add bower ember-cli
    # Install Deps
    - yarn install
    - bower -s install
    # Deploy using Ember CLI Deploy
    - ember deploy staging --activate
```

Failing when installing `"node-zopfli": "2.0.1"`

**What is the expected behavior?**
Expect that the build completes successfully.

**Please mention your node.js, yarn and operating system version.**
Node 6.9.1
Yarn 0.16.1
Windows Server 2012 R2 (x64)

**Comment by Daniel15** [comment]
It looks like `node-zopfli` only builds 64-bit versions, whereas you're running a 32-bit version of Node.js. Change the Install-Product line in your appveyor.yml file to:
```
Install-Product node $env:nodejs_version x64
```

And see if that helps.

**Comment by Daniel15** [comment]
Actually since you're just building with a single version of Node.js, you can just change it to this:
```
Install-Product node 6 x64
```

And remove the `nodejs_version` variable.

**Comment by jamesdixon** [comment]
@Daniel15 I actually run a 32-bit version of Node on my server. I'm curious, if `node-zopfli` only builds a 64-bit version, then why are there no issues when installing via `npm` rather than Yarn?

**Comment by jamesdixon** [comment]
@Daniel15 regardless - going to give this a try! Thx

**Comment by Daniel15** [comment]
So I think there's two issues:
1. There's only a precompiled version of `node-zopfli` for 64-bit (see https://github.com/pierreinglebert/node-zopfli/blob/master/appveyor.yml#L21-L22). If you use a 64-bit Node.js, you're able to use a pre-built version of node-zopfli rather than compiling it yourself, which should avoid this issue
2. There's some issue with compiling the code, which isn't occuring with npm. I'm not quite sure why that would be happening, but it's something that should be fixed :)

The build is performed using `node-gyp`, so I guess there's an environment difference (eg. missing environment variables) between npm and Yarn, or npm adds extra command-line parameters that Yarn isn't providing. It's probably worth looking at the exact commands that npm runs, and comparing it to Yarn.

**Comment by jamesdixon** [comment]
@Daniel15 thanks for the fantastic explanation! Much appreciated 👍

**Comment by Iwasawafag** [comment]
Also stumbled upon simillar(?) problem when tried to install sharp. If I try to install the package through npm - it works fine, but with yarn, says "*ValueError: Variable expansion in this context permits str and int only, found long for lastUpdateCheck while trying to load binding.gyp*". Weird

Here's full [output](https://gist.github.com/Iwasawafag/418481fa8c37b3ccba336ac3da68497e).

I should also mention that it's hard to find actual error message in this wall of text. With how clumsy npm's error messages are, in my opinion, npm does it better. Colored output or some spacing around error message would be nice to have.

**Comment by lfender6445** [comment]
Similar issue on mac, running `yarn upgrade gl` fixed the version mismatch for me.

**Comment by mnpenner** [comment]
I have the exact opposite issue. Works with yarn, fails with npm.
