### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'LICENSE.md'

### ISSUE THREAD

**Issue by berezovskyi** [yarnpkg/yarn#1706]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

> error An unexpected error occured, please open a bug report with the information provided in "/Users/andrew/code/aether/yarn-error.log".

[yarn-error.log.zip](https://github.com/yarnpkg/yarn/files/573633/yarn-error.log.zip)

**If the current behavior is a bug, please provide the steps to reproduce.**

    git clone https://github.com/jiemakel/aether
    yarn

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**

Yarn version:
  0.16.1

Node version:
  7.0.0

Platform:
  darwin x64

**Comment by hpurmann** [comment]
Installing with current `master` ([`73ea5b4`](https://github.com/yarnpkg/yarn/tree/73ea5b47b50ec906dfdb325d1b0711767502c908)) and node `5.12.0`, which is specified in the `package.json` of `jiemakel/aether` works. _yarn does not officially support this node version though._

When using node `7.1.0`, some packages even tell us about incompatibilities:
```
[1/4] 🔍  Resolving packages...
warning bower-config > graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
warning gulp-cache > cache-swap > rimraf > graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
```

which gives me this error in the end:
```
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning Unmet peer dependency "protractor@*".
[4/4] 📃  Building fresh packages...
[1/5] ⠠ ws
[2/5] ⠠ gifsicle
[3/5] ⠠ jpegtran-bin
[4/5] ⠠ optipng-bin
error /Users/hpurmann/dev/yarn-1706/aether/node_modules/gifsicle: Command failed.
Exit code: 1
Command: sh
Arguments: -c node index.js
Directory: /Users/hpurmann/dev/yarn-1706/aether/node_modules/gifsicle
Output:
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received { url: 'https://raw.github.com/imagemin/gifsicle-bin/v0.1.7/vendor/osx/gifsicle',
  name: 'gifsicle',
  os: 'darwin' }
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at /Users/hpurmann/dev/yarn-1706/aether/node_modules/download/index.js:35:43
    at each (/Users/hpurmann/dev/yarn-1706/aether/node_modules/download/node_modules/each-async/each-async.js:63:4)
    at module.exports (/Users/hpurmann/dev/yarn-1706/aether/node_modules/download/index.js:33:5)
    at /Users/hpurmann/dev/yarn-1706/aether/node_modules/bin-wrapper/index.js:108:20
    at /Users/hpurmann/dev/yarn-1706/aether/node_modules/bin-wrapper/index.js:141:24
    at /Users/hpurmann/dev/yarn-1706/aether/node_modules/bin-check/index.js:30:20
    at /Users/hpurmann/dev/yarn-1706/aether/node_modules/executable/index.js:39:20
    at FSReqWrap.oncomplete (fs.js:111:15)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
This seems more like an issue with the dependencies of `jiemakel/aether` than with yarn. I'd vote for closing this.
