### ISSUE TITLE
Unable to fetch packages from private registry

### ISSUE THREAD

**Issue by owais** [yarnpkg/yarn#1721]
Try to add a package using `yarn add` fails for private registries. I'm using yarn `0.16.1`.

.npmrc
```
@mycompany:registry=http://npm.mycompany.com:8080/
//npm.mycompany.com:8080/:_authToken=<auth-token>
```

```bash
$ yarn add @mycompany/test-package
yarn add v0.16.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occured, please open a bug report with the information provided in "/Users/owais/playground/cyclo/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

```bash
$ cat yarn-error.log
Arguments:
  /usr/local/bin/node /usr/local/bin/yarn add @mycompany/test-package

PATH:
  /Users/owais/.fzf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Users/owais/go/bin:/usr/local/opt/go/libexec//bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/owais/bin:/Users/owais/.pub-cache/bin:/Users/owais/Library/Android/sdk/platform-tools:/Users/owais/playground/flutter/bin

Yarn version:
  0.16.1

Node version:
  6.9.1

Platform:
  darwin x64

npm manifest:
  No manifest

yarn manifest:
  No manifest

bower manifest:
  No manifest

Lockfile:
  No lockfile

Trace:
  Error: http://npm.mycompany.com:8080/@/@mycompany/test-package/_attachments/test-package-1.1.2.tgz: invalid tar file
      at Extract.Parse._startEntry (/usr/local/lib/node_modules/yarn/node_modules/tar/lib/parse.js:149:13)
      at Extract.Parse._process (/usr/local/lib/node_modules/yarn/node_modules/tar/lib/parse.js:131:12)
      at BlockStream.<anonymous> (/usr/local/lib/node_modules/yarn/node_modules/tar/lib/parse.js:47:8)
      at emitOne (events.js:96:13)
      at BlockStream.emit (events.js:188:7)
      at BlockStream._emitChunk (/usr/local/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:145:10)
      at BlockStream.flush (/usr/local/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:70:8)
      at BlockStream.end (/usr/local/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:66:8)
      at Extract.Parse.end (/usr/local/lib/node_modules/yarn/node_modules/tar/lib/parse.js:86:23)
      at UnpackStream.onend (_stream_readable.js:511:10)
```

This is not an authentication error is yarn is able to find out the package version and dependencies (briefly prints them out on console). Also, if I change the auth token to a wrong one, yarn totally fails to contact the server.

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Is unable to install packages from a private registry

**If the current behavior is a bug, please provide the steps to reproduce.**

* Define your private registry in project's .npmrc as
```
@mycompany:registry=http://npm.mycompany.com:8080/
//npm.mycompany.com:8080/:_authToken=<auth-token>
```
* Initialize yarn using `yarn init`
* Try installing a package from your private registry

```
yarn add @mycompany/test-package
```

**What is the expected behavior?**

Private package should be installed

**Please mention your node.js, yarn and operating system version.**
Node v6.9.1
Yarn v0.16.1
macOS Sierra 10.12 Beta (16A293a)

**Comment by maybeec** [comment]
May relate to #1619, #1687

**Comment by wyze** [comment]
Duplicate #1687.
