### ISSUE TITLE
"error OAuth2 authentication" on: yarn self-update

### ISSUE THREAD

**Issue by Elliot-Evans-95** [yarnpkg/yarn#1778]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
used yarn self-update and it has produced an error:
`error OAuth2 authentication requires a token or key & secret to be set
    at module.exports.__dirname.authenticate (/Users/elliot/.yarn/node_modules/github/lib/index.js:334:23)
    at Object.<anonymous> (/Users/elliot/.yarn/lib/cli/commands/self-update.js:30:12)
    at Generator.next (<anonymous>)
    at step (/Users/elliot/.yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/elliot/.yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at F (/Users/elliot/.yarn/node_modules/core-js/library/modules/_export.js:35:28)
    at Object.<anonymous> (/Users/elliot/.yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at Object.run (/Users/elliot/.yarn/lib/cli/commands/self-update.js:99:17)
    at run (/Users/elliot/.yarn/lib/cli/index.js:237:18)
    at config.init.then (/Users/elliot/.yarn/lib/cli/index.js:345:12)
info Visit http://yarnpkg.com/en/docs/cli/self-update for documentation about this command.`
**If the current behavior is a bug, please provide the steps to reproduce.**
1. Install yarn via homebrew
2. entered yarn self-update
3. error occurred
**What is the expected behavior?**
To update Yarn to the latest version
**Please mention your node.js, yarn and operating system version.**
OS: MAC OC X El Captain.
Installed via: homebrew.
Terminal: iTerm2 with zsh

**Comment by Daniel15** [comment]
Duplicate(-ish) of #1139.  I'm going to close this - Feel free to subscribe to #1139 to get updates on this issue. Thanks for trying Yarn! 😄
