### ISSUE TITLE
An unexpected error occured while using "Scoped packages"

### ISSUE THREAD

**Issue by ikhilko** [yarnpkg/yarn#1797]
An unexpected error occured while trying to execute `yarn outdated`. The error report is here:

```
Arguments: 
  /Users/ikhilko/.nvm/versions/node/v7.0.0/bin/node /usr/local/bin/yarn outdated

PATH: 
  /Users/ikhilko/.nvm/versions/node/v7.0.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

Yarn version: 
  0.16.1

Node version: 
  7.0.0

Platform: 
  darwin x64

npm manifest: 
  {
    "name": "some-project",
    "version": "0.0.1",
    "private": true,
    "engines": {
      "node": ">=4.x"
    },
    "dependencies": {
      "@turf/turf": "^3.5.3"
      ...
    }
}

yarn manifest: 
  No manifest

bower manifest: 
  No manifest

Lockfile: 
  # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
  # yarn lockfile v1
  "@turf/along@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/along/-/along-3.5.3.tgz#6d7b99409ea5095fef6bbe7b0e7c9f074f3944f6"
    dependencies:
      "@turf/bearing" "^3.5.2"
      "@turf/destination" "^3.5.3"
      "@turf/distance" "^3.5.3"
      "@turf/helpers" "^3.5.3"
  
  "@turf/area@^3.5.2":
    version "3.5.2"
    resolved "https://registry.yarnpkg.com/@turf/area/-/area-3.5.2.tgz#a01d6b1bbbde00b68385fea158433ea75890018e"
    dependencies:
      geojson-area "^0.2.1"
  
  "@turf/bbox-polygon@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/bbox-polygon/-/bbox-polygon-3.5.3.tgz#b7ec27a9c6c200c09c0c1b83c5550982f732ceb8"
    dependencies:
      "@turf/helpers" "^3.5.3"
  
  "@turf/bbox@^3.0.0", "@turf/bbox@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/bbox/-/bbox-3.5.3.tgz#2d2b67c15b51ca145ad65836c799f21868ddf6c3"
    dependencies:
      "@turf/meta" "^3.5.3"
  
  "@turf/bearing@^3.5.2":
    version "3.5.2"
    resolved "https://registry.yarnpkg.com/@turf/bearing/-/bearing-3.5.2.tgz#cefdc8bab1125f187f8735431cb6ea350f402173"
    dependencies:
      "@turf/invariant" "^3.5.2"
  
  "@turf/bezier@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/bezier/-/bezier-3.5.3.tgz#e0b6e939002f79c89d6ef40dd4fa8833ddc01649"
    dependencies:
      "@turf/helpers" "^3.5.3"
  
  "@turf/buffer@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/buffer/-/buffer-3.5.3.tgz#449244c41057e1df85cf70da5c7580bd03e1965f"
    dependencies:
      "@turf/combine" "^3.5.3"
      "@turf/helpers" "^3.5.3"
      geojson-normalize "0.0.0"
      jsts "1.2.0"
  
  "@turf/center-of-mass@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/center-of-mass/-/center-of-mass-3.5.3.tgz#4adc572fb801ed433256cbf33f5698d3e83cb3d6"
    dependencies:
      "@turf/centroid" "^3.5.3"
      "@turf/convex" "^3.5.3"
      "@turf/explode" "^3.5.3"
      "@turf/helpers" "^3.5.3"
      "@turf/meta" "^3.5.3"
  
  "@turf/center@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/center/-/center-3.5.3.tgz#3e524fcb4d04fe59a1144b7ae1840c52dca64d6e"
    dependencies:
      "@turf/bbox" "^3.5.3"
      "@turf/helpers" "^3.5.3"
  
  "@turf/centroid@^3.0.0", "@turf/centroid@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/centroid/-/centroid-3.5.3.tgz#35f47ca27d9a7febe1c0cb50d4431f7f2e613a23"
    dependencies:
      "@turf/helpers" "^3.5.3"
      "@turf/meta" "^3.5.3"
  
  "@turf/circle@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/circle/-/circle-3.5.3.tgz#51b0610ceca12d80423e8009346f832672bdc900"
    dependencies:
      "@turf/destination" "^3.5.3"
      "@turf/helpers" "^3.5.3"
  
  "@turf/collect@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/collect/-/collect-3.5.3.tgz#c055ab94b6610fcdf3327c0a55ed681630f9ccfb"
    dependencies:
      "@turf/inside" "^3.5.3"
  
  "@turf/combine@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/combine/-/combine-3.5.3.tgz#52f74ae9275a0f695526c41cb66d7bd95d0358be"
    dependencies:
      "@turf/meta" "^3.5.3"
  
  "@turf/concave@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/concave/-/concave-3.5.3.tgz#5f579830b2e042d4e6d42ae1e6ab340320ecf718"
    dependencies:
      "@turf/distance" "^3.5.3"
      "@turf/meta" "^3.5.3"
      "@turf/tin" "^3.5.3"
      "@turf/union" "^3.5.2"
  
  "@turf/convex@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/convex/-/convex-3.5.3.tgz#08e647f83236bbccca39b175283af0b1db930c3c"
    dependencies:
      "@turf/helpers" "^3.5.3"
      "@turf/meta" "^3.5.3"
      convex-hull "^1.0.3"
  
  "@turf/destination@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/destination/-/destination-3.5.3.tgz#92825130d2aaa02ba7143aa0dcc405daae079675"
    dependencies:
      "@turf/helpers" "^3.5.3"
      "@turf/invariant" "^3.5.2"
  
  "@turf/difference@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/difference/-/difference-3.5.3.tgz#e81443b4abfbe5e7cbb5d1dd0b3e19c1dd536957"
    dependencies:
      "@turf/helpers" "^3.5.3"
      jsts "1.2.0"
  
  "@turf/distance@^3.0.0", "@turf/distance@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/distance/-/distance-3.5.3.tgz#0f8a87675d98bd45cfe48c754df83fdc1d05436a"
    dependencies:
      "@turf/helpers" "^3.5.3"
      "@turf/invariant" "^3.5.2"
  
  "@turf/envelope@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/envelope/-/envelope-3.5.3.tgz#12fb65be97acec1875e745dc4040ffdb52e5b953"
    dependencies:
      "@turf/bbox" "^3.5.3"
      "@turf/bbox-polygon" "^3.5.3"
  
  "@turf/explode@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/explode/-/explode-3.5.3.tgz#f94e73c91a7126b0bb00d9d27b82eb760ab29530"
    dependencies:
      "@turf/helpers" "^3.5.3"
      "@turf/meta" "^3.5.3"
  
  "@turf/flip@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/flip/-/flip-3.5.3.tgz#12a0229038d21a7bdb3bc71cdc3aebf9efdbc60f"
    dependencies:
      "@turf/meta" "^3.5.3"
  
  "@turf/helpers@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/helpers/-/helpers-3.5.3.tgz#32142d2c1aec9c3e92c6855fb8988b18a487cf9b"
  
  "@turf/hex-grid@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/hex-grid/-/hex-grid-3.5.3.tgz#a50c92cbdca03874793338be82728c910c674521"
    dependencies:
      "@turf/distance" "^3.5.3"
      "@turf/helpers" "^3.5.3"
  
  "@turf/idw@^3.5.3":
    version "3.6.0"
    resolved "https://registry.yarnpkg.com/@turf/idw/-/idw-3.6.0.tgz#df5d4028e6f772dcb05039649348dbf121b092d1"
    dependencies:
      "@turf/bbox" "^3.0.0"
      "@turf/centroid" "^3.0.0"
      "@turf/distance" "^3.0.0"
      "@turf/square-grid" "^3.0.0"
  
  "@turf/inside@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/inside/-/inside-3.5.3.tgz#4866e7eac228fb399296b5fa1fdd4d2f87b1c012"
    dependencies:
      "@turf/invariant" "^3.5.2"
  
  "@turf/intersect@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/intersect/-/intersect-3.5.3.tgz#9d1dfd2ba45cb80d075228d04de7c0bde2015351"
    dependencies:
      jsts "1.2.0"
  
  "@turf/invariant@^3.5.2":
    version "3.5.2"
    resolved "https://registry.yarnpkg.com/@turf/invariant/-/invariant-3.5.2.tgz#a4cbdfa625acbc57fe320db0c2a6325812a3291e"
  
  "@turf/isolines@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/isolines/-/isolines-3.5.3.tgz#2045fd9bd5b6bba7b33d084ec60803c714a3ec65"
    dependencies:
      "@turf/bbox" "^3.5.3"
      "@turf/distance" "^3.5.3"
      "@turf/helpers" "^3.5.3"
      "@turf/inside" "^3.5.3"
      "@turf/planepoint" "^3.5.2"
      "@turf/point-grid" "^3.5.3"
      "@turf/square" "^3.5.3"
      "@turf/tin" "^3.5.3"
  
  "@turf/kinks@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/kinks/-/kinks-3.5.3.tgz#826ff891e65b7d927d712a84ef673c6aacf34164"
    dependencies:
      "@turf/helpers" "^3.5.3"
  
  "@turf/line-distance@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/line-distance/-/line-distance-3.5.3.tgz#6a61e18fa51aa2c19bd6eb3baf55e7b78dc84be6"
    dependencies:
      "@turf/distance" "^3.5.3"
      "@turf/helpers" "^3.5.3"
  
  "@turf/line-slice-along@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/line-slice-along/-/line-slice-along-3.5.3.tgz#1809f4c9f66d2494624879d0493727cf4c054bff"
    dependencies:
      "@turf/bearing" "^3.5.2"
      "@turf/destination" "^3.5.3"
      "@turf/distance" "^3.5.3"
      "@turf/helpers" "^3.5.3"
  
  "@turf/line-slice@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/line-slice/-/line-slice-3.5.3.tgz#4323bc68343a7d6e8d62b5677689ba4a26e693c5"
    dependencies:
      "@turf/bearing" "^3.5.2"
      "@turf/destination" "^3.5.3"
      "@turf/distance" "^3.5.3"
      "@turf/helpers" "^3.5.3"
      "@turf/point-on-line" "^3.5.3"
  
  "@turf/meta@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/meta/-/meta-3.5.3.tgz#91bc7883e3ab8e76a9b09b9ea7b82cca24e35f05"
  
  "@turf/midpoint@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/midpoint/-/midpoint-3.5.3.tgz#7f364f60bab8ecd5b933cc516a4a48b603ab660d"
    dependencies:
      "@turf/bearing" "^3.5.2"
      "@turf/destination" "^3.5.3"
      "@turf/distance" "^3.5.3"
      "@turf/invariant" "^3.5.2"
  
  "@turf/nearest@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/nearest/-/nearest-3.5.3.tgz#684a8c01460ea5a7053702968e8806ec73d9b74c"
    dependencies:
      "@turf/distance" "^3.5.3"
  
  "@turf/planepoint@^3.5.2":
    version "3.5.2"
    resolved "https://registry.yarnpkg.com/@turf/planepoint/-/planepoint-3.5.2.tgz#2869d1e0c9bf69947a8e9d1f19baffe334ce8c0a"
  
  "@turf/point-grid@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/point-grid/-/point-grid-3.5.3.tgz#eacf0a7c09298a2720dddaf3943f7012e8f59304"
    dependencies:
      "@turf/distance" "^3.5.3"
      "@turf/helpers" "^3.5.3"
  
  "@turf/point-on-line@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/point-on-line/-/point-on-line-3.5.3.tgz#15c69cd243d76d0dcbc0143e980a0dfe06ebb7e8"
    dependencies:
      "@turf/bearing" "^3.5.2"
      "@turf/destination" "^3.5.3"
      "@turf/distance" "^3.5.3"
      "@turf/helpers" "^3.5.3"
  
  "@turf/point-on-surface@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/point-on-surface/-/point-on-surface-3.5.3.tgz#8ad020463e82e23beaff1e22006a160f3fa2d634"
    dependencies:
      "@turf/center" "^3.5.3"
      "@turf/distance" "^3.5.3"
      "@turf/explode" "^3.5.3"
      "@turf/helpers" "^3.5.3"
      "@turf/inside" "^3.5.3"
  
  "@turf/random@^3.5.2":
    version "3.5.2"
    resolved "https://registry.yarnpkg.com/@turf/random/-/random-3.5.2.tgz#c7da64cd8c09b835f89d984e834865cface13129"
    dependencies:
      geojson-random "^0.2.2"
  
  "@turf/sample@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/sample/-/sample-3.5.3.tgz#ca6a5274e8c896bb64b30330c51ac69201cb7ba8"
    dependencies:
      "@turf/helpers" "^3.5.3"
  
  "@turf/simplify@^3.5.2":
    version "3.5.2"
    resolved "https://registry.yarnpkg.com/@turf/simplify/-/simplify-3.5.2.tgz#3ab58e1cea2e5af73f55af973453247324913c23"
    dependencies:
      simplify-js "^1.2.1"
  
  "@turf/square-grid@^3.0.0", "@turf/square-grid@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/square-grid/-/square-grid-3.5.3.tgz#6954c83b2a373c9ae606400458b69a6f2b49dae3"
    dependencies:
      "@turf/distance" "^3.5.3"
      "@turf/helpers" "^3.5.3"
  
  "@turf/square@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/square/-/square-3.5.3.tgz#17ef27e8c51e46f6323bfe0e0a7effed913e54e5"
    dependencies:
      "@turf/distance" "^3.5.3"
      "@turf/helpers" "^3.5.3"
  
  "@turf/tag@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/tag/-/tag-3.5.3.tgz#e40739cb8a3ca4c91489b799b297d450c7434947"
    dependencies:
      "@turf/inside" "^3.5.3"
  
  "@turf/tesselate@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/tesselate/-/tesselate-3.5.3.tgz#fff40b3bb05d3a111363a1cde6b527cfe0f1180d"
    dependencies:
      "@turf/helpers" "^3.5.3"
      earcut "^2.0.0"
  
  "@turf/tin@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/tin/-/tin-3.5.3.tgz#07ef03c6fa5d5819b2806f82e05d9d759024c98b"
    dependencies:
      "@turf/helpers" "^3.5.3"
  
  "@turf/triangle-grid@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/triangle-grid/-/triangle-grid-3.5.3.tgz#0e5a07e65a35c872b39a5f24589d516d6e83561f"
    dependencies:
      "@turf/distance" "^3.5.3"
      "@turf/helpers" "^3.5.3"
  
  "@turf/turf":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/turf/-/turf-3.5.3.tgz#da4775c165d098b0e97610df4a0717f2e20e2dae"
    dependencies:
      "@turf/along" "^3.5.3"
      "@turf/area" "^3.5.2"
      "@turf/bbox" "^3.5.3"
      "@turf/bbox-polygon" "^3.5.3"
      "@turf/bearing" "^3.5.2"
      "@turf/bezier" "^3.5.3"
      "@turf/buffer" "^3.5.3"
      "@turf/center" "^3.5.3"
      "@turf/center-of-mass" "^3.5.3"
      "@turf/centroid" "^3.5.3"
      "@turf/circle" "^3.5.3"
      "@turf/collect" "^3.5.3"
      "@turf/combine" "^3.5.3"
      "@turf/concave" "^3.5.3"
      "@turf/convex" "^3.5.3"
      "@turf/destination" "^3.5.3"
      "@turf/difference" "^3.5.3"
      "@turf/distance" "^3.5.3"
      "@turf/envelope" "^3.5.3"
      "@turf/explode" "^3.5.3"
      "@turf/flip" "^3.5.3"
      "@turf/helpers" "^3.5.3"
      "@turf/hex-grid" "^3.5.3"
      "@turf/idw" "^3.5.3"
      "@turf/inside" "^3.5.3"
      "@turf/intersect" "^3.5.3"
      "@turf/invariant" "^3.5.2"
      "@turf/isolines" "^3.5.3"
      "@turf/kinks" "^3.5.3"
      "@turf/line-distance" "^3.5.3"
      "@turf/line-slice" "^3.5.3"
      "@turf/line-slice-along" "^3.5.3"
      "@turf/meta" "^3.5.3"
      "@turf/midpoint" "^3.5.3"
      "@turf/nearest" "^3.5.3"
      "@turf/planepoint" "^3.5.2"
      "@turf/point-grid" "^3.5.3"
      "@turf/point-on-line" "^3.5.3"
      "@turf/point-on-surface" "^3.5.3"
      "@turf/random" "^3.5.2"
      "@turf/sample" "^3.5.3"
      "@turf/simplify" "^3.5.2"
      "@turf/square" "^3.5.3"
      "@turf/square-grid" "^3.5.3"
      "@turf/tag" "^3.5.3"
      "@turf/tesselate" "^3.5.3"
      "@turf/tin" "^3.5.3"
      "@turf/triangle-grid" "^3.5.3"
      "@turf/union" "^3.5.2"
      "@turf/within" "^3.5.3"
  
  "@turf/union@^3.5.2":
    version "3.5.2"
    resolved "https://registry.yarnpkg.com/@turf/union/-/union-3.5.2.tgz#afa9cb7d6ae7b14739c211e3465280159ec8b99f"
    dependencies:
      jsts "1.2.0"
  
  "@turf/within@^3.5.3":
    version "3.5.3"
    resolved "https://registry.yarnpkg.com/@turf/within/-/within-3.5.3.tgz#903c9e86010b9cac55f69cc55845c6f945cf6ca5"
    dependencies:
      "@turf/helpers" "^3.5.3"
      "@turf/inside" "^3.5.3"

...

Trace: 
  Error: https://registry.yarnpkg.com/@turf/turf: Not found
      at Request.params.callback [as _callback] (/usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/lib/util/request-manager.js:294:18)
      at Request.self.callback (/usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/node_modules/request/request.js:187:22)
      at emitTwo (events.js:106:13)
      at Request.emit (events.js:191:7)
      at Request.<anonymous> (/usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/node_modules/request/request.js:1048:10)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:188:7)
      at IncomingMessage.<anonymous> (/usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/node_modules/request/request.js:969:12)
      at emitNone (events.js:91:20)
      at IncomingMessage.emit (events.js:185:7)

```

**Comment by ikhilko** [comment]
Looks like relates with https://github.com/yarnpkg/yarn/issues/620

**Comment by wyze** [comment]
Duplicate #620. This is fixed on master and will be in the next release.
