### ISSUE TITLE
peerflix problems

### ISSUE THREAD

**Issue by soredake** [yarnpkg/yarn#1851]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
yarn is not doing a this stage https://github.com/mafintosh/peerflix/blob/master/package.json#L17
and when manually linked throws this:
```
module.js:471
    throw err;
    ^

Error: Cannot find module 'optimist'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/bausch/.cache/yarn/npm-peerflix-0.36.0-fe3b087f07389ca1c2fd3d71e38a7971d5508924/app.js:3:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
```
yarn global add --ignore-engines --ignore-optional --prefix "$HOME/bin" peerflix@latest
cd "$HOME"/.cache/yarn/npm-peerflix-*
ln -s "$PWD"/app.js "$HOME"/bin/peerflix
```

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**
yarn 0.17.0
node 6.9.1

**Comment by bestander** [comment]
@soredake, is this a regression in 0.17 release?

**Comment by soredake** [comment]
No, it was in 0.16.1 and older.

**Comment by soredake** [comment]
0.17.3 fixed this, thanks.
