### ISSUE TITLE
Command `yarn --version` throws an error.

### ISSUE THREAD

**Issue by inglkruiz** [yarnpkg/yarn#1870]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Command `yarn --version` throws an error.

```
/home/myUser/.nvm/versions/node/v6.9.0/lib/node_modules/yarn/bin/yarn.js:47
      throw err;
      ^

Error: ENOENT: no such file or directory, open '/home/myUser/.cache/yarn/.roadrunner.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Install yarn 0.17.0 and run the command.

**What is the expected behavior?**
Get to know yarn version installed.

**Please mention your node.js, yarn and operating system version.**
node v6.9.0 - yarn 0.17.0 - Ubuntu 16.04.1 LTS 64-bit

**Comment by hpurmann** [comment]
Got nearly the same error, installed with brew.

node v7.1.0 - yarn 0.17.0 - macOS 10.12.1
```
➜  repo git:(master) yarn --version
0.17.0
/usr/local/Cellar/yarn/0.17.0/libexec/lib/node_modules/yarn/bin/yarn.js:47
      throw err;
      ^

Error: ENOENT: no such file or directory, open '/Users/myUser/Library/Caches/Yarn/.roadrunner.json'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.writeFileSync (fs.js:1214:33)
    at /usr/local/Cellar/yarn/0.17.0/libexec/lib/node_modules/yarn/node_modules/roadrunner/index.js:25:6
    at /usr/local/Cellar/yarn/0.17.0/libexec/lib/node_modules/yarn/node_modules/roadrunner/index.js:12:12
    at emitOne (events.js:101:20)
    at process.emit (events.js:188:7)
    at processEmit [as emit] (/usr/local/Cellar/yarn/0.17.0/libexec/lib/node_modules/yarn/node_modules/signal-exit/index.js:140:35)
    at process.exit (internal/process.js:147:15)
    at Command.<anonymous> (/usr/local/Cellar/yarn/0.17.0/libexec/lib/node_modules/yarn/node_modules/commander/index.js:825:13)
    at emitNone (events.js:91:20)
```

**Comment by wampiedriessen** [comment]
Is probably the same error as in #1834.
Fix is probably being picked into 0.17.1

**Comment by hpurmann** [comment]
I just cloned the repository to look into the problem myself. Now everything works, even when executed through brew.

**Comment by wyze** [comment]
Duplicate #1724.
