### ISSUE TITLE
Running yarn --version throws after upgrade

### ISSUE THREAD

**Issue by GlurG** [yarnpkg/yarn#1881]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Running `yarn --version` after upgrade results in an error.

````
/usr/local/lib/node_modules/yarn/bin/yarn.js:47
      throw err;
      ^

Error: ENOENT: no such file or directory, open '/Users/GlurG/Library/Caches/Yarn/.roadrunner.json'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.writeFileSync (fs.js:1214:33)
    at /usr/local/lib/node_modules/yarn/node_modules/roadrunner/index.js:25:6
    at /usr/local/lib/node_modules/yarn/node_modules/roadrunner/index.js:12:12
    at emitOne (events.js:101:20)
    at process.emit (events.js:188:7)
    at processEmit [as emit] (/usr/local/lib/node_modules/yarn/node_modules/signal-exit/index.js:140:35)
    at process.exit (internal/process.js:147:15)
    at Command.<anonymous> (/usr/local/lib/node_modules/yarn/node_modules/commander/index.js:825:13)
    at emitNone (events.js:91:20)
````

The issue disappears after running `yarn`.

**If the current behavior is a bug, please provide the steps to reproduce.**
1) `npm install -g yarn`
2) `yarn --version`

**What is the expected behavior?**
The version should be printed.

**Please mention your node.js, yarn and operating system version.**
Node 7.1.0
Yarn 0.17.2
MacOS 10.10.5

**Comment by WoodyWoodsta** [comment]
Dupe https://github.com/yarnpkg/yarn/issues/1724
