### ISSUE TITLE
Unable to run yarn tests

### ISSUE THREAD

**Issue by onemen** [yarnpkg/yarn#1883]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I have a local fork of yarn mater in my windows 10 laptop
I run ``` yarn run build``` after each pull, all the dependencies and devDependencies are up-to-date 
When I run ``` npm run test-only``` or ``` yarn run test-only```
I get this message:
```
yarn run v0.18.0-0
$ jest --coverage --verbose --maxWorkers 3
Determining test suites to run...events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
    at WriteStream.Socket._writeGeneric (net.js:683:19)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at VerboseReporter._clearStatus (C:\Users\Onemen\Documents\Incoming Mail\yarn\node_modules\jest-cli\build\reporters\DefaultReporter.js:98:12)
    at doFlush (C:\Users\Onemen\Documents\Incoming Mail\yarn\node_modules\jest-cli\build\reporters\DefaultReporter.js:67:12)
    at flush (C:\Users\Onemen\Documents\Incoming Mail\yarn\node_modules\jest-cli\build\reporters\DefaultReporter.js:77:9)
    at WriteStream.stream.write.chunk [as write] (C:\Users\Onemen\Documents\Incoming Mail\yarn\node_modules\jest-cli\build\reporters\DefaultReporter.js:91:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
``` yarn run test-only```

**What is the expected behavior?**
Run the tests

**Please mention your node.js, yarn and operating system version.**
Node v7.1.0
Yarn v0.18.0-0 (forked from master - https://github.com/yarnpkg/yarn.git)
Windows 10 - version 10.0.14393

**Comment by KidkArolis** [comment]
Does running an individual test work? e.g. `jest __tests__/commands/init.js`

**Comment by onemen** [comment]
No.

**Comment by onemen** [comment]
I found a workaround for this issue:
`jest __tests__/commands/init.js > nul`

all the tests work when i add `> nul`after the command

**Comment by torifat** [comment]
I'm facing the same thing and it's a `node` `v7.1.0` issue.

You will find details here: https://github.com/nodejs/node/issues/9542
