### ISSUE TITLE
 SyntaxError: /home/smalike/.yarn-cache/npm-faye-websocket-0.10.0/.yarn-metadata.json: Unexpected end of JSON input

### ISSUE THREAD

**Issue by smalike** [yarnpkg/yarn#1906]
Ubuntu 14.04

Nodejs: v6.0.0

yarn: 0.16.1

yarn-error.log:
```
Arguments: 
  /opt/node/bin/node /usr/share/yarn/bin/yarn.js

PATH: 
  /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/opt/node/bin

Yarn version: 
  0.16.1

Node version: 
  6.0.0

Platform: 
  linux x64

npm manifest: 
  {
    "name": "this-is-it-www",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "directories": {
      "test": "tests"
    },
    "scripts": {
      "test": "echo \"Error: no test specified\" && exit 1",
      "start": "nodemon ./src/index.js --debug",
      "server": "nodemon webpack.server.js",
      "browsersync": "node browsersync-server.js",
      "compile": "babel -d ./dest ./src",
      "publish": "webpack --config webpack.config.js",
      "debug-insp": "node-inspector",
      "debug-devtool": "devtool",
      "weinre": "weinre --boundHost 192.168.1.101 --httpPort 9090",
      "wpnode": "webpack --config webpack.node.config.babel.js"
    },
    "author": "smalike",
    "license": "ISC",
    "dependencies": {
      "classnames": "^2.2.3",
      "co-busboy": "^1.3.1",
      "crypto": "0.0.3",
      "es6-promise": "^3.1.2",
      "gm": "^1.22.0",
      "isomorphic-fetch": "^2.2.1",
      "jssha": "^2.0.2",
      "koa": "^1.1.2",
      "koa-handlebars": "^0.5.7",
      "koa-logger": "^1.3.0",
      "koa-onerror": "^1.2.1",
      "koa-router": "^5.3.0",
      "koa-session": "^3.3.1",
      "koa-static": "^2.0.0",
      "koa.io": "0.0.3",
      "md5": "^2.1.0",
      "mongoose": "^4.3.5",
      "react": "^0.14.6",
      "react-addons-css-transition-group": "^0.14.7",
      "react-dom": "^0.14.6",
      "react-redux": "^4.0.6",
      "react-router": "^2.0.0",
      "redux": "^3.0.5",
      "redux-thunk": "^1.0.3",
      "sharp": "^0.14.0",
      "socket.io-client": "^1.4.5",
      "whatwg-fetch": "^0.11.0"
    },
    "devDependencies": {
      "babel-cli": "^6.5.1",
      "babel-core": "^6.4.0",
      "babel-loader": "^6.2.1",
      "babel-plugin-react-transform": "^2.0.0",
      "babel-plugin-transform-object-assign": "^6.5.0",
      "babel-polyfill": "^6.7.4",
      "babel-preset-es2015": "^6.3.13",
      "babel-preset-react": "^6.3.13",
      "babel-preset-react-hmre": "^1.0.1",
      "babel-runtime": "^6.3.19",
      "bs-fullscreen-message": "^1.0.2",
      "css-loader": "^0.23.1",
      "extract-text-webpack-plugin": "^1.0.1",
      "font-awesome-webpack": "0.0.4",
      "handlebars": "^4.0.5",
      "handlebars-loader": "^1.2.0",
      "html-webpack-plugin": "^2.16.0",
      "less": "^2.5.3",
      "less-loader": "^2.2.2",
      "node-inspector": "^0.12.7",
      "node-sass": "^3.4.2",
      "nodemon": "^1.9.1",
      "react-transform-hmr": "^1.0.1",
      "redux-devtools": "^3.1.1",
      "redux-devtools-dock-monitor": "^1.1.0",
      "redux-devtools-inspector": "^0.3.1",
      "redux-devtools-log-monitor": "^1.0.5",
      "redux-slider-monitor": "^1.0.2",
      "sass-loader": "^3.1.2",
      "strip-ansi": "^3.0.1",
      "style-loader": "^0.13.0",
      "url-loader": "^0.5.7",
      "webpack": "^1.12.10",
      "webpack-dev-middleware": "^1.6.1",
      "webpack-dev-server": "^1.14.0",
      "webpack-hot-middleware": "^2.6.0"
    }
  }
```

```
yarn manifest: 
  No manifest

bower manifest: 
  No manifest

Lockfile: 
  No lockfile
```

```
Trace: 
  SyntaxError: /home/smalike/.yarn-cache/npm-faye-websocket-0.10.0/.yarn-metadata.json: Unexpected end of JSON input
      at Object.parse (native)
      at /usr/share/yarn/lib/util/fs.js:271:57
      at next (native)
      at step (/usr/share/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /usr/share/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
      at run (/usr/share/yarn/node_modules/core-js/library/modules/es6.promise.js:87:22)
      at /usr/share/yarn/node_modules/core-js/library/modules/es6.promise.js:100:28
      at flush (/usr/share/yarn/node_modules/core-js/library/modules/_microtask.js:18:9)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by wyze** [comment]
Duplicate #660.
