### ISSUE TITLE
Test run fails

### ISSUE THREAD

**Issue by hpurmann** [yarnpkg/yarn#1968]
When running `yarn test-only`, the "install a scoped module from authed private registry" always fails. Even after removing `lib` and `lib-legacy` and re-buiding with `yarn build`.

```
Summary of all failing tests
 FAIL  __tests__/commands/install.js (27.264s)
  ● install a scoped module from authed private registry

    AssertionError: 'Bearer 8849862e-5244-4083-9771-353d1c4058b3' == 'Bearer abc123'

      at __tests__/commands/install.js:790:71
          at Generator.next (<anonymous>)
      at step (node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
      at F (node_modules/core-js/library/modules/_export.js:35:28)
      at node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
      at __tests__/commands/install.js:795:48
      at __tests__/commands/_install.js:115:17
          at Generator.next (<anonymous>)
      at step (node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      Console output:
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
warning No license field
success Folder in sync.

      at __tests__/commands/_install.js:124:13
          at Generator.throw (<anonymous>)
      at step (node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/babel-runtime/helpers/asyncToGenerator.js:30:20


Test Suites: 1 failed, 1 skipped, 35 passed, 36 of 37 total
Tests:       1 failed, 18 skipped, 278 passed, 297 total
Snapshots:   50 passed, 50 total
Time:        28.022s
Ran all test suites.
error Command failed with exit code 1.
```

This is really strange because `yarn test-ci` always succeeds.

node `6.9.1`, yarn `0.17.6`

**Comment by torifat** [comment]
@hpurmann running via `yarn` pass the token from config file. if you run `jest --coverage --verbose --maxWorkers 3` directly it will work.

BTW, I have removed your token from the description 😉

**Comment by torifat** [comment]
It's a bug I think, local `npmrc` should always override the global one. Need to figure out the reason. Something with the `run` command.

**Comment by hpurmann** [comment]
Oh damn, thank you for removing the token! I invalidated it, just to be sure.

You are right, `jest --coverage --verbose --maxWorkers 3` works when I install `jest` globally. When running `./node_modules/.bin/jest --coverage --verbose --maxWorkers 3` it doesn't work in node 7 (but this will be another issue, `UnhandledPromiseRejectionWarning`).

Yeah it's another weird case that `yarn test-ci` works differently than manually building and runnnig `test-only`.

**Comment by hpurmann** [comment]
@torifat you are right, it is the run command which apparently works slightly different than `npm`s.

`yarn test-ci` does a `npm run test-only` whereas `yarn test-only` uses `yarn` to run. I'll rename this issue to reflect this.
