### ISSUE TITLE
prebuild --install of gl fails with yarn, works with npm

### ISSUE THREAD

**Issue by scjody** [yarnpkg/yarn#1987]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

`yarn add gl@4.0.2` from a clean directory fails:

```
yarn add v0.17.8
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/1] ⢀ gl: '-Goutput_dir=.' ]
[-/1] ⢀ waiting...
[-/1] ⠠ waiting...
[-/1] ⠠ waiting...
error /home/vagrant/yarn/node_modules/gl: Command failed.
Exit code: 2
Command: sh
Arguments: -c prebuild --install
Directory: /home/vagrant/yarn/node_modules/gl
Output:
prebuild info begin Prebuild version 4.4.0
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/vagrant/yarn/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/vagrant/yarn/node_modules/gl/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/vagrant/yarn/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/vagrant/.node-gyp/6.7.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/vagrant/.node-gyp/6.7.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/vagrant/yarn/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/vagrant/yarn/node_modules/gl',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
Package xi was not found in the pkg-config search path.
Perhaps you should add the directory containing `xi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xi' found
Package xext was not found in the pkg-config search path.
Perhaps you should add the directory containing `xext.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xext' found
gyp: Call to 'pkg-config --libs-only-l x11 xi xext' returned exit status 1 while in angle/src/angle.gyp. while loading dependencies of binding.gyp while trying to load binding.gyp
prebuild ERR! configure error
prebuild ERR! stack Error: `gyp` failed with exit code: 1
prebuild ERR! stack     at ChildProcess.onCpExit (/home/vagrant/yarn/node_modules/node-gyp/lib/configure.js:305:16)
prebuild ERR! stack     at emitTwo (events.js:106:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:191:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
prebuild ERR! not ok
prebuild ERR! build Error: `gyp` failed with exit code: 1
prebuild ERR! build     at ChildProcess.onCpExit (/home/vagrant/yarn/node_modules/node-gyp/lib/configure.js:305:16)
prebuild ERR! build     at emitTwo (events.js:106:13)
prebuild ERR! build     at ChildProcess.emit (events.js:191:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

`yarn add gl@4.0.2` (from a clean directory, to avoid potential issues caused by other modules)

**What is the expected behavior?**

gl is installed. This works with npm:

```
$ npm install gl@4.0.2

> gl@4.0.2 install /home/vagrant/npm/node_modules/gl
> prebuild --install

/home/vagrant/npm
└─┬ gl@4.0.2
  ├── bindings@1.2.1
  ├── bit-twiddle@1.0.2  ├─┬ glsl-tokenizer@2.1.2
[Snipped. Let me know if the rest of the tree is useful and I'll send it.]
    │   └── util-deprecate@1.0.2
    └── xtend@4.0.1

npm WARN enoent ENOENT: no such file or directory, open '/home/vagrant/npm/package.json'
npm WARN npm No description
npm WARN npm No repository field.
npm WARN npm No README data
npm WARN npm No license field.
```

**Please mention your node.js, yarn and operating system version.**

```
$ node --version
v6.7.0
$ yarn --version
0.17.8
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```

**This may be related to #1986 but the output is significantly different so I'm logging a separate issue.**

**Comment by corbinu** [comment]
@scjody The issue is you don't have the libraries need to build the native module from scratch. Your not seeing it on npm because yarn does not support the package format that prebuild needs to download the prebuilt binary. This is in issue #1050

You can simply install the x11, xi and xext in your vagrant vm. On ubuntu this would probably be `xserver-xorg-dev libxext-dev`

However because the package will be rebuilt each time yarn will still be far slower than npm until this is fixed.

**Comment by scjody** [comment]
Cool, thanks for the info. I'm going to close this now since it sounds like all the work on your end is covered by #1050.
