### ISSUE TITLE
unexpected eof when making yarn upgrade or yarn add

### ISSUE THREAD

**Issue by Oxyaction** [yarnpkg/yarn#1990]
After publishing package via `yarn publish` and then trying to install it with
`yarn upgrade` or `yarn add` getting next error:
```
yarn upgrade react-native-ducks-router
yarn upgrade v0.17.8
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/react-native-ducks-router/-/react-native-ducks-router-0.1.26.tgz: unexpected eof".
info If you think this is a bug, please open a bug report with the information provided in "/Users/alexandrkompaniets/web/age/walletclient/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.
```
Here is the content of `yarn-error.log`
```
Trace:
  Error: https://registry.yarnpkg.com/react-native-ducks-router/-/react-native-ducks-router-0.1.26.tgz: unexpected eof
      at decorate (/usr/local/Cellar/yarn/0.17.8/libexec/lib/node_modules/yarn/node_modules/fstream/lib/abstract.js:67:36)
      at Extract.Abstract.error (/usr/local/Cellar/yarn/0.17.8/libexec/lib/node_modules/yarn/node_modules/fstream/lib/abstract.js:61:12)
      at Extract._streamEnd (/usr/local/Cellar/yarn/0.17.8/libexec/lib/node_modules/yarn/node_modules/tar/lib/extract.js:91:35)
      at BlockStream.<anonymous> (/usr/local/Cellar/yarn/0.17.8/libexec/lib/node_modules/yarn/node_modules/tar/lib/parse.js:51:8)
      at emitNone (events.js:86:13)
      at BlockStream.emit (events.js:185:7)
      at BlockStream._emitChunk (/usr/local/Cellar/yarn/0.17.8/libexec/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:203:10)
      at BlockStream.resume (/usr/local/Cellar/yarn/0.17.8/libexec/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:58:15)
      at Extract.Reader.resume (/usr/local/Cellar/yarn/0.17.8/libexec/lib/node_modules/yarn/node_modules/fstream/lib/reader.js:249:34)
      at Entry.<anonymous> (/usr/local/Cellar/yarn/0.17.8/libexec/lib/node_modules/yarn/node_modules/tar/lib/parse.js:261:8)
```
After some workaround we found that the problem is in `yarn publish` because after `npm publish` it became available, and was installed via yarn without errors.

node version: __v7.1.0__
yarn version: __0.17.8__

**Comment by DefCon-007** [comment]
@Oxyaction  Were you able to resolve this. I am also facing the same issue.

**Comment by BYK** [comment]
I suggest using a newer version of Yarn. ).17.x is pretty old.

**Comment by MaxCCC** [comment]
@BYK I'm facing this issue during a yarn install with v0.23.4. Always on another .tgz from our npm repo

**Comment by Oxyaction** [comment]
Can not reproduce it with yarn **1.0.1**, looks like problem is fixed

**Comment by BYK** [comment]
Thanks @Oxyaction!
