### ISSUE TITLE
Importing yarn cache on CircleCI misses certain dependency files

### ISSUE THREAD

**Issue by joemckie** [yarnpkg/yarn#2014]
*NOTE: I've currently got around this by running* `yarn cache clean` *before installing dependencies*.

**Do you want to request a *feature* or report a *bug*?**

A bug. Not sure whether this is an issue with Yarn or with CircleCI, though.

**What is the current behavior?**

When loading files from the cache on CircleCI (cache is generated by following [these](https://yarnpkg.com/en/docs/install-ci#circle-tab) instructions), some files aren't loaded from the cache correctly. A good example of one of these files is `flow` from the `flow-bin` package. Running `flow` will result in an ENOENT error.

Like so:

```
> flow; test $? -eq 0 -o $? -eq 2

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/ubuntu/native-app/node_modules/flow-bin/vendor/flow ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:609:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Hard to tell how best to reproduce this... Build a project using CircleCI and yarn, then install flow & try to run it?

My circle.yml can be found [here](https://gist.github.com/joemckie/ddefb638577c34f50146d16d86a03fb1)

**What is the expected behavior?**

It should get the correct files.

**Please mention your node.js, yarn and operating system version.**

- Node 7.2.0
- Yarn 0.17.8

**Comment by bestander** [comment]
Is it 100% reproducing?
Could it be related to https://github.com/yarnpkg/yarn/issues/2035?

**Comment by moimael** [comment]
It is 100% reproductible for me and was actually the issue I was encountering here: #1933
Upgrading to 0.18.0 I know hae this output on circle ci : 
```bashyarn build v0.18.0
$ yarn run clean && yarn build-client && cp -r src dist && yarn build-server 
yarn run v0.18.0
$ rm -rf dist 
Done in 0.10s.
yarn build-client v0.18.0
$ NODE_ENV=production node --harmony ./node_modules/webpack/bin/webpack.js -p 
module.js:471
    throw err;
    ^

Error: Cannot find module 'assets-webpack-plugin'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/galaxy/webpack.config.js:3:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at require (internal/module.js:20:19)
error Command failed with exit code 1.
error Command failed with exit code 1.

yarn build returned exit code 1
```

**Comment by bestander** [comment]
@moimael, if you run `yarn cache clean` or clean Circle caches once will it start working?
I think it is related to https://github.com/yarnpkg/yarn/issues/2035

**Comment by moimael** [comment]
Unfortunately no, it seems that `yarn cache clean` has no effect on it.

**Comment by bestander** [comment]
In 0.17 we changed cache location the instructions are not correct anymore https://yarnpkg.com/en/docs/install-ci#circle-tab.

It is different for different OS and configs.
Could you set up Circle to use path from `yarn cache dir` output?

**Comment by moimael** [comment]
I tried it and I have the exact same output.

**Comment by MoOx** [comment]
I am facing issues as well and tried multiples instructions but this issue keep coming to my face again and again.

@bestander I just tried https://circleci.com/docs/install-and-use-yarn/ does it look good?
It's really confusing that the website show out of date instruction. I always have to rebuild without cache again and again :(

**Comment by bestander** [comment]
@MoOx, the guide in the website may be a bit outdated, would you send a PR for https://github.com/yarnpkg/website/blob/master/en/docs/_ci/circle.md?

Do you have problems with caches even when following https://circleci.com/docs/install-and-use-yarn/?
May be the reason is that we switched cache directory recently.
```
yarn cache dir
```
Would tell you what folder is used in Circle.

**Comment by MoOx** [comment]
I tried all techniques I found, none is better and I always have similar issue. The issue came when the cache is restored, no issue without the cache.

**Comment by bestander** [comment]
@MoOx, can you help me and provide a bit more data?
Do you have a broken install if you use Circle CI with caches?
Without caches it works fine?

A few commands to debug what is going on:
- `yarn cache ls` - lists everything that is in cache
- `yarn install --force` - will force install if there is something in node_modules present
- `yarn check` - verifies correctness of node_modules structure

**Comment by bestander** [comment]
@moimael, your issue looks unrelated to this one.
Do you get in incomplete node_modules after install no matter of caches?
Is it only on Circle, can you reproduce locally?

**Comment by simoami** [comment]
same issue here with circleci failing eslint:
```
$ yarn test
yarn test v0.18.1
$ npm run lint && nsp check

> hs-service-apigateway@1.0.0 lint /home/ubuntu/hs-service-apigateway
> eslint .

module.js:471
    throw err;
    ^

Error: Cannot find module 'concat-stream'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/.cache/yarn/npm-eslint-3.16.1-9bc31fc7341692cf772e80607508f67d711c5609/bin/eslint.js:30:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by gdaolewe** [comment]
Saw the same error as OP, but on Travis CI, with Yarn 0.22.0 and flow-bin 0.30.0. If while debugging the Travis build I run `yarn add --force flow-bin@0.30.0`, that fixes it, but when I run the build again I get the same error.

```
flow version && flow check 
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: spawn /home/travis/build/seatgeek/sellerdirect-portal/node_modules/flow-bin/vendor/flow ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
error Command failed with exit code 1.
```

**Comment by gdaolewe** [comment]
I fixed the above by clearing Travis' build cache for my project.

**Comment by bilby91** [comment]
I have a similar problem, after cache is restored, some packages are missing. I don't have the problem locally and I didn't have the problem before with Circle. I'm using this [docs](https://circleci.com/docs/1.0/yarn/)

**Comment by BYK** [comment]
Closing due to inactivity.
