### ISSUE TITLE
Can't access to module (EACCES: permission denied)

### ISSUE THREAD

**Issue by feddasch** [yarnpkg/yarn#2197]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

```
casa@solarium ~/Git> hexo init blog
fs.js:557
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/usr/local/share/.config/yarn/global/node_modules/arr-flatten/index.js'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at Object.Module._extensions..js (module.js:579:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/arr-diff/index.js:10:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

- Install Hexo (`sudo yarn global add hexo-cli`).
- Try to run a command.

**What is the expected behavior?**
Quite obvious: modules should be readable so the program can work.

**Please mention your node.js, yarn and operating system version.**
- NodeJS `7.2.0`
- Yarn `0.18.0`
- Solus 1.2.1

**Comment by noahziheng** [comment]
same bug on Arch Linux,yarn 0.20.3

**Comment by feddasch** [comment]
I had set the `prefix` setting so this no longer affects me
