### ISSUE TITLE
Bug with es6.promise.js

### ISSUE THREAD

**Issue by Datamance** [yarnpkg/yarn#2237]
Here's my bug report, just started a brand new project with an existent package.json, wanted to try out yarn and here's what I saw:

Arguments: 
  /usr/local/bin/node /usr/local/bin/yarn init

PATH: 
  /Applications/Postgres.app/Contents/Versions/latest/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin

Yarn version: 
  0.17.10

Node version: 
  6.2.2

Platform: 
  darwin x64

npm manifest: 
  {
    "name": "datamance-web",
    "version": "0.1.0",
    "description": "The client code for datamance.",
    "author": "Rico Rodriguez <rico.l.rodriguez@gmail.com>",
    "main": "index.js",
    "scripts": {
      "test": "test"
    },
    "repository": {
      "type": "git",
      "url": "git+https://github.com/Datamance/datamance.git"
    },
    "keywords": [
      "knowledge",
      "graph"
    ],
    "license": "MIT",
    "bugs": {
      "url": "https://github.com/Datamance/datamance/issues"
    },
    "homepage": "https://github.com/Datamance/datamance#readme",
    "dependencies": {
      "babel-core": "^6.20.0",
      "rollup": "^0.37.0",
      "rollup-plugin-babel": "^2.7.0",
      "rollup-plugin-closure-compiler-js": "^1.0.2",
      "rollup-plugin-json": "^2.0.2",
      "rollup-plugin-svelte": "^1.2.0",
      "svelte": "^1.2.3",
      "svelte-cli": "^1.2.1"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  TypeError: Cannot convert object to primitive value
      at Object.<anonymous> (/usr/local/Cellar/yarn/0.17.10/libexec/lib/node_modules/yarn/lib/cli/commands/init.js:93:27)
      at next (native)
      at step (/usr/local/Cellar/yarn/0.17.10/libexec/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /usr/local/Cellar/yarn/0.17.10/libexec/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
      at run (/usr/local/Cellar/yarn/0.17.10/libexec/lib/node_modules/yarn/node_modules/core-js/library/modules/es6.promise.js:87:22)
      at /usr/local/Cellar/yarn/0.17.10/libexec/lib/node_modules/yarn/node_modules/core-js/library/modules/es6.promise.js:100:28
      at flush (/usr/local/Cellar/yarn/0.17.10/libexec/lib/node_modules/yarn/node_modules/core-js/library/modules/_microtask.js:18:9)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by paul-soporan** [comment]
Closing as most probably fixed in v1 (and if not, it's definitely fixed in v2).
