### ISSUE TITLE
cannot find correct command path

### ISSUE THREAD

**Issue by kagawagao** [yarnpkg/yarn#2252]
**Do you want to request a *feature* or report a *bug*?**

A bug
**What is the current behavior?**
yarn connot find correct path when run command
**If the current behavior is a bug, please provide the steps to reproduce.**

`package.json`:

```json
{
  "scripts": {
    "dev": "better-npm-run dev",
    "test": "better-npm-run test",
    "test:dev": "npm run test -- --watch",
    "lint": "eslint --max-warnings 10 .",
    "lint:fix": "npm run lint -- --fix",
    "lint:flow": "flow check"
  },
  "betterScripts": {
    "dev": {
      "command": "nodemon --exec webpack-dev-server --progress",
      "env": {
        "NODE_ENV": "development",
        "DEBUG": "app:*"
      }
    },
    "test": {
      "command": "babel-node ./node_modules/karma/bin/karma start karma.config",
      "env": {
        "NODE_ENV": "test",
        "DEBUG": "app:*"
      }
    }
  },
  "dependencies": {
    "antd": "^2.5.2",
    "react": "^15.4.1",
    "react-dom": "^15.4.1",
    "react-redux": "^4.4.6",
    "react-router": "^3.0.0",
    "redux": "^3.6.0",
    "redux-promise": "^0.5.3"
  },
  "devDependencies": {
    "babel-cli": "^6.18.0",
    "babel-core": "^6.20.0",
    "babel-eslint": "^7.1.1",
    "babel-loader": "^6.2.9",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-istanbul": "^3.0.0",
    "babel-plugin-transform-runtime": "^6.15.0",
    "babel-preset-latest": "^6.16.0",
    "babel-preset-react": "^6.16.0",
    "babel-preset-stage-0": "^6.16.0",
    "better-npm-run": "^0.0.13",
    "chai": "^3.5.0",
    "chai-as-promised": "^6.0.0",
    "chai-enzyme": "^0.6.1",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.26.1",
    "debug": "^2.3.3",
    "enzyme": "^2.6.0",
    "eslint": "^3.12.1",
    "eslint-config-standard": "^6.2.1",
    "eslint-config-standard-react": "^4.2.0",
    "eslint-friendly-formatter": "^2.0.6",
    "eslint-loader": "^1.6.1",
    "eslint-plugin-babel": "^4.0.0",
    "eslint-plugin-flowtype": "^2.29.1",
    "eslint-plugin-flowtype-errors": "^2.0.1",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-react": "^6.8.0",
    "eslint-plugin-standard": "^2.0.1",
    "extract-text-webpack-plugin": "2.0.0-beta.4",
    "file-loader": "^0.9.0",
    "flow-bin": "^0.37.0",
    "html-webpack-plugin": "^2.24.1",
    "json-loader": "^0.5.4",
    "karma": "^1.3.0",
    "karma-coverage": "^1.1.1",
    "karma-es6-shim": "^1.0.0",
    "karma-mocha": "^1.3.0",
    "karma-mocha-reporter": "^2.2.1",
    "karma-phantomjs-launcher": "^1.0.2",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^1.8.0",
    "karma-webpack-with-fast-source-maps": "^1.10.0",
    "mocha": "^3.2.0",
    "nodemon": "^1.11.0",
    "phantomjs-polyfill": "^0.0.2",
    "phantomjs-prebuilt": "^2.1.14",
    "postcss-loader": "^1.2.1",
    "react-addons-test-utils": "^15.4.1",
    "react-hot-loader": "^3.0.0-beta.6",
    "sinon": "^2.0.0-pre.4",
    "sinon-chai": "^2.8.0",
    "style-loader": "^0.13.1",
    "stylelint": "^7.6.0",
    "stylelint-config-standard": "^15.0.0",
    "url-loader": "^0.5.7",
    "webpack": "2.1.0-beta.27",
    "webpack-dev-server": "2.1.0-beta.12",
    "yargs": "^6.5.0"
  }
}

```

when i run script, `cmd` path is `yarn` cache path, ie.
```bash
$ npm test

> react-admin@1.0.0-alpha.1 test d:\desk\gitlab\react-admin
> better-npm-run test

module.js:472
    throw err;
    ^

Error: Cannot find module 'd:\desk\gitlab\react-admin\node_modules\.bin\C:\Users\Administrator\AppData\Local\Yarn\cache\npm-better-npm-run-0.0.13-38a340d0546c831ce80bae66d4def19c5c7ee963\index.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
npm ERR! Test failed.  See above for more details.
```

**What is the expected behavior?**
find `cmd` by correct path

**Please mention your node.js, yarn and operating system version.**
- node: `v7.2.1`
- npm: `v4.0.3`
- yarn: `0.17.10`
- OS: `Win 64`

**Comment by kagawagao** [comment]
maybe caused by `$basedir`:
```sh
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/C:/Users/Administrator/AppData/Local/Yarn/cache/npm-better-npm-run-0.0.13-38a340d0546c831ce80bae66d4def19c5c7ee963/index.js" "$@"
  ret=$?
else 
  node  "$basedir/C:/Users/Administrator/AppData/Local/Yarn/cache/npm-better-npm-run-0.0.13-38a340d0546c831ce80bae66d4def19c5c7ee963/index.js" "$@"
  ret=$?
fi
exit $ret
```
