### ISSUE TITLE
Skipped Optional Dependency Causes Error During [4/4] Building fresh packages...

### ISSUE THREAD

**Issue by ryanelian** [yarnpkg/yarn#2282]
**Version:** 0.17.10
**OS:** Windows 10 64-bit

**Bug:** 

The package that caused the bug in question is `fsevents` when installed in Windows, apparently.
```
E:\VS\ryan-compiler\ryan-compiler>yarn why fsevents
yarn why v0.17.10
[1/4] Why do we have the module "fsevents"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
info This module exists because "gulp-watch#chokidar" depends on it.
Done in 1.78s.
```

When installing `gulp-watch`, which contains `chokidar` using NPM, these messages will appear:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```

When `yarn` is used instead, it does this:
```
E:\VS\ryan-compiler\ryan-compiler>yarn
yarn install v0.17.10
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.15: The platform "win32" is incompatible with this module.
info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/2] ⠠ node-sass: Downloading binary from https://github.com/sass/node-sass/releases/download/v4.0.0/win32-x64
[2/2] ⠠ fsevents: info spawn args   '-Goutput_dir=.' ]
[-/2] ⠠ waiting...
[-/2] ⠠ waiting...
error Error running install script for optional dependency: "E:\\VS\\ryan-compiler\\ryan-compiler\\node_modules\\fsevents: Command failed.\nExit code: 1\nCommand: C:\\Windows\\system32\\cmd.exe\nArguments: /d /s /c node-pre-gyp install --fallback-to-build\nDirectory: E:\\VS\\ryan-compiler\\ryan-compiler\\node_modules\\fsevents\nOutput:\nnode-pre-gyp info it worked if it ends with ok\nnode-pre-gyp info using node-pre-gyp@0.6.29\nnode-pre-gyp info using node@6.9.2 | win32 | x64\nnode-pre-gyp info check checked for \"E:\\VS\\ryan-compiler\\ryan-compiler\\node_modules\\fsevents\\lib\\binding\\Release\\node-v48-win32-x64\\fse.node\" (not found)\nnode-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.15/fse-v1.0.15-node-v48-win32-x64.tar.gz\nnode-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.15/fse-v1.0.15-node-v48-win32-x64.tar.gz\nnode-pre-gyp ERR! Tried to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.15/fse-v1.0.15-node-v48-win32-x64.tar.gz \nnode-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.15 and node@6.9.2 (node-v48 ABI) (falling back to source compile with node-gyp) \nnode-pre-gyp http Pre-built binary not available for your system, looked for https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.15/fse-v1.0.15-node-v48-win32-x64.tar.gz \ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.4.0\ngyp info using node@6.9.2 | win32 | x64\ngyp info ok \ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.4.0\ngyp info using node@6.9.2 | win32 | x64\ngyp info spawn C:\\Python27\\python.EXE\ngyp info spawn args [ 'E:\\\\VS\\\\ryan-compiler\\\\ryan-compiler\\\\node_modules\\\\node-gyp\\\\gyp\\\\gyp_main.py',\ngyp info spawn args   'binding.gyp',\ngyp info spawn args   '-f',\ngyp info spawn args   'msvs',\ngyp info spawn args   '-G',\ngyp info spawn args   'msvs_version=auto',\ngyp info spawn args   '-I',\ngyp info spawn args   'E:\\\\VS\\\\ryan-compiler\\\\ryan-compiler\\\\node_modules\\\\fsevents\\\\build\\\\config.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   'E:\\\\VS\\\\ryan-compiler\\\\ryan-compiler\\\\node_modules\\\\node-gyp\\\\addon.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   'C:\\\\Users\\\\Ryan\\\\.node-gyp\\\\6.9.2\\\\include\\\\node\\\\common.gypi',\ngyp info spawn args   '-Dlibrary=shared_library',\ngyp info spawn args   '-Dvisibility=default',\ngyp info spawn args   '-Dnode_root_dir=C:\\\\Users\\\\Ryan\\\\.node-gyp\\\\6.9.2',\ngyp info spawn args   '-Dnode_gyp_dir=E:\\\\VS\\\\ryan-compiler\\\\ryan-compiler\\\\node_modules\\\\node-gyp',\ngyp info spawn args   '-Dnode_lib_file=node.lib',\ngyp info spawn args   '-Dmodule_root_dir=E:\\\\VS\\\\ryan-compiler\\\\ryan-compiler\\\\node_modules\\\\fsevents',\ngyp info spawn args   '--depth=.',\ngyp info spawn args   '--no-parallel',\ngyp info spawn args   '--generator-output',\ngyp info spawn args   'E:\\\\VS\\\\ryan-compiler\\\\ryan-compiler\\\\node_modules\\\\fsevents\\\\build',\ngyp info spawn args   '-Goutput_dir=.' ]\nTraceback (most recent call last):\r\n  File \"E:\\VS\\ryan-compiler\\ryan-compiler\\node_modules\\node-gyp\\gyp\\gyp_main.py\", line 16, in <module>\r\n    sys.exit(gyp.script_main())\r\n  File \"E:\\VS\\ryan-compiler\\ryan-compiler\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\__init__.py\", line 545, in script_main\r\n    return main(sys.argv[1:])\r\n  File \"E:\\VS\\ryan-compiler\\ryan-compiler\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\__init__.py\", line 538, in main\r\n    return gyp_main(args)\r\n  File \"E:\\VS\\ryan-compiler\\ryan-compiler\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\__init__.py\", line 523, in gyp_main\r\n    generator.GenerateOutput(flat_list, targets, data, params)\r\n  File \"E:\\VS\\ryan-compiler\\ryan-compiler\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\generator\\msvs.py\", line 2003, in GenerateOutput\r\n    sln_projects, project_objects, flat=msvs_version.FlatSolution())\r\n  File \"E:\\VS\\ryan-compiler\\ryan-compiler\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\generator\\msvs.py\", line 1762, in _GatherSolutionFolders\r\n    return _DictsToFolders('', root, flat)\r\n  File \"E:\\VS\\ryan-compiler\\ryan-compiler\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\generator\\msvs.py\", line 1715, in _DictsToFolders\r\n    for folder, contents in bucket.iteritems():\r\nAttributeError: 'MSVSProject' object has no attribute 'iteritems'\r\ngyp ERR! configure error \ngyp ERR! stack Error: `gyp` failed with exit code: 1\ngyp ERR! stack     at ChildProcess.onCpExit (E:\\VS\\ryan-compiler\\ryan-compiler\\node_modules\\node-gyp\\lib\\configure.js:305:16)\ngyp ERR! stack     at emitTwo (events.js:106:13)\ngyp ERR! stack     at ChildProcess.emit (events.js:191:7)\ngyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)\ngyp ERR! System Windows_NT 10.0.14393\ngyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"E:\\\\VS\\\\ryan-compiler\\\\ryan-compiler\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"configure\" \"--fallback-to-build\" \"--module=E:\\\\VS\\\\ryan-compiler\\\\ryan-compiler\\\\node_modules\\\\fsevents\\\\lib\\\\binding\\\\Release\\\\node-v48-win32-x64\\\\fse.node\" \"--module_name=fse\" \"--module_path=E:\\\\VS\\\\ryan-compiler\\\\ryan-compiler\\\\node_modules\\\\fsevents\\\\lib\\\\binding\\\\Release\\\\node-v48-win32-x64\"\ngyp ERR! cwd E:\\VS\\ryan-compiler\\ryan-compiler\\node_modules\\fsevents\ngyp ERR! node -v v6.9.2\ngyp ERR! node-gyp -v v3.4.0\ngyp ERR! not ok \nnode-pre-gyp ERR! build error \nnode-pre-gyp ERR! stack Error: Failed to execute 'C:\\Program Files\\nodejs\\node.exe E:\\VS\\ryan-compiler\\ryan-compiler\\node_modules\\node-gyp\\bin\\node-gyp.js configure --fallback-to-build --module=E:\\VS\\ryan-compiler\\ryan-compiler\\node_modules\\fsevents\\lib\\binding\\Release\\node-v48-win32-x64\\fse.node --module_name=fse --module_path=E:\\VS\\ryan-compiler\\ryan-compiler\\node_modules\\fsevents\\lib\\binding\\Release\\node-v48-win32-x64' (1)\nnode-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\\VS\\ryan-compiler\\ryan-compiler\\node_modules\\fsevents\\node_modules\\node-pre-gyp\\lib\\util\\compile.js:83:29)\nnode-pre-gyp ERR! stack     at emitTwo (events.js:106:13)\nnode-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)\nnode-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)\nnode-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)\nnode-pre-gyp ERR! System Windows_NT 10.0.14393\nnode-pre-gyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"E:\\\\VS\\\\ryan-compiler\\\\ryan-compiler\\\\node_modules\\\\fsevents\\\\node_modules\\\\node-pre-gyp\\\\bin\\\\node-pre-gyp\" \"install\" \"--fallback-to-build\"\nnode-pre-gyp ERR! cwd E:\\VS\\ryan-compiler\\ryan-compiler\\node_modules\\fsevents\nnode-pre-gyp ERR! node -v v6.9.2\nnode-pre-gyp ERR! node-pre-gyp -v v0.6.29\nnode-pre-gyp ERR! not ok \nFailed to execute 'C:\\Program Files\\nodejs\\node.exe E:\\VS\\ryan-compi

Done in 171.63s.
```

That is quite a gigantic error output for a package which is skipped. I'm scared that my packages aren't properly restored.

**Comment by bestander** [comment]
We've made a change in 0.18.1, could you give it a try?

**Comment by ryanelian** [comment]
I would love to, but running `self-update` (from the yarn obtained via msi in the main site) displays:

```
E:\VS\ryan-compiler\ryan-compiler>yarn self-update
yarn self-update v0.17.10
success Yarn is already using the latest version.
Done in 6.04s.
```

And NPM shows 0.17.10 as latest too.

Where I can grab the install for 0.18.1?

Unrelated question: Does yarn prefers offline package by default?

**Comment by bestander** [comment]
Can you try again? I just bumped 0.18.1.
I think yarn finds the needed versions in package-resolver.js and after that if that version is in cache it won't try to download it from network.

**Comment by ryanelian** [comment]
Okay, cool. I upgraded successfully to 0.18.1.

Unrelated feature suggestion: `self-update` should probably has a progress bar, no? It currently does not have one...

```
E:\VS\ryan-compiler\ryan-compiler>yarn
yarn install v0.18.1
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.15: The platform "win32" is incompatible with this module.
info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 185.46s.
```

Excellent, no more gigantic error messages. Thank you, guys.
