### ISSUE TITLE
yarn complains about electron prebuilt

### ISSUE THREAD

**Issue by varunjayaraman** [yarnpkg/yarn#2350]
First off, just wanted to thank the maintainers. Yarn is pretty gnarly and am extremely happy with its performance + simplicity.

**Do you want to request a *feature* or report a *bug*?**

*bug*
**What is the current behavior?**
Yarn complains about electron-prebuilt symlink when I try to use `yarn remove`.

**If the current behavior is a bug, please provide the steps to reproduce.**

Sorry if this isn't too helpful in reproducing, but this error seems to only happen sporadically, and it's not always for `yarn remove`.  I've actually gotten this issue before when I try to `yarn install` from scratch (i.e. no node_modules folder yet) for a project.

Here's the full error when i ran `yarn remove angular-chart.js`:

```
yarn remove v0.18.1
[1/2] Removing module angular-chart.js...
[2/2] Regenerating lockfile and installing missing dependencies...
warning api-server@0.0.1: No license field
warning Unmet peer dependency "pug@^2.0.0-beta5".
warning Incorrect peer dependency "stylus@>=0.52.4".
warning Incorrect peer dependency "ajv@>=4.9.0".
[1/7] ⢀ bcrypt: gyp info spawn args   '-Goutput_dir=.' ]
[6/7] ⢀ phantomjs-prebuilt
[7/7] ⢀ electron-prebuilt
[4/7] ⢀ bufferutil: gyp info spawn args   '-Goutput_dir=.' ]
error /Users/roonie/sixplus/api-server/node_modules/electron-prebuilt: Command failed.
Exit code: 1
Command: sh
Arguments: -c node install.js
Directory: /Users/roonie/sixplus/api-server/node_modules/electron-prebuilt
Output:
/Users/roonie/sixplus/api-server/node_modules/electron-prebuilt/install.js:15
  throw err
  ^

Error: EEXIST: file already exists, symlink 'Versions/Current/Electron Framework' -> '/Users/roonie/sixplus/api-server/node_modules/electron-prebuilt/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework'
    at Error (native)
info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.
```
**What is the expected behavior?**
Just to remove the npm dependency from node_modules and the `yarn.lock` file.
**Please mention your node.js, yarn and operating system version.**
node v 5.6.0
yarn v 0.18.1
OS: OSX 10.11.4 
(not sure if necessary): npm v 3.6.0

**Comment by varunjayaraman** [comment]
I recently purged node and NPM from my computer, brew uninstalled it, removed node and npm references from `/usr/local/bin`, `/usr/local/include`, etc. and then reinstalled it with the MacOS installer (i dont want to use homebrew anymore) for v6.9.2 which comes with NPM v3.10.9.

Now when I run yarn install, I get this error:

```
roonie:api-server roonie$ yarn install
yarn install v0.18.1
warning api-server@0.0.1: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning Unmet peer dependency "pug@^2.0.0-beta5".
warning Incorrect peer dependency "stylus@>=0.52.4".
warning Incorrect peer dependency "ajv@>=4.9.0".
[4/4] 📃  Building fresh packages...
[1/7] ⠁ bcrypt:                      ^
[-/7] ⠂ waiting...
[-/7] ⠂ waiting...
[-/7] ⠂ waiting...
error /Users/roonie/sixplus/api-server/node_modules/bcrypt: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-gyp rebuild
Directory: /Users/roonie/sixplus/api-server/node_modules/bcrypt
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.2 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/roonie/.yarn/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/roonie/sixplus/api-server/node_modules/bcrypt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/roonie/.yarn/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/roonie/.node-gyp/6.9.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/roonie/.node-gyp/6.9.2',
gyp info spawn args   '-Dnode_gyp_dir=/Users/roonie/.yarn/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/roonie/sixplus/api-server/node_modules/bcrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
In file included from ../src/bcrypt_node.cc:1:
In file included from ../../nan/nan.h:184:
../../nan/nan_maybe_43_inl.h:221:17: warning: 'CloneElementAt' is deprecated [-Wdeprecated-declarations]
  return array->CloneElementAt(GetCurrentContext(), index);
                ^
/Users/roonie/.node-gyp/6.9.2/include/node/v8.h:3032:36: note: 'CloneElementAt' has been explicitly marked deprecated here
                MaybeLocal<Object> CloneElementAt(Local<Context> context,
                                   ^
In file included from ../src/bcrypt_node.cc:1:
In file included from ../../nan/nan.h:190:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:40:29: warning: 'New' is deprecated [-Wdeprecated-declarations]
  return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                            ^
/Users/roonie/.node-gyp/6.9.2/include/node/v8.h:4007:56: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
                                                       ^
In file included from ../src/bcrypt_node.cc:1:
../../nan/nan.h:592:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:598:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:603:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:609:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:1933:15: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
  return obj->SetAccessor(
              ^
/Users/roonie/.node-gyp/6.9.2/include/node/v8.h:2751:22: note: 'SetAccessor' has been explicitly marked deprecated here
                bool SetAccessor(Local<Name> name,
                     ^
3 warnings and 4 errors generated.
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/roonie/.yarn/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/bin/node" "/Users/roonie/.yarn/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/roonie/sixplus/api-server/node_modules/bcrypt
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

Seems like both problems have something to do with node-gyp and bcrypt, but based on how I can't find another instance of this error, I'm guessing it also has something to do with my local configuration. Any ideas?

**Comment by varunjayaraman** [comment]
Nvm, figured it out. I upgraded bcrypt to 1.0.2 and all fixed
