### ISSUE TITLE
Yarn 0.18.1 does not run on Windows 10 (ENOENT error)

### ISSUE THREAD

**Issue by nightlyop** [yarnpkg/yarn#2371]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I start yarn with `yarn` or `yarn --version` I get the error
```
C:\Users\username>yarn --version
C:\Program Files (x86)\Yarn\bin\yarn.js:62
      throw err;
      ^

Error: ENOENT: no such file or directory, open 'C:\Program Files (x86)\Yarn\updates\0.16.1\lib\cli\index.js'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at Object.Module._extensions..js (module.js:549:20)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Program Files (x86)\Yarn\bin\yarn.js:54:22)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Install yarn by executing `yarn-0.18.1.msi`
2. Check yarn installation with `yarn --version`

**Please mention your node.js, yarn and operating system version.**
Windows: Windows 10 Pro Version 10.0.14393
Node: v6.2.1
Yarn: 0.18.1 (at least that's what I expect)

**Other information**
There is no `updates` folder in `C:\Program Files (x86)\Yarn`
I've tried to install earlier versions of yarn but I've neve been successful. However, before installing yarn 0.18.1 I removed the old version and deleted environment variables to the old version. I don't see any enty in $PATH or other environment variables of the old installation.

**Comment by Daniel15** [comment]
Hmm I'm not sure why it's looking for 0.16.1 files in that directory. Try uninstall Yarn, delete all of `C:\Program Files (x86)\Yarn` and `%LocalAppData\Yarn`, then reinstall it.
