### ISSUE TITLE
Native Modules (heapdump, bufferutil) on Windows

### ISSUE THREAD

**Issue by calebboyd** [yarnpkg/yarn#2376]
**Do you want to request a *feature* or report a *bug*?**
- bug

**What is the current behavior?**
Cannot build some native modules (maybe others?) 
specifically `heapdump`, and `bufferutil`

**If the current behavior is a bug, please provide the steps to reproduce.**
```bash
C:\ mkdir test
C:\ cd test
C:\ yarn add heapdump
```
**What is the expected behavior?**
heapdump be installed in `C:\test\node_modules`

**Please mention your node.js, yarn and operating system version.**'
- Nodejs: 6.9.2 x64
- OS: Windows 10: Version 10.0.14393 Build 14393
- Yarn: 0.18.1
- Python: 2.7.13
- Build Env: Visual Studio 2015 Update 3

`npm i heapdump bufferutil` performs as expected

```
error D:\code\test\node_modules\heapdump: Command failed.
Exit code: 1
Command: C:\Windows\system32\cmd.exe
Arguments: /d /s /c node-gyp rebuild
Directory: D:\code\test\node_modules\heapdump
Output:
D:\code\test\node_modules\heapdump>if not defined npm_config_node_gyp (node "C:\Program Files (
x86)\Yarn\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node
rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.2 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Program Files (x86)\\Yarn\\node_modules\\node-gyp\\gyp\\gyp_main.py',

gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\code\\test\\node_modules\\heapdump\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files (x86)\\Yarn\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\testuser\\.node-gyp\\6.9.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\testuser\\.node-gyp\\6.9.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files (x86)\\Yarn\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\code\\test\\node_modules\\heapdump',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\code\\test\\node_modules\\heapdump\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Yarn\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>

    sys.exit(gyp.script_main())
  File "C:\Program Files (x86)\Yarn\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545,
in script_main
    return main(sys.argv[1:])
  File "C:\Program Files (x86)\Yarn\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538,
in main
    return gyp_main(args)
  File "C:\Program Files (x86)\Yarn\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514,
in gyp_main
    options.duplicate_basename_check)
  File "C:\Program Files (x86)\Yarn\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line
 130, in Load
    params['parallel'], params['root_targets'])
  File "C:\Program Files (x86)\Yarn\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 2775, in Load
    variables, includes, depth, check, True)
  File "C:\Program Files (x86)\Yarn\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 417, in LoadTargetBuildFile
    build_file_data, PHASE_EARLY, variables, build_file_path)
  File "C:\Program Files (x86)\Yarn\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1214, in ProcessVariablesAndConditionsInDict
    variables, build_file, 'variables')
  File "C:\Program Files (x86)\Yarn\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1225, in ProcessVariablesAndConditionsInDict
    'only, found ' + expanded.__class__.__name__ + ' for ' + key)
ValueError: Variable expansion in this context permits str and int only, found long for lastUpdateCheck while trying to load binding.gyp
ValueError: Variable expansion in this context permits str and int only, found long for lastUpdateCheck while trying to load binding.g
yp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files (x86)\Yarn\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files (x86)\\Yarn\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\code\test\node_modules\heapdump
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by Jeff-Lewis** [comment]
See https://github.com/nodejs/node-gyp/pull/1085

**Comment by bestander** [comment]
Looks like it is fixed now
