### ISSUE TITLE
Javascript bundle version is broken in 0.19.0

### ISSUE THREAD

**Issue by thetrompf** [yarnpkg/yarn#2410]
The 0.19.0 build is only a few kilobytes, instead of a couple of megabytes.

![image](https://cloud.githubusercontent.com/assets/1430118/21745530/91600d92-d52e-11e6-89d1-ca6bd0164c58.png)

And when I run it I get:

```sh
$ node ./yarn-0.19.0.js
~/Downloads/yarn-0.19.0.js:74
(function webpackMissingModule() { throw new Error("Cannot find module \"/home/ubuntu/yarn/src/cli/index.js\""); }());
                                   ^

Error: Cannot find module "/home/ubuntu/yarn/src/cli/index.js"
    at webpackMissingModule (~/Downloads/yarn-0.19.0.js:74:42)
    at Object.<anonymous> (~/Downloads/yarn-0.19.0.js:74:115)
    at __webpack_require__ (~/Downloads/yarn-0.19.0.js:21:30)
    at ~/Downloads/yarn-0.19.0.js:67:18
    at Object.<anonymous> (~/Downloads/yarn-0.19.0.js:70:10)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)

```

Node.js: v7.1.0
OS: Ubuntu 16.04

**Comment by shouze** [comment]
Same for me
