### ISSUE TITLE
Yarn fails to pack simple npm manifest

### ISSUE THREAD

**Issue by DarthHater** [yarnpkg/yarn#2418]
Using yarn 18.1 (installed from brew), and node 6.0.0 (listed as dependency from brew):

Current behavior is with a very simple npm manifest, I try and run yarn pack or publish and get the dreaded node toString error.

To reproduce best I can tell, you can setup a very minimal npm manifest like such:

`{
  "name": "npmtest",
  "version": "1.0.1",
  "description": "blah",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}`

After running npm pack I'm able to generate a npmtest-1.0.1.tgz, so I would expect similar behavior from yarn pack.

nodejs: 6.0.0
yarn: 18.1
OS X version: 10.11.1 (El Capitan)

Full stack trace:

`Arguments: 
  /usr/local/Cellar/node/6.0.0/bin/node /usr/local/bin/yarn pack

PATH: 
  /Users/myname/.rbenv/shims:/Users/myname/.rbenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin

Yarn version: 
  0.18.1

Node version: 
  6.0.0

Platform: 
  darwin x64

npm manifest: 
  {
    "name": "npmtest",
    "version": "1.0.1",
    "description": "blah",
    "main": "index.js",
    "scripts": {
      "test": "echo \"Error: no test specified\" && exit 1"
    },
    "author": "",
    "license": "ISC"
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: "toString()" failed
      at Buffer.toString (buffer.js:528:11)
      at tryToString (fs.js:445:15)
      at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)`

**Comment by DarthHater** [comment]
I spent some time debugging this today, and I figured out what was causing it. I for some reason had an npm-registry-all.json file locally that was massive (probably some other test I'd done, not yarn related) that was choking pack.js

The interesting difference here is that npm pack seems to skip over this file, and yarn pack does not. Likely there is some improvement to be made here where yarn only picks up files that are necessary, as the line that's causing pack to fail is here: https://github.com/DarthHater/yarn/blob/master/src/cli/commands/pack.js#L147

Not sure if yarn should be looping through all files, is what I'm getting at, just the ones that are necessary, or potentially borrowing from npm's approach here (not 100% what it is but it's the buffer that causes this to die, I think).

That said, I doubt many people will run into such an odd issue.
