### ISSUE TITLE
Fails to install phantomjs-prebuilt with production flag

### ISSUE THREAD

**Issue by alagodich** [yarnpkg/yarn#2421]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`"phantomjs-prebuilt"` fails to build with `yarn --production`, but builds ok without production flag
**If the current behavior is a bug, please provide the steps to reproduce.**
```
yarn --production
yarn install v0.18.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/1] ⠄ phantomjs-prebuilt
[-/1] ⠄ waiting...
[-/1] ⠄ waiting...
[-/1] ⠄ waiting...
error Error running install script for optional dependency: "PATH/test/node_modules
/phantomjs-prebuilt: Command failed.\nExit code: 1\nCommand: sh\nArguments: -c node install.js\nDirectory
: PATH/test/node_modules/phantomjs-prebuilt\nOutput:\nmodule.js:471\n    throw err;
\n    ^\n\nError: Cannot find module 'isarray'\n    at Function.Module._resolveFilename (module.js:469:15
)\n    at Function.Module._load (module.js:417:25)\n    at Module.require (module.js:497:17)\n    at requ
ire (internal/module.js:20:19)\n    at Object.<anonymous> (/PATH/test/node_modules/r
✨  Done in 1.48s.
```

I have the following dependencies:
```
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "html-pdf": "^2.1.0"
  },
  "devDependencies": {
    "extract-text-webpack-plugin": "2.0.0-beta.4",
    "nightwatch": "0.9.12",
    "react": "^15.4.2",
    "webpack": "2.1.0-beta.28"
  }
}
```

**What is the expected behavior?**
`yarn install --production` should work
**Please mention your node.js, yarn and operating system version.**
node v6.9.2
yarn v0.18.1
macOS Sierra v10.12.2 (16C67)

**Steps to reproduce**
Using `package.json` above
* `yarn` (generate lock file)
* `rm -rf node_modules`
* `yarn --production`

**Comment by bestander** [comment]
Fixed in master and 0.20.0 released next week
