### ISSUE TITLE
The yarn.js in v0.19.0 release is broken

### ISSUE THREAD

**Issue by moretea** [yarnpkg/yarn#2456]
**What is the current behavior?**

I tried to  downloads the latest released yarn.js file and run it with node 6.8.0, but this failed.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
$ wget https://github.com/yarnpkg/yarn/releases/download/v0.19.0/yarn-0.19.0.js
$ node yarn-0.19.0.js 
/home/maarten/code/nixos/yarn2nix/2/yarn-0.19.0.js:74
(function webpackMissingModule() { throw new Error("Cannot find module \"/home/ubuntu/yarn/src/cli/index.js\""); }());
                                   ^

Error: Cannot find module "/home/ubuntu/yarn/src/cli/index.js"
    at webpackMissingModule (/home/maarten/code/nixos/yarn2nix/2/yarn-0.19.0.js:74:42)
    at Object.<anonymous> (/home/maarten/code/nixos/yarn2nix/2/yarn-0.19.0.js:74:115)
    at __webpack_require__ (/home/maarten/code/nixos/yarn2nix/2/yarn-0.19.0.js:21:30)
    at /home/maarten/code/nixos/yarn2nix/2/yarn-0.19.0.js:67:18
    at Object.<anonymous> (/home/maarten/code/nixos/yarn2nix/2/yarn-0.19.0.js:70:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
**What is the expected behavior?**

To not crash. The v0.18.1 release works just fine.

**Please mention your node.js, yarn and operating system version.**
```
$ node -v
v6.8.0
```

Running NixOS 16.09

**Comment by asapach** [comment]
The file is 2.6 KB against 3.22 MB for `yarn-0.18.1.js`

**Comment by moretea** [comment]
Yes, based on that `/home/ubuntu/yarn/src/cli/index.js` cannot be found, it appears that the compilation of all source files into `yarn-0.19.0.js` failed. 

(I'm not running ubuntu, nor have an ubuntu user on my machine)

**Comment by Daniel15** [comment]
cc @bestander 

> (I'm not running ubuntu, nor have an ubuntu user on my machine)

`/home/ubuntu/yarn/`  is the path on the build server.

**Comment by bestander** [comment]
Ah, this was fixed and merged already.
I'll do a 0.19.1 now
