### ISSUE TITLE
@mycomp/error: no such package available

### ISSUE THREAD

**Issue by unional** [yarnpkg/yarn#2463]
yarn: 0.18.1

`@mycomp/error` is a private package hosted locally.
When I run `npm install @mycomp/error` or `npm info @mycomp/error`, it is working correctly.

If I run `yarn add/info @mycomp/error`, it errors with:

```sh
error An unexpected error occurred: "http://localhost:4873/@mycomp%2ferror: no such package available".   
```

```sh
Yarn version: 
  0.18.1

Node version: 
  7.4.0

Platform: 
  win32 x64

...

Trace: 
  Error: http://localhost:4873/@mycomp%2ferror: no such package available
      at Request.params.callback [as _callback] (C:\Program Files (x86)\Yarn\lib\util\request-manager.js:309:18)
      at Request.self.callback (C:\Program Files (x86)\Yarn\node_modules\request\request.js:186:22)
      at emitTwo (events.js:106:13)
      at Request.emit (events.js:191:7)
      at Request.<anonymous> (C:\Program Files (x86)\Yarn\node_modules\request\request.js:1081:10)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:188:7)
      at IncomingMessage.<anonymous> (C:\Program Files (x86)\Yarn\node_modules\request\request.js:1001:12)
      at Object.onceWrapper (events.js:290:19)
      at emitNone (events.js:91:20)
```

**Comment by unional** [comment]
When I add others, e.g. `yarn add @mycomp/logging`, it is working fine.
