### ISSUE TITLE
Yarn dependency on `debug` error

### ISSUE THREAD

**Issue by vnguyen94** [yarnpkg/yarn#2552]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Yarn crashes on any command.

**If the current behavior is a bug, please provide the steps to reproduce.**
Running any command on Yarn (v0.19.1) terminates immediately, citing a missing `debug/index.js`. I've tried deleted my node_modules reinstalling, as well as restarting. It looks like the [debug package used to have an index.js](https://github.com/visionmedia/debug/tree/7e741fcc2f834672796333c97aa15f27f0ea2b5c).

**What is the expected behavior?**
It runs the specified command.

**Please mention your node.js, yarn and operating system version.**
```
Arguments: 
  /Users/vnguyen/.nvm/versions/node/v4.4.3/bin/node /Users/vnguyen/.nvm/versions/node/v4.4.3/bin/yarn install

PATH: 
  /Users/vnguyen/.nvm/versions/node/v4.4.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

Yarn version: 
  0.19.1

Node version: 
  4.4.3

Platform: 
  darwin x64

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: ENOENT: no such file or directory, open '/Users/vnguyen/.nvm/versions/node/v4.4.3/lib/node_modules/yarn/node_modules/debug/index.js'
      at Error (native)
      at Object.fs.openSync (fs.js:549:18)
      at Object.fs.readFileSync (fs.js:397:15)
      at Object.Module._extensions..js (module.js:415:20)
      at Module.load (module.js:343:32)
      at Function.Module._load (module.js:300:12)
      at Module.require (module.js:353:17)
      at require (internal/module.js:12:17)
      at Object.<anonymous> (/Users/vnguyen/.nvm/versions/node/v4.4.3/lib/node_modules/yarn/lib-legacy/util/blocking-queue.js:33:15)
      at Module._compile (module.js:409:26)
```

**Comment by bestander** [comment]
Can you try removing `npm uninstall -g yarn` and install it again?

**Comment by vnguyen94** [comment]
Couldn't replicate and it works now, so closing.
