### ISSUE TITLE
Support for login identity to retrieve from private registry

### ISSUE THREAD

**Issue by doliver3** [yarnpkg/yarn#2573]
0.19.1

**Do you want to request a *feature* or report a *bug*?**

*feature*

**What is the current behavior?**
npm login does not provide a way to login before a yarn add command and the yarn add command does not send the identity of the user to the registry. Then the registry does not allow any reads of the packages because the registry permissions are set to require authorization to read the packages. The yarn add command fails because no credentials were passed by yarn to the registry. 

**If the current behavior is a bug, please provide the steps to reproduce.**

yarntest$ yarn login
```
yarn login v0.19.1
info npm username: david-oliver
info npm username: doliver3@aol.com
✨  Done in 0.04s.
yarn add v0.19.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "http://messagewave.org:4873/chalk: unregistered users are not allowed to access package chalk".
info If you think this is a bug, please open a bug report with the information provided in "/Applications/MAMP/htdocs/verdaccio/yarntest/yarn-error.log".
```
yarntest$ cat /Applications/MAMP/htdocs/verdaccio/yarntest/yarn-error.log
Arguments: 
  /usr/local/bin/node /usr/local/bin/yarn add chalk

PATH: 
  /Users/beyondenergy/.rvm/gems/ruby-head/bin:/Users/beyondenergy/.rvm/bin:/opt/local/bin:/opt/local/sbin:/Users/beyondenergy/Code2/software/selenium/phantomjs-2.1.1-macosx/bin:/Users/beyondenergy/.rvm/gems/ruby-head/bin:/Users/beyondenergy/.rvm/gems/ruby-head@global/bin:/Users/beyondenergy/.rvm/rubies/ruby-head/bin:/Users/beyondenergy/.rvm/bin:~/bin:/Users/beyondenergy/.npm-packages/bin:/Users/beyondenergy/Documents/DevFocus/DavidOliver/software/groovy-2.3.4/bin:/Users/beyondenergy/Documents/DevFocus/DavidOliver/software/gradle-2.0/bin:/usr/local/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/beyondenergy/Documents/DevFocus/DavidOliver/software/sqlite:/Library/Frameworks/Python.framework/Versions/3.3/bin:/opt/X11/bin:/usr/local/go/bin:/Users/beyondenergy/devApps/activator-1.2.10:/Users/beyondenergy/bin:/Users/beyondenergy/Documents/DEV/Software/scala-2.11.4/bin:/Users/beyondenergy/scripts:/Users/beyondenergy/.composer/vendor/bin

Yarn version: 
  0.19.1

Node version: 
  7.1.0

Platform: 
  darwin x64

npm manifest: 
  {
    "name": "yarntest",
    "version": "1.0.0",
    "main": "index.js",
    "repository": {},
    "license": "MIT"
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: http://messagewave.org:4873/chalk: unregistered users are not allowed to access package chalk
      at Request.params.callback [as _callback] (/usr/local/Cellar/yarn/0.19.1/libexec/lib/node_modules/yarn/lib/util/request-manager.js:313:18)
      at Request.self.callback (/usr/local/Cellar/yarn/0.19.1/libexec/lib/node_modules/yarn/node_modules/request/request.js:186:22)
      at emitTwo (events.js:106:13)
      at Request.emit (events.js:191:7)
      at Request.<anonymous> (/usr/local/Cellar/yarn/0.19.1/libexec/lib/node_modules/yarn/node_modules/request/request.js:1081:10)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:188:7)
      at IncomingMessage.<anonymous> (/usr/local/Cellar/yarn/0.19.1/libexec/lib/node_modules/yarn/node_modules/request/request.js:1001:12)
      at IncomingMessage.g (events.js:292:16)
      at emitNone (events.js:91:20)

**What is the expected behavior?**
yarn login should prompt for password or there should be a password prompt when yarn add <package-name> is run, and the yarn add <package-name> command should pass the identity of the user to the registry.

**Please mention your node.js, yarn and operating system version.**
node 7.1 or 7.4
Yarn 0.19.1
macOS 10.12.2

**Comment by doliver3** [comment]
Without this feature private registries on the internet cannot be used because Yarn is only supporting unauthenticated access to the registries. The registries must refuse unauthorized users for security reasons so this makes Yarn very insecure.  Yarn should support secure code and authentication of users to read files.

**Comment by carmelone** [comment]
+1

**Comment by tkambler** [comment]
Showstopper.

**Comment by averypfeiffer** [comment]
+1.
I've seen various solutions around github, but none have worked for me. This seems like a basic feature to me

**Comment by tkambler** [comment]
This is how we finally managed to make this work:

```
// project .npmrc
registry = "https://registry.acmeco.com"
ca = null
always-auth = true
//registry.acmeco.com/:_authToken=${NPM_TOKEN}
```

```
// project .yarnrc
registry "https://registry.acmeco.com"
```

As long as you have your npm token stored in the NPM_TOKEN environment variable, this works.

**Comment by averypfeiffer** [comment]
The solution @tkambler posted worked for me.  However our internal registry doesn't support NPM tokens yet so I had to tweak it a little. I changed:

`//our.internal.repo:_authToken=username:password`

**Comment by pascencio** [comment]
Guys try this.

https://stackoverflow.com/a/52527213/1214052

For me works with nexus 3

**Comment by buffcode** [comment]
Can confirm with v1.16.0 that it's still required to override the global registry together with `always-auth` to get reliable downloads.

Works for any package:
```
# .yarnrc
always-auth=true
registry=https://npm.example.org/
//npm.example.org/:_authToken=my-token
```

Only works for `@example/test-1` but not `test-2` though the lockfile uses the custom registry and yarn also tries to fetch from `example.org`:
```
# .yarnrc
always-auth=true
@example:registry=https://npm.example.org/
//npm.example.org/:_authToken=my-token
```

```
verbose 0.604 Error: https://npm.example.org/test-2/-/test-2-0.0.1.tgz: Request failed "403 Forbidden"
    at ResponseError.ExtendableBuiltin (C:\Program Files (x86)\Yarn\lib\cli.js:696:66)
    at new ResponseError (C:\Program Files (x86)\Yarn\lib\cli.js:802:124)
    at Request.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:65270:16)
    at Request.emit (events.js:198:13)
    at Request.module.exports.Request.onRequestResponse (C:\Program Files (x86)\Yarn\lib\cli.js:130467:10)
    at ClientRequest.emit (events.js:203:15)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:198:13)
error An unexpected error occurred: "https://npm.example.org/test-2/-/test-2-0.0.1.tgz: Request failed \"403 Forbidden\"".
```

**Comment by buffcode** [comment]
After investigating the source I saw that yarn on the one hand wants to correctly detect the registries and corresponding auths, but fails to check the actual URL. I will create a PR with failing tests and propose a patch for this.

**Comment by johan-lindqvist** [comment]
I ran into this issue this week where I was getting 403 with a personal access token when trying to install a package from a private package repository on GitHub.

I was a member in two organizations in an enterprise where we have MFA required and I had authorized the personal access token with one organization but not the other. Once I authorized the personal access token with the correct organization I no longer got 403 during `npm install`.

Just a heads up if anyone is having this issue.

**Comment by vedmant** [comment]
There is simple command for npm `npm login --scope=@name --auth-type=legacy --registry=https://npm.pkg.github.com
` to login to github registry, what's similar `yarn` command?
