### ISSUE TITLE
Invalid YAML generated in yarn.lock

### ISSUE THREAD

**Issue by rentzsch** [yarnpkg/yarn#2626]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Invalid YAML is generated in `yarn.lock`.

**If the current behavior is a bug, please provide the steps to reproduce.**

    $ mkdir yarn-invalid-yaml-repro && cd yarn-invalid-yaml-repro
    $ yarn init -y
    yarn init v0.20.0
    warning The yes flag has been set. This will automatically answer yes to all questions which may have security implications.
    success Saved package.json
    ✨  Done in 0.10s.
    $ yarn add meow js-yaml
    yarn add v0.20.0
    info No lockfile found.
    [1/4] 🔍  Resolving packages...
    [2/4] 🚚  Fetching packages...
    [3/4] 🔗  Linking dependencies...
    [4/4] 📃  Building fresh packages...
    success Saved lockfile.
    success Saved 47 new dependencies.
    ├─ argparse@1.0.9
    ├─ array-find-index@1.0.2
    ├─ builtin-modules@1.1.1
    ├─ camelcase-keys@2.1.0
    ├─ camelcase@2.1.1
    ├─ currently-unhandled@0.4.1
    ├─ decamelize@1.2.0
    ├─ error-ex@1.3.0
    ├─ esprima@2.7.3
    ├─ find-up@1.1.2
    ├─ get-stdin@4.0.1
    ├─ graceful-fs@4.1.11
    ├─ hosted-git-info@2.1.5
    ├─ indent-string@2.1.0
    ├─ is-arrayish@0.2.1
    ├─ is-builtin-module@1.0.0
    ├─ is-finite@1.0.2
    ├─ is-utf8@0.2.1
    ├─ js-yaml@3.7.0
    ├─ load-json-file@1.1.0
    ├─ loud-rejection@1.6.0
    ├─ map-obj@1.0.1
    ├─ meow@3.7.0
    ├─ minimist@1.2.0
    ├─ normalize-package-data@2.3.5
    ├─ number-is-nan@1.0.1
    ├─ object-assign@4.1.1
    ├─ parse-json@2.2.0
    ├─ path-exists@2.1.0
    ├─ path-type@1.1.0
    ├─ pify@2.3.0
    ├─ pinkie-promise@2.0.1
    ├─ pinkie@2.0.4
    ├─ read-pkg-up@1.0.1
    ├─ read-pkg@1.1.0
    ├─ redent@1.0.0
    ├─ repeating@2.0.1
    ├─ semver@5.3.0
    ├─ signal-exit@3.0.2
    ├─ spdx-correct@1.0.2
    ├─ spdx-expression-parse@1.0.4
    ├─ spdx-license-ids@1.2.2
    ├─ sprintf-js@1.0.3
    ├─ strip-bom@2.0.0
    ├─ strip-indent@1.0.1
    ├─ trim-newlines@1.0.0
    └─ validate-npm-package-license@3.0.1
    ✨  Done in 1.83s.
    $ node -e 'require("js-yaml").safeLoad(fs.readFileSync("yarn.lock","utf8"))'

    /Users/wolf/Desktop/yarn-invalid-yaml-repro/node_modules/js-yaml/lib/js-yaml/loader.js:168
      throw generateError(state, message);
      ^
    YAMLException: bad indentation of a mapping entry at line 8, column 15:
          dependencies:
                      ^
        at generateError (/Users/wolf/Desktop/yarn-invalid-yaml-repro/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
        at throwError (/Users/wolf/Desktop/yarn-invalid-yaml-repro/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
        at readBlockMapping (/Users/wolf/Desktop/yarn-invalid-yaml-repro/node_modules/js-yaml/lib/js-yaml/loader.js:1075:7)
        at composeNode (/Users/wolf/Desktop/yarn-invalid-yaml-repro/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
        at readDocument (/Users/wolf/Desktop/yarn-invalid-yaml-repro/node_modules/js-yaml/lib/js-yaml/loader.js:1489:3)
        at loadDocuments (/Users/wolf/Desktop/yarn-invalid-yaml-repro/node_modules/js-yaml/lib/js-yaml/loader.js:1545:5)
        at load (/Users/wolf/Desktop/yarn-invalid-yaml-repro/node_modules/js-yaml/lib/js-yaml/loader.js:1562:19)
        at Object.safeLoad (/Users/wolf/Desktop/yarn-invalid-yaml-repro/node_modules/js-yaml/lib/js-yaml/loader.js:1580:10)
        at [eval]:1:20
        at ContextifyScript.Script.runInThisContext (vm.js:25:33)

Here's the snippet the parse exception is referring to:

    argparse@^1.0.7:
      version "1.0.9"
      resolved "https://registry.yarnpkg.com/argparse/-/argparse-1.0.9.tgz#73d83bc263f86e97f8cc4f6bae1b0e90a7d22c86"
      dependencies:
        sprintf-js "~1.0.2"

Posting this snippet into <http://www.yamllint.com> yields a similar error.

**What is the expected behavior?**
Valid YAML in `yarn.lock`.

**Please mention your node.js, yarn and operating system version.**
Node v6.9.4, Yarn 0.20.0, macOS 10.11.6

**Comment by rentzsch** [comment]
nm, a friend told me you guys were using yaml for the lock file format and I didn't actually check before trying to load it. I see it's custom.
