### ISSUE TITLE
Error: Cannot find module 'semver' at master-branch

### ISSUE THREAD

**Issue by soredake** [yarnpkg/yarn#2667]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
```
module.js:471
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib64/node_modules/yarn/bin/yarn.js:8:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
**If the current behavior is a bug, please provide the steps to reproduce.**
Install yarn-9999 in gentoo and run `yarn`

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**
Node v6.9.4
Yarn latest mater-branch.
Gentoo stable.

**Comment by atalebagha** [comment]
I'm having this same issue @soredake. Were you able to solve it?

**Comment by soredake** [comment]
My problem was that I installed yarn without modules.
