### ISSUE TITLE
Error with react-native

### ISSUE THREAD

**Issue by proProbe** [yarnpkg/yarn#2696]
Im currently running into a problem when installing my node_modules with yarn in my react-native project. I get the following error on version `0.19.1-1`:
```
### CLEANING XCODE ###
### STARTING PACKAGER ###
/home/me/Workspace/node_modules/babel-core/lib/transformation/file/index.js:600
      throw err;
      ^

SyntaxError: /home/me/Workspace/node_modules/react-native/packager/react-packager/src/Bundler/index.js: Unexpected token, expected ) (45:8)
  43 | 
  44 | export type GetTransformOptions<T> = (
> 45 |   string,
     |         ^
  46 |   Object,
  47 |   string => Promise<Array<string>>,
  48 | ) => T | Promise<T>;
    at Parser.pp$5.raise (/home/me/Workspace/node_modules/babylon/lib/index.js:4215:13)
    at Parser.pp.unexpected (/home/me/Workspace/node_modules/babylon/lib/index.js:1599:8)
    at Parser.pp.expect (/home/me/Workspace/node_modules/babylon/lib/index.js:1587:33)
    at Parser.pp$7.flowParsePrimaryType (/home/me/Workspace/node_modules/babylon/lib/index.js:4952:14)
    at Parser.pp$7.flowParsePostfixType (/home/me/Workspace/node_modules/babylon/lib/index.js:5025:38)
    at Parser.pp$7.flowParsePrefixType (/home/me/Workspace/node_modules/babylon/lib/index.js:5041:17)
    at Parser.pp$7.flowParseIntersectionType (/home/me/Workspace/node_modules/babylon/lib/index.js:5047:19)
    at Parser.pp$7.flowParseUnionType (/home/me/Workspace/node_modules/babylon/lib/index.js:5057:19)
    at Parser.pp$7.flowParseType (/home/me/Workspace/node_modules/babylon/lib/index.js:5068:19)
    at Parser.pp$7.flowParseTypeInitialiser (/home/me/Workspace/node_modules/babylon/lib/index.js:4393:19)
```
Anyone that has runned into the same error?

**Comment by Daniel15** [comment]
This error looks unrelated to Yarn... Do you not see it when using npm instead?

**Comment by proProbe** [comment]
I dont see this problem with npm. npm works fine

**Comment by bestander** [comment]
This looks like a wrong babel plugin configuration for React Native.
Maybe with Yarn a wrong version of babel runtime is hoisted on top and some scripts try to get the first one available.

**Comment by bestander** [comment]
Anyway, we need repro steps to help you out - a package.json and the script you are running.

**Comment by proProbe** [comment]
I realized that I somehow had installed yarn via npm thus having two version of yarn on the computer. Now the problem doesnt seem to appear any longer. Closing this issue. thanks for the quick responses everyone!

**Comment by Venryx** [comment]
Had the same issue, and solved it with solution here: https://github.com/facebook/react-native/issues/11336#issuecomment-265421547

(though in my case the problem was from running react-native-git-upgrade, rather than having two versions of yarn on my computer)
