### ISSUE TITLE
Yarn install breaks node module resolution

### ISSUE THREAD

**Issue by ianp** [yarnpkg/yarn#2716]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

Module resolution fails. If I delete `node_modules` and recreate with `nom i` then it works. Note that I noticed this issue when trying to compile TypeScript code and the linked repo includes this, along with a `yarn start` script that dumps the TypeScript resolution trace, however the issue is still present when you just try to run the compiled JS file, and this is what I have done in the examples below (i.e. pretty sure it isn't a TS issue).

```sh
$ node lib
module.js:472
    throw err;
    ^

Error: Cannot find module 'googleapis'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ianp/Projects/yarn-install-issue/lib/index.js:2:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

ianp/yarn-install-issue

**What is the expected behavior?**

```sh
$ node lib
so some work...
```

**Please mention your node.js, yarn and operating system version.**

macOS 10.12.3

```
$ node --version
v7.5.0
$ uname -a
Darwin Ians-MacBook-Pro 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
```

**Comment by ianp** [comment]
Oops! That link in steps to reproduce should be https://github.com/ianp/yarn-install-issue (I thought GitHub would have auto-linked it).

Steps to reproduce then should be

1. `git clone https://github.com/ianp/yarn-install-issue`
2. `cd yarn-install-issue`
3. `yarn install`
4. either `yarn start` or `node lib`

then to demonstrate the expected behaviour

1. `rm -r node_modules`
2. `npm i`
3. either `npm start` or `node lib`
