### ISSUE TITLE
Publishing with yarn, breaks the installation of it

### ISSUE THREAD

**Issue by ingenalls** [yarnpkg/yarn#2764]
Using yarn v0.20.3, node v7.5.0, macOS Sierra 10.12.3
 
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Publishing with yarn breaks the package and you can't install it. Tested on my computer and a colleagues

Installing with yarn returns
```
Trace: 
  Error: https://registry.yarnpkg.com/circularity/-/circularity-0.2.0.tgz: invalid tar file
      at Extract.Parse._startEntry (/usr/local/Cellar/yarn/0.20.3/libexec/lib/node_modules/yarn/node_modules/tar/lib/parse.js:149:13)
      at Extract.Parse._process (/usr/local/Cellar/yarn/0.20.3/libexec/lib/node_modules/yarn/node_modules/tar/lib/parse.js:131:12)
      at BlockStream.<anonymous> (/usr/local/Cellar/yarn/0.20.3/libexec/lib/node_modules/yarn/node_modules/tar/lib/parse.js:47:8)
      at emitOne (events.js:96:13)
      at BlockStream.emit (events.js:189:7)
      at BlockStream._emitChunk (/usr/local/Cellar/yarn/0.20.3/libexec/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:145:10)
      at BlockStream.resume (/usr/local/Cellar/yarn/0.20.3/libexec/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:58:15)
      at Extract.Reader.resume (/usr/local/Cellar/yarn/0.20.3/libexec/lib/node_modules/yarn/node_modules/fstream/lib/reader.js:249:34)
      at Entry.<anonymous> (/usr/local/Cellar/yarn/0.20.3/libexec/lib/node_modules/yarn/node_modules/tar/lib/parse.js:261:8)
      at emitNone (events.js:86:13)

```
Installing with npm returns
```
npm ERR! cb() never called!
```

**If the current behavior is a bug, please provide the steps to reproduce.**
yarn publish
yarn add \<pkg\>

**What is the expected behavior?**
I expect to be able to publish with yarn and be able to install that published package version.

**Other info**
If I publish the same package with npm it works fine...
Don't know if a comparison of packages are required but here they are.

Published with yarn(breaking):
- circularity@0.2.0
- circularity@0.2.2

Published with npm(working):
- circularity@0.2.1
- circularity@0.2.3

**Comment by saeidalidadi** [comment]
This issue is exactly the same that I have. for `yarn add shahcache` after `publishing` [the package](https://www.npmjs.com/package/shahcache).

**Comment by bestander** [comment]
Does it break .tar.gz for good?
Can you install it with npm after that?

**Comment by ingenalls** [comment]
Nope, trying to install that .tar.gz manually does not work.
That got me thinking... It seems like the packaging is the breaking part. Ran `yarn pack` and tried to install that tar-file but it was broken aswell

**Comment by bestander** [comment]
So can you reproduce `yarn pack` producing a broken .tar.gz?

**Comment by ingenalls** [comment]
Yes...

**Comment by bestander** [comment]
Great, can you share the steps?
I try that on a clone of react native and .tgz is fine there.

**Comment by ingenalls** [comment]
Steps to reproduce:
```
mkdir test
git clone git@github.com:ingenalls/circularity.git
cd circularity
yarn pack
cd ../test
yarn add ../circularity/circularity-v0.4.0.tgz
```

**Comment by bestander** [comment]
Afaik we don't have this feature yet in Yarn, adding a .tgz file from disk.
It would be great to have it though.
After `yarn pack` the .tgz file unzips correctly, so it is not malformed

**Comment by ingenalls** [comment]
I think you do... I just installed a local package with yarn though using that very same command. 
Either way, `npm install ../circularity/circularity-v0.4.0.tgz` doesnt work either

**Comment by saeidalidadi** [comment]
what should we do for now to fix this issue for publishing our package? will solve it turning back to `npm`?
I am using `nvm` and `npm` needs `root` permission for `publish` and I have not npm installed for `root` already. so the yarn publish was the best !!

**Comment by hueyhe** [comment]
I have the same problem. 
When I tried to publish a new version of my package, it works fine with `npm version patch` then `npm publish`. 
But with `yarn publish`, I got following message when I tried `yarn add <pkg>`
```bash
yarn add v0.20.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/mackage/-/mackage-0.1.10.tgz: invalid tar file".
info If you think this is a bug, please open a bug report with the information provided in "/Users/huey/workspace/mackage/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
And got following with `npm install <pkg>`
```bash
npm ERR! cb() never called!
```

**Comment by snaptopixel** [comment]
Same issue here, since trying yarn publish my module is not installable, even after a `version patch` and `npm publish` not sure where to go from here...

**Comment by ingenalls** [comment]
@snaptopixel Are you saying that you can't re-publish the same repo with npm? If so, that would be a different issue.
Have you tried to clone the repo again and then publish it with npm?

 I would open that as a new issue if you can't resolve it, since that would be more critical to fix.

**Comment by snaptopixel** [comment]
Thanks @ingenalls I was finally able to get it working after posting this last night... Here's the full sequence of events...

1. Initially published a [new lib](https://www.npmjs.com/package/vuex-ts-decorators) to npm via `npm publish`
1. `npm install` 😀 
1. Made updates to lib and thought, Hey! Let's try `yarn publish` instead
1. `yarn publish`
1. In separate project that consumes module:
1. `npm install` ➡️ `cb() never called` 😢 
1. `yarn` ➡️ `invalid tar file`
1. bump version and `npm publish`
1. `npm install` ➡️ `cb() never called` 😢 
1. `yarn` ➡️ `invalid tar file`
1. Delete yarn.lock
1. `npm install` ➡️ `cb() never called` 😢 
1. `yarn` 😀 
1. `npm install` 😀 

So apparently deleting the lock file and re-yarn'ing fixed things.

**Comment by xuezhma** [comment]
I had this `npm ERR! cb() never called!` error too, tried `npm publish` to publish a new version, the new version can be install, the old one published by yarn still can't

**Comment by Spy-Seth** [comment]
I'm facing the same issue. 

I've publish the version 1.0.7 of the package [https://www.npmjs.com/package/gulp-uglifycss](gulp-uglifycss) with `yarn publish` but this version is corrupted. I have to publish a new version (1.0.8) with `npm publish` to solve the issue.

If I try to install the corrupted version with npm:

```
$ npm install gulp-uglifycss@1.0.7
npm http request GET https://registry.npmjs.org/gulp-uglifycss
npm http 200 https://registry.npmjs.org/gulp-uglifycss
npm http fetch GET https://registry.npmjs.org/gulp-uglifycss/-/gulp-uglifycss-1.0.7.tgz
npm http fetch 200 https://registry.npmjs.org/gulp-uglifycss/-/gulp-uglifycss-1.0.7.tgz
npm ERR! cb() never called!
```

And with yarn:
```
$ yarn add gulp-uglifycss@1.0.7
yarn add v0.21.3
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/gulp-uglifycss/-/gulp-uglifycss-1.0.7.tgz: invalid tar file".
info If you think this is a bug, please open a bug report with the information provided in "/Users/spy-seth/workspace/test-gulp-uglifycss-1.0.7/yarn-error.log".
```

Here the verbose logs: https://gist.github.com/Spy-Seth/624960b5196629b533cf3ca1d63bb476

**Comment by bestander** [comment]
I think there is a bug in Yarn `pack` command.
For @ingenalls's, [example](https://github.com/yarnpkg/yarn/issues/2764#issuecomment-283133839) some files are not packed in the resulting .tgz compared to `npm pack` result.

I haven't touched that code much but `possibleKeepFiles` at https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/pack.js#L124 looks weird because it gets written to but never used and it contains all the dist files unlike `keepFiles` variable.

I wonder if the fix could be as simple as iterating over `possibleKeepFiles` instead of `keepFiles` https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/pack.js#L137.

Can anyone test this and send a PR?

**Comment by saeidalidadi** [comment]
I will test it and will send a PR asap.

**Comment by saeidalidadi** [comment]
Test result before any change:
```
Test Suites: 5 failed, 47 passed, 52 total
Tests:       15 failed, 6 skipped, 423 passed, 444 total
Snapshots:   51 passed, 51 total
Time:        573.925s
```

**Comment by bestander** [comment]
Master branch on CI is green https://circleci.com/gh/yarnpkg/yarn/tree/master
