### ISSUE TITLE
fs.js:558   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);

### ISSUE THREAD

**Issue by fruity4pie** [yarnpkg/yarn#2825]
**When I download packages via YARN and start task 'GULP', which contains:**

 "devDependencies": {
    "browser-sync": "^2.18.8",
    "del": "^2.2.2",
    "gulp": "^3.9.1",
    "gulp-autoprefixer": "^3.1.1",
    "gulp-cache": "^0.4.5",
    "gulp-concat": "^2.6.1",
    "gulp-cssnano": "^2.1.2",
    "gulp-imagemin": "^3.1.1",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "^3.1.0",
    "gulp-uglifyjs": "^0.6.2",
    "imagemin-pngquant": "^5.0.0"
  }

**Console shows me this message:** 

[19:26:57] Starting 'css-libs'...
fs.js:558
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/robot/webdev/build/node_modules/svgo/lib/svgo/../../.svgo.yml'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.readFileSync (fs.js:468:33)
    at module.exports (/home/robot/webdev/build/node_modules/svgo/lib/svgo/config.js:31:48)
    at new module.exports (/home/robot/webdev/build/node_modules/svgo/lib/svgo.js:21:19)
    at /home/robot/webdev/build/node_modules/postcss-svgo/dist/index.js:95:16
    at Object.creator [as postcssSvgo] (/home/robot/webdev/build/node_modules/postcss/lib/postcss.js:150:35)
    at /home/robot/webdev/build/node_modules/cssnano/dist/index.js:295:40
    at Array.forEach (native)
    at /home/robot/webdev/build/node_modules/cssnano/dist/index.js:282:29
    at creator (/home/robot/webdev/build/node_modules/postcss/lib/postcss.js:150:35)
    at Function.cssnano.process (/home/robot/webdev/build/node_modules/cssnano/dist/index.js:306:36)
    at Transform.stream._transform (/home/robot/webdev/build/node_modules/gulp-cssnano/index.js:23:18)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)

**If I delete node_modules and install packages via NPM, error does not occur.**

**Why doesn't YARN install cssnano in the correct path ???????**

**Comment by arcanis** [comment]
We will need a repro script to help you. From what I can see, the issue comes from the `svgo` package, not Yarn.

**Comment by fruity4pie** [comment]
If I use Ubuntu, should I install packages via -sudo ??)

28 апр. 2017 г. 19:26 пользователь "Maël Nison" <notifications@github.com>
написал:
