### ISSUE TITLE
error An unexpected error occurred: "Unknown token 1:40" on MacOS Sierra

### ISSUE THREAD

**Issue by HoweChen** [yarnpkg/yarn#2872]
```
Arguments:
  /usr/local/Cellar/node/7.7.1_1/bin/node /usr/local/bin/yarn

PATH:
  /Users/howechen/.jenv/shims:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/Users/howechen/gopath/bin:/Users/howechen/.cargo/bin:/usr/local/opt/go/libexec/bin:/Users/howechen/.composer/vendor/bin:/bin:/usr/local/Cellar/scala/2.12.1/bin:/usr/local/Cellar/storm/1.0.3/bin

Yarn version:
  0.21.3

Node version:
  7.7.1

Platform:
  darwin x64

npm manifest:
  {
    "name": "JavaScript_Note",
    "version": "1.0.0",
    "main": "index.js",
    "repository": "https://github.com/HoweChen/JavaScript_Note.git",
    "author": "SkyFather <cyh278889789@gmail.com>",
    "license": "MIT",
    "dependencies": {}
  }

yarn manifest:
  No manifest

Lockfile:
  # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
  # yarn lockfile v1

Trace:
  SyntaxError: Unknown token 1:40
      at Parser.unexpected (/usr/local/Cellar/yarn/0.21.3/libexec/lib/node_modules/yarn/lib/lockfile/parse.js:224:11)
      at Parser.parse (/usr/local/Cellar/yarn/0.21.3/libexec/lib/node_modules/yarn/lib/lockfile/parse.js:329:14)
      at exports.default (/usr/local/Cellar/yarn/0.21.3/libexec/lib/node_modules/yarn/lib/lockfile/parse.js:13:17)
      at /usr/local/Cellar/yarn/0.21.3/libexec/lib/node_modules/yarn/lib/registries/yarn-registry.js:123:62
      at Generator.next (<anonymous>)
      at step (/usr/local/Cellar/yarn/0.21.3/libexec/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /usr/local/Cellar/yarn/0.21.3/libexec/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
```

**Comment by torifat** [comment]
Sorry, I couldn't reproduce it using your repo.

<img width="408" alt="screen shot 2017-03-09 at 8 40 23 pm" src="https://cloud.githubusercontent.com/assets/208544/23744539/b7929048-0508-11e7-87eb-2f4614f65570.png">

**Comment by HoweChen** [comment]
@torifat actually this happens every time and this doesn't about the project you are working on. I installed yarn through the homebrew and whenever you type yarn this error occurs

**Comment by HoweChen** [comment]
It's okay right now, it turns out I have changed the registry to npm address by using yrm, and when I changed back to yarn official site, this error was solved, thank you for your response.
