### ISSUE TITLE
An unexpected error occurred: "Commit hash required".

### ISSUE THREAD

**Issue by roderik** [yarnpkg/yarn#2976]
I've got a project, that has been running fine for months, where suddenly adding/installing `eth-lightwallet` fails during `fetching packages` with `An unexpected error occurred: "Commit hash required".`

Suddenly is defined as between March 21st, 9:51AM CET - March 22nd, 5:30PM CET with a commit that did not touch the package.json or lock files (just a css and html fix)

I've tried:

- changing node version 7.7.4 and 7.7.1 (on 7.7.1 it worked before without question)
- removing all caches, npm_modules, lockfiles
- it fails both on a linux (alpine and debian) ci docker image, and on OSX
- *created a new project and added it. this worked, so it's my dependency set that breaks it*
- it appears to be related to bignumber.js in the dependencies, so tried a lot of different formats in https://github.com/roderik/eth-lightwallet.git
- added `if (!commit) console.log(_this2)` to my git-fetcher.js line 113 and installed using `yarn add https://github.com/roderik/eth-lightwallet.git --verbose --network-concurrency 1 --force` Result: https://gist.github.com/roderik/f5ff6abfcdcdb364f2a5327016317de0 and the error log, but this does not show a reason for the commit hash to be empty
- *it installs fine with npm, so it's my dependencies + yarn*

I'm stumped and reverted to `yarn install || npm i` on my ci, but this is not really the way it's supposed to be.

**Comment by grydstedt** [comment]
Seeing this as well. Can't seem to get out of it either.

**Comment by sixinli** [comment]
try regenerating your yarn.lock file? the resolved link has been changed for external dependencies - 

i had a dependency that looks like

`"leaflet.markercluster": "Leaflet/Leaflet.markercluster#leaflet-0.7"`

and it originally resolves to 
`  resolved "https://codeload.github.com/Leaflet/Leaflet.markercluster/tar.gz/232e93ccbe5b70241913f47a4d1a8ceec8c88c30"` which the git-fetcher fails to extra commit hash from

and after regenerating yarn.lock file it resolves to
`  resolved "git://github.com/Leaflet/Leaflet.markercluster#232e93ccbe5b70241913f47a4d1a8ceec8c88c30"
`

**Comment by s3ththompson** [comment]
Seeing this error as well.

My `yarn-error.log`: https://gist.github.com/s3ththompson/39bf7d98faeef3811d8a5bc747427b74

**Comment by kaicataldo** [comment]
Same here - I'm also seeing some duplicate entries from nested dependencies unless I use the `git://github.com` format.

**Comment by s3ththompson** [comment]
I haven't tracked down an exact repo yet, but I was running into issues installing `"inline-styles": "^1.0.0"` ([inline-styles](https://github.com/maxogden/inline-styles)) which in turn has a dependency on `cheerio` of the form `git://github.com/cheeriojs/cheerio`. I believe the cheerio dependency was what was breaking...

**Comment by smitt04** [comment]
I am having same issue
[yarn-error.txt](https://github.com/yarnpkg/yarn/files/914574/yarn-error.txt)

**Comment by jeffscottward** [comment]
Same issue as well
We are using "next" in pkg.json for "uport-connect" possibly the issue?
[yarn-error.txt](https://github.com/yarnpkg/yarn/files/922538/yarn-error.txt)

**Comment by smitt04** [comment]
Found out this problem has to do with `git, especially when the dependency was resolving to a git url with out a commit hash as the version. It makes since as there is no way to lock down the version when you are just loading what ever is in master. Removing all git dependencies resolved this issue for me.

**Comment by kaicataldo** [comment]
@smitt04 Glad you found a workaround. Not an option for us, unfortunately :(

**Comment by s3ththompson** [comment]
@smitt04 @kaicataldo I don't follow that there is no way to lock down a version when you are loading from master... it seems as though the `yarn.lock` should track the commit hash that matches HEAD at the time the git dependency is installed.

**Comment by jeffscottward** [comment]
> Removing all git dependencies resolved this issue for me.
What exactly does this mean? As in stuff that doesn't exist on NPM? Some sort of git tooling?

**Comment by bestander** [comment]
@roderik, can you share a yarn.lock + package.json that reproduce the issue?
The trick with git dependencies is that sometimes hash can be a commit hash and other times it can be a sha1 hash.

**Comment by smitt04** [comment]
@jeffscottward what i meant was that any npm packages in my `package.json` file that referenced by a git url i switched to use the npm version and it fixed the issues i was having.

**Comment by roderik** [comment]
@bestander everything is in https://gist.github.com/roderik/f5ff6abfcdcdb364f2a5327016317de0

**Comment by jeremyong** [comment]
Seeing this as well even after a yarn cache clean and removal of the node_modules folder

**Comment by weyert** [comment]
I am having the issue too. Downgrading to an older version seems to solve it for me on Heroku

**Comment by levity** [comment]
I just started seeing this on Heroku today as well, with version 0.22.0 of yarn. Changing to version 0.23.2 fixed it.

Change the version on Heroku by adding to package.json:
```json
{ 
  "engines": {
    "yarn": "0.23.2"
  }
}
```

**Comment by matrunchyk** [comment]
Yay! Thanks @levity! Adding 
```
{ 
  "engines": {
    "yarn": "0.23.2"
  }
}
```
to my `package.json` on BitBucket did the trick!

**Comment by s3ththompson** [comment]
I thought 23.2 fixed this issue for a little while, but I ran into it again trying to remove a dependency from `yarn.lock`.

**Comment by lukehedger** [comment]
Also seeing an error when managing the `eth-lightwallet` dependency with Yarn. After installing the dependency, subsequent `yarn` commands (`add`, `install`) fail with this error:

```
An unexpected error occurred: "ENOENT: no such file or directory, open '/Users/luke/Library/Caches/Yarn/v1/npm-bignumber.js-2.0.7-c4840fe42268643818b2730ebedb0eec7271ee42/.yarn-metadata.json
```

Running `yarn cache clean` and removing `node_modules` and the `yarn.lock` file resolves the issue but obviously re-running `yarn install` will cause the issue to resurface.

**Comment by bestander** [comment]
Thanks for more data.
We are tracking a set of issues related to git hosted dependencies, apparently there are many edge cases to consider.
We'll sort it out soon.

**Comment by BYK** [comment]
Is this still an issue? Can someone try with a recent version of Yarn?

**Comment by rymndhng** [comment]
@BYK I'm still seeing this issue :/

**Comment by hugodutra** [comment]
I was having the same issue, what solved for me was change the import on package.json 

from: "react-common": "git+https://github.com/vizinhanca/react-common.git#master"
to:      "react-common": "git+ssh://git@github.com/vizinhanca/react-common.git#master",

**Comment by sudoanand** [comment]
Try deleting the yarn.lock file and then `git stash`  or commit existing changes.

**Comment by pbirbarah** [comment]
"Try deleting the yarn.lock file and then commit existing changes". that worked for me!

**Comment by saadSarwar28** [comment]
@pbirbarah , worked for me too. in my case, i received an app that was created on mac and i am on windows, yarn.lock should never be committed in a repo I think.

**Comment by elie222** [comment]
> @pbirbarah , worked for me too. in my case, i received an app that was created on mac and i am on windows, yarn.lock should never be committed in a repo I think.

`yarn.lock` should be committed.

**Comment by kuldeep2110** [comment]
Check your node version 
I was on v14.20.0 and when i switched to 16.14.0 it resolved the issue for me
then delete the lock file and yarn install again

**Comment by ianrowan** [comment]
I am also receiving this issue and have tried almost everything here 

I'm on yarn install v1.22.19 

And added npm package `"userop": "^0.3.0"` to my package.json and started receiving the error message. As far as I can tell the package is resolved via npm in yarn lock when generated 
```
userop@^0.2.0:
    version "0.2.0"
    resolved "https://registry.npmjs.org/userop/-/userop-0.2.0.tgz"
    integrity sha512-WvPUktveT0lqyvuEl1eBIFLCG+72FBy1fE7vcRVgDAGSDYB3oW+VVvOA5AFhQFZzVjJe7PbSFyyN9lWqww03oQ==
    dependencies:
      ethers "^5.7.2"
```

Would be nice if the error message was more descriptive of what package is 'missing a commit hash'
Even the error log is very generic and can only debug from deduction 

```
Invariant Violation: Commit hash required
      at invariant (/usr/local/Cellar/yarn/1.22.19/libexec/lib/cli.js:2318:15)
      at GitFetcher.<anonymous> (/usr/local/Cellar/yarn/1.22.19/libexec/lib/cli.js:89316:7)
      at Generator.next (<anonymous>)
      at step (/usr/local/Cellar/yarn/1.22.19/libexec/lib/cli.js:310:30)
      at /usr/local/Cellar/yarn/1.22.19/libexec/lib/cli.js:328:14
      at new Promise (<anonymous>)
```

**Comment by bibhuti9** [comment]
Well, I removed node_module and yarn.lock file and re-install all dependencies it worked for me.

**Comment by Nguyen-Xuan-Son** [comment]
It works to me, thank you.
