### ISSUE TITLE
"Cannot find module '../util/misc.js'"

### ISSUE THREAD

**Issue by llimllib** [yarnpkg/yarn#3124]
**Do you want to request a *feature* or report a *bug*?**

report a bug

**What is the current behavior?**

Run `yarn install` on my CI instance, note that `yarn` hangs indefinitely. I give the package.json and a `--verbose` log below. Yarn does throw an error with a stacktrace while it's hanging:

```
[4/4] Building fresh packages...
verbose 7.165 Error: Cannot find module '../util/misc.js'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (/jenkins/workspace/WindowShopping/windowshop-gh/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at _load_misc (/jenkins/workspace/WindowShopping/windowshop-gh/node_modules/yarn/lib/lockfile/wrapper.js:45:18)
    at Lockfile.getLockfile (/jenkins/workspace/WindowShopping/windowshop-gh/node_modules/yarn/lib/lockfile/wrapper.js:165:69)
    at /jenkins/workspace/WindowShopping/windowshop-gh/node_modules/yarn/lib/cli/commands/install.js:764:55
    at Generator.next (<anonymous>)
    at step (/jenkins/workspace/WindowShopping/windowshop-gh/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /jenkins/workspace/WindowShopping/windowshop-gh/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Run `yarn install` with the package.json below

**What is the expected behavior?**

yarn does not hang indefinitely

**Please mention your node.js, yarn and operating system version.**

node.js: 7.1.0
yarn: 0.23.0
OS: Red Hat Enterprise Linux Server release 6.8 (Santiago)
git: 1.9.5 (I mention because it's an old git and the package.json contains one github reference, so this could be relevant?)

** Below is the full package.json and verbose log **

https://gist.github.com/llimllib/6cbea8e0b4a6b6ce202130b659334031

**Comment by llimllib** [comment]
fixed by installing yarn globally

**Comment by gberberoglu** [comment]
sorry but installing yarn globally seems like a workaround. Can you please reopen this issue ?
