### ISSUE TITLE
yarn 0.23.2 searches package.json in test directory

### ISSUE THREAD

**Issue by sibelius** [yarnpkg/yarn#3225]
yarn is looking in for package.json in  `test` of my boilerplate: https://github.com/entria/graphql-dataloader-boilerplate

![image](https://cloud.githubusercontent.com/assets/2005841/25294919/b2c04c38-26b7-11e7-96d3-6f4745afc8a1.png)

```jsx
yarn install v0.23.2
verbose 0.208 current time: 2017-04-21T20:29:14.995Z
[1/4] 🔍  Resolving packages...
verbose 0.442 Performing "GET" request to "https://registry.yarnpkg.com/babel-polyfill".
verbose 0.446 Performing "GET" request to "https://registry.yarnpkg.com/dataloader".
verbose 0.446 Performing "GET" request to "https://registry.yarnpkg.com/dotenv-safe".
verbose 0.447 Performing "GET" request to "https://registry.yarnpkg.com/graphql".
verbose 0.448 Performing "GET" request to "https://registry.yarnpkg.com/graphql-relay".
verbose 0.449 Performing "GET" request to "https://registry.yarnpkg.com/jsonwebtoken".
verbose 0.45 Performing "GET" request to "https://registry.yarnpkg.com/koa".
verbose 0.451 Performing "GET" request to "https://registry.yarnpkg.com/koa-bodyparser".
verbose 0.539 Error: Couldn't find a package.json file in "/Users/sibelius/Dev/me/graphql-dataloader-boilerplate/test"
    at MessageError (/usr/local/Cellar/yarn/0.23.2/libexec/lib/errors.js:8:5)
    at /usr/local/Cellar/yarn/0.23.2/libexec/lib/config.js:445:15
    at next (native)
    at step (/usr/local/Cellar/yarn/0.23.2/libexec/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/Cellar/yarn/0.23.2/libexec/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
error Couldn't find a package.json file in "/Users/sibelius/Dev/me/graphql-dataloader-boilerplate/test"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by sibelius** [comment]
I've found the issue

jest package was in `test` version

I think this should be marked as a bug

**Comment by torifat** [comment]
> jest package was in `test` version

Sorry, can you please explain what does this actually mean?

**Comment by sibelius** [comment]
package.json
```json
  "jest": "test",
    "jest-cli": "test",
```

**Comment by torifat** [comment]
`npm dist-tags ls jest`

```
canary: 18.5.0-alpha.7da3df39
latest: 19.0.2
next: 19.1.0-alpha.eed82034
test: 16.1.0-alpha.691b0e22
```
`"jest": "test"` treat `jest` as a local package.
