### ISSUE TITLE
Yarn throws error 

### ISSUE THREAD

**Issue by dchinn** [yarnpkg/yarn#3277]
**What is the current behavior?**
yarn error when trying to restore packages

**If the current behavior is a bug, please provide the steps to reproduce.**
using angular-cli to generate a new project, foo
ng cli is set to use npm to restore the packages.
project gets created correctly, npm restores packages

cd to project folder, invoke yarn

**observed:
yarn throws an error...

```
D:\dev\samples\Angular\foo>yarn
module.js:471
    throw err;
    ^

Error: Cannot find module 'v8-compile-cache'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\david\AppData\Roaming\nvm\v6.10.0\node_modules\yarn\bin\yarn.js:25:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

```
**What is the expected behavior?**
yarn should restore packages properly

...three days ago it was working.  then i started making changes to the project, and discovered the error.
tried to instantiate a new project, and get the same error.
assuming it was some environment problem, i uninstalled and re installed both yarn and the angular cli.
note that it isn't likely the packages requested, as 'yarn --version' yields same error

**Please mention your node.js, yarn and operating system version.**
node v 6.10.0
yarn freshly installed 0.23.3, but 'yarn --version' yields same error as above
windows 10 pc

**Comment by Daniel15** [comment]
Can you please try installing Yarn using its installer rather than npm?

**Comment by benhunt29** [comment]
I have this same issue on Google App Engine. Unfortunately I can't change how it installs yarn. Here's the error

```
Step 1 : FROM gcr.io/google_appengine/nodejs
latest: Pulling from google_appengine/nodejs
Digest: sha256:94812e54a19537ae637ab6fc11d7c66a55c41857b3b37e90385b563a2393edc0
Status: Downloaded newer image for gcr.io/google_appengine/nodejs:latest
 ---> 459db92cf06b
Step 2 : RUN /usr/local/bin/install_node '>=6.10'
 ---> Running in 552f7df961d6
 ---> 5799b1e5164c
Removing intermediate container 552f7df961d6
Step 3 : RUN npm install --unsafe-perm --global yarn
 ---> Running in 1cc4eef305f4
/nodejs/bin/yarn -> /nodejs/lib/node_modules/yarn/bin/yarn.js
/nodejs/bin/yarnpkg -> /nodejs/lib/node_modules/yarn/bin/yarn.js
/nodejs/lib
`-- yarn@0.23.4 

 ---> 772d02a8d2aa
Removing intermediate container 1cc4eef305f4
Step 4 : COPY . /app/
 ---> c8b99c95b77b
Removing intermediate container d58b61b73100
Step 5 : RUN yarn install --production ||   ((if [ -f yarn-error.log ]; then       cat yarn-error.log;     fi) && false)
 ---> Running in 24cec67fbf5b
module.js:471
    throw err;
    ^

Error: Cannot find module 'v8-compile-cache'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/nodejs/lib/node_modules/yarn/bin/yarn.js:25:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
The command '/bin/sh -c yarn install --production ||   ((if [ -f yarn-error.log ]; then       cat yarn-error.log;     fi) && false)' returned a non-zero code: 1
ERROR
ERROR: build step "gcr.io/cloud-builders/docker@sha256:926dc1a14e6f7eb5b3462b5c1d491aa6c73090291167ac2bf181c026b05f19da" failed: exit status 1
```

**Comment by andreugrimalt** [comment]
Same as @benhunt29 here...
```
Step 1 : FROM gcr.io/google_appengine/nodejs
latest: Pulling from google_appengine/nodejs
Digest: sha256:94812e54a19537ae637ab6fc11d7c66a55c41857b3b37e90385b563a2393edc0
Status: Downloaded newer image for gcr.io/google_appengine/nodejs:latest
 ---> 459db92cf06b
Step 2 : RUN /usr/local/bin/install_node '>=6.10.2'
 ---> Running in 49412d639c85
 ---> eb9e166cc12b
Removing intermediate container 49412d639c85
Step 3 : RUN npm install --unsafe-perm --global yarn
 ---> Running in 59e3fe542c09
/nodejs/bin/yarn -> /nodejs/lib/node_modules/yarn/bin/yarn.js
/nodejs/bin/yarnpkg -> /nodejs/lib/node_modules/yarn/bin/yarn.js
/nodejs/lib
`-- yarn@0.23.4 

 ---> 90fba0f4bf2b
Removing intermediate container 59e3fe542c09
Step 4 : COPY . /app/
 ---> c650e4077c1f
Removing intermediate container 1d6d05f45421
Step 5 : RUN yarn install --production ||   ((if [ -f yarn-error.log ]; then       cat yarn-error.log;     fi) && false)
 ---> Running in d2a3eb98e485
module.js:471
    throw err;
    ^

Error: Cannot find module 'v8-compile-cache'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/nodejs/lib/node_modules/yarn/bin/yarn.js:25:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
The command '/bin/sh -c yarn install --production ||   ((if [ -f yarn-error.log ]; then       cat yarn-error.log;     fi) && false)' returned a non-zero code: 1
ERROR
ERROR: build step "gcr.io/cloud-builders/docker@sha256:926dc1a14e6f7eb5b3462b5c1d491aa6c73090291167ac2bf181c026b05f19da" failed: exit status 1
```

**Comment by benhunt29** [comment]
It's a known issue. Seems like it's with Google App Engine, not yarn. https://issuetracker.google.com/issues/37978206

**Comment by bestander** [comment]
Is it still an issue?

**Comment by benhunt29** [comment]
nope, fixed. Thanks!

**Comment by dchinn** [comment]
sorry i haven't been commenting on this; i haven't been getting all the notices of activity on this thread.

At the suggestion of daniel15, i uninstalled yarn and re installed using the installer.

Now yarn --version says i'm running 0.24.6

On windows 10, yarn is still not installing all the packages correctly...

**Comment by GBeauny** [comment]
FYI: I solved this issue by upgrading node.js.
