### ISSUE TITLE
[Bug] gyp ERR! stack Error: `make` failed with exit code: 2

### ISSUE THREAD

**Issue by adrianmcli** [yarnpkg/yarn#3278]
This may potentially not be a Yarn bug, but nevertheless the equivalent commands work fine in NPM. Please direct me to a more suitable repo if it exists.

### Current Behaviour

I'm currently experiencing an issue installing native binaries like `yarn global add prettier` or `yarn global add create-react-app`. The equivalent commands work perfectly fine with NPM.

When I try to install these packages, Yarn tells me that it's: `Building fresh packages...`

And before long, I get a large list of warnings that finally end with the following error:

```
error: error opening './Release/.deps/Release/obj.target/openssl/vendor/openssl/openssl/crypto/rand/randfile.o.d.raw': No such file or directory
1 error generated.
make: *** [Release/obj.target/openssl/vendor/openssl/openssl/crypto/rand/randfile.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/liadrian/.config/yarn/global/node_modules/git-hours/node_modules/nodegit/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/Users/liadrian/n/bin/node" "/Users/liadrian/.config/yarn/global/node_modules/git-hours/node_modules/nodegit/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/liadrian/.config/yarn/global/node_modules/git-hours/node_modules/nodegit
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
1
1
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

### Expected Behaviour

Install without error.

### Versions

MacOS: v10.11.6 (El Capitan)
Fresh install of Yarn: v0.23.3
Node: v7.9.0 (also tried with v7.7.1 and v.7.8.0)
Node-gyp: v3.0.3
npm: v4.2.0

**Comment by Daniel15** [comment]
Can you please post the entire log file?

**Comment by BYK** [comment]
Closing due to inactivity.
