### ISSUE TITLE
ETIMEDOUT always for the same package

### ISSUE THREAD

**Issue by Profpatsch** [yarnpkg/yarn#3334]
```
→ yarn add ember-cli
yarn add v0.23.2
info No lockfile found.
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/broccoli-babel-transpiler: ETIMEDOUT".
```

I already deleted `~/.config/yarn`, `~/.yarnrc` and `~/.cache/yarn`, same error keeps happening 

```
→ ping registry.yarnpkg.com
PING registry.yarnpkg.com(2400:cb00:2048:1::6810:3ead (2400:cb00:2048:1::6810:3ead)) 56 data bytes
64 bytes from 2400:cb00:2048:1::6810:3ead (2400:cb00:2048:1::6810:3ead): icmp_seq=1 ttl=57 time=18.1 ms
```

```
Arguments: 
  /nix/store/2c8kwzzgc294mncbwpn81jm4999f2xpb-nodejs-6.9.5/bin/node /nix/store/5yl07qka1aqiklr8w8352w0m5ljkrm31-yarn-0.23.2/libexec/yarn/bin/yarn.js add ember-cli --registry=https://registry.npmjs.org

PATH: 
  /nix/store/5yl07qka1aqiklr8w8352w0m5ljkrm31-yarn-0.23.2/bin:/nix/store/6wx9990q8gz2g891q5s2qjkqwycgi3fv-patchelf-0.9/bin:/nix/store/x05hh43cg7jy49ibzql7gy9adkg56h21-paxctl-0.9/bin:/nix/store/sxzm5kva1gb0hxm60xvr45m3c5l84xlz-coreutils-8.27/bin:/nix/store/d11rsb04c5rfnswbkm93fdcq162zimdb-findutils-4.6.0/bin:/nix/store/7ar9yp248w1l47hpizqqs9bxzbmsb16q-diffutils-3.5/bin:/nix/store/r6i411fxz6smd1ar6yxav6pfn3qjmkxw-gnused-4.4/bin:/nix/store/8dzax3l17j1slxn129wm82ifqppnfs0n-gnugrep-3.0/bin:/nix/store/lnfy734ma75wf3c5csn6vj830q0g058c-gawk-4.1.4/bin:/nix/store/lvnpwyfi50lfa7xd64ihzysb4ij2k33z-gnutar-1.29/bin:/nix/store/w40j6ji6zhnv9v4svjsq1f6d0wjcy6zx-gzip-1.8/bin:/nix/store/lipzmks7zlw2wxiasg3babhbj42ryl4p-bzip2-1.0.6.0.1-bin/bin:/nix/store/qmg3wkxq02a4j5xdfdd5ad7vyqbp1qzk-gnumake-4.2.1/bin:/nix/store/wsz11sx18n85if6gp50m870rypgavwpd-bash-4.4-p12/bin:/nix/store/7rp4cidxrm1yhl8a08xrhhks1xx38g0g-patch-2.7.5/bin:/nix/store/1nsbgi7l93idk0y82vvrbgvnp8jwbijl-xz-5.2.3-bin/bin:/home/philip/scripts:/nix/store/k4k58kbjigqh56rb545qkg8x0fp73b5n-fasd-unstable-2016-08-11/bin:/home/philip/bin:/run/wrappers/bin:/home/philip/.nix-profile/bin:/home/philip/.nix-profile/sbin:/home/philip/.nix-profile/lib/kde4/libexec:/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/default/sbin:/nix/var/nix/profiles/default/lib/kde4/libexec:/run/current-system/sw/bin:/run/current-system/sw/sbin:/run/current-system/sw/lib/kde4/libexec

Yarn version: 
  0.23.2

Node version: 
  6.9.5

Platform: 
  linux x64

npm manifest: 
  No manifest

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: https://registry.yarnpkg.com/broccoli-babel-transpiler: ETIMEDOUT
      at Timeout._onTimeout (/nix/store/5yl07qka1aqiklr8w8352w0m5ljkrm31-yarn-0.23.2/libexec/yarn/node_modules/request/request.js:852:19)
      at ontimeout (timers.js:365:14)
      at tryOnTimeout (timers.js:237:5)
      at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by rally25rs** [comment]
I don't get a timeout if I try adding the same package. Are you still having this issue?

You should be able to copy/paste the URL that is timing out (https://registry.yarnpkg.com/broccoli-babel-transpiler) directly to your web browser address bar, and with browser dev-tools open, see how long the response takes.

**Comment by Profpatsch** [comment]
> You should be able to copy/paste the URL that is timing out (https://registry.yarnpkg.com/broccoli-babel-transpiler) directly to your web browser address bar, and with browser dev-tools open, see how long the response takes.

Yes, the response was instant.

Right now it works, but it is definitely a kind of error that has bitten me several times now.

**Comment by bestander** [comment]
Could be related to CDN responses maybe, cc @Daniel15.
I'll close as this can't be reproduced anymore.
Thanks for reporting.
