### ISSUE TITLE
Getting authentication error when running yarn install

### ISSUE THREAD

**Issue by alvincrespo** [yarnpkg/yarn#3378]
**What is the current behavior?**

I'm currently using ember-cli to install a package:

```
ember install ember-cli-mocha
```

While running this command, I get the following:

```
➜  ember-links-with-follower git:(ac-upgrade) ember install ember-cli-mocha
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `release`
    at addons.forEach.addon (/Users/alvincrespo/workspace/ember-links-with-follower/node_modules/ember-cli/lib/models/project.js:452:40)
Command failed: yarn add --dev ember-cli-mocha
warning ember-links-with-follower@0.5.0: "dependencies" has dependency "ember-cli-htmlbars" with range "^1.0.3" that collides with a dependency in "devDependencies" of the same name with version "^1.1.1"
error An unexpected error occurred: "https://registry.yarnpkg.com/@glimmer%2fresolver: Could not authenticate alvincrespo".
yarn add v0.23.4
[1/4] Resolving packages...
info If you think this is a bug, please open a bug report with the information provided in "/Users/alvincrespo/workspace/ember-links-with-follower/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Error: Command failed: yarn add --dev ember-cli-mocha
warning ember-links-with-follower@0.5.0: "dependencies" has dependency "ember-cli-htmlbars" with range "^1.0.3" that collides with a dependency in "devDependencies" of the same name with version "^1.1.1"
error An unexpected error occurred: "https://registry.yarnpkg.com/@glimmer%2fresolver: Could not authenticate alvincrespo".
yarn add v0.23.4
[1/4] Resolving packages...
info If you think this is a bug, please open a bug report with the information provided in "/Users/alvincrespo/workspace/ember-links-with-follower/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

    at Promise.all.then.arr (/Users/alvincrespo/workspace/ember-links-with-follower/node_modules/execa/index.js:210:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

My environment is:

```
➜  ember-links-with-follower git:(ac-upgrade) ✗ ember -v
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `release`
    at addons.forEach.addon (/Users/alvincrespo/workspace/ember-links-with-follower/node_modules/ember-cli/lib/models/project.js:452:40)
ember-cli: 2.13.1
node: 7.10.0
os: darwin x64
```

I'm on macOS Sierra 10.12.4

➜  ember-links-with-follower git:(ac-upgrade) ✗ yarn -v
yarn install v0.23.4

PS - while running `yarn -v` I received:

```
warning ember-links-with-follower@0.5.0: "dependencies" has dependency "ember-cli-htmlbars" with range "^1.0.3" that collides with a dependency in "devDependencies" of the same name with version "^1.1.1"
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@glimmer%2fcompiler: Could not authenticate alvincrespo".
info If you think this is a bug, please open a bug report with the information provided in "/Users/alvincrespo/workspace/ember-links-with-follower/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by alvincrespo** [comment]
My yarn-error.log is [here](https://gist.github.com/alvincrespo/9a1309a0feabe6c8fa4f12f6fe848c0a).

**Comment by ErisDS** [comment]
I'm having the same issue https://github.com/yarnpkg/yarn/issues/3093, would be good to get these triaged together? There seems to be something specifically wrong with fetching packages from @glimmer?

**Comment by ErisDS** [comment]
For anyone else who runs into this, based on #3407 I've managed to [figure out a workaround](https://github.com/yarnpkg/yarn/issues/3093#issuecomment-306413909), by commenting several lines of my `~/.npmrc` file.
