### ISSUE TITLE
Package (arp-a) fails to install with yarn but succeeds with npm

### ISSUE THREAD

**Issue by julien-f** [yarnpkg/yarn#3479]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

```
$ yarn add arp-a
yarn add v0.25.2
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /tmp/tmp.5WRwegkZMH/tmp/node_modules/arp-a: Command failed.
Exit code: 7
Command: sh
Arguments: -c node-gyp rebuild
Directory: /tmp/tmp.5WRwegkZMH/tmp/node_modules/arp-a
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.10.0 | linux | x64
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: Cannot find module 'internal/fs'
gyp ERR! stack     at Function.Module._resolveFilename (module.js:470:15)
gyp ERR! stack     at Function.Module._load (module.js:418:25)
gyp ERR! stack     at Module.require (module.js:498:17)
gyp ERR! stack     at require (internal/module.js:20:19)
gyp ERR! stack     at evalmachine.<anonymous>:18:20
gyp ERR! stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/fstream/node_modules/graceful-fs/fs.js:11:1)
gyp ERR! stack     at Module._compile (module.js:571:32)
gyp ERR! stack     at Object.Module._extensions..js (module.js:580:10)
gyp ERR! stack     at Module.load (module.js:488:32)
gyp ERR! stack     at tryModuleLoad (module.js:447:12)
gyp ERR! System Linux 4.8.0-1-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/tmp.5WRwegkZMH/tmp/node_modules/arp-a
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**What is the expected behavior?**

Works with npm 4:

```
$ npm i arp-a

> arp-a@0.5.1 install /tmp/tmp.5WRwegkZMH/tmp/node_modules/arp-a
> node-gyp rebuild

make : on entre dans le répertoire « /tmp/tmp.5WRwegkZMH/tmp/node_modules/arp-a/build »
  SOLINK_MODULE(target) Release/obj.target/macos.node
  COPY Release/macos.node
make : on quitte le répertoire « /tmp/tmp.5WRwegkZMH/tmp/node_modules/arp-a/build »
/tmp/tmp.5WRwegkZMH/tmp
└── arp-a@0.5.1 

npm WARN enoent ENOENT: no such file or directory, open '/tmp/tmp.5WRwegkZMH/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.
```

And npm5:

```
$ npm5 i arp-a
npm notice BETA npm5 is beta software. Please see https://github.com/npm/npm/issues/16510 for known issues, and please file a new one if you find something new.

> arp-a@0.5.1 install /tmp/tmp.5WRwegkZMH/tmp/node_modules/arp-a
> node-gyp rebuild

make : on entre dans le répertoire « /tmp/tmp.5WRwegkZMH/tmp/node_modules/arp-a/build »
  SOLINK_MODULE(target) Release/obj.target/macos.node
  COPY Release/macos.node
make : on quitte le répertoire « /tmp/tmp.5WRwegkZMH/tmp/node_modules/arp-a/build »
npm WARN saveError ENOENT: no such file or directory, open '/tmp/tmp.5WRwegkZMH/tmp/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/tmp/tmp.5WRwegkZMH/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

added 1 package in 0.757s
```

**Please mention your node.js, yarn and operating system version.**

- **Node:** 7.10.0
- **yarn**: tested with 0.24.5 and 0.25.2
- **OS**: Debian GNU/Linux 9 (stretch)

**Comment by Daniel15** [comment]
The error says "Try to update node-gyp" - maybe try that? `yarn global add node-gyp`.

**Comment by julien-f** [comment]
I've never installed it by myself but maybe the version packaged with yarn is too old for 7.10.0 indeed.

I'll try :)

**Comment by julien-f** [comment]
I don't reproduce with Node 8.1.
