### ISSUE TITLE
Support for private packages (yarn is searching for http instead of https)

### ISSUE THREAD

**Issue by beatrizaldaz** [yarnpkg/yarn#3532]
Yarn version: 
  0.24.6

Node version: 
  6.9.5

Platform: 
  win32 x64

npm manifest: 
  {
    "name": "kendo-test",
    "version": "0.0.0",
    "license": "MIT",
    "scripts": {
      "ng": "ng",
      "start": "ng serve",
      "build": "ng build",
      "test": "ng test",
      "lint": "ng lint",
      "e2e": "ng e2e"
    },
    "private": true,
    "dependencies": {
      "@angular/common": "^4.0.0",
      "@angular/compiler": "^4.0.0",
      "@angular/core": "^4.0.0",
      "@angular/forms": "^4.0.0",
      "@angular/http": "^4.0.0",
      "@angular/platform-browser": "^4.0.0",
      "@angular/platform-browser-dynamic": "^4.0.0",
      "@angular/router": "^4.0.0",
      "@angular/animations": "^4.0.0",
      "core-js": "^2.4.1",
      "rxjs": "^5.1.0",
      "zone.js": "^0.8.4",
      "@progress/kendo-angular-charts" : "1.1.0",
      "@progress/kendo-angular-intl" : "1.0.0",
      "@progress/kendo-angular-l10n" : "1.0.0",
      "@progress/kendo-drawing" : "1.0.3",
      "hammerjs" : "2.0.8"
    },
    "devDependencies": {
      "@angular/cli": "1.0.3",
      "@angular/compiler-cli": "^4.0.0",
      "@types/jasmine": "2.5.38",
      "@types/node": "~6.0.60",
      "codelyzer": "~2.0.0",
      "jasmine-core": "~2.5.2",
      "jasmine-spec-reporter": "~3.2.0",
      "karma": "~1.4.1",
      "karma-chrome-launcher": "~2.1.1",
      "karma-cli": "~1.0.1",
      "karma-jasmine": "~1.1.0",
      "karma-jasmine-html-reporter": "^0.2.2",
      "karma-coverage-istanbul-reporter": "^0.2.0",
      "protractor": "~5.1.0",
      "ts-node": "~2.0.0",
      "tslint": "~4.5.0",
      "typescript": "~2.2.0"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: connect ETIMEDOUT 23.253.4.114:80
      at Object.exports._errnoException (util.js:1022:11)
      at exports._exceptionWithHostPort (util.js:1045:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

Project https://github.com/beatrizaldaz/kendo-test_trial.git

Example of .npmrc
@progress:registry=https://registry.npm.telerik.com/
//registry.npm.telerik.com/:_authToken=.....
strict-ssl=true

To create a trial account in telerik to test private packages: https://www.telerik.com/login/v2/kendo?ReturnUrl=https%3a%2f%2fwww.telerik.com%2fdownload-trial-file%2fv2%2fkendo-angular-ui#register

**Comment by bestander** [comment]
Please see other issues with https://github.com/yarnpkg/yarn/labels/feature-private-registries, I think there should be a workaround

**Comment by bestander** [comment]
Maybe a setting in .yarnrc IIRC
