### ISSUE TITLE
Yarn install throw gyp ERR [Binary has a problem]

### ISSUE THREAD

**Issue by ganny26** [yarnpkg/yarn#3602]
**Do you want to request a *feature* or report a *bug*?**

Bug
**What is the current behavior?**

1. I cloned this angular 2 repo git clone **https://github.com/preboot/angular-webpack.git my-app**
.  and did yarn install 
2. It took almost 5 mins to show status

**If the current behavior is a bug, please provide the steps to reproduce.**
1.cd my-app
2.yarn install

```
yarn install v0.24.6
info No lockfile found.
[1/4] Resolving packages...
warning protractor > jasmine > glob > minimatch@0.3.0: Please update to minimatc                                                                                            h 3.0.2 or higher to avoid a RegExp DoS issue
warning remap-istanbul > istanbul > fileset > minimatch@2.0.10: Please update to                                                                                             minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[2/4] Fetching packages...
warning fsevents@1.1.1: The platform "win32" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error E:\Angular2\my-app\node_modules\node-sass: Command failed.
Exit code: 1
Command: C:\WINDOWS\system32\cmd.exe
Arguments: /d /s /c node scripts/build.js
Directory: E:\Angular2\my-app\node_modules\node-sass
Output:
Binary found at E:\Angular2\my-app\node_modules\node-sass\vendor\win32-x64-48\binding.node
Testing binary
Binary has a problem: Error: %1 is not a valid Win32 application.
\\?\E:\Angular2\my-app\node_modules\node-sass\vendor\win32-x64-48\binding.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (E:\Angular2\my-app\node_modules\node-sass\lib\binding.js:19:10)
    at Object.<anonymous> (E:\Angular2\my-app\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:570:32)
Building the binary locally
Building: C:\Program Files\nodejs\node.exe E:\Angular2\my-app\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'E:\\Angular2\\my-app\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@6.9.2 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\Angular2\my-app\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\Angular2\my-app\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\Angular2\my-app\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\Angular2\my-app\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\Angular2\my-app\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\Angular2\my-app\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\Angular2\my-app\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\Angular2\my-app\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\Angular2\my-app\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\Angular2\my-app\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\Angular2\my-app\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\Angular2\my-app\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python D:\ProgramFiles\python27\python.EXE
gyp verb check python version `D:\ProgramFiles\python27\python.EXE -c "import platform; print(platform.python_version());"` returned: "2.7.13\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 6.9.2
gyp verb command install [ '6.9.2' ]
gyp verb install input version string "6.9.2"
gyp verb install installing version: 6.9.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 6.9.2
gyp verb build dir attempting to create "build" dir: E:\Angular2\my-app\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? E:\Angular2\my-app\node_modules\node-sass\build
gyp verb Not using VS2017: Could not use PowerShell to find VS2017
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: E:\Angular2\my-app\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: E:\Angular2\my-app\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: E:\Angular2\my-app\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn D:\ProgramFiles\python27\python.EXE
gyp info spawn args [ 'E:\\Angular2\\my-app\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\Angular2\\my-app\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\Angular2\\my-app\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\dellpc\\.node-gyp\\6.9.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\dellpc\\.node-gyp\\6.9.2',
gyp info spawn args   '-Dnode_gyp_dir=E:\\Angular2\\my-app\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\dellpc\\.node-gyp\\6.9.2\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\Angular2\\my-app\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\Angular2\\my-app\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\dellpc\.node-gyp\6.9.2
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 6/7/2017 11:14:14 PM.
Project "E:\Angular2\my-app\node_modules\node-sass\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [E:\Angular2\my-app\node_modules\node-sass\build\binding.sln]
Done Building Project "E:\Angular2\my-app\node_modules\node-sass\build\binding.sln" (default targets) -- FAILED.

Build FAILED.

"E:\Angular2\my-app\node_modules\node-sass\build\binding.sln" (default target) (1) ->
(_src_\libsass target) ->
  MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [E:\Angular2\my-app\node_modules\node-sass\build\binding.sln]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.15
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\Angular2\my-app\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\Angular2\\my-app\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\Angular2\my-app\node_modules\node-sass
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
**What is the expected behavior?**
Successful installation of node_modules
**Please mention your node.js, yarn and operating system version.**
node -v
v6.9.2

yarn --version
0.24.6

**Comment by Daniel15** [comment]
Sounds like an issue while building a native module:

>  MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [E:\Angular2\my-app\node_modules\node-sass\build\binding.sln]

Please ensure you have the .NET Framework SDK installed and then try again.

**Comment by ganny26** [comment]
Issue resolved after upgrading to .net framework
