### ISSUE TITLE
rror running install script for node_modules/fsevents: Command failed.

### ISSUE THREAD

**Issue by dschinkel** [yarnpkg/yarn#3678]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When running `yarn` I get:

```
yarn install v0.24.6
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/1] ⢀ fsevents: node-pre-gyp ERR!
[-/1] ⢀ waiting...
[-/1] ⢀ waiting...
[-/1] ⢀ waiting...
warning Error running install script for optional dependency: "/Users/dave/code/projects/consulting/mayfield/branches/w1-user-can-log-in/node_modules/fsevents: Command failed.\nExit code: 1\nCommand: sh\nArguments: -c node-pre-gyp install --fallback-to-build\nDirectory: /Users/dave/code/projects/consulting/mayfield/branches/w1-user-can-log-in/node_modules/fsevents\nOutput:\nnode-pre-gyp info it worked if it ends with ok\nnode-pre-gyp info using node-pre-gyp@0.6.32\nnode-pre-gyp info using node@8.1.0 | darwin | x64\nnode-pre-gyp info check checked for \"/Users/dave/code/projects/consulting/mayfield/branches/w1-user-can-log-in/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node\" (not found)\nnode-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.17/fse-v1.0.17-node-v57-darwin-x64.tar.gz\nnode-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.17/fse-v1.0.17-node-v57-darwin-x64.tar.gz\nnode-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.17/fse-v1.0.17-node-v57-darwin-x64.tar.gz \nnode-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.17 and node@8.1.0 (node-v57 ABI) (falling back to source compile with node-gyp) \nnode-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.17/fse-v1.0.17-node-v57-darwin-x64.tar.gz \nnode-pre-gyp ERR! build error \nnode-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)\nnode-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/dave/code/projects/consulting/mayfield/branches/w1-user-can-log-in/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:77:29)\nnode-pre-gyp ERR! stack     at emitOne (events.js:115:13)\nnode-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:7)\nnode-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:195:12)\nnode-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:366:16)\nnode-pre-gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:102:11)\nnode-pre-gyp ERsuccess Saved lockfile.
✨  Done in 19.99s.
```

**package.json**
```
{
  "name": "gizmo_web_app",
  "version": "0.1.0",
  "engines": {
    "node": "8.1.0",
    "npm": "5.0.3"
  },
  "private": true,
  "dependencies": {
    "babel-cli": "^6.24.1",
    "bootstrap": "^3.3.7",
    "chalk": "^1.1.3",
    "confidence": "^3.0.2",
    "dotenv": "^4.0.0",
    "lodash": "^4.17.4",
    "prop-types": "^15.5.9",
    "react": "^15.5.4",
    "react-bootstrap": "^0.31.0",
    "react-dom": "^15.5.4",
    "react-redux": "^5.0.5",
    "react-router-dom": "^4.1.1",
    "react-test-renderer": "^15.5.4",
    "redux": "^3.6.0",
    "redux-logger": "^3.0.1",
    "reselect": "^3.0.1",
    "superagent": "^3.5.2",
    "zxcvbn": "^4.4.2"
  },
  "devDependencies": {
    "babel-eslint": "^7.2.3",
    "babel-plugin-transform-object-rest-spread": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react-app": "^2.2.0",
    "chai": "^3.5.0",
    "chai-enzyme": "^0.6.1",
    "enzyme": "^2.8.2",
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^14.1.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^3.0.2",
    "eslint-plugin-react": "^6.10.3",
    "jsdom": "^11.0.0",
    "mocha": "^3.4.1",
    "nock": "^9.0.13",
    "react-addons-test-utils": "^15.5.1",
    "react-scripts": "0.9.5",
    "redux-mock-store": "^1.2.3",
    "redux-thunk": "^2.2.0",
    "sinon": "^2.3.2",
    "supertest": "^3.0.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "push": "yarn run build && git push",
    "eject": "react-scripts eject",
    "lint": "node_modules/.bin/eslint src"
  },
  "babel": {
    "presets": [
      "react-app"
    ]
  }
}
```

**Please mention your node.js, yarn and operating system version.**
node v8.1.0
npm v5.0.3

**Comment by chrissrogers** [comment]
Experiencing this as well.

Here's the error formatted a bit nicer

```
warning Error running install script for optional dependency: "/Users/dave/code/projects/consulting/mayfield/branches/w1-user-can-log-in/node_modules/fsevents: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-pre-gyp install --fallback-to-build
Directory: /Users/dave/code/projects/consulting/mayfield/branches/w1-user-can-log-in/node_modules/fsevents
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.32
node-pre-gyp info using node@8.1.0 | darwin | x64
node-pre-gyp info check checked for \"/Users/dave/code/projects/consulting/mayfield/branches/w1-user-can-log-in/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node\" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.17/fse-v1.0.17-node-v57-darwin-x64.tar.gz
node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.17/fse-v1.0.17-node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.17/fse-v1.0.17-node-v57-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.17 and node@8.1.0 (node-v57 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.17/fse-v1.0.17-node-v57-darwin-x64.tar.gz 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/dave/code/projects/consulting/mayfield/branches/w1-user-can-log-in/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:77:29)
node-pre-gyp ERR! stack     at emitOne (events.js:115:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:7)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:195:12)
node-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:366:16)
node-pre-gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:102:11)
node-pre-gyp ERsuccess Saved lockfile.
```

**Comment by chrissrogers** [comment]
Looks like the fsevents binary has gone AWOL for some reason and isn't falling back to compiling. v1.1.2 is present, however, so if you're able to update your dependency to that version, you'll be good to go

**Comment by bestander** [comment]
Thanks for repro steps.
I think @chrissrogers is right, the binary was not uploaded to node-pre-gyp storage yet.
I can't repro this anymore with Node 8, I think it should be resolved now.

**Comment by cramhead** [comment]
I installed it manually, `yarn global add node-pre-gyp` and it installed fine. I did have the error though

**Comment by wendywww** [comment]
`yarn global add node-pre-gyp` helps solving the above error, thanks @cramhead 
Just a heads up, my system is node 8+ and "node-pre-gyp info using node-pre-gyp@0.6.33" and after run the command above, 'Installed "node-pre-gyp@0.10.0" with binaries:
      - node-pre-gyp'. Problem solved.

**Comment by vinsrepo** [comment]
Great @wendywww It works for me. Thanks.

**Comment by kevincoleman** [comment]
Just going to chime in here—

In my case, a project dependency had its own dependency on fsevents, which was no longer being served at its old URL.

In case you have a similar situation (aka a bitrotting project), here’s what I did:

- Visit yarn.lock or package-lock.json
- Search through any mentions of fsevents for the version number that matches the one in your error
- Look up the tree to see if that dependency is listed as a dependency of an actual direct dependency of your project
- Find the associated project dependency in your package.json
- Check for available updates to that dependency
- Cross your fingers that updating that dependency version doesn’t cause mayhem

To me this seemed like a more “correct” solution (in my case) because manually/directly updating just that subdependency could cause unexpected errors in the project dependency. If updating your project dependency causes errors, the docs/help for that dependency should at least help you through the upgrade path.

Not saying other answers are wrong, but I thought someone else might benefit from seeing this.
