### ISSUE TITLE
Error starting packager: Any reason for npm v5.0.3 not supported?

### ISSUE THREAD

**Issue by aschrijver** [yarnpkg/yarn#3744]
Just after clean install of Yarn and on `yarn start` I get the following error:
```
yarn start v0.24.6
$ react-native-scripts start 
15:08:22: Starting packager...
***ERROR STARTING PACKAGER***

Error: You are using npm version 5.0.3. Please use an npm version that is >= 3.0.0 and < 5.0.0.
15:08:22: Error starting packager: Error: Couldn't start project. Please fix the errors and restart the project.
    at /xdl/src/Project.js:1038:11
    at Generator.next (<anonymous>)
    at step (/home/barnie/DatReactNative/node_modules/xdl/build/Project.js:1468:191)
    at /home/barnie/DatReactNative/node_modules/xdl/build/Project.js:1468:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
...
```

Is this intentional and should I downgrade `npm`, or is this a project dependency that can be updated?

Node: v8.1.2
Yarn: v0.24.6
OS: Ubuntu 16.04.1 LTS

**Comment by rally25rs** [comment]
There is an open issue for this over here: https://github.com/react-community/create-react-native-app/issues/275

I suspect some dependency up the chain requires that version of NPM.
