### ISSUE TITLE
yarn upgrade --latest error

### ISSUE THREAD

**Issue by IgorAufricht** [yarnpkg/yarn#3806]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
When using `yarn upgrade --latest`, in some cases there's an error (even though `yarn` and `yarn upgrade` work fine).

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create an empty directory with the following `package.json` (this is the minimal example that shows the error):
```
{
  "name": "test",
  "dependencies": {
    "karma-coverage": "^1.1.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-junit-reporter": "^1.2.0",
    "karma-phantomjs-launcher": "^1.0.2",
    "karma-sourcemap-loader": "~0.3.7",
    "karma-webpack": "^1.8.1",
    "phantomjs-prebuilt": "^2.1.14"
  },
  "devDependencies": {
    "grunt": "~1.0.1"
  }
}
```
2. Run `yarn`. (This works correctly.)
3. Run `yarn upgrade --latest`.
4. I get an error like this (clearing yarn cache doesn't help):
```
$ yarn upgrade --latest
yarn upgrade v0.27.5
warning package.json: No license field
warning package.json: No license field
warning test: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
warning Pattern ["phantomjs-prebuilt@^2.1.14"] is trying to unpack in the same destination "C:\\Users\\U001912\\AppData\\Local\\Yarn\\cache\\v1\\npm-phantomjs-prebuilt-2.1.14-d53d311fcfb7d1d08ddb24014558f1188c516da0" as pattern ["phantomjs-prebuilt@^2.1.7"]. This could result in a non deterministic behavior, skipping.
[3/4] Linking dependencies...
warning "webpack-dev-middleware@1.11.0" has unmet peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0".
warning "karma-jasmine@1.1.0" has unmet peer dependency "jasmine-core@*".
warning "karma-jasmine@1.1.0" has unmet peer dependency "karma@*".
warning "karma-junit-reporter@1.2.0" has unmet peer dependency "karma@>=0.9".
warning "karma-phantomjs-launcher@1.0.4" has unmet peer dependency "karma@>=0.9".
warning "karma-webpack@2.0.3" has unmet peer dependency "webpack@^1.1.0 || ^2 || ^2.1.0-beta.0 || ^2.2.0-rc.0".
[4/4] Rebuilding all packages...
error C:\Users\U001912\AppData\Local\Yarn\cache\v1\npm-phantomjs-prebuilt-2.1.14-d53d311fcfb7d1d08ddb24014558f1188c516da0: Command failed.
Exit code: 1
Command: C:\Windows\system32\cmd.exe
Arguments: /d /s /c node install.js
Directory: C:\Users\U001912\AppData\Local\Yarn\cache\v1\npm-phantomjs-prebuilt-2.1.14-d53d311fcfb7d1d08ddb24014558f1188c516da0
Output:
module.js:442
    throw err;
    ^

Error: Cannot find module 'request-progress'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\U001912\AppData\Local\Yarn\cache\v1\npm-phantomjs-prebuilt-2.1.14-d53d311fcfb7d1d08ddb24014558f1188c516da0\install.js:9:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.
```

**What is the expected behavior?**
The dependencies are correctly installed and then updated to the latest version.

**Please mention your node.js, yarn and operating system version.**
Git Bash on Windows 7 x64
Node v6.3.0
yarn 0.27.5

**Comment by IgorAufricht** [comment]
Removing `phantomjs-prebuilt` finishes correctly both for the minimal example above and for our full `package.json`.

**Comment by ibbatta** [comment]
+ 1 here

**Comment by BYK** [comment]
No longer happening.
