### ISSUE TITLE
tape command not working with yarn in Windows 8

### ISSUE THREAD

**Issue by sudo-suhas** [yarnpkg/yarn#3827]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Not able to run test using `tape`. Fails with `Error: Cannot find module 'E:\Projects\repos\autodll-webpack-plugin\-r'`

**If the current behavior is a bug, please provide the steps to reproduce.**
```
λ git clone https://github.com/asfktz/autodll-webpack-plugin.git
...
λ yarn
yarn install v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.1.2: The platform "win32" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 70.70s.

λ yarn test
yarn test v0.27.5
$ tape -r babel-register specs/**/*.js | faucet
module.js:487
    throw err;
    ^

Error: Cannot find module 'E:\Projects\repos\autodll-webpack-plugin\-r'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at E:\Projects\repos\autodll-webpack-plugin\node_modules\faucet\node_modules\tape\bin\tape:5:5
    at Array.forEach (native)
    at Object.<anonymous> (E:\Projects\repos\autodll-webpack-plugin\node_modules\faucet\node_modules\tape\bin\tape:4:23)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
not ok 1 no plan found
not ok 2 no assertions found
⨯ fail  2
error Command failed with exit code 1.
```
`npm test` also fails with the same error.

**What is the expected behavior?**
If I run `npm install`, it works fine. This is due to the difference in `node_modules/.bin/tape.cmd`:

```
# npm
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\tape\bin\tape" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\tape\bin\tape" %*
)

# yarn
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\faucet\node_modules\tape\bin\tape" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\faucet\node_modules\tape\bin\tape" %*
)
```
If I overwrite the file with `npm` version, things work fine.

**Please mention your node.js, yarn and operating system version.**
```
λ node --version
v8.1.2
λ yarn --version
0.27.5
λ systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 8 Pro
OS Version:                6.2.9200 N/A Build 9200
```

**Comment by BYK** [comment]
Looks like the bin definition from `faucet` overwrites the bin definition from your newer tape requirement from `devDependencies`. @bestander I remember you working on link creation recently (cc @arcanis if my memory is at fault). Any idea if we fixed this on master or not?

**Comment by bestander** [comment]
Yep, package-linker.js->determineTopLevelBinLinks should have a run through top level patterns first.
https://github.com/yarnpkg/yarn/issues/3801 related

**Comment by BYK** [comment]
Closing in favor of #3801.
