### ISSUE TITLE
Cannot find module 'babel-runtime/core-js/get-iterator'

### ISSUE THREAD

**Issue by Tin-Nguyen** [yarnpkg/yarn#3844]
hi all,

After upgraded to the latest version of Yarn (0.27.5), we got the issue:
```
23:51:25 ERROR in ./demo/index.jsx
23:51:25 Module build failed: Error: Cannot find module 'babel-runtime/core-js/get-iterator'
23:51:25     at Function.Module._resolveFilename (module.js:470:15)
23:51:25     at Function.Module._load (module.js:418:25)
23:51:25     at Module.require (module.js:498:17)
23:51:25     at require (internal/module.js:20:19)
23:51:25     at Object.<anonymous> (/var/lib/jenkins/workspace/UI_Pure_Render_Components_01_Pull_Requests/node_modules/babel-core/lib/transformation/file/index.js:6:21)
23:51:25     at Module._compile (module.js:571:32)
23:51:25     at Object.Module._extensions..js (module.js:580:10)
23:51:25     at Module.load (module.js:488:32)
23:51:25     at tryModuleLoad (module.js:447:12)
23:51:25     at Function.Module._load (module.js:439:3)
23:51:25     at Module.require (module.js:498:17)
23:51:25     at require (internal/module.js:20:19)
23:51:25     at Object.<anonymous> (/var/lib/jenkins/workspace/UI_Pure_Render_Components_01_Pull_Requests/node_modules/babel-core/lib/api/node.js:6:13)
23:51:25     at Module._compile (module.js:571:32)
23:51:25     at Object.Module._extensions..js (module.js:580:10)
23:51:25     at Module.load (module.js:488:32)
23:51:25     at tryModuleLoad (module.js:447:12)
23:51:25     at Function.Module._load (module.js:439:3)
23:51:25     at Module.require (module.js:498:17)
23:51:25     at require (internal/module.js:20:19)
23:51:25     at Object.<anonymous> (/var/lib/jenkins/workspace/UI_Pure_Render_Components_01_Pull_Requests/node_modules/babel-core/index.js:1:80)
23:51:25     at Module._compile (module.js:571:32)
23:51:25     at Object.Module._extensions..js (module.js:580:10)
23:51:25     at Module.load (module.js:488:32)
23:51:25     at tryModuleLoad (module.js:447:12)
23:51:25     at Function.Module._load (module.js:439:3)
23:51:25     at Module.require (module.js:498:17)
23:51:25     at require (internal/module.js:20:19)
23:51:25     at Object.<anonymous> (/var/lib/jenkins/workspace/UI_Pure_Render_Components_01_Pull_Requests/node_modules/babel-loader/lib/index.js:3:13)
23:51:25     at Module._compile (module.js:571:32)
```

The process worked well on the old version of Yarn (0.24.6).

We're using node : v7.7.4, npm  : 4.1.2

The issue works well on my local (MacOS), but cannot work well in Jenkins using AWS Linux.

If someone got the same issue, please let me know if you can fix it.

Thanks

**Comment by Tin-Nguyen** [comment]
downgraded to the old version 0.24.6, it works well

**Comment by paul-soporan** [comment]
Closing as this issue is very old and this has likely been resolved.
