### ISSUE TITLE
npm install -g yarn -> Cannot set property 'getDocsInfo' of undefined

### ISSUE THREAD

**Issue by raphael22** [yarnpkg/yarn#3850]
Last installation though npm lead to this error after cli usage.

```
npm install -g yarn

yarn

/home/nikopol/.nvm/versions/node/v6.9.4/lib/node_modules/yarn/lib/cli/commands/index.js:308
commands[key].getDocsInfo = getDocsInfo(key);

TypeError: Cannot set property 'getDocsInfo' of undefined
    at Object.<anonymous> (/home/nikopol/.nvm/versions/node/v6.9.4/lib/node_modules/yarn/lib/cli/commands/index.js:308:29)
    at Module._compile (/home/nikopol/.nvm/versions/node/v6.9.4/lib/node_modules/yarn/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (/home/nikopol/.nvm/versions/node/v6.9.4/lib/node_modules/yarn/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at _load_index3 (/home/nikopol/.nvm/versions/node/v6.9.4/lib/node_modules/yarn/lib/cli/index.js:18:43)
    at Object.<anonymous> (/home/nikopol/.nvm/versions/node/v6.9.4/lib/node_modules/yarn/lib/cli/index.js:135:54)

```

**Please mention your node.js, yarn and operating system version.**
node : v6.9.4 / v6.11
yarn : tried v0.24 & v0.27.5
os : Lubuntu x64

**Comment by emckay** [comment]
I'm also having this issue on v0.24.5 and v0.27.5 on Ubuntu 16.04 with node 6.10.3

**Comment by eluleci** [comment]
Me too while creating Docker image from node:6.9.5-alpine .

**Comment by talldan** [comment]
We've also just started experiencing this out of the blue:

Node v6.10.3
Yarn: 0.27.5
Ubuntu (not sure on the version, it's a CI server)

**Comment by ot-juan-davila** [comment]
same issue 
Node v6.9.5
Yarn: 0.27.5
windows 10

**Comment by jdbevan** [comment]
I got the same on:
Node v6.11.0
Yarn 0.27.5 / 0.27.3
macOS Sierra 10.12.5

and

Node v8.1.3
Yarn 0.27.5
macOS Sierra 10.12.5

**Comment by christoph-daehne** [comment]
Got the same on
Node v6.3.1, v8.1.2
Yarn >= 0.24.0
macOS and Docker Image node:6.3.1

**Comment by niieani** [comment]
Workaround: `npm install -g node-emoji@1.4.3`

**Comment by raphael22** [comment]
@niieani Same error with node-emoji in global.

**Comment by AChusuei** [comment]
I think it's fixed.

**Comment by eluleci** [comment]
Yes, it is working now.

**Comment by raphael22** [comment]
Last ```npm install -g yarn``` successful !

**Comment by duncanfinney** [comment]
Works for me! Fixed.

**Comment by ot-juan-davila** [comment]
working after uninstall and reinstall

**Comment by bestander** [comment]
merging into https://github.com/yarnpkg/yarn/issues/3853
