### ISSUE TITLE
Yarn fails to launch on debian

### ISSUE THREAD

**Issue by rapha8l** [yarnpkg/yarn#3852]
Hi, 

I've just installed yarn on Debian testing, with npm install -g yarn (yarn@0.27.5)
 npm -v 3.10.10
node -v v6.11.0 (from deb.nodesource.com)
And that's what I get when lauching yarn

 yarn                                                   
/usr/lib/node_modules/yarn/lib/cli/commands/index.js:322
  commands[key].getDocsInfo = getDocsInfo(key);
                            ^

TypeError: Cannot set property 'getDocsInfo' of undefined
    at Object.<anonymous> (/usr/lib/node_modules/yarn/lib/cli/commands/index.js:322:29)
    at Module._compile (/usr/lib/node_modules/yarn/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (/usr/lib/node_modules/yarn/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at _load_index3 (/usr/lib/node_modules/yarn/lib/cli/index.js:18:43)
    at Object.<anonymous> (/usr/lib/node_modules/yarn/lib/cli/index.js:136:54)

Thanks !

**Comment by jdbevan** [comment]
This is a duplicate of https://github.com/yarnpkg/yarn/issues/3851

**Comment by yoyo837** [comment]
This is a duplicate of #3851 and #3850

**Comment by rapha8l** [comment]
sorry, I close
