### ISSUE TITLE
yarn 0.28.2 clean install fails on exec, @ "Error: Cannot find module 'semver'"

### ISSUE THREAD

**Issue by pgnd** [yarnpkg/yarn#3895]
**Before creating an issue please make sure you are using the latest version of yarn.**

```
YARN_VER="0.28.2"
wget -O yarn-${YARN_VER}.tar.gz \
 https://github.com/yarnpkg/yarn/archive/v${YARN_VER}.tar.gz
tar zvxf yarn-${YARN_VER}.tar.gz
```

**Please mention your node.js, yarn and operating system version.**

```
node -v && npm -v
	v8.1.3
	5.1.0
lsb_release -rd
	Description:    openSUSE Leap 42.2
	Release:        42.2
```

**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

clean install of yarn 0.28.2 fails on exec,

```
	"Error: Cannot find module 'semver'"
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```
sh -x yarn-0.28.2/bin/yarn
	++ echo yarn-0.28.2/bin/yarn
	++ sed -e 's,\\,/,g'
	+ argv0=yarn-0.28.2/bin/yarn
	+++ readlink yarn-0.28.2/bin/yarn
	+++ echo yarn-0.28.2/bin/yarn
	++ dirname yarn-0.28.2/bin/yarn
	+ basedir=yarn-0.28.2/bin
	+ case "$(uname -s)" in
	++ uname -s
	+++ readlink -f yarn-0.28.2/bin/yarn
	++ dirname /usr/local/src/yarn/yarn-0.28.2/bin/yarn
	+ basedir=/usr/local/src/yarn/yarn-0.28.2/bin
	+ command_exists node
	+ command -v node
	+ '[' '' = 1 ']'
	+ node /usr/local/src/yarn/yarn-0.28.2/bin/yarn.js
	module.js:487
	    throw err;
	    ^

	Error: Cannot find module 'semver'
	    at Function.Module._resolveFilename (module.js:485:15)
	    at Function.Module._load (module.js:437:25)
	    at Module.require (module.js:513:17)
	    at require (internal/module.js:11:18)
	    at Object.<anonymous> (/usr/local/src/yarn/yarn-0.28.2/bin/yarn.js:8:14)
	    at Module._compile (module.js:569:30)
	    at Object.Module._extensions..js (module.js:580:10)
	    at Module.load (module.js:503:32)
	    at tryModuleLoad (module.js:466:12)
	    at Function.Module._load (module.js:458:3)
	+ ret=1
	+ exit 1
```

checking

```
cat /usr/local/src/yarn/yarn/bin/yarn.js

	...
	// validate that used node version is supported
	var semver = require('semver');
	...

which npm
	/usr/local/nodejs/bin/npm

ls -al /usr/local/nodejs/bin/npm
	lrwxrwxrwx 1 root root 38 Jul 10 18:39 /usr/local/nodejs/bin/npm -> ../lib/node_modules/npm/bin/npm-cli.js*

npm list -g --depth=1
	/usr/local/src/node-v8.1.3-linux-x64/lib
	└─┬ npm@5.2.0
	  ├── abbrev@1.1.0
	  ...
	  ├── semver@5.3.0
	  ...
	  └── write-file-atomic@2.1.0

```

**Comment by pgnd** [comment]
This is not yarn-specific -- some issue with node itself ...

**Comment by arcanis** [comment]
You must not use the raw Yarn source code - it doesn't contain the Yarn dependencies. Use the single-file release instead (such as `yarn-0.28.1.js`).

**Comment by pgnd** [comment]
@arcanis 

well that makes a difference, doesn't it!?  now ...
```
yarn --version
  0.28.1
```
thx! o/
