### ISSUE TITLE
Cannot read property 'config' of undefined"

### ISSUE THREAD

**Issue by moretti** [yarnpkg/yarn#3905]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
I'm getting the following error when running `yarn install`:
```
error An unexpected error occurred: "project-name/node_modules/node-sass: Cannot read property 'config' of undefined".
```

Here's the full error log:
https://github.com/moretti/yarn-node-sass-bug/blob/master/yarn-error.log

I created a minimal repo where I can reproduce the issue (using yarn@0.27.5):
https://github.com/moretti/yarn-node-sass-bug

I think it's a regression introduced by one of the recent stable releases, I don't get any error with yarn@0.24.6, for example.

**Please mention your node.js, yarn and operating system version.**
Yarn version:
  0.27.5 (installed with homebrew)

Node version:
  6.11.0

Platform:
  darwin x64

**Comment by BYK** [comment]
I'm not getting the same error but I can reproduce the install failure with latest master.

**Comment by BYK** [comment]
This is probably a duplicate of #3728. What do you think?

**Comment by moretti** [comment]
@BYK Thanks for your help!
Seems slightly different, I don't see "success Saved lockfile." and I get exactly the same error if I run `yarn` twice.

**Comment by mcmar** [comment]
I'm getting the same error with the same trace in `yarn-error.log`
I'm getting it with `node-sass` and with `nodent-runtime`
Ex:
```
Trace:
  TypeError: /Users/mike/informed-web/node_modules/nodent-runtime: Cannot read property 'config' of undefined
      at /usr/local/Cellar/yarn/0.27.5/libexec/lib/yarn-cli.js:34600:185
      at Generator.next (<anonymous>)
      at step (/usr/local/Cellar/yarn/0.27.5/libexec/lib/yarn-cli.js:91:30)
      at /usr/local/Cellar/yarn/0.27.5/libexec/lib/yarn-cli.js:102:13
      at <anonymous>
```

**Comment by mcmar** [comment]
Success! I figured out what was breaking (for me). The issue was that node-gyp wasn't installed globally.
So yarn does tell you this
```
info This package requires node-gyp, which is not currently installed. Yarn will attempt to automatically install it. If this fails, you can run "yarn global add node-gyp" to manually install it.
```
but when it says "Yarn will attempt to automatically install it", that code is actually broken atm.
So that's fine. I expected that. And I ran `yarn global add node-gyp` and it succeeded. Perfect! But it still broke! But when I ran `which node-gyp` I got nothing. But when I ran `yarn global list node-gyp` it was there! It turns out that yarn's global package manager is also totally ~fucked~ screwed. The issue is that all your global packages get lost when you upgrade, except yarn still thinks they're there. See issue here: https://github.com/yarnpkg/yarn/issues/2064
So I ran
```
yarn global remove node-gyp
yarn global add node-gyp
```
and that seems to work!
```
$ which node-gyp
/usr/local/Cellar/node/8.1.4/bin/node-gyp

$ rm -r node_modules && yarn cache clean && yarn install
...blah...
success Saved lockfile.
```
Now that said, all my other global yarn packages are still ~fucked up~ messed up.
There's a package out there to fix this: https://www.npmjs.com/package/fix-yarn-global-packages
But ironically, that also needs to be installed globally. So then you're back to square one.
Apparently, word on the street is that you should just use `npm -g install <package>` until yarn gets its ~shit~ stuff together with regards to global packages.

**Comment by BYK** [comment]
@mcmar would you say this is a duplicate of @2064 then, which has a PR attached?

Also can you please remove the stroked-out words from your previous message? Looks like you already know it's not a great idea to use that tone here so why leave them there? 😉
