### ISSUE TITLE
Can't yarn add for some packages

### ISSUE THREAD

**Issue by metheglin** [yarnpkg/yarn#3925]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Can't `yarn add` against some packages.

**If the current behavior is a bug, please provide the steps to reproduce.**

I guess the packages which includes `@` or `/` in its name give these errors.

```
% node -v
v6.11.1
% yarn --version
0.27.5
```

I confirmed `@expo/bunyan`, `@expo/ngrok` give errors.

```
% yarn add @expo/bunyan
yarn add v0.27.5
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@expo%2fbunyan: Could not authenticate metheglin".
info If you think this is a bug, please open a bug report with the information provided in "/Users/metheglin/rvprov-picasso/ReactNativeTemplate/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

```
% yarn add @expo/ngrok
yarn add v0.27.5
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@expo%2fngrok: Could not authenticate metheglin".
info If you think this is a bug, please open a bug report with the information provided in "/Users/metheglin/rvprov-picasso/ReactNativeTemplate/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

On the other hand, most packages like `query-string`, `babel` looks good.

```
% yarn add query-string
yarn add v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 3 new dependencies.
├─ object-assign@4.1.1
├─ query-string@4.3.4
└─ strict-uri-encode@1.1.0
Done in 0.81s.
```

```
% yarn add babel
yarn add v0.27.5
[1/4] Resolving packages...
warning babel@6.23.0: In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ babel@6.23.0
Done in 0.56s.
```

Also, I confirmed I could `npm install --save` against the packages which give errors in case of `yarn`.

```
% npm install --save @expo/bunyan
npm notice created a lockfile as package-lock.json. You should commit this file.
+ @expo/bunyan@1.8.10
added 18 packages and removed 1 package in 3.513s

% ls -ld node_modules/@expo/bunyan
drwxr-xr-x  15 metheglin  staff  510  7 13 17:12 node_modules/@expo/bunyan/
```

Here is the error report.
yarn-error.log

```
Arguments:
  /usr/local/bin/node /usr/local/bin/yarn add @expo/bunyan

PATH:
  /Users/metheglin/efprov-api/shared/efssh:/Users/metheglin/.rbenv/shims:/Users/metheglin/.rbenv/bin:/Users/metheglin/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/opt/ImageMagick/bin:/usr/local/ec2/ec2-api-tools-1.6.13.0/bin

Yarn version:
  0.27.5

Node version:
  6.11.1

Platform:
  darwin x64

npm manifest:
  {
    "name": "ReactNativeTemplate",
    "version": "0.1.0",
    "private": true,
    "dependencies": {}
  }

yarn manifest:
  No manifest

Lockfile:
  # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
  # yarn lockfile v1

Trace:
  Error: https://registry.yarnpkg.com/@expo%2fbunyan: Could not authenticate metheglin
      at Request.params.callback [as _callback] (/usr/local/Cellar/yarn/0.27.5/libexec/lib/yarn-cli.js:58200:18)
      at Request.self.callback (/usr/local/Cellar/yarn/0.27.5/libexec/lib/yarn-cli.js:114242:22)
      at emitTwo (events.js:106:13)
      at Request.emit (events.js:191:7)
      at Request.<anonymous> (/usr/local/Cellar/yarn/0.27.5/libexec/lib/yarn-cli.js:115225:10)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:188:7)
      at IncomingMessage.<anonymous> (/usr/local/Cellar/yarn/0.27.5/libexec/lib/yarn-cli.js:115145:12)
      at IncomingMessage.g (events.js:292:16)
      at emitNone (events.js:91:20)
```

**What is the expected behavior?**

The packages is to be installed under `node_modules` by `yarn add`.

**Please mention your node.js, yarn and operating system version.**

MacOSX 10.11.6

```
% node -v
v6.11.1
% yarn --version
0.27.5
```

**Comment by metheglin** [comment]
Sorry, this was the same issue for 
https://github.com/yarnpkg/yarn/issues/1952

The problem resolved with commenting out `_auth` section at `$HOME/.npmrc`.
