### ISSUE TITLE
Cannot install @mapbox/togeojson

### ISSUE THREAD

**Issue by thomassuckow** [yarnpkg/yarn#3928]
**What is the current behavior?**

Visit https://yarnpkg.com/en/package/@mapbox/togeojson
Copy install command "`yarn add @mapbox/togeojson`"
Run command
`$yarn add @mapbox/togeojson`

```
yarn add @mapbox/togeojson
yarn add v0.27.5
info No lockfile found.
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@mapbox%2ftogeojson: User not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/user/test/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
An unexpected error occurred: "https://registry.yarnpkg.com/@mapbox/togeojson/-/togeojson-0.16.0.tgz: Request failed \"404 Not Found\"".
```

/Users/user/test/yarn-error.log:
```
Arguments:
  /usr/local/bin/node /usr/local/bin/yarn add @mapbox/togeojson

PATH:
  /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/Library/TeX/texbin

Yarn version:
  0.27.5

Node version:
  6.9.4

Platform:
  darwin x64

npm manifest:
  No manifest

yarn manifest:
  No manifest

Lockfile:
  No lockfile

Trace:
  Error: https://registry.yarnpkg.com/@mapbox%2ftogeojson: User not found
      at Request.params.callback [as _callback] (/usr/local/Cellar/yarn/0.27.5/libexec/lib/yarn-cli.js:58200:18)
      at Request.self.callback (/usr/local/Cellar/yarn/0.27.5/libexec/lib/yarn-cli.js:114242:22)
      at emitTwo (events.js:106:13)
      at Request.emit (events.js:191:7)
      at Request.<anonymous> (/usr/local/Cellar/yarn/0.27.5/libexec/lib/yarn-cli.js:115225:10)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:188:7)
      at IncomingMessage.<anonymous> (/usr/local/Cellar/yarn/0.27.5/libexec/lib/yarn-cli.js:115145:12)
      at IncomingMessage.g (events.js:291:16)
      at emitNone (events.js:91:20)
```

If the package is in the package.json and lockfile you get:
```
Trace:
  Error: https://registry.yarnpkg.com/@mapbox/togeojson/-/togeojson-0.16.0.tgz: Request failed "404 Not Found"
      at Request.handleRequestError (/usr/local/Cellar/yarn/0.27.5/libexec/lib/yarn-cli.js:56351:20)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:188:7)
      at Request.onRequestResponse (/usr/local/Cellar/yarn/0.27.5/libexec/lib/yarn-cli.js:115128:10)
      at emitOne (events.js:96:13)
      at ClientRequest.emit (events.js:188:7)
      at HTTPParser.parserOnIncomingClient (_http_client.js:474:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
      at TLSSocket.socketOnData (_http_client.js:363:20)
      at emitOne (events.js:96:13)
```

Yet `wget https://registry.yarnpkg.com/@mapbox/togeojson/-/togeojson-0.16.0.tgz` works...

**What is the expected behavior?**

The package should install. It works with `npm install @mapbox/togeojson`

The package I swear worked in June. But my old copy of 0.24.5 doesn't work anymore either. Maybe a registry bug?

**Please mention your node.js, yarn and operating system version.**
$ yarn --version
0.27.5
$ node --version
v6.9.4
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73

**Comment by thomassuckow** [comment]
Derp. It is because my npmrc has auth info for a private registry which is down, so I removed the registry line but forgot to remove the auth lines.

The error message could be a lot better.
