### ISSUE TITLE
New Projects Don't Run Yarn Install

### ISSUE THREAD

**Issue by mtpultz** [yarnpkg/yarn#3970]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
Running `ng new projectName` with or without any options drops the files into place, but no longer runs `yarn install` instead I get the output below, and a yarn error log (also below).  I only remember updating the Angular CLI from 1.2.0 to 1.2.1 in the last two days, but at some point last week I did update Node from 7.x to 8.x.  When I run `ng get packageManager` it returns yarn, and just for good measure I set it again.

```
You can `ng set --global packageManager=yarn`.
Installing packages for tooling via yarn.
You can `ng set --global packageManager=yarn`.
Project 'projectName' successfully created.
```

**Yarn Error Log**

```
Arguments:
  D:\Installs\nodejs\node.exe D:\Installs\yarn\bin\yarn.js install

PATH:
  D:\Installs\Git\mingw64\bin;D:\Installs\Git\usr\bin;C:\Users\mtpul\bin;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;D:\Installs\Git\cmd;C:\ProgramData\ComposerSetup\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\erl8.0\bin;C:\Program Files (x86)\Elixir\bin;C:\WINDOWS\system32\config\systemprofile\.mix\escripts;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;D:\Installs\yarn\bin;C:\HashiCorp\Vagrant\bin;D:\Installs\nodejs;D:\Installs\Ruby\22-x64\bin;C:\Users\mtpul\AppData\Local\Microsoft\WindowsApps;D:\Installs\php\php-7.0.12;C:\Users\mtpul\AppData\Roaming\Composer\vendor\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\mtpul\AppData\Local\Yarn\bin;C:\Program Files\Docker Toolbox;C:\Users\mtpul\AppData\Roaming\npm

Yarn version:
  0.27.5

Node version:
  8.1.4

Platform:
  win32 x64

npm manifest:
  {
    "name": "projectName",
    "version": "0.0.0",
    "license": "MIT",
    "scripts": {
      "ng": "ng",
      "start": "ng serve",
      "build": "ng build",
      "test": "ng test",
      "lint": "ng lint",
      "e2e": "ng e2e"
    },
    "private": true,
    "dependencies": {
      "@angular/animations": "^4.0.0",
      "@angular/common": "^4.0.0",
      "@angular/compiler": "^4.0.0",
      "@angular/core": "^4.0.0",
      "@angular/forms": "^4.0.0",
      "@angular/http": "^4.0.0",
      "@angular/platform-browser": "^4.0.0",
      "@angular/platform-browser-dynamic": "^4.0.0",
      "@angular/router": "^4.0.0",
      "core-js": "^2.4.1",
      "rxjs": "^5.1.0",
      "zone.js": "^0.8.4"
    },
    "devDependencies": {
      "@angular/cli": "1.2.1",
      "@angular/compiler-cli": "^4.0.0",
      "@angular/language-service": "^4.0.0",
      "@types/jasmine": "~2.5.53",
      "@types/jasminewd2": "~2.0.2",
      "@types/node": "~6.0.60",
      "codelyzer": "~3.0.1",
      "jasmine-core": "~2.6.2",
      "jasmine-spec-reporter": "~4.1.0",
      "karma": "~1.7.0",
      "karma-chrome-launcher": "~2.1.1",
      "karma-cli": "~1.0.1",
      "karma-coverage-istanbul-reporter": "^1.2.1",
      "karma-jasmine": "~1.1.0",
      "karma-jasmine-html-reporter": "^0.2.2",
      "protractor": "~5.1.2",
      "ts-node": "~3.0.4",
      "tslint": "~5.3.2",
      "typescript": "~2.3.3"
    }
  }

yarn manifest:
  No manifest

Lockfile:
  No lockfile

Trace:
  Error: write EPIPE
      at exports._errnoException (util.js:1022:11)
      at Socket._writeGeneric (net.js:762:25)
      at Socket._write (net.js:781:8)
      at doWrite (_stream_writable.js:371:12)
      at writeOrBuffer (_stream_writable.js:357:5)
      at Socket.Writable.write (_stream_writable.js:274:11)
      at Socket.write (net.js:699:40)
      at ConsoleReporter._log (D:\Installs\yarn\lib\yarn-cli.js:81298:17)
      at ConsoleReporter.log (D:\Installs\yarn\lib\yarn-cli.js:81290:10)
      at ConsoleReporter.step (D:\Installs\yarn\lib\yarn-cli.js:81243:10)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
`ng new projectName` creates the files and runs `yarn `install` to pull down dependencies instead of running it manually.

**Please mention your node.js, yarn and operating system version.**
Node v8.x, Yarn 0.27.5, Windows 10

**Comment by BYK** [comment]
Looks like it fails when trying to write out to console. Which terminal emulator are you using?

Also sometimes if `yarn` is called indirectly, files may be used for piping on Windows. May be you are running out of disk space or memory or something?

**Comment by mtpultz** [comment]
I'm using the VSCode's terminal, but just in case I also tried it using ConEmu, and then Git Bash all with the same result.  I'd be surprised if I was running of disk space or memory on this desktop.  

Can run it manually afterwards so not blocking, but wanted to report it since it wasn't happening last week, and as mentioned only Node and the CLI were updated.
