### ISSUE TITLE
Yarn fails to install `murmurhash-native`

### ISSUE THREAD

**Issue by davidaurelio** [yarnpkg/yarn#4155]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

Yarn fails with 

```

Using Yarn from /Users/davidaurelio/fbsource/xplat/third-party/yarn/yarn
yarn add v0.28.4
warning package.json: No license field
info No lockfile found.
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/1] ⠠ murmurhash-native: https://github.com/royaltm/node-murmurhash-native/releases/download/v3.2.1/murmurhash-v3.2.1-node-v57-darwin-x64.tar.gz
[-/1] ⠠ waiting...
[-/1] ⠠ waiting...
[-/1] ⠠ waiting...
error /Users/davidaurelio/fbsource/xplat/foo/node_modules/murmurhash-native: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-pre-gyp install --fallback-to-build
Directory: /Users/davidaurelio/fbsource/xplat/foo/node_modules/murmurhash-native
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.36
node-pre-gyp info using node@8.3.0 | darwin | x64
node-pre-gyp info check checked for "/Users/davidaurelio/fbsource/xplat/foo/node_modules/murmurhash-native/lib/Release/murmurhash.node" (not found)
node-pre-gyp http GET https://github.com/royaltm/node-murmurhash-native/releases/download/v3.2.1/murmurhash-v3.2.1-node-v57-darwin-x64.tar.gz
node-pre-gyp http 404 https://github.com/royaltm/node-murmurhash-native/releases/download/v3.2.1/murmurhash-v3.2.1-node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/royaltm/node-murmurhash-native/releases/download/v3.2.1/murmurhash-v3.2.1-node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for murmurhash-native@3.2.1 and node@8.3.0 (node-v57 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/royaltm/node-murmurhash-native/releases/download/v3.2.1/murmurhash-v3.2.1-node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/davidaurelio/fbsource/xplat/foo/node_modules/node-pre-gyp/lib/util/compile.js:77:29)
node-pre-gyp ERR! stack     at emitOne (events.js:115:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:7)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
node-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:374:16)
node-pre-gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
node-pre-gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:180:9)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/8.3.0/bin/node" "/Users/davidaurelio/fbsource/xplat/foo/node_modules/murmurhash-native/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/davidaurelio/fbsource/xplat/foo/node_modules/murmurhash-native
node-pre-gyp ERR! node -v v8.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

`yarn add murmurhash-native`

**What is the expected behavior?**

`murmurhash-native` gets installed

**Comment by davidaurelio** [comment]
it works with npm

**Comment by arcanis** [comment]
> 404 status code downloading tarball https://github.com/royaltm/node-murmurhash-native/releases/download/v3.2.1/murmurhash-v3.2.1-node-v57-darwin-x64.tar.gz

Seems like an issue with murmurhash-native. It tries do download an archive that doesn't exist.

**Comment by arcanis** [comment]
Weirdly, I'm not able to reproduce this issue - running `yarn add murmurhash-native` seems to work fine :/

**Comment by kaylieEB** [comment]
Also verified that it installs properly on the latest master. I think it's good to close.

**Comment by davidaurelio** [comment]
after checking with @arcanis it turned out that this happened because I did not have `node-gyp` installed globally.

**Comment by stouch** [comment]
If you meet this error while a gitlab-runner execution on a kubernetes cluster, I think you can refer to this : https://gitlab.com/gitlab-org/gitlab/-/issues/345402
