### ISSUE TITLE
master is randomly failing

### ISSUE THREAD

**Issue by arcanis** [yarnpkg/yarn#4191]
All the failures are on CircleCI, and look like this:

```
Summary of all failing tests
 FAIL  __tests__/commands/info.js
  ● without arguments and in directory containing a valid package file

    expect(array).toContain(value)
    
    Expected array:
      ["name", "description", "dist-tags", "versions", "maintainers", "time", "repository", "readmeFilename", "homepage", "bugs", "license", "users", "version", "installationMethod", "preferGlobal", "engines", "bin", "dist", "directories"]
    To contain value:
      "scripts"
      
      at expectedKeys.forEach.key (__tests__/commands/info.js:55:52)
      at Array.forEach (native)
      at runInfo (__tests__/commands/info.js:55:18)
      at __tests__/commands/info.js:29:13
      at next (native)
      at step (node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
```

Have we changed something related to this? @BYK @Daniel15

**Comment by arcanis** [comment]
Seems like the first failure related to the error above appeared in #4189, but the PR is unrelated and I get the same error on one of my PR that hasn't been rebased since #4189 landed. Previous errors on master are 500 or timeouts.

**Comment by arcanis** [comment]
Also breaks other PRs that were passing before - #4174.
