### ISSUE TITLE
Packages located in `node_modules/.bin` disappearing!  Very weird behavior

### ISSUE THREAD

**Issue by thebigredgeek** [yarnpkg/yarn#4209]
For whatever reason, there seems to be very strange behavior when attempting to install dependencies in `node_modules/.bin`, such as when installing mocha as a dev dependency of a project.

See package.json / yarn.lock [here](https://gist.github.com/thebigredgeek/89aff101ebd1f0fe283efeef93dd96f9).

Mocha is listed as a dev dependency.  After running `yarn`, I get the following weirdness:

```bash
edge(cleanup*)$ ./node_modules/.bin/mocha
zsh: no such file or directory: ./node_modules/.bin/mocha
```

If I add yarn explicitly via `yarn add mocha --dev`, if it works:

```bash
edge(cleanup*)$ ./node_modules/.bin/mocha
module.js:471
    throw err;
    ^

Error: Cannot find module 'chai'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/andrew.rhyne/Projects/collectivehealth/edge/test/cli/edge-build.spec.js:1:1)
    at Module._compile (module.js:570:32)
    at loader (/Users/andrew.rhyne/Projects/collectivehealth/edge/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/andrew.rhyne/Projects/collectivehealth/edge/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/andrew.rhyne/Projects/collectivehealth/edge/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/andrew.rhyne/Projects/collectivehealth/edge/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/Users/andrew.rhyne/Projects/collectivehealth/edge/node_modules/mocha/lib/mocha.js:513:10)
    at Object.<anonymous> (/Users/andrew.rhyne/Projects/collectivehealth/edge/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

Except it now cannot find locally installed dev dependencies like `chai`.  If i want to use other dependencies, I have to install them along-side mocha in a single command:

```bash
edge(cleanup*)$ yarn add mocha chai supertest --dev
yarn add v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved 3 new dependencies.
├─ chai@4.1.1
├─ mocha@3.5.0
└─ supertest@3.0.0
Done in 2.40s.
edge(cleanup*)$ ./node_modules/.bin/mocha


  cli/edge-build
    ✓ returns exit code 0 (null) (1065ms)
```

After this, if I install anything else in my project via yarn, `mocha` is removed from `node_modules/.bin`.

This seems very bizarre.  Any advice?

Thanks!

### Versions
**yarn** 0.27.5
**nodejs** 6.11.1
**osx** 10.12.6

**Comment by BYK** [comment]
I am almost sure that you are in production mode via `NODE_ENV=production` :)

**Comment by thebigredgeek** [comment]
Nope, I am not!  This was one of the first things that I checked!

**Comment by BYK** [comment]
@thebigredgeek sorry, I can't reproduce this locally with the latest build from master. Can you try this with one of the nightlies? You can use https://yarnpkg.com/en/docs/nightly to see how to get one. I'd suggest downloading the JS file and trying that.

**Comment by BYK** [comment]
Closing due to inactivity.
