### ISSUE TITLE
Cannot publish package

### ISSUE THREAD

**Issue by jonhue** [yarnpkg/yarn#4228]
```
$ yarn publish
/c/Program Files (x86)/Yarn/bin/yarn: line 3: readlink: command not found
yarn publish v0.27.5
[1/4] Bumping version...
info Current version: 0.1.1
question New version: 0.1.1
[2/4] Logging in...
info npm username: <USERNAME>
info npm email: <EMAIL>
question npm password:
success Logged in.
[3/4] Publishing...
error An unexpected error occurred: "https://registry.yarnpkg.com/turboboost: You must be logged in to publish packages.".
info If you think this is a bug, please open a bug report with the information provided in "c:\\Users\\Jonas\\apps\\turboboost\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.
```

Log:
```
Arguments: 
  c:\Program Files\nodejs\node.exe c:\Program Files (x86)\Yarn\bin\yarn.js publish

PATH: 
  c:\Users\Jonas\bin;.;C:\RailsInstaller\Git\local\bin;C:\RailsInstaller\Git\mingw\bin;C:\RailsInstaller\Git\bin;c:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;c:\Program Files\ImageMagick-7.0.5-Q16;c:\ProgramData\Oracle\Java\javapath;c:\WINDOWS\system32;c:\WINDOWS;c:\WINDOWS\System32\Wbem;c:\WINDOWS\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\AMD\ATI.ACE\Core-Static;c:\Program Files\Microsoft SQL Server\130\Tools\Binn\;c:\Program Files (x86)\GtkSharp\2.12\bin;c:\Program Files\nodejs\;c:\Program Files\dotnet\;c:\Program Files\Redis\;c:\Program Files\Git\cmd;c:\Program Files (x86)\Yarn\bin;c:\Users\Jonas\scoop\apps\yarn\current\Yarn\bin;c:\Users\Jonas\scoop\apps\yarn\current\bin;c:\Users\Jonas\scoop\shims;C:\RailsInstaller\Git\cmd;c:\RailsInstaller\Ruby2.3.0\bin;c:\Users\Jonas\AppData\Local\Microsoft\WindowsApps;c:\Program Files\Heroku\bin;c:\Users\Jonas\AppData\Roaming\npm;c:\Users\Jonas\AppData\Local\Microsoft\WindowsApps;c:\Users\Jonas\AppData\Local\atom\bin;c:\Users\Jonas\AppData\Local\Yarn\bin

Yarn version: 
  0.27.5

Node version: 
  7.5.0

Platform: 
  win32 x64

npm manifest: 
  {
    "name": "turboboost",
    "version": "0.1.1",
    "description": "Enhanced AJAX handling for Rails apps",
    "main": "app/assets/javascripts/turboboost/turboboost.js.coffee",
    "repository": {
      "url": "https://github.com/waymondo/turboboost",
      "type": "git"
    },
    "homepage": "https://github.com/waymondo/turboboost",
    "author": "Waymondo <justin@waymondo.com>",
    "license": "MIT",
    "bugs": "https://github.com/waymondo/turboboost/issues",
    "files": [
      "app/assets/javascripts/turboboost/turboboost.js.coffee"
    ]
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: https://registry.yarnpkg.com/turboboost: You must be logged in to publish packages.
      at Request.params.callback [as _callback] (c:\Program Files (x86)\Yarn\lib\yarn-cli.js:58200:18)
      at Request.self.callback (c:\Program Files (x86)\Yarn\lib\yarn-cli.js:114242:22)
      at emitTwo (events.js:106:13)
      at Request.emit (events.js:192:7)
      at Request.<anonymous> (c:\Program Files (x86)\Yarn\lib\yarn-cli.js:115225:10)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:189:7)
      at IncomingMessage.<anonymous> (c:\Program Files (x86)\Yarn\lib\yarn-cli.js:115145:12)
      at Object.onceWrapper (events.js:291:19)
      at emitNone (events.js:91:20)
```

**Comment by BYK** [comment]
Closing due to inactivity. Also probably fixed in a recent version.
