### ISSUE TITLE
tarball fetcher fails with 401 for private registry

### ISSUE THREAD

**Issue by kenotron** [yarnpkg/yarn#4230]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
We host an internal registry (via VSTS). When the tarball-fetcher.js tries to retrieve a package artifact, it fails with the follow stack trace:
Trace: 
  Error: https://xxx.pkgs.visualstudio.com/_packaging/yyy/npm/registry/zzz/-/zzz-1.1.4.tgz: Request failed "401 Unauthorized"
      at Request.<anonymous> (E:\workspace\yarn\lib\fetchers\tarball-fetcher.js:210:26)
      at emitOne (events.js:115:13)
      at Request.emit (events.js:210:7)
      at Request.onRequestResponse (E:\workspace\yarn\node_modules\request\request.js:1074:10)
      at emitOne (events.js:115:13)
      at ClientRequest.emit (events.js:210:7)
      at HTTPParser.parserOnIncomingClient (_http_client.js:564:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
      at TLSSocket.socketOnData (_http_client.js:453:20)
      at emitOne (events.js:115:13)

**If the current behavior is a bug, please provide the steps to reproduce.**

Try to fetch from private registry - something that would trigger the tarball-fetcher

**What is the expected behavior?**
With the current stable release, it successfully fetches everything.

**Please mention your node.js, yarn and operating system version.**
node: 8.1.4
yarn: 1.0.0 (master, via link)
os: windows 10

**Comment by kenotron** [comment]
NVM, might be an artifact of running yarn via link
