### ISSUE TITLE
Issue with offline installation of @types/node

### ISSUE THREAD

**Issue by subyraman** [yarnpkg/yarn#4266]
**Do you want to request a *feature* or report a *bug*?**
Bug. @BYK suggested I repost this as a new issue.

**What is the current behavior?**
Offline installation of JSDOM fails on the dependency `@types/node`. This was noted in #825 but does not seem fully resolved.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
sraman@sraman: bar$ yarn add jsdom@11.0.0 --offline
yarn add v0.27.5
info No lockfile found.
[1/4] Resolving packages...
error Couldn't find any versions for "@types/node" that matches "^6.0.46" in our cache. Possible versions: ""
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

It is definitely available in my cache.

```
sraman@sraman: bar$ yarn cache ls | grep "@types"
@types/node                                          6.0.78                      npm      https://registry.yarnpkg.com/@types/node/-/node-6.0.78.tgz#5d4a3f579c1524e01ee21bf474e6fba09198f470
@types/node                                          6.0.87                      npm      https://registry.yarnpkg.com/@types/node/-/node-6.0.87.tgz#5ab5774f8351a33a935099fa6be850aa0b0ad564
@types/node     
```

A similar failure with a different message in the latest nightly:

```
sraman@sraman: bin$ ./yarn add jsdom@11.0.0 --offline
yarn add v1.0.0-20170825.1555
warning package.json: No license field
warning No license field
[1/4] 🔍  Resolving packages...
error Couldn't find any versions for "@types/node" that matches "^6.0.46" in our cache (possible versions are ""). This is usually caused by a missing entry in the lockfile, running Yarn without the --offline flag may help fix this issue.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**What is the expected behavior?**

I expect JSDOM to be installed offline. Other cached packages work fine with offline installation:

```
sraman@sraman: bin$ ./yarn add yargs@3.27.0 --offline
yarn add v1.0.0-20170825.1555
warning package.json: No license field
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 18 new dependencies.
├─ align-text@0.1.4
├─ camelcase@1.2.1
├─ center-align@0.1.3
├─ cliui@2.1.0
├─ decamelize@1.2.0
├─ invert-kv@1.0.0
├─ is-buffer@1.1.5
├─ kind-of@3.2.2
├─ lazy-cache@1.0.4
├─ lcid@1.0.0
├─ longest@1.0.1
├─ os-locale@1.4.0
├─ repeat-string@1.6.1
├─ right-align@0.1.3
├─ window-size@0.1.4
├─ wordwrap@0.0.2
├─ y18n@3.2.1
└─ yargs@3.27.0
warning No license field
✨  Done in 0.43s.
```

Node: v6.7.0
Tested with Yarn 0.27.5 and nightly  v1.0.0-20170825.1555

**Comment by GAumala** [comment]
I tried replicating this in yarn v0.28.4 and it's not fixed yet. But I don't really understand what is going on. Why does yarn try to find versions for `@types/node`? It is **not** listed as a [dependency of jsdom@11.0.0](https://github.com/tmpvar/jsdom/blob/0f4128dabbf155160eceae50a2217572439a631e/package.json)

**Comment by subyraman** [comment]
`@types/node` is a dependency of `parse5`, which is listed in the dependencies there.

**Comment by BYK** [comment]
Maybe this is a bug with scoped packages?

**Comment by sharno** [comment]
I took a shot at this issue and described what I found in PR #4815

**Comment by newren** [comment]
We had pretty severe problems with scoped packages and offline mode, particularly around @types modules, and found a simple fix that I made available at #4822.  It might be orthogonal to the issue reported here, but it sounded similar enough that I thought it was worth mentioning (at least for future folks doing google searches trying to find their problem and who come across this bug report)

**Comment by assafmo** [comment]
Still happens to me with 1.3.2 on ubuntu 16.04 with nodejs 9.3.0 and nodejs 7.7.4 and on ubuntu 17.10 with nodejs 9.3.0.
```
$ yarn add --offline jest 
yarn add v1.3.2
info No lockfile found.
[1/4] Resolving packages...
error Couldn't find any versions for "@types/node" that matches "*" in our cache (possible versions are ""). This is usually caused by a missing entry in the lockfile, running Yarn without the --offline flag may help fix this issue.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Couldn't find any versions for "@babel/code-frame" that matches "^7.0.0-beta.35" in our cache (possible versions are ""). This is usually caused by a missing entry in the lockfile, running Yarn without the --offline flag may help fix this issue.
    at /usr/local/lib/node_modules/yarn/lib/cli.js:49034:15
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:92:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:103:13
    at <anonymous>
```
