### ISSUE TITLE
Yarn 1.0.1 failing to install grpc (worked in 0.27.5)

### ISSUE THREAD

**Issue by psbanka** [yarnpkg/yarn#4404]
When trying to install grpc, I get the following:
```
error <project-dir>/node_modules/gcloud/node_modules/grpc: Command failed.
Exit code: 127
Command: ./node_modules/.bin/node-pre-gyp install --fallback-to-build
Arguments:
```

Basically, this works in 0.27.5, but now fails in 1.0.1. This is using node 6.11.1., 6.11.2, and 7.10.1 using OS X

**Comment by Daniel15** [comment]
Can you please try manually running that `node-pre-gyp` command and see if it works?

**Comment by psbanka** [comment]
Yes, here you go:
```
$ ./node_modules/.bin/node-pre-gyp install --fallback-to-build
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.36
node-pre-gyp info using node@7.10.1 | darwin | x64
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: tango package.json is not node-pre-gyp ready:
node-pre-gyp ERR! stack package.json must declare these properties:
node-pre-gyp ERR! stack main
node-pre-gyp ERR! stack binary.module_name
node-pre-gyp ERR! stack binary.module_path
node-pre-gyp ERR! stack binary.host
node-pre-gyp ERR! stack     at validate_config (/Users/psbanka/dev/tango/node_modules/node-pre-gyp/lib/util/versioning.js:203:15)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/Users/psbanka/dev/tango/node_modules/node-pre-gyp/lib/util/versioning.js:261:5)
node-pre-gyp ERR! stack     at install (/Users/psbanka/dev/tango/node_modules/node-pre-gyp/lib/install.js:165:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/Users/psbanka/dev/tango/node_modules/node-pre-gyp/lib/node-pre-gyp.js:50:37)
node-pre-gyp ERR! stack     at run (/Users/psbanka/dev/tango/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/Users/psbanka/dev/tango/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:571:32)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:580:10)
node-pre-gyp ERR! stack     at Module.load (module.js:488:32)
node-pre-gyp ERR! stack     at tryModuleLoad (module.js:447:12)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command "/Users/psbanka/.nvm/versions/node/v7.10.1/bin/node" "/Users/psbanka/dev/tango/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/psbanka/dev/tango
node-pre-gyp ERR! node -v v7.10.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
tango package.json is not node-pre-gyp ready:
package.json must declare these properties:
main
binary.module_name
binary.module_path
binary.host
```

**Comment by Daniel15** [comment]
```
node-pre-gyp ERR! stack Error: tango package.json is not node-pre-gyp ready:
node-pre-gyp ERR! stack package.json must declare these properties:
node-pre-gyp ERR! stack main
node-pre-gyp ERR! stack binary.module_name
node-pre-gyp ERR! stack binary.module_path
node-pre-gyp ERR! stack binary.host
```

This seems specific to that package, rather than a Yarn issue?
