### ISSUE TITLE
Yarn workspace incorrectly resolves node_modules path during script execution of workspace dependencies

### ISSUE THREAD

**Issue by labriola** [yarnpkg/yarn#4564]
**What is the current behavior?**
When you install the main project, it correctly begins installing the workspace dependencies. However, if one of the scripts in a dependencies attempts to execute a command, the location of the node_modules folder is incorrectly resolved.

As an example of the error:
\workspaceModuleBug\**node_modules\node_modules**\shx\lib\cli.js

**If the current behavior is a bug, please provide the steps to reproduce.**
With yarn workspaces enabled, clone the following repository and do a yarn install.
https://github.com/labriola/workspaceModuleBug

Yarn will throw an error when attempting to do an shx echo.

**What is the expected behavior?**
The node_module path should recurse upward correctly instead of making (what I believe to be) an invalid assumption.

**Please mention your node.js, yarn and operating system version.**
node v.6.11.3
yarn 1.1.0
windows 10

Happy to attempt to resolve if I can get a hint on where to poke around.

**Comment by labriola** [comment]
Apparently this is windows only. There seems to be a relationships between the CWD provided to the process spawn and the invocation of the cmd on windows, wherein a path assumption is being made.

**Comment by labriola** [comment]
This line is where the potentially errant path is added:

https://github.com/yarnpkg/yarn/blob/d64512c632e1ed12f5bffe8a1f50d235c18f0196/src/util/execute-lifecycle-script.js#L152

I am not saying this is necessarily where the fix should go but I am hoping it provides a quick way for someone to review and let me know a valid way to proceed.

**Comment by darkalor** [comment]
Still an issue in yarn 1.7.0. Have not found any workaround yet.

@BYK is this still on your list? It seems like a rather big blocker for using workspaces.

**Comment by pronebird** [comment]
We have the same issue with yarn 1.9.2, `node_modules` twice and scripts in `node_modules/.bin` are broken for scripts in the packages in workspaces.

**Comment by pronebird** [comment]
This seems to be Windows only problem, so I wonder if junctions are somehow not properly handled which causes node_modules being added twice to the bin path?

**Comment by marcelolx** [comment]
I'm facing same issue.

**Comment by Heliks** [comment]
Still not fixed for windows

**Comment by FMGordillo** [comment]
Can confirm that still happens on version 2.4.0 :c

**Comment by nwittwer** [comment]
Seeing this as well. OS: Windows, Yarn v1.22.5, Node v14.15.3.

```bash
error C:\Users\hi\Documents\...\node_modules\@myapp\app: Command failed.
Exit code: 1
Command: electron-builder install-app-deps
Arguments:
Directory: C:\Users\hi\Documents\...\node_modules\@myapp\app
Output:
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\Users\hi\Documents\...\node_modules\node_modules\electron-builder\out\cli\cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
```

**Comment by CGQAQ** [comment]
why this critical issue is not been solved, and even not a single contributor commented on this???

**Comment by drktfl** [comment]
Not a solution, but in some cases another workaround could be to prevent yarn from hoisting the required dependencies:

I.e., in the failing packages (_not_ in the root package.json!):

```json
"workspaces": {
  "nohoist": [
    "rimraf"
  ]
}
```

This will make sure that rimraf is resolved in the package-local node_modules.

But I would appreciate a fix in yarn, too :-)

**Comment by cruhl** [comment]
Just ran into this with a co-worker on windows.

**Comment by KAJdev** [comment]
Also running into this. 1.22.5

**Comment by lsarrazi** [comment]
Still a problem in 2023 ...

**Comment by slyduda** [comment]
just ran into this issue on windows as well

**Comment by m0rtalis** [comment]
Is there a fix for this? Having the same issue

**Comment by nonara** [comment]
Quick update on what's happening here.

The failure is happening when running the generated cmd files.

## Detail

Here's an example:

Say we have

```
- /package.json
- /packages/a
- /packages/b
```

Now assume our packages are scoped as: `@pkg/a` `@pkg/b`

`/packages/b/node_modules/.bin/rimraf.cmd`
```
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\..\..\..\node_modules\prisma\build\index.js" %*
  
  ; Added this line
  echo "%~dp0\..\..\..\..\node_modules\prisma\build\index.js"
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%

  ; Added this line
  echo "%~dp0\..\..\..\..\node_modules\prisma\build\index.js"

  node  "%~dp0\..\..\..\..\node_modules\prisma\build\index.js" %*
)
```

When it gets run from the symlink path (eg. `C:\project\node_modules\@pkg\a\node_modules\.bin`) instead of the resolved (real) path (eg. `C:\project\packages\a\node_modules\.bin`), it will resolve incorrectly, because the files are written assuming we're relative to the repo root. 

For example, this is what the paths would look like:

```
bin file path:

C:\project\node_modules\pkg\a\node_modules\.bin\\..\..\..\..\node_modules\prisma\build\index.js

resolved:

C:\project\node_modules\\node_modules\prisma\build\index.js
```

## Why it Happens

The issue is due to the fact that yarn is adding the symlink path instead of the real path to the PATH env.

@labriola was correct in it originating here:

https://github.com/yarnpkg/yarn/blob/master/src/util/execute-lifecycle-script.js#L198

This gets added as the top-most search location. Using the symlink path instead of the fully resolved real path will cause the relative paths to be broken.

## Solutions

### Solution 1 : Modify execute-lifecycle-script.js

This would be the most ideal IMO, assuming there are no side-effects.

A simple change is to edit `makeEnv` to the following:

```
  // Add node_modules .bin folders to the PATH
  for (const registryFolder of config.registryFolders) {
    const binFolder = path.join(registryFolder, '.bin');
    if (config.workspacesEnabled && config.workspaceRootFolder) {
      pathParts.unshift(path.join(config.workspaceRootFolder, binFolder));
    }
    pathParts.unshift(path.join(config.linkFolder, binFolder));

    // We resolve the path here before adding to PATH
    const realBinFolder = await fs.realpath(path.join(cwd, binFolder));
    pathParts.unshift(realBinFolder);
  }
```

### Solution 2 : Modify cmd files

We can resolve symlinks in the generated command files.

Here is an example:

```
@echo off
SETLOCAL
FOR /f "tokens=*" %%i IN ('fsutil reparsepoint query "%~dp0" ^| find "Print Name"') DO SET RealPath=%%i
SET RealPath=%RealPath:*Print Name: =%

@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%RealPath%\..\..\..\node_modules\rimraf\dist\esm\bin.mjs" %*
  echo "%RealPath%\..\..\..\node_modules\rimraf\dist\esm\bin.mjs"
) ELSE (
  node  "%RealPath%\..\..\..\node_modules\rimraf\dist\esm\bin.mjs" %*
  echo "%RealPath%\..\..\..\node_modules\rimraf\dist\esm\bin.mjs"
)
ENDLOCAL
```

We'd want to ensure that this works with Win XP and up, but I believe it will.

If not, we can also do something more simple, like using cd to the path.

## Questions for the Yarn Team


Questions I'd have for the Yarn team are:

1. Solution 1
   a. Would it be better to just use realpath at a higher level?
   b. Is there any potential downside to modifying it here?

Also: I see that some patches are being accepted for Yarn 1 which are not strictly security related. Notably, I tried this on Yarn 3 and had the same issue.

I'd love to get this merged, and if you require, I'll do an update Yarn 3 as well on whatever route we determine.

## PR

- #

**Comment by nonara** [comment]
PR is submitted. Hopefully I can get in touch with a team member so we can get it through.

Here's a release you all can use for now:

[@nonara/yarn@1.22.22-next.2](https://www.npmjs.com/package/@nonara/yarn)

I'll keep the `latest` tag pointing to the most recent

**Comment by nonara** [comment]
## Workaround & Update

I'm holding on the PR for now to see if I get a response. My published version works in the case of lifecycle scripts, but there are certain other issues where it plays a factor.

It seems it may make more sense to hit this in the generated `.cmd` files.

In any case, I'll wait to see if the team responds.

In the mean time, I made an npx tool we can use that will correct the .cmd files by making them resolve and use the realpath, where possible / necessary.

- https://github.com/nonara/yarn-fix-bin-cmds
