### ISSUE TITLE
Exits with code 1 on SIGTERM without waiting for child

### ISSUE THREAD

**Issue by adamdunkley** [yarnpkg/yarn#4667]
**Do you want to request a *feature* or report a *bug*?**
This is a bug

**What is the current behavior?**
Currently yarn terminates with exit code 1 when it receives a SIGTERM without waiting for the child to exit and without passing its child's exit status up the chain.

The issue that this stemmed from was about handling SIGTERM events (#3424) and was introduced in pull request #3789. 

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a simple express script:

```javascript
const app = require('./express');

const server = app.listen(config.port, () => {
    console.log(`server started`);
});
process.on('SIGTERM', () => {
    server.close(() => {
      setTimeout(() => {
        process.exit(0);
      }, 1000);
    });
});
```

Note that the script uses `setTimeout` to wait before exiting (as if it is waiting 1s for a client connection to end).

```
⇒  yarn start
yarn run v1.1.0
$ node src/index.js
server started
```

In another session run the following with the PID of that command:

```
kill $PID
```

Finally in that first session after it has exited:

```
⇒  echo $?
1
```

You can see that it exits immediately (not waiting 1s) and the error code is 1.

**What is the expected behavior?**

Expected behaviour is to do exactly as node would:

```
⇒  node src/index.js
server started
⇒  echo $?
0
```

This waits the 1s for the `setTimeout` (we kill using `kill $PID` in between the node and echo commands as above). You can also see we get the child's exit status (you can verify this by setting it to something else like `process.exit(9)` and seeing it come out.

I see some comments in the code where it is questioning what we should do about this: 
https://github.com/yarnpkg/yarn/blob/daa599d5fed8fe786d1f41031f271e2c703fced3/src/util/signal-handler.js#L6-L8

I think it's the child's job to decide what to do if a SIGTERM event is received. The parent should hand the signal to the child and wait to see if it exits. The only thing that I think Yarn *should* consider is whether there is a time limit that we would like to wait for naughty child processes that do not exit on time. Docker sets this to 10 seconds, whatever we set this to (if we do at all!!) we should make it a) clear and b) configurable.

One other thing: currently not sure what we do with SIGINT. I see weird stuff happening with that too (and I presume other signals?). Probably worth investigating signal handling more holistically?

**Please mention your node.js, yarn and operating system version.**

* Node version: 7 & 8
* Yarn version:  1.10.0
* macOS 16.3.0 and alpine

**Comment by adamdunkley** [comment]
I am very willing to commit time/code to getting this fixed properly as I think it's in a bit of a state at the moment but would like to get some agreement on direction first :)

**Comment by thetimothyp** [comment]
Has there been any more discussion on this anywhere? I agree that it's in a bit of a state right now.

W.r.t SIGINT, it doesn't look like it's being handled at all other than in onDeath(), similar to SIGTERM in [this comment](https://github.com/yarnpkg/yarn/issues/3424#issuecomment-308593931) from the old issue. I'm wondering if SIGINT might need to have slightly different handling from SIGTERM, since it's sent to all the processes in the foreground group instead of being forwarded to them through the parent.

cc @adamdunkley

**Comment by thetimothyp** [comment]
Has there been any more discussion on this?

I agree that it might be worth taking a look at signal handling as whole; it doesn't look like SIGINT is handled at all, apart from where [onDeath() handles it in mutex mode](https://github.com/yarnpkg/yarn/issues/3424#issuecomment-308593931). I think it might have to be handled slightly differently, since SIGINT is sent to all the processes in the foreground group instead of needing to be forwarded through the parent.

I'd also be willing to devote some time to this.

**Comment by ianstormtaylor** [comment]
Any maintainer input on this? It seems like it prevents Yarn from being used for real in any situations where you need `yarn run` to spawn a child in the background, which would be very useful in CI.

**Comment by presidenten** [comment]
Same problem.
```shell
$ yarn -v
1.12.3

$ node -v
v8.12.0

$ npm -v
6.4.1

$ node index.js
^C

Doing async cleaning
Done

$ npm start
^C

Doing async cleaning


Doing async cleaning
Done

$ yarn start
yarn run v1.12.3
^C

Doing async cleaning

$ Done # <--- Console.log('Done') ends up on new line in console, because yarn already quit.
```

To test: 
--package.json--
```json
{
  "scripts": {
    "start": "node index.js"
  }
}
```

--index.js--
```javascript
process.stdin.resume();

process.on('SIGINT', () => {
  console.log('\n');
  console.log('Doing async cleaning');
  
  setTimeout(() => {
    console.log('Done');
    process.exit(0);
  }, 500);
});
```

**Comment by heisian** [comment]
Agreed, this makes it impossible to use `yarn` for running processes that manage child processes...

In testing @presidenten's example:
```
timbo@Timbos-MacBook-Air.local:~/Web/ethos/cli
 [sandbox|✚ 2…1] ▷ yarn run test
yarn run v1.12.3
$ /Volumes/Case-Sensitive/Web/ethos/cli/node_modules/.bin/test
^C

Doing async cleaning

timbo@Timbos-MacBook-Air.local:~/Web/ethos/cli
 [sandbox|✚ 2…1] ▷ yarn run testevents.js:167
      throw er; // Unhandled 'error' event
      ^

Error: read EIO
    at TTY.onread (net.js:660:25)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

We can see that the process exits _immediately_, and output comes _after_ sending `SIGINT` (after "Doing async cleaning" we see the bash prompt again, indicating that the script has already exited).

**Comment by heisian** [comment]
Here is what I ended up doing:

```node
// The following captures keypress events and effectively blocks any of the
// CTRL+C/CTRL+Z/CTRL+D combinations from sending their respective signals.

readline.emitKeypressEvents(process.stdin)

if (process.stdin.isTTY) process.stdin.setRawMode(true)

process.stdin.on('keypress', (char, key) => {
  if (key.ctrl && key.name === 'c') {
    console.log("Caught CTRL+C and asking you to wait for this process to exit gracefully, mi'lord.")
    const exitCode = 0
    cleanupHandler(exitCode)
  }
})
```

**Comment by fyodorvi** [comment]
Same here, any ideas if this can be fixed?

**Comment by aleclarson** [comment]
I'm seeing this issue in yarn v1.22.4 but not in npm v6.12.0

It makes yarn unusable 😢

**Comment by adamdunkley** [comment]
@aleclarson my feeling is that attention now needs to moved to yarn v2 to get this fixed. They actually have a regression on the issue https://github.com/yarnpkg/yarn/issues/3424 (which is the issue that when fixed gave rise to this bug). I have commented on the issue on v2 that talks about this regression asking whoever implements a solution for it to consider this documented behaviour in order to avoid these problems. (see https://github.com/yarnpkg/berry/issues/991)

**Comment by adamdunkley** [comment]
After some careful review (read https://github.com/yarnpkg/berry/issues/991 for all the juicy details) the new behaviour I mentioned in v2 is actually desirable and the nub of it is that this is no longer a problem in v2 (yarn's exit status is the exit status of the child process). I will leave this open in case someone wants to either backport how it works in v2 to here (which might cause more problems if people rely on v1's behaviour) or fix the issue for v1, but for anyone who wants a solution to this now I recommend upgrading to v2!

**Comment by morungos** [comment]
Whatever is happening with this issue, it's still an annoyance. I ended up throwing together a tiny wrapper script -- my use case is that I use yarn and `run-p` to test a hybrid PHP app, and I needed a way to serve PHP alongside a proxy for migration, and I was using `php-fpm`. Weirdly, if I SIGINT php-fpm on the command line, all was fine, but if I use a yarn script, the SIGINT never got passed to `php-fpm`, so all the worker processes were left orphaned. My tiny wrapper script simply executes a command with inherit on its pipes, but forwards SIGINT to the child `php-fpm`. It's literally 10 lines. But I could not find any other way to make yarn + `run-p` handle process interruption correctly. Of course, seeing as how this is `php-fpm`, this is one of those cases where leaving it to the child to decide won't work.

**Comment by danmelton** [comment]
Sample code, if it's helpful:

const childProcesses = {};

function killProcessAfterChildrenDie() {
    if (Object.keys(childProcesses).length === 0) {
        process.exit(0)
    } else {
        setTimeout(() => {
            killProcessAfterChildrenDie()
        },             1000)
    }
}

readline.emitKeypressEvents(process.stdin)

if (process.stdin.isTTY) process.stdin.setRawMode(true)

process.stdin.on('keypress', (char, key) => {
    if (key.ctrl && key.name === 'c') {
        if (Object.keys(childProcesses).length) {
            Object.keys(childProcesses).forEach(key => {
                childProcesses[key].kill()
            })
        }
        killProcessAfterChildrenDie()
    }
})

const commands = process.argv.slice(2)

commands.forEach(command => {
        const cp = exec(command);
        cp.stdout.pipe(process.stdout);
        cp.stderr.pipe(process.stderr);
        cp.on("exit", code => {
            delete childProcesses[command]
            if (code) {
                console.error(`Non-Zero Exit(${code}): ${command}`);
                process.exit(1);
            }
        });
        cp.on("error", err => {
            console.error(`Error(${err.message}): ${command}`);
            process.exit(1);
        });

        childProcesses[command] = cp
    });

**Comment by JasonMan34** [comment]
Is this issue still unresolved?  
I'm aware that this is solved in yarn v3, but my docker environment is using yarn 1 to spawn yarn 3, so it's still an issue

**Comment by dobesv** [comment]
This is a major issue for shutdown handling when using yarn berry or yarn v1.  Node will not update the version of yarn in the docker image and yarn seemingly will not backport the fix to yarn v1, so you have to manually update the global yarn in your own docker images before using it to run apps with yarn inside docker.

**Comment by johncip** [comment]
It's worse than just the exit code mangling -- for scripts run in an interactive terminal, you'll get a prompt back before any children you shelled out to are done printing. Took me forever to figure out why.

Raw mode / handling Ctrl-C yourself does prevent it, but here's a workaround that doesn't require modifying the script.

```bash
#!/usr/bin/env bash

# trampoline.sh
#
# Puts `node` in its own process group and foregrounds it.
#
# Yarn v1 exits immediately on SIGINT without waiting for children (yarnpkg/yarn#4667),
# which causes scripts waiting for with Ctrl-C to misbehave.

set -m

# ensure local binaries in node_modules/.bin are still found
export PATH="$(cd "$(dirname "$0")/.." && pwd)/node_modules/.bin:$PATH"

node "$@" &
fg %1
```

In package.json:

```json
  "scripts": {
    "banana": "scripts/trampoline.sh scripts/banana.mjs",
  }
```

I'm glad it got fixed in later releases, and IMO it's deserving of a backport too. No one's relying on the v1 behavior:
- getting a prompt back before children are done writing to the terminal (not useful)
- getting a non-zero exit code when you're expecting a zero and potentially having to ignore real errors (not useful)
