### ISSUE TITLE
rc-hammerjs-0.6.5.tgz not found

### ISSUE THREAD

**Issue by alessiodionisi** [yarnpkg/yarn#4733]
I'm trying to install rc-hammerjs version 0.6.5, tgz archive is not found.

```
  rc-hammerjs@~0.6.0:
    version "0.6.5"
    resolved "https://registry.yarnpkg.com/rc-hammerjs/-/rc-hammerjs-0.6.5.tgz#fae3ea6fbc5cf483c06b9580be46f531b72e3921"
    dependencies:
      babel-runtime "^6.23.0"
      hammerjs "^2.0.8"
      prop-types "^15.5.9"
```

```
Trace: 
  Error: https://registry.yarnpkg.com/rc-hammerjs/-/rc-hammerjs-0.6.5.tgz: Request failed "404 Not Found"
      at ResponseError (/usr/local/Cellar/yarn/1.2.1/libexec/lib/cli.js:163:5)
      at Request.<anonymous> (/usr/local/Cellar/yarn/1.2.1/libexec/lib/cli.js:59296:26)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:188:7)
      at Request.module.exports.Request.onRequestResponse (/usr/local/Cellar/yarn/1.2.1/libexec/lib/cli.js:123897:10)
      at emitOne (events.js:96:13)
      at ClientRequest.emit (events.js:188:7)
      at HTTPParser.parserOnIncomingClient (_http_client.js:474:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
      at TLSSocket.socketOnData (_http_client.js:363:20)
```

**Comment by Daniel15** [comment]
0.6.5 doesn't seem to exist on npm's end either: https://registry.npmjs.org/rc-hammerjs/-/rc-hammerjs-0.6.5.tgz

0.6.4 and 0.6.6 both exist, so maybe 0.6.5 was unpublished.

This is not a Yarn issue, please follow up with the npm team as this is on their end 😃

**Comment by lizhengnacl** [comment]
I've had this problem, too. `yarn cache clean` works for me

**Comment by Daniel15** [comment]
`yarn cache clean` won't help if the file doesn't physically exist :)
