### ISSUE TITLE
yarn global add's offline flag seems to be ignored in Windows

### ISSUE THREAD

**Issue by ruidfigueiredo** [yarnpkg/yarn#4913]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
With the offline mirror correctly configured and populated (yarn config set yarn-offline-mirror ...)
yarn global add @angular/cli --offline 
or
yarn global add @angular/cli@specificVersion --offline --exact
will contact https://registry.yarnpkg.com/

**If the current behavior is a bug, please provide the steps to reproduce.**

On Windows:
Setup an offline mirror:
    yarn config set yarn-offline-mirror pathToMirror
Populate the mirror:
   yarn add @angular/cli
Turn off internet connection
   yarn global add @angular/cli --offline
Will fail while trying to contact https://registry.yarnpkg.org/

**What is the expected behavior?**
Should use the offline mirror as it does in Linux

**Please mention your node.js, yarn and operating system version.**
node version: 6.11.2
yarn version: 1.3.2
OS: Windows 10

**Comment by BYK** [comment]
I think this is not a Windows-specific issue but simply a configuration issue. `yarn config set yarn-offline-mirror` would usually set the config in either the user's home directory or in the project directory and `yarn global` wouldn't use the one from the project. I'd argue `yarn global` should use the user's config from the home directory tho.

I've looked at the code and this seems to be the case. Can you make sure `offline-mirror` is set in your `.yarnrc` in your home directory and not in the project?

**Comment by ruidfigueiredo** [comment]
It's picking up the correct config file, here's the output when running with `--verbose`

`C:\Users\rfigueiredo\Projects\temp\offline-new-ng>yarn global add @angular/cli --offline --verbose
yarn global v1.3.2
verbose 0.513 Checking for configuration file "C:\\Users\\rfigueiredo\\Projects\\temp\\offline-new-ng\\.npmrc".
verbose 0.515 Checking for configuration file "C:\\Users\\rfigueiredo\\.npmrc".
verbose 0.516 Checking for configuration file "C:\\Program Files\\nodejs\\etc\\npmrc".
verbose 0.518 Checking for configuration file "C:\\Users\\rfigueiredo\\Projects\\temp\\offline-new-ng\\.npmrc".
verbose 0.519 Checking for configuration file "C:\\Users\\rfigueiredo\\Projects\\temp\\.npmrc".
verbose 0.52 Checking for configuration file "C:\\Users\\rfigueiredo\\Projects\\.npmrc".
verbose 0.521 Checking for configuration file "C:\\Users\\rfigueiredo\\.npmrc".
verbose 0.521 Checking for configuration file "C:\\Users\\.npmrc".
verbose 0.523 Checking for configuration file "C:\\Users\\rfigueiredo\\Projects\\temp\\offline-new-ng\\.yarnrc".
verbose 0.523 Checking for configuration file "C:\\Users\\rfigueiredo\\.yarnrc".
verbose 0.523 Found configuration file "C:\\Users\\rfigueiredo\\.yarnrc".
verbose 0.526 Checking for configuration file "C:\\Program Files\\nodejs\\etc\\yarnrc".
verbose 0.526 Checking for configuration file "C:\\Users\\rfigueiredo\\Projects\\temp\\offline-new-ng\\.yarnrc".
verbose 0.527 Checking for configuration file "C:\\Users\\rfigueiredo\\Projects\\temp\\.yarnrc".
verbose 0.527 Checking for configuration file "C:\\Users\\rfigueiredo\\Projects\\.yarnrc".
verbose 0.527 Checking for configuration file "C:\\Users\\rfigueiredo\\.yarnrc".
verbose 0.528 Found configuration file "C:\\Users\\rfigueiredo\\.yarnrc".
verbose 0.528 Checking for configuration file "C:\\Users\\.yarnrc".
verbose 0.532 current time: 2017-11-23T14:16:28.687Z
verbose 0.538 Checking for configuration file "C:\\Users\\rfigueiredo\\AppData\\Local\\Yarn\\config\\global\\.npmrc".
verbose 0.541 Checking for configuration file "C:\\Users\\rfigueiredo\\.npmrc".
verbose 0.542 Checking for configuration file "C:\\Program Files\\nodejs\\etc\\npmrc".
verbose 0.543 Checking for configuration file "C:\\Users\\rfigueiredo\\AppData\\Local\\Yarn\\config\\global\\.npmrc".
verbose 0.543 Checking for configuration file "C:\\Users\\rfigueiredo\\AppData\\Local\\Yarn\\config\\.npmrc".
verbose 0.544 Checking for configuration file "C:\\Users\\rfigueiredo\\AppData\\Local\\Yarn\\.npmrc".
verbose 0.544 Checking for configuration file "C:\\Users\\rfigueiredo\\AppData\\Local\\.npmrc".
verbose 0.545 Checking for configuration file "C:\\Users\\rfigueiredo\\AppData\\.npmrc".
verbose 0.545 Checking for configuration file "C:\\Users\\rfigueiredo\\.npmrc".
verbose 0.546 Checking for configuration file "C:\\Users\\.npmrc".
verbose 0.546 Checking for configuration file "C:\\Users\\rfigueiredo\\AppData\\Local\\Yarn\\config\\global\\.yarnrc".
verbose 0.547 Checking for configuration file "C:\\Users\\rfigueiredo\\.yarnrc".
verbose 0.547 Found configuration file "C:\\Users\\rfigueiredo\\.yarnrc".
verbose 0.548 Checking for configuration file "C:\\Program Files\\nodejs\\etc\\yarnrc".
verbose 0.549 Checking for configuration file "C:\\Users\\rfigueiredo\\AppData\\Local\\Yarn\\config\\global\\.yarnrc".
verbose 0.549 Checking for configuration file "C:\\Users\\rfigueiredo\\AppData\\Local\\Yarn\\config\\.yarnrc".
verbose 0.55 Checking for configuration file "C:\\Users\\rfigueiredo\\AppData\\Local\\Yarn\\.yarnrc".
verbose 0.55 Checking for configuration file "C:\\Users\\rfigueiredo\\AppData\\Local\\.yarnrc".
verbose 0.55 Checking for configuration file "C:\\Users\\rfigueiredo\\AppData\\.yarnrc".
verbose 0.551 Checking for configuration file "C:\\Users\\rfigueiredo\\.yarnrc".
verbose 0.551 Found configuration file "C:\\Users\\rfigueiredo\\.yarnrc".
verbose 0.551 Checking for configuration file "C:\\Users\\.yarnrc".
verbose 0.599 Performing "GET" request to "yarnpkg.com/latest-version".
[1/4] Resolving packages...
verbose 0.695 Performing "GET" request to "https://registry.yarnpkg.com/@angular%2fcli".
verbose 21.729 Error: connect ETIMEDOUT 104.16.61.173:443
at Object.exports._errnoException (util.js:1020:11)
at exports._exceptionWithHostPort (util.js:1043:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
error An unexpected error occurred: "https://registry.yarnpkg.com/@angular%2fcli: connect ETIMEDOUT 104.16.61.173:443".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\rfigueiredo\\AppData\\Local\\Yarn\\config\\global\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

C:\Users\rfigueiredo\Projects\temp\offline-new-ng> `

The .yarnrc file that is found has the full path to the offline mirror and works fine when not using `global`

**Comment by Infern1** [comment]
seeing the same behaviour

**Comment by chaddotson** [comment]
Seeing this behavior on:
Ubuntu 16.04.4 LTS
Node v8.11.1
Yarn 1.6.0

After setting the yarn-offline-mirror.
yarn global add --offline vue-cli

results in:

$ yarn global v1.6.0

[1/4] Resolving packages...
info There appears to be trouble with your network connection. Retrying...
....

**Comment by userings** [comment]
Also seeing this issue on windows

**Comment by buchedlab** [comment]
I am seeing this issue. Offline behavior differs for global.

Both systems configured with yarn-offline-mirror and all packages synced between. For purpose of reproducing offline system is fresh install of yarn on air-gapped machine.

Steps to reproduce on offline system:

1) Generate a yarn lock file on the online system, then bring it into air-gapped environment .
2) Create new project folder and place yarn.lock file inside
~/folder> ls
yarn.lock
3) Add package to project -- Successful
~/folder>yarn add --offline @angular/cli
...
Done in ...
4) Add package to global -- Fails
~/folder>yarn global add --offline @angular/cli
[1/4] Resolving packages...
@angular/clii_

Yarn 1.12.3
Windows 7
Node 10.3.0

**Comment by figiel** [comment]
It seems it's not Windows-specific. 
It looks like for `yarn global` the command-line configuration is thrown out of the window here: https://github.com/yarnpkg/yarn/blob/1089b39c17cd7054a549cf640deb9155f7d964d6/src/cli/commands/global.js#L49
