### ISSUE TITLE
failed to install amphtml-validator in win10

### ISSUE THREAD

**Issue by maple3142** [yarnpkg/yarn#4918]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
run `yarn add amphtml-validator` on win10 then cause an error
error log:
```
C:\Users\Administrator\Documents\temp>yarn add amphtml-validator
openssl config failed: error:02001003:system library:fopen:No such process
yarn add v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/1] ⠐ amphtml-validator
[-/1] ⠐ waiting...
[-/1] ⠐ waiting...
[-/1] ⠐ waiting...
error C:\Users\Administrator\Documents\temp\node_modules\amphtml-validator: Command failed.
Exit code: 1
Command: \bin\sh -c "exit 0" 2> postinstall.DELETEME && rm postinstall.DELETEME || node postinstall-windows.js
Arguments:
Directory: C:\Users\Administrator\Documents\temp\node_modules\amphtml-validator
Output:
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:489:7)
    at Object.<anonymous> (C:\Users\Administrator\Documents\temp\node_modules\amphtml-validator\postinstall-windows.js:43:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```
`npm install --save amphtml-validator` works on both `win10` and `bash on windows`
`yarn add amphtml-validator` only works on `bash on windows`

**What is the expected behavior?**
install correctly

**Please mention your node.js, yarn and operating system version.**
- yarn 1.3.2
- node 8.1.4
- Windows10 professional, version 1709, build 16299.19

**Comment by blobcat** [comment]
I was able to work around this issue by defining the `NPM_CONFIG_PREFIX` environment variable and pointing it at my node installation dir. 

For example, if you installed to C:\nodejs: `setx NPM_CONFIG_PREFIX C:\nodejs`

If you're using nvm for windows this works: `setx NPM_CONFIG_PREFIX %NVM_SYMLINK%`

Not sure what the root cause is but in this case the amphtml-validator package has a post install script for windows that is supposed to update a global installation if there is one. It uses the NPM_CONFIG_PREFIX var to check if it exists.

**Comment by alrra** [comment]
@pbakaus ⬆️

**Comment by pbakaus** [comment]
paging @Gregable, who might know more.

**Comment by alrra** [comment]
@pbakaus, @Gregable FYI: [This](https://github.com/sonarwhal/sonarwhal/commit/87798d53bbe4b8eeafe0034ee6885c6fbf06fc9e#diff-82336f6a3e79999aed016545a5e68741) is what we are using in the `sonarwhal` project to work around this issue.
