### ISSUE TITLE
yarn fails to install git+ssh:// repo when git warns about "Warning: Permanently added"

### ISSUE THREAD

**Issue by buhichan** [yarnpkg/yarn#5013]
**Do you want to request a *feature* or report a *bug*?**
bug.

**What is the current behavior?**
I cannot install a git+ssh repo, yarn's warning is like:
```
Couldn't find match for "Warning:" in "_c" for "git@gitlab.xxx:xxx/xxx.git".
```
**If the current behavior is a bug, please provide the steps to reproduce.**

This message was very confusing to me, but I manage to find the reason in the source code, it's
because someone in my team changed `~/.ssh/config` to this:
```
Host *
  ...
  UserKnownHostsFile /dev/null
  ...
```
which makes ssh warn the message below every time I or yarn use `git ls-remote`:
```
Warning: Permanently added 'gitlab.xxxxx.com' (RSA) to the list of known hosts.
```
Then yarn just [took the first word](https://github.com/yarnpkg/yarn/blob/850e71f49197d03caf5b501f59a9fe45b98bde8e/src/util/git.js#L429) as the sha of this package and produced the confusing warning above.
After I changed `UserKnownHostsFile` to `~/.ssh/known_host`, the problem was solved.

**What is the expected behavior?**
It will be better if yarn can tolarate ssh's warning or provide a more reasonable message.

**Please mention your node.js, yarn and operating system version.**
node.js v7.2.1
yarn 1.3.2
os: centos-release-6-3.el6.centos.9.x86_64

**Comment by rally25rs** [comment]
I'm guess ing this is due to the code in `src/util/git.js` not being tollerant of any variation in output from the Git command

```
  async resolveDefaultBranch(): Promise<ResolvedSha> {
    try {
      const stdout = await spawnGit(['ls-remote', '--symref', this.gitUrl.repository, 'HEAD']);
      const lines = stdout.split('\n');
      const [, ref] = lines[0].split(/\s+/);
      const [sha] = lines[1].split(/\s+/);
      return {sha, ref};
```

It assumes the first 2 lines of output will be the ref and the sha.

We probably need a better way of parsing this output.

**Comment by acidio** [comment]
I was having the same issue but I saw that another [similar onde](https://github.com/yarnpkg/yarn/issues/5077) was solved and the newer version is working perfectly, I guess we could close this issue as well.

**Comment by nishunmind** [comment]
I'm having the same issue, is there any fix needed for this?

Please mention your node.js, yarn and operating system version.
node.js v10.15.3
yarn v1.16.0
os: MacOs Mojave v10.14.3 (18D42)

**Comment by PeterDaveHello** [comment]
I have some similiar issues here:

```
verbose 7.955 Error: Command failed.
Exit code: 1
Command: git
Arguments: archive --remote=ssh://git@gitlab.internal/web/share.git git.c:415 package.json
Directory: /builds/web-repos/2019/guess
Output:

    at ProcessTermError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:727:66)
    at ProcessTermError.MessageError (/usr/share/yarn/lib/cli.js:756:123)
    at new ProcessTermError (/usr/share/yarn/lib/cli.js:796:113)
    at ChildProcess.<anonymous> (/usr/share/yarn/lib/cli.js:25795:17)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Pipe._handle.close (net.js:600:12)
error Command failed.
Exit code: 1
Command: git
Arguments: archive --remote=ssh://git@gitlab.internal/web/share.git git.c:415 package.json
Directory: /builds/web-repos/2019/guess
Output:

info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Job failed: exit code 1
```

**Comment by PeterDaveHello** [comment]
Hi @arcanis, would you like to help take a look at this issue and my comment above? I'd like to send a PR for it if you agree, thanks!

**Comment by rockwyc992** [comment]
I found a bug, when warning message start with `/[a-f]/`, like `Fail` of `fatal`.
Fixed that with #7428.

**Comment by rockwyc992** [comment]
@arcanis @PeterDaveHello Hey, I think PR(#7428) could resolve above problems perfectly.

Though, there is still a bug when the first word contains only /[a-f]/, like `deadbeef`. We have no idea to check whether that is a real hash value.

**Comment by kym6464** [comment]
I was getting an error `Couldn't find match for "ref:" in "..."` when trying to install from a private github repo. The fix was to append `#desired-branch`:

```
"fancy": "git+https://4c7ee8df5fc91c55b2553569d39189a2c4fa6ea1:x-oauth-basic@github.com/strzibny/fancy.git#desired-branch"
```

**Comment by dom111** [comment]
I know this is an old issue, but I've just encountered a variation of this issue using yarn classic v1.22.19 (and it took me a while to find any discussion of it!).

When installing packages for a personal project (which contains a few repos referenced via `github:` since they are WIP) I encountered the follwing error message (although the `user/package` could change each time):

```
error An unexpected error occurred: "https://codeload.github.com/user/package/tar.gz/ref:: Request failed \"404 Not Found\"".
```

Note the `ref:` at the end of the URL which is [incorrectly parsed from the output of `git ls-remote ...`](https://github.com/yarnpkg/yarn/blob/v1.22.19/src/util/git.js#L451):

```js
stdout = await spawnGit(['ls-remote', '--symref', this.gitUrl.repository, 'HEAD']);
const lines = stdout.split('\n').filter(validRef);
const [, ref] = lines[0].split(/\s+/);
const [sha] = lines[1].split(/\s+/);
```

In my case this was due to [`ssh`'s `ControlMaster` setting](https://man.openbsd.org/ssh_config#ControlMaster) not working (presumably due to multiple references to GitHub repos in my project) resulting in an additional line of output:

```
ControlSocket /tmp/.ssh/master-git@github.com:22 already exists, disabling multiplexing
```

I've checked locally (modifying the copy of the sctipt in `.yarn`) and [gating this block](https://github.com/yarnpkg/yarn/blob/v1.22.19/src/util/child.js#L142-L144):

```js
if (proc.stderr) {
    proc.stderr.on('data', updateStdout);
}
```

with a check like `if (proc.stderr && opts.includeStderr) {` avoids this particular problem (and possibly any others with similar failures due to content in stderr). I'd be happy to make a PR (if relevant, and to include such a flag - defaulted to `true` and set to `false` for the particular `git ls-remote` call).

Alternatively, and please forgive my ignorance on this but, in the original block of code, will the happy path always expect a line that starts `ref:`? If so, could this be checked for and input upto that point be ingored instead?

**Comment by PeterDaveHello** [comment]
Actually, you won't get update or support on this old version, so many just drop it, use the newer versions. `npm` is much more faster now, thanks to the inspiration of yarn, besides that, you can also use `ied` or `pnpm`, so there's no need to stick to this old version of yarn.
