### ISSUE TITLE
yarn install fails after updating jest

### ISSUE THREAD

**Issue by 3af** [yarnpkg/yarn#5120]
**Do you want to request a *feature* or report a *bug*?**
A bug. Initially I [reported bug with jest](https://github.com/facebook/jest/issues/5135) but was sent here.

**What is the current behavior?**
After updating jest from 21.2.1 to 22.0.2 yarn install has some problems and causes TeamCity build to fail. It also displays warning on my developer notebook.

**If the current behavior is a bug, please provide the steps to reproduce.**
I updated from 21.2.1 to 22.0.2 and let TeamCity do its work.

In TeamCity this is the relevant part of log:
```
[14:30:55][Step 1/1] [INFO] yarn install v1.3.2
[14:30:55][Step 1/1] [INFO] [1/5] Resolving packages...
[14:30:56][Step 1/1] [INFO] [2/5] Fetching packages...
[14:30:57][Step 1/1] [INFO] info fsevents@1.1.3: The platform "linux" is incompatible with this module.
[14:30:57][Step 1/1] [INFO] info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[14:30:57][Step 1/1] [INFO] [3/5] Linking dependencies...
[14:30:57][Step 1/1] [ERROR] warning " > react-toolbox@2.0.0-beta.12" has unmet peer dependency "classnames@^2.2.0".
[14:30:57][Step 1/1] [ERROR] warning " > react-toolbox@2.0.0-beta.12" has incorrect peer dependency "react@^15.5.0".
[14:30:57][Step 1/1] [ERROR] warning " > react-toolbox@2.0.0-beta.12" has incorrect peer dependency "react-dom@^15.5.0".
[14:30:57][Step 1/1] [ERROR] warning " > react-toolbox@2.0.0-beta.12" has unmet peer dependency "react-transition-group@^1.1.3".
[14:30:57][Step 1/1] [ERROR] warning "react-toolbox > react-css-themr@2.1.2" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0".
[14:30:57][Step 1/1] [ERROR] warning " > postcss-cssnext@3.0.2" has unmet peer dependency "caniuse-lite@^1.0.30000697".
[14:31:08][Step 1/1] [INFO] [4/5] Building fresh packages...
[14:31:09][Step 1/1] [INFO] info This package requires node-gyp, which is not currently installed. Yarn will attempt to automatically install it. If this fails, you can run "yarn global add node-gyp" to manually install it.
[14:31:09][Step 1/1] [INFO] [1/4] Resolving packages...
[14:31:39][Step 1/1] [ERROR] warning Error running install script for optional dependency: "/home/buildagent/app/work/58d613bc822e2a8/module/mer-client/node_modules/weak: Failed to auto-install node-gyp. Please run \"yarn global add node-gyp\" manually. Error: \"https://registry.yarnpkg.com/node-gyp: ETIMEDOUT\""
[14:31:39][Step 1/1] [INFO] info This module is OPTIONAL, you can safely ignore this error
[14:31:39][Step 1/1] [INFO] [5/5] Cleaning modules...
[14:31:39][Step 1/1] [ERROR] error An unexpected error occurred: "ENOENT: no such file or directory, open '/home/buildagent/.config/yarn/global/.yarnclean'".
[14:31:39][Step 1/1] [INFO] info If you think this is a bug, please open a bug report with the information provided in "/home/buildagent/.config/yarn/global/yarn-error.log".
[14:31:39][Step 1/1] [INFO] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[14:31:39][Step 1/1] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:yarn (yarn install) on project mer-client: Failed to run task
```
Interesting parts are two errors at 14:31:39.
1/ `[ERROR] warning Error running install script for optional dependency: "/home/buildagent/app/work/58d613bc822e2a8/module/mer-client/node_modules/weak: Failed to auto-install node-gyp. Please run \"yarn global add node-gyp\" manually. Error: \"https://registry.yarnpkg.com/node-gyp: ETIMEDOUT\""`
2/ `error An unexpected error occurred: "ENOENT: no such file or directory, open '/home/buildagent/.config/yarn/global/.yarnclean'`.

On my local machine the output is little bit different.
```
yarn install v1.3.2
[1/5] Resolving packages...
[2/5] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/5] Linking dependencies...
warning " > react-toolbox@2.0.0-beta.12" has unmet peer dependency "classnames@^2.2.0".
warning " > react-toolbox@2.0.0-beta.12" has incorrect peer dependency "react@^15.5.0".
warning " > react-toolbox@2.0.0-beta.12" has incorrect peer dependency "react-dom@^15.5.0".
warning " > react-toolbox@2.0.0-beta.12" has unmet peer dependency "react-transition-group@^1.1.3".
warning "react-toolbox > react-css-themr@2.1.2" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0".
warning " > postcss-cssnext@3.0.2" has unmet peer dependency "caniuse-lite@^1.0.30000697".
[4/5] Building fresh packages...
[-/3] ⠁ waiting...
[2/3] ⠁ weak: node@8.9.1 | win32 | x64
[3/3] ⠁ node-sass
[-/3] ⠁ waiting...
warning Error running install script for optional dependency: "C:\\Users\\me\\code\\merchants\\module\\mer-client\\node_modules\\weak: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: C:\\Users\\me\\code\\merchants\\module\\mer-client\\node_modules\\weak
Output:
C:\\Users\\me\\code\\merchants\\module\\mer-client\\node_modules\\weak>if not defined npm_config_node_gyp (node \"C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )  else(node \"\" rebuild ) 
gyp info it worked if it ends with ok
 info using node-gyp@3.6.2
 info using node@8.9.1 | win32 | x64
 ERR! configure error 
 ERR! stack Error: Can't find Python executable \"python\", you can set the PYTHON env variable.
 ERR! stack     at PythonFinder.failNoPython (C:\\Users\\me\\AppData\\Roaming\\nvm\\v8.9.1\\node_modules\\npm\\node_modules\\node-gyp\\lib\\configure.js:483:19)
 ERR! stack     at PythonFinder.<anonymous> (C:\\Users\\me\\AppData\\Roaming\\nvm\\v8.9.1\\node_modules\\npm\\node_modules\\node-gyp\\lib\\configure.js:508:16)
 ERR! stack     at C:\\Users\\me\\AppData\\Roaming\\nvm\\v8.9.1\\node_modules\\npm\\node_modules\\graceful-fs\\polyfills.js:284:29
 ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
 ERR! System Windows_NT 6.1.7601
 ERR! command
[5/5] Cleaning modules...
Done in 37.95s.
```

There is an error that Python is not found which is correct because I don't have it.

I tried installing with `--ignore-optional` but that resulted in [different error](https://github.com/facebook/jest/issues/5135#issuecomment-352811250).

**What is the expected behavior?**
There is no error nor warning. Everything should work like it did before.

**Please mention your node.js, yarn and operating system version.**
My notebook:
OS: Win 7
node: 8.9.1
yarn: 1.3.2

Build agent:
OS: Linux
node: 8.9.1
yarn: 1.3.2

For now I locked myself at v21 and everything works fine.

Thank you!

**Comment by screendriver** [comment]
I'm getting a different error with Yarn and the latest version of Jest:

```sh
warning "chokidar#fsevents#node-pre-gyp@^0.6.39" could be deduped from "0.6.39" to "node-pre-gyp@0.6.39"
error "compressible#mime-db" is wrong version: expected "1.32.0", got "1.30.0"
warning Optional dependency "mime-types#mime-db" not installed
error "node-pre-gyp#request" is wrong version: expected "2.81.0", got "2.83.0"
error "jsdom#request" not installed
error "jsdom#request-promise-native" not installed
error "request#aws-sign2" is wrong version: expected "0.6.0", got "0.7.0"
error "jsdom#request#aws-sign2" not installed
error "request#form-data" is wrong version: expected "2.1.4", got "2.3.1"
error "jsdom#request#form-data" not installed
error "request#har-validator" is wrong version: expected "4.2.1", got "5.0.3"
error "jsdom#request#har-validator" not installed
error "jsdom#request#hawk" not installed
error "request#http-signature" is wrong version: expected "1.1.1", got "1.2.0"
error "jsdom#request#http-signature" not installed
warning Optional dependency "request#performance-now" not installed
warning Optional dependency "request#qs" not installed
error "jsdom#request#uuid" not installed
error "jsdom#request-promise-native#request-promise-core" not installed
warning Optional dependency "har-validator#ajv" not installed
warning Optional dependency "http-signature#assert-plus" not installed
error "jsdom#hawk#boom" not installed
error "jsdom#hawk#cryptiles" not installed
error "har-validator#har-schema" is wrong version: expected "1.0.5", got "2.0.0"
error "jsdom#har-validator#har-schema" not installed
error "jsdom#hawk#sntp" not installed
error "jsdom#cryptiles#boom" not installed
error Found 21 errors.
```

**Comment by JamesJefferyUK** [comment]
Yarn version: 1.3.2

Same problem. Happens with any package I try to install. I updated my yarn version with `brew` and after that I started getting this error. 

```
yarn add rollup-plugin-babel -D                                            [~]✭
yarn add v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > rollup-plugin-babel@3.0.3" has unmet peer dependency "babel-core@6".
[4/4] 📃  Building fresh packages...
[1/1] ⠈ weak
[-/1] ⠈ waiting...
[-/1] ⠁ waiting...
[-/1] ⠁ waiting...
warning Error running install script for optional dependency: "/Users/jamesjeffery/Desktop/react-m
idi/node_modules/weak: Command failed.\nExit code: 1\nCommand: node-gyp rebuild\nArguments: \nDirectory: /Users/jamesjeffery/Desktop/react-midi/node_modules/weak\nOutput:\nmodule.js:529\n    throw err;\n    ^\n\nError: Cannot find module 'abbrev'\n    at Function.Module._resolveFilename (module.js:527:15)\n    at Function.Module._load (module.js:476:23)\n    at Module.require (module.js:568:17)\n    at require (internal/module.js:11:18)\n    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/nopt/lib/nopt.js:10:14)\n    at Module._compile (modsuccess Saved lockfile.success Saved 3 new dependencies.├─ estree-walker@0.2.1
├─ rollup-plugin-babel@3.0.3
└─ rollup-pluginutils@1.5.2
✨  Done in 16.29s.
```

**Comment by JamesJefferyUK** [comment]
I downgraded to 1.2.1 and I'm still getting the same problem. This is an absolute headache.

**Comment by WnP** [comment]
upgrading to `1.4.1` fix this issue, at least on my system.

**Comment by fangzhzh** [comment]
@WnP Hi, how to upgrade the yarn version?
Latest yarn version in HomeBrew is 1.3.2.

**Comment by 3af** [comment]
I will try it today or tomorrow and let you know.

**Comment by 3af** [comment]
I updated jest to 22.0.2 and yarn to 1.5.1 and TC build passed so it seems it's fixed. Thanks!
