### ISSUE TITLE
throws TypeError in slow network

### ISSUE THREAD

**Issue by vajahath** [yarnpkg/yarn#5141]
**Do you want to request a *feature* or report a *bug*?**
Bug 🐛 

**What is the current behavior?**
In slow networks, yarn throws an err saying:
```
events.js:180
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'listener', 'Function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function
```
here is the full terminal output:
```
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS D:\vaju\works\mig> git status
On branch master
nothing to commit, working tree clean
PS D:\vaju\works\mig> yarn install
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
[#######################------------------------------------------------------------------------------] 218/973events.js:180
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'listener', 'Function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function
    at _addListener (events.js:180:11)
    at WriteStream.addListener (events.js:240:10)
    at WriteStream.close (fs.js:2298:10)
    at C:\Program Files (x86)\Yarn\lib\cli.js:67129:37
    at call (C:\Program Files (x86)\Yarn\lib\cli.js:67139:3)
    at Array.forEach (<anonymous>)
    at C:\Program Files (x86)\Yarn\lib\cli.js:67159:25
    at f (C:\Program Files (x86)\Yarn\lib\cli.js:43203:25)
    at WriteStream.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:67118:21)
    at WriteStream.f (C:\Program Files (x86)\Yarn\lib\cli.js:43203:25)
PS D:\vaju\works\mig>
```
**If the current behavior is a bug, please provide the steps to reproduce.**
- created an empty app with angular-cli
- `yarn install` (in slow network)

**Please mention your node.js, yarn and operating system version.**
```
PS D:\vaju\works\mig> yarn --version
1.3.2
PS D:\vaju\works\mig> node --version
v9.3.0
```
Windows 10 64x

**Comment by cooltoast** [comment]
Is there any update or workaround on this? It's breaking my build and I can't even develop ...

**Comment by sth** [comment]
As a work around it might help to increase the timeout yarn uses for network requests. The `--network-timeout` command line option takes a timeout in milliseconds, so for example `--network-timeout 600000` increases it from the default 30 seconds to 5 minutes.

**Comment by merceyz** [comment]
Closing as fixed in v2 where the timeout logic is less susceptible to this sort of issue

https://yarnpkg.com/getting-started/migration
