### ISSUE TITLE
Yarn scripts fail when nested 3 or more layers deep

### ISSUE THREAD

**Issue by asgallant** [yarnpkg/yarn#5196]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**

When running a script via yarn that calls another yarn script that calls a 3rd yarn script (etc...) yarn throws an error like this:

```
TypeError: Cannot create property '-10-24-0-138-8081-repository-npm-all-' on string '{"-10-24-0-138-8081-repository-npm-all-":true}'
    at set (C:\Program Files (x86)\Yarn\lib\cli.js:66901:28)
    at set (C:\Program Files (x86)\Yarn\lib\cli.js:66915:14)
    at set (C:\Program Files (x86)\Yarn\lib\cli.js:66895:16)
    at Function.objectPath.set (C:\Program Files (x86)\Yarn\lib\cli.js:66948:14)
    at NpmRegistry.mergeEnv (C:\Program Files (x86)\Yarn\lib\cli.js:86811:18)
    at C:\Program Files (x86)\Yarn\lib\cli.js:30466:14
    at Generator.next (<anonymous>)
    at step (C:\Program Files (x86)\Yarn\lib\cli.js:92:30)
    at C:\Program Files (x86)\Yarn\lib\cli.js:110:14
    at Promise (<anonymous>)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a new project (I used Angular, but I don't think it matters). [Angular-cli](https://github.com/angular/angular-cli) will create a project that works for this error. Modify the `package.json` file to contain the scripts that call other scripts, eg (example case simplified here to provide a MCRE):

```
"scripts": {
    "build": "ng build --base-href=app",
    "build:prod": "yarn build --prod",
    "build:prod:verbose": "yarn build:prod --verbose"
}
```

`yarn build` and `yarn build:prod` both run as expected, as does `yarn build --base-href=app --prod --verbose` (the command we expect to run when executing `yarn build:prod:verbose`). But `yarn build:prod:verbose` throws an error:

```
PS C:\dev\MyApp> yarn build:prod:verbose
yarn run v1.3.2
$ yarn build:prod --verbose
$ yarn build --base-href=app --prod --verbose
error An unexpected error occurred: "Cannot create property '-10-24-0-138-8081-repository-npm-all-' on string '{\"-10-24-0-138-8081-repository-npm-all-\":true}'".
info If you think this is a bug, please open a bug report with the information provided in "C:\\dev\\MyApp\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

These are the contents of the `yarn-error.log` file:

```
Arguments: 
  C:\Program Files\nodejs\node.exe C:\Program Files (x86)\Yarn\bin\yarn.js build --prod --verbose

PATH: 
  <snip for brevity>

Yarn version: 
  1.3.2

Node version: 
  8.6.0

Platform: 
  win32 x64

npm manifest: 
  {
    "name": "MyApp",
    "version": "0.0.0",
    "license": "MIT",
    "scripts": {
      "ng": "ng",
      "start": "ng serve",
      "build": "ng build --base-href=app",
      "build:prod": "yarn build --prod",
      "build:prod:verbose": "yarn build:prod --verbose",
      "test": "ng test",
      "lint": "ng lint",
      "e2e": "ng e2e"
    },
    "private": true,
    "dependencies": {
      "@angular/animations": "^5.0.0",
      "@angular/common": "^5.0.0",
      "@angular/compiler": "^5.0.0",
      "@angular/core": "^5.0.0",
      "@angular/forms": "^5.0.0",
      "@angular/http": "^5.0.0",
      "@angular/platform-browser": "^5.0.0",
      "@angular/platform-browser-dynamic": "^5.0.0",
      "@angular/router": "^5.0.0",
      "core-js": "^2.4.1",
      "rxjs": "^5.5.2",
      "zone.js": "^0.8.14"
    },
    "devDependencies": {
      "@angular/cli": "1.5.0",
      "@angular/compiler-cli": "^5.0.0",
      "@angular/language-service": "^5.0.0",
      "@types/jasmine": "~2.5.53",
      "@types/jasminewd2": "~2.0.2",
      "@types/node": "~6.0.60",
      "codelyzer": "~3.2.0",
      "jasmine-core": "~2.6.2",
      "jasmine-spec-reporter": "~4.1.0",
      "karma": "~1.7.0",
      "karma-chrome-launcher": "~2.1.1",
      "karma-cli": "~1.0.1",
      "karma-coverage-istanbul-reporter": "^1.2.1",
      "karma-jasmine": "~1.1.0",
      "karma-jasmine-html-reporter": "^0.2.2",
      "protractor": "~5.1.2",
      "ts-node": "~3.2.0",
      "tslint": "~5.7.0",
      "typescript": "~2.4.2"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  <snip for brevity>

Trace: 
  TypeError: Cannot create property '-10-24-0-138-8081-repository-npm-all-' on string '{"-10-24-0-138-8081-repository-npm-all-":true}'
      at set (C:\Program Files (x86)\Yarn\lib\cli.js:66901:28)
      at set (C:\Program Files (x86)\Yarn\lib\cli.js:66915:14)
      at set (C:\Program Files (x86)\Yarn\lib\cli.js:66895:16)
      at Function.objectPath.set (C:\Program Files (x86)\Yarn\lib\cli.js:66948:14)
      at NpmRegistry.mergeEnv (C:\Program Files (x86)\Yarn\lib\cli.js:86811:18)
      at C:\Program Files (x86)\Yarn\lib\cli.js:30466:14
      at Generator.next (<anonymous>)
      at step (C:\Program Files (x86)\Yarn\lib\cli.js:92:30)
      at C:\Program Files (x86)\Yarn\lib\cli.js:110:14
      at Promise (<anonymous>)
```

**What is the expected behavior?**
The scripts execute without error

**Please mention your node.js, yarn and operating system version.**
Node v 8.6.0
Yarn 1.3.2
Windows 7 Pro

**Comment by ericente** [comment]
I had this issue (on Mac OS X) and found that I had a malformed entry in my `~/.npmrc` file - getting rid of that line resolved this issue for me.

**Comment by torifat** [comment]
Please check your `~/.npmrc` as @ericente suggested. It seems like an npm config or npm related environment variable problem.

**Comment by asgallant** [comment]
I looked at my .npmrc file, and everything seems OK. I don't have any environment variables set for NPM. Just to confirm, I deleted everything from the .npmrc file and tried the nested scripts again. They still fail, but this time without any error message. The yarn-error.log file shows this in the trace:

```
Trace: 
  Error: Command failed.
  Exit code: 1
  Command: C:\WINDOWS\system32\cmd.exe
  Arguments: /d /s /c yarn build:prod --verbose
  Directory: C:\dev\testApp
  Output:
  
      at ProcessTermError.MessageError (C:\Program Files (x86)\Yarn\lib\cli.js:186:110)
      at new ProcessTermError (C:\Program Files (x86)\Yarn\lib\cli.js:226:113)
      at ChildProcess.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:30281:17)
      at emitTwo (events.js:126:13)
      at ChildProcess.emit (events.js:214:7)
      at maybeClose (internal/child_process.js:925:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

Note that I have upgraded to yarn v 1.5.1 since I originally filed this ticket.

**Comment by budajeff** [comment]
I'm encountering this bug as well. I'm using yarn version 1.13.0. 

The project I'm working on has several nested yarn script calls as the original poster described.

**Comment by budajeff** [comment]
My issue was that I had an entry in my .npmrc file that did not have a key name.

**Comment by andi1984** [comment]
What is with this issue? I can not confirm that the `.npmrc` file is the issue here. I have an .npmrc file stating `registry=https://myregistry`. But as soon as I wrap yarn three times I get the issue that it `Cannot create property`.

**Comment by soundslikeodd** [comment]
My team had this issue.  We did not change our .npmrc file but updated yarn from 1.13.0 to 1.15.2 and the problem disappeared.

I hope that can help someone.

**Comment by andi1984** [comment]
@soundslikeodd thx. I will try out.
