### ISSUE TITLE
[Bug] Can't install nodemon

### ISSUE THREAD

**Issue by andyperisho** [yarnpkg/yarn#5245]
```
❯ yarn -v
1.3.2
```

I am trying to install `nodemon` via yarn. It works fine when I do `npm install --save-dev nodemon`.
But, when I run `yarn add nodemon` or `yarn add -D nodemon`, I get the following error:

```
❯ ya -D nodemon
yarn add v1.3.2
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
⠁ 
⠁ 
⠁ 
⠁ 
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: read ENOTCONN
    at _errnoException (util.js:1003:13)
    at Socket._read (net.js:495:20)
    at Socket.Readable.read (_stream_readable.js:449:10)
    at Socket.read (net.js:376:43)
    at new Socket (net.js:259:12)
    at createSocket (internal/child_process.js:241:11)
    at ChildProcess.spawn (internal/child_process.js:357:23)
    at Object.exports.spawn (child_process.js:499:9)
    at default (/home/orvad/.local/npm-global/lib/node_modules/yarn/lib/cli.js:29936:24)
    at new Promise (<anonymous>)
```

**Comment by jiripospisil** [comment]
Related nodejs/node/issues/18225

**Comment by andyperisho** [comment]
Yes, it's related. Closing.
