### ISSUE TITLE
.rbenv/shims/yarn: No such file or directory

### ISSUE THREAD

**Issue by MadRiver44** [yarnpkg/yarn#5276]
**Which operating system are you using:**
OSX 10.11.6 El Cap

**Please describe the steps you took when trying to install Yarn and what went wrong:**
1. $ brew install yarn, result: Warning yarn 1.3.2 is already installed
2. $ yarn -v, result - rbenv: yarn: command not found
3. $ yarn --version, result - rbenv: yarn: command not found
4. $ which yarn, result - /Users/kevinturney/.rbenv/shims/yarn

I did a complete uninstallation and then reinstallation of rbenv and yarn. Before this I used create-react-app to start a project and when I tried yarn start instead of npm run start I got this error:
(Note: npm run start works fine)

    /Users/kevinturney/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/yarn-0.1.1/lib/yarn/server.rb:14:in `<class:Server>': uninitialized constant Socket::SOL_TCP (NameError)

	from /Users/kevinturney/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/yarn-0.1.1/lib/yarn/server.rb:6:in `<module:Yarn>'

	from /Users/kevinturney/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/yarn-0.1.1/lib/yarn/server.rb:4:in `<top (required)>'

	from /Users/kevinturney/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/yarn-0.1.1/bin/yarn:26:in `<top (required)>'

	from /Users/kevinturney/.rbenv/versions/2.2.3/bin/yarn:23:in `load'
	from /Users/kevinturney/.rbenv/versions/2.2.3/bin/yarn:23:in `<main>'

My .bash_profile has

    PATH="$HOME/.rbenv/bin:$PATH"                              # RBENV
    PATH="/usr/local/share/npm/bin:$PATH"                      # NPM
    PATH="/usr/local/bin:/usr/local/sbin:$PATH"                # Homebrew

    export PATH="$PATH:/opt/yarn-[version]/bin"
    export PATH="$PATH:`yarn global bin`"

and at the bottom as per rbenv docs
     eval "$(rbenv init -)"

I don't know what to do and I looked [https://github.com/rbenv/rbenv/issues/1051](url)
How come it shows I have 1.3.2 installed and the yarn command doesn't work? I'm very confused.

**Comment by ebrett** [comment]
I am also having this issue.

**Comment by hwangzc** [comment]
I am also having this issue.!!!!!!!!!

**Comment by josuetex** [comment]
I am also having this issue.
