### ISSUE TITLE
Yarn does not work in Git Bash on Windows

### ISSUE THREAD

**Issue by Yagun** [yarnpkg/yarn#5349]
Windows 7
Yarn 1.3.2 (the same issue with 1.1.0)
Git 2.16.1.windows.4

The path to Yarn is in the Environment PATH variable: D:\Program Files (x86)\Yarn\bin

Yarn works in Windows cmd.exe and PowerShell console. For example:
c:\>yarn --version

But does not work in Git Bash:
$ yarn --version

module.js:538
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\Git\yarn.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

I restarted Windows after yarn installation.

**Comment by torifat** [comment]
What is the output of `which yarn` in Git Bash?

**Comment by Yagun** [comment]
/d/Program Files (x86)/Yarn/bin/yarn

**Comment by Yagun** [comment]
Just found that **yarn.cmd** command works.

For example:
$ **yarn.cmd** --version
1.3.2

But:
$ **yarn** --version
module.js:538
throw err;
^
Error: Cannot find module 'C:\Program Files\Git\yarn.js'

**Comment by torifat** [comment]
And, what is the output of `which yarn.cmd`?

**Comment by Yagun** [comment]
$ which yarn.cmd

which: no yarn.cmd in (/c/Users/USERNAME_HERE/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/USERNAME_HERE/bin:/d/Program Files/Python35/Scripts:/d/Program Files/Python35:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64:

... (lots of paths here) ...

/d/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin:/d/Caffe/python:/cmd:/d/Program Files (x86)/Yarn/bin:/c/Users/USERNAME_HERE/AppData/Local/Yarn/bin:/c/Users/USERNAME_HERE/AppData/Roaming/npm:/c/Users/USERNAME_HERE/AppData/Local/Yarn/bin:/usr/bin/vendor_perl:/usr/bin/core_perl)

**Comment by torifat** [comment]
This doesn't seem like a problem with Yarn. Try adding it to `PATH` in `~/.bash_profile`.

**Comment by Yagun** [comment]
Well, other things like _npm_ and _nodejs_ work fine. Only _yarn_ does not.

I added the path to yarn to PATH to the profile this way:
PATH=$PATH':/d/Program Files (x86)/Yarn/bin'

The error message is still the same.

**Comment by imudak** [comment]
The same problem has occurred in msys2. I run msys2 on Windows 8.1.
```
$ yarn
module.js:559
    throw err;
    ^

Error: Cannot find module 'C:\yarn.js'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:665:3
```

I edited the yarn script and confirmed it. 
It seems to be caused by the result of sed becoming empty character.
```
$ cat /c/Program\ Files\ \(x86\)/Yarn/bin/yarn
#!/bin/sh
echo "0: $0"
argv0=$(echo "$0" | sed -e 's,\\,/,g')
echo "argv0: $argv0"
basedir=$(dirname "$(readlink "$0" || echo "$argv0")")
echo "basedir: $basedir"
...
```
```
[result]
$ yarn
0: /c/Program Files (x86)/Yarn/bin/yarn
argv0:
basedir: .
```

I do not know why it will be empty.
Tentatively, replacing sh with zsh worked fine.
```
$ cat /c/Program\ Files\ \(x86\)/Yarn/bin/yarn
#!/bin/zsh
...
```
```
$ yarn --version
1.3.2
```

**Comment by imudak** [comment]
The cause was found out. This is caused by MacType. Please uninstall MacType and try it.

**Comment by Yagun** [comment]
I do not have MacType on my PC. So, in my case Yarn issue is not related to MacType.

**Comment by emilchristensen** [comment]
Same issues replicated on a freshly installed Windows 10 Pro 64-bit machine:

Git for windows 2.16.2-64-bit (Also tried with 2.15.x)
NVM for Windows 1.1.6 (Also tried with 1.1.5)
Yarn 1.5.1 (Also tried with 1.3.2)

When run from cmd.exe:
```
C:\Users\echristensen>yarn --version
1.5.1
```

When run from Powershell:
```
PS C:\Users\echristensen> yarn --version
1.5.1
```

When run from Git Bash (MINGW64):
```
echristensen@ECHRISTENSEN-PC MINGW64 ~
$ yarn --version
module.js:478
    throw err;
    ^

Error: Cannot find module 'C:\Users\echristensen\yarn.js'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
    at bootstrap_node.js:500:3
```

The funny thing is that it works if I run the js file directly or the cmd from Git Bash:
```
echristensen@ECHRISTENSEN-PC MINGW64 ~
$ yarn.js --version
1.5.1
```

```
echristensen@ECHRISTENSEN-PC MINGW64 ~
$ yarn.cmd --version
1.5.1
```

**Comment by emilchristensen** [comment]
Bonus information:
Git for Windows:
```
echristensen@ECHRISTENSEN-PC MINGW64 ~
$ which yarn
/c/Program Files (x86)/Yarn/bin/yarn

echristensen@ECHRISTENSEN-PC MINGW64 ~
$ which yarn.js
/c/Program Files (x86)/Yarn/bin/yarn.js

echristensen@ECHRISTENSEN-PC MINGW64 ~
$ which yarn.cmd
which: no yarn.cmd in (/c/Users/echristensen/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/echristensen/bin:/c/Python27:/c/Python27/Scripts:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files/dotnet:/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/cmd:/c/Program Files (x86)/Yarn/bin:%NVM_HOME%:%NVM_SYMLINK%:/c/Users/echristensen/AppData/Local/Microsoft/WindowsApps:/c/Users/echristensen/AppData/Local/Yarn/bin:/c/Users/echristensen/AppData/Roaming/npm:/c/Users/echristensen/AppData/Roaming/nvm:/c/Program Files/nodejs:/usr/bin/vendor_perl:/usr/bin/core_perl)

```

cmd.exe:
```
C:\Users\echristensen>where yarn
C:\Program Files (x86)\Yarn\bin\yarn
C:\Program Files (x86)\Yarn\bin\yarn.cmd
C:\Program Files (x86)\Yarn\bin\yarn.js
```

**Comment by robotanz** [comment]
I have **the same** issue on a Windows 10 Pro that occured just after Windows installed some updates.

**Comment by robotanz** [comment]
I have the very same issue here on Windows 10 Pro. It happened when Windows rebooted after some update installation.

Looks like this is a git bash environment or config problem, the `yarn` shell script could not set its `basedir` path correctly (look like it's empty) and so tries to execute `node yarn.js` in current directory and of course there's no yarn.js to be found.

**Comment by jsweitzer** [comment]
Not sure if this would be a separate Windows Git Bash path issue but it fits the title here:

Windows 7
yarn v1.6.0
git version 2.7.2.windows.1


```
$ yarn
module.js:538
    throw err;
    ^

Error: Cannot find module 'C:\c\Program Files (x86)\Yarn\bin\yarn.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

Resolved by adding MINGW64 to the yarn shell script basedir case statement:

```
case "$(uname -s)" in
  Linux) basedir=$(dirname "$(readlink -f "$0" || echo "$argv0")");;
  *CYGWIN* | *MINGW64*) basedir=`cygpath -w "$basedir"`;;
esac
```

**Comment by ela34** [comment]
Same kind of patch works if you are using MSYS on Windows 10:
```
case "$(uname -s)" in
  Linux) basedir=$(dirname "$(readlink -f "$0" || echo "$argv0")");;
  *CYGWIN* | *MSYS*) basedir=`cygpath -w "$basedir"`;;
esac
```

**Comment by jdelucaa** [comment]
I am getting the following error when trying to use yarn from git bash:

$ yarn --version
module.js:538
    throw err;
    ^

Error: Cannot find module 'C:\c\Program Files (x86)\Yarn\bin\yarn.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by Nielio** [comment]
I don't really know what i am doing, but i got a small and quick fix.

Edit C:\Program Files (x86)\Yarn\bin\yarn

Replace 
basedir=$(dirname "$(readlink "$0" || echo "$argv0")")
by
basedir=$( cd -P -- "$(dirname -- "$0")" && pwd -P )

This works for me. I hope i can help some people out.

**Comment by dahlbyk** [comment]
This might be a duplicate of https://github.com/git-for-windows/git/issues/1619. Is anyone here using Comodo Cloud Antivirus?

**Comment by dahlbyk** [comment]
@mordentware even if it's not specifically related to Comodo, this does seem like the same kind of problem. Are you able to reproduce these tests results: https://github.com/git-for-windows/git/issues/1619#issuecomment-394073051?

**Comment by mordentware** [comment]
Fair comment. Created the shell script below (copying here for benefit of future people):
```
#!/bin/sh
echo "A) $0"
echo "B) $0" | sed -e 's,\\,/,g'
echo "C) $(echo "$0" | sed -e 's,\\,/,g')"
echo "D) $(dirname "$(echo "$0" | sed -e 's,\\,/,g')")"
echo $(ls) | cat
echo $(ls | cat)
echo $(echo $(ls) | cat)
```
Output in Git Bash:
```
$ ./test.sh
A) ./test.sh
B) ./test.sh
C)
D) .
Files...
Files...
Files...
```
My `sed`-fu is weak, but I believe I should be expecting to see *something* in there?

**Comment by dahlbyk** [comment]
Looping in @dscho

**Comment by dscho** [comment]
This looks like (don't laugh, it is really sad) the old Comodo Internet Security problem. See https://github.com/git-for-windows/git/issues/1619 for the full story.

**Comment by dahlbyk** [comment]
That was my thought, but @mordentware says he's not using Comodo. Not sure what else to try, or if there's anything here that's yarn-specific?

**Comment by emilchristensen** [comment]
Yeah I'm not using Comodo Internet Security either. I am however using Sophos Antivirus. But I've had it working on the same PC with the same software installed before a reinstall. After the fresh install of Windows 10 Pro with pretty much nothing on it but Sophos Antivirus, I got this error.

**Comment by dahlbyk** [comment]
@emilchristensen Is it possible you're using a different version of Node, which might be handled differently by Sophos? I don't suppose either of these products have any way of telling you when they so stuff that's affecting your runtime environment? 😒

**Comment by emilchristensen** [comment]
I've tried with multiple versions of node, including the same version as I ran before the reinstall. And yeah, I don't see any logs anywhere for whether Sophos is affecting my runtime.

**Comment by yonirab** [comment]
I have the exact same problem on Windows 7. Not using Comodo Internet Security.
@Nielio's workaround works for me.

**Comment by dscho** [comment]
> Replace
> basedir=$(dirname "$(readlink "$0" || echo "$argv0")")
> by
> basedir=$( cd -P -- "$(dirname -- "$0")" && pwd -P )

@Nielio interesting!

Note: you will want to imitate the coding style by avoiding the extra spaces after/before the parentheses, and you definitely will want to quote the result (the original code gets this wrong, too).

Does it also work for you if you instead edit the `case` statement to catch `*CYGWIN*|*MINGW*|*MSYS*` instead of only `*CYGWIN*`? I think *that* would be the proper fix, and I guess that we will want to open a Pull Request in whatever project writes these shell scripts (it might be `npm`?)

**Comment by dscho** [comment]
> Does it also work for you if you instead edit the case statement to catch *CYGWIN*|*MINGW*|*MSYS* instead of only *CYGWIN*? I think that would be the proper fix, and I guess that we will want to open a Pull Request in whatever project writes these shell scripts (it might be npm?)

As can be seen [here](https://github.com/npm/cmd-shim/pull/30), I did exactly that.

**Comment by Nielio** [comment]
@dscho It works! Even without changing the basedir line. Thank you!

This is my yarn file right now.

```
#!/bin/sh
argv0=$(echo "$0" | sed -e 's,\\,/,g')
basedir=$(dirname "$(readlink "$0" || echo "$argv0")")

case "$(uname -s)" in
  Linux) basedir=$(dirname "$(readlink -f "$0" || echo "$argv0")");;
  *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac

command_exists() {
  command -v "$1" >/dev/null 2>&1;
}

if command_exists node; then
  if [ "$YARN_FORCE_WINPTY" = 1 ] || command_exists winpty && test -t 1; then
    winpty node "$basedir/yarn.js" "$@"
  else
    exec node "$basedir/yarn.js" "$@"
  fi
  ret=$?
# Debian and Ubuntu use "nodejs" as the name of the binary, not "node", so we
# search for that too. See:
# https://lists.debian.org/debian-devel-announce/2012/07/msg00002.html
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=614907
elif command_exists nodejs; then
  exec nodejs "$basedir/yarn.js" "$@"
  ret=$?
else
  >&2 echo 'Yarn requires Node.js 4.0 or higher to be installed.'
  ret=1
fi

exit $ret
```

**Comment by dscho** [comment]
Great! Now, if only we could get that PR going... Not sure whether there is *any* maintainer at `cmd-shim`...

**Comment by hop2** [comment]
Also ran into this issue trying to use yarn in Git Bash 2.18.0 for Windows. Since I installed a specific version of yarn in custom location /c/yarn/yarn-v1.0.2/bin, I updated that basedir line like so:

basedir=$(dirname $(which yarn))

**Comment by dscho** [comment]
> I tried @dscho solution and wasn't quite working.

A bug report like this is *really* frustrating to the developer who tried to help you. You might want to show your gratitude by improving the detail of your bug report *a lot*, to the point where it is actually useful in helping to figure out what needs to be improved. Right now, I know nothing, except that *something* is broken for you. *Something*. Really frustrating.

**Comment by GlenHughes** [comment]
@Nielio fix worked for me, thank you

**Comment by dscho** [comment]
@GlenHughes @Nielio really, anybody in this community who is familiar with its inner workings, could you *please* help me get https://github.com/npm/cmd-shim/pull/30 accepted? Or are you happy with everybody and their friend having to work around this?

**Comment by dahlbyk** [comment]
@dscho opened this for you: https://npm.community/t/fix-generated-shell-scripts-for-msys2-mingw/965

**Comment by dscho** [comment]
@dahlbyk thank you so much! Is this process documented anywhere (open PR on GitHub, new post on npm forum linking to the PR)?

**Comment by dahlbyk** [comment]
No idea, just guessing since they disabled GH Issues on the CLI. 🤞

**Comment by GlenHughes** [comment]
Incase anyone is wondering about this issue, I've updated to 2.19.1 and its now working fine without having to apply @Nielio fix

**Comment by TylerButh** [comment]
@GlenHughes Updated what?

**Comment by GlenHughes** [comment]
I updated Git. I've also updated my comment to be more clear.

**Comment by whatsdis** [comment]
I remember why I started my electron project on my mac

**Comment by prasadhbaapaat** [comment]
@Nielio your fix worked for me, thank you 🥇

**Comment by afilp** [comment]
@GlenHughes How did you update git in Windows Bash? I understand that this installation is different than the native one, correct?

**Comment by dscho** [comment]
> @dscho opened this for you: https://npm.community/t/fix-generated-shell-scripts-for-msys2-mingw/965

@dahlbyk seems like nobody of those in power to review and merge the PR cared at all?

**Comment by dscho** [comment]
> How did you update git in Windows Bash?

I think what we're talking about is the *Git Bash* included in Git for Windows. You upgrade it by installing a newer version of Git for Windows, as downloaded from https://gitforwindows.org/.

**Comment by spencore** [comment]
updating git for windows definitely fixed this problem for me.

**Comment by rogerioyuuki** [comment]
I had this problem after updating Git and forgetting to choose this option:

![image](https://user-images.githubusercontent.com/11280342/57561184-ae4f5480-7360-11e9-92cd-7d9dbd937cdd.png)

So I reinstalled and it worked.

**Comment by afilp** [comment]
I believe this is related to the same problem, yarn works OK when run from the `Windows` side but not OK when run from the `Bash` side (for the exaxt same project):

While in `bash`, I get an error:
![image](https://user-images.githubusercontent.com/7850073/57566884-07a79a00-73da-11e9-921a-06c0f4722016.png)

Note that git for `windows` is different than the one in `bash`:
![image](https://user-images.githubusercontent.com/7850073/57566904-40477380-73da-11e9-86dc-61e129260acb.png)

@dscho I upgraded "Git for Windows"

**Comment by ggomez2k** [comment]
I don't know how relevant is, but I'm experiencing some odd behavior, if I try to open a folder from within VSCode, yarn would not work at all. Though if I right click the same folder from the Windows Explorer and select open with VSCode, yarn would work perfectly fine.

**Comment by HosseinAlipour** [comment]
I have a similar problem and @Nielio fix didn't help, it also happens in the windows command line!
`yarn run v1.17.2
$ node scripts/start.js
/usr/bin/bash: Files\git\bin\bash.exe: No such file or directory
?[2K?[1G?[31merror?[39m Command failed with exit code 127.
?[2K?[1G?[94minfo?[39m Visit ?[1mhttps://yarnpkg.com/en/docs/cli/run?[22m for documentation about this command.`

**Comment by smi1lee** [comment]
My environment is vscode powershell, the same problem happend with me. 
internal/modules/cjs/loader.js:638
    throw err;

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

.npmrc file
prefix=D:\Program Files\nodejs\node_global
cache=D:\Program Files\nodejs\node_cache
.yarnrc file
cache-folder "D:\\Program Files\\nodejs\\node_cache"
global-folder "D:\\Program Files\\nodejs\\node_global"

when I search yarn in D:\Program Files\nodejs\node_global\node_modules, I can't find the dir yarn, then I tried to reinstall it and it worked.
System environmental variable D:\Program Files\nodejs\node_global\

**Comment by mohkale** [comment]
This is still an issue. I just upgraded to bash 4.4.23 and I still have problems. All yarn commands don't produce any output (there's just a somewhat large gap from when I start the command to my prompt, such as if I had run clear). Also, running yarn completely hides my prompt, which makes the shell basically unusable. I have to keep restarting my shell everytime I accidentally run yarn. Could you please add an option to disable winpty? It's super annoying.

**Comment by JulioJu** [comment]
On Microsoft Windows 10 version 1909, with bash for Windows version 2.28.0, with mingw64 when we run `node --version` we have the same problem, with nodejs-lts v12.18.4 or nodejs version 14.11.0

Maybe `node` is broken on mingw64 ? 

We should probably make a PR to Yarn to call `node.exe` into https://github.com/yarnpkg/yarn/blob/master/bin/yarn?

On `npm` they do that https://github.com/npm/cli/blob/latest/bin/npm

```
case `uname` in
  *MINGW*)
    NPM_PREFIX=`"$NODE_EXE" "$NPM_CLI_JS" prefix -g`
    NPM_PREFIX_NPM_CLI_JS="$NPM_PREFIX/node_modules/npm/bin/npm-cli.js"
    if [ -f "$NPM_PREFIX_NPM_CLI_JS" ]; then
      NPM_CLI_JS="$NPM_PREFIX_NPM_CLI_JS"
    fi
    ;;
  *CYGWIN*)
    NPM_PREFIX=`"$NODE_EXE" "$NPM_CLI_JS" prefix -g`
    NPM_PREFIX_NPM_CLI_JS="$NPM_PREFIX/node_modules/npm/bin/npm-cli.js"
    if [ -f "$NPM_PREFIX_NPM_CLI_JS" ]; then
      NPM_CLI_JS="$NPM_PREFIX_NPM_CLI_JS"
    fi
    ;;
esac
```

**Comment by JulioJu** [comment]
Maybe I've found. Could be cause by Trend Micro https://github.com/rprichard/winpty/issues/95

**Comment by YX-XiaoBai** [comment]
The some problem trouble with me. Finally, I find out the solution. 🖐

![image](https://user-images.githubusercontent.com/45746195/96954998-301c4900-1527-11eb-8511-68b9b222d72a.png)

🙂Because my `yarn` install via `brew`, so i try `brew unintall yarn` and `brew install yarn`, as u can see, but problem just still keep 

![image](https://user-images.githubusercontent.com/45746195/96955098-68238c00-1527-11eb-851a-0c51e25319ac.png)

🙂Finally, i find out the problem is my file `~/.zshrc` yarn config path is not right, just fix the path of `yarn` correctly.

![image](https://user-images.githubusercontent.com/45746195/96957537-7e344b00-152d-11eb-8072-249123fbef2f.png)

![image](https://user-images.githubusercontent.com/45746195/96957635-c2275000-152d-11eb-8185-90487687af00.png)

![image](https://user-images.githubusercontent.com/45746195/96955280-cd777d00-1527-11eb-9b7b-6219c1baac16.png)

then, it' work again~~🙃🙃🙃

![image](https://user-images.githubusercontent.com/45746195/96957659-cf443f00-152d-11eb-9c26-8af554010ea6.png)

**Comment by dscho** [comment]
It seems that this here ticket is addressed, as of https://github.com/npm/cmd-shim/pull/30#event-2551131773.

@Yagun would you mind closing the ticket, please?

@YX-XiaoBai please note that this here bug tracker concerns itself about bugs in Git for Windows, not Git on macOS. I am not quite certain how the original report in this ticket is related to your report, but I am fairly certain that you are talking about a very different problem.

**Comment by SohelIslamImran** [comment]
Same issue.
`C:\Users\Sohel Islam Imran\AppData\Roaming\npm/node_modules/node/bin/node: line 1: This: command not found`

![image](https://user-images.githubusercontent.com/76745339/165057454-f037d4d9-3a28-40d1-bb92-5468ff6bbb18.png)

**Comment by dahlbyk** [comment]
@SohelIslamImran what does `which node` show? This seems like `yarn` was able to execute (this issue, which can be closed), but it can't find `node`.

**Comment by SohelIslamImran** [comment]
@dahlbyk  No! It is find `node`. But error with yarn only. Can't execute yarn commands.
![image](https://user-images.githubusercontent.com/76745339/165099367-881a40d1-0835-4e75-b879-697ad773d802.png)

**Comment by JulioJu** [comment]
Please try 

`node.exe $(type -p yarn)` .

**Comment by SohelIslamImran** [comment]
This issue has been open since 2018. Will this not be resolved? @torifat

**Comment by SohelIslamImran** [comment]
Adding `*MINGW64*` in these files resolved my problrm.

![image](https://user-images.githubusercontent.com/76745339/165562779-a2a2b4a7-596d-4353-a3b1-08d03718f81b.png)
![image](https://user-images.githubusercontent.com/76745339/165562845-766f8a05-2fd1-43bf-a135-1f9538d476cd.png)
![image](https://user-images.githubusercontent.com/76745339/165562860-eec623d2-9e92-42ca-bd97-4f02c9e8d811.png)

**Comment by SohelIslamImran** [comment]
> 

Thank you.

**Comment by SohelIslamImran** [comment]
> Resolved by adding MINGW64 to the yarn shell script basedir case statement:
> 
> ```
> case "$(uname -s)" in
>   Linux) basedir=$(dirname "$(readlink -f "$0" || echo "$argv0")");;
>   *CYGWIN* | *MINGW64*) basedir=`cygpath -w "$basedir"`;;
> esac
> ```

Thank you @jsweitzer

**Comment by dscho** [comment]
> ![image](https://user-images.githubusercontent.com/76745339/165562845-766f8a05-2fd1-43bf-a135-1f9538d476cd.png)

This is unnecessary, as the `*MINGW64*` case is already included in the `*MINGW*` case.

However, the last one, the change to `node_modules/yarn/bin/yarn` seems totally legit.

**Comment by SohelIslamImran** [comment]
Again the same problem 😔
![image](https://user-images.githubusercontent.com/76745339/166062830-ef366a1b-2619-4cdb-9d12-c8f96b6181b2.png)

**Comment by djimenezdev** [comment]
So for some reason I tried using the change to `node_modules/yarn/bin/yarn` and when I restarted my terminal It still gave me the error it couldn't find the yarn module.

But remembered that yarn offers a  way of configuring yarn via a msi installation!  as seen below: 
![Screenshot 2022-05-27 125254](https://user-images.githubusercontent.com/42664403/170780758-bac4fd58-c36f-41ae-a51f-f9621e1278da.png)

And when I attempted to use the `yarn install` command again in one of my projects for dependencies I needed to install, it worked again! And verified it worked with other key yarn commands as well. I know it says on the installation page it says it recommends to use `npm install --global yarn` to install. But the npm command was not installing some essential yarn config in the `C:\Program Files (x86)\Yarn\bin\yarn` and this is where for me it was saying it couldn't find the module yarn

But using the msi  I went back and notice that the Yarn folder was there and contained the yarn script in the bin folder and it worked

**Comment by alex-bluetrain** [comment]
5 years, still not fixed? is there any workaround other than not using git bash ?

**Comment by WardenDrew** [comment]
I saw a few comments in here and this is a top result when searching

If you are still getting the case specifically where you get a duplicate drive letters in both the windows and the unix path formats, check if you have set `MSYS_NO_PATHCONV=1` (such as in your .bash_profile) Its common to set this to avoid some other path conversion issues, but it ends up screwing with node's module filepath resolution. I ran into this first with corepack and then with yarn in git bash after setting them up in windows cmd.exe

```bash
AzureAD+AndrewHaskell@REDACTED MINGW64 ~
> corepack -v
0.28.1

AzureAD+AndrewHaskell@REDACTED  MINGW64 ~
> yarn -v
4.3.1

AzureAD+AndrewHaskell@REDACTED  MINGW64 ~
> export MSYS_NO_PATHCONV=1

AzureAD+AndrewHaskell@REDACTED  MINGW64 ~
> corepack -v
node:internal/modules/cjs/loader:1148
  throw err;
  ^

Error: Cannot find module 'C:\c\Program Files\nodejs\node_modules\corepack\dist\corepack.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.15.1

AzureAD+AndrewHaskell@REDACTED  MINGW64 ~
> yarn -v
node:internal/modules/cjs/loader:1148
  throw err;
  ^

Error: Cannot find module 'C:\c\Program Files\nodejs\node_modules\corepack\dist\yarn.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.15.1

AzureAD+AndrewHaskell@REDACTED  MINGW64 ~
> export -n MSYS_NO_PATHCONV

AzureAD+AndrewHaskell@REDACTED  MINGW64 ~
> corepack -v
0.28.1

AzureAD+AndrewHaskell@REDACTED  MINGW64 ~
> yarn -v
4.3.1
```
