### ISSUE TITLE
Yarn silently fails to install package, missing from node_modules

### ISSUE THREAD

**Issue by VictorBjelkholm** [yarnpkg/yarn#5374]
**Do you want to request a *feature* or report a *bug*?**

Bug
**What is the current behavior?**

Installing dependencies for https://github.com/ipfs/js-ipfs fails silently as `karma-mocha-webworker` never ends up in `node_modules/` directory. Running `yarn add karma-mocha-webworker` or even `npm install` installs the package correctly.

**If the current behavior is a bug, please provide the steps to reproduce.**

- Clone https://github.com/ipfs/js-ipfs.git
- Run `yarn`
- Now `karma-mocha-webworker` should be in `node_modules/`
- Instead, `ls node_modules | grep -i webworker ; echo $?` returns `1` instead of `0` 

**What is the expected behavior?**

Yarn installs all dependencies.

**Please mention your node.js, yarn and operating system version.**

```
$ node --version
v9.5.0

$ yarn --version
1.4.1-20180217.1901

$ uname -a
Linux lasoa 4.15.3-1-ARCH #1 SMP PREEMPT Mon Feb 12 23:01:17 UTC 2018 x86_64 GNU/Linux

```

** Extra information **

`yarn check` doesn't find that the module is missing but just mentions it could be deduped. 
```
$ yarn check 2>&1 >/dev/null | grep -i webworker
warning "aegir#karma-mocha-webworker#mocha@*" could be deduped from "5.0.1" to "mocha@5.0.1"
```

Tried installing modules with both `--check-files` and `--force` to no avail.

I've also tried the different versions of `yarn`, stable and daily. Also the npm version and the standalone.

**Comment by VictorBjelkholm** [comment]
Strange, created a new package with nothing but `aegir` defined as either a `dependency` or `devDependency`. With this new package, `yarn` installs `karma-mocha-webworker` correctly.

**Comment by VictorBjelkholm** [comment]
Logs for `yarn --verbose` and then grepping for `karma-mocha-webworker` shows that the directory is created at one point, but deleted afterwards (but the deletion is missing any logged action): https://gist.github.com/VictorBjelkholm/f05769c4fc3b761ad8a8c6b766b2dc8d

**Comment by VictorBjelkholm** [comment]
One step closer, seems `karma-mocha-webworker` is installed into `node_modules/aegir/node_modules` instead of at root `node_modules`. Which means, other modules can't use it even if it's supposedly there:

```
$ find node_modules -name "karma-mocha-webworker"
node_modules/aegir/node_modules/karma-mocha-webworker

$ node -e "require('karma-mocha-webworker')"
module.js:557
    throw err;
    ^

Error: Cannot find module 'karma-mocha-webworker'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:65:33)
    at Object.runInThisContext (vm.js:199:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:660:30)
    at evalScript (bootstrap_node.js:519:27)
```

**Comment by bestander** [comment]
Thanks for report, this looks like a legit issue with Yarn.
`karma-mocha-webworker` should have been hoisted to node_modules folder, besides on my system `yarn check` returns 3 error

```
error "nyc#yargs#cliui" is wrong version: expected "4.0.0", got "2.1.0"
error "nyc#cliui#strip-ansi" is wrong version: expected "4.0.0", got "3.0.1"
warning "nyc#cliui#strip-ansi#ansi-regex@^2.0.0" could be deduped from "2.1.1" to "ansi-regex@2.1.1"
error "nyc#strip-ansi#ansi-regex" is wrong version: expected "3.0.0", got "2.1.1"
```

Looks like something breaks hoisting system.

**Comment by bestander** [comment]
As a workaround just do `yarn add karma-mocha-webworker@^1.3.0` to add `karma-mocha-webworker` to your project's direct dependencies.
In general you can't rely on a dependency to be at the top of node_modules if you don't have it as a dependency.

**Comment by bestander** [comment]
As for yarn check returning errors for `nyc` dependencies it is because nyc has bundledDependencies and it probably bundles a wrong version which does not match the one in `nyc`'s package.json.

Handling of bundled dependencies is a separate issue though

**Comment by bestander** [comment]
I don't think the fact that `karma-mocha-webworker` does not get hoisted to top is a high priority issue, Yarn does not provide that guarantee, Yarn guarantees that every install will result with the same structure of node_modules though which is correct.

If anyone wants to debug why `karma-mocha-webworker` does not get hoisted a PR with a fix will be welcome though

**Comment by VictorBjelkholm** [comment]
> In general you can't rely on a dependency to be at the top of node_modules if you don't have it as a dependency.

The problem was actually not that it was in top level node_modules but that karma couldn't load it when it ended up with aegir's node_modules directory. When changing the way aegir does injection of plugins, things turned out fine. 

Haven't hit any issues with `nyc`, even though I get the same errors from `yarn check` (but they were filtered with grep above.).

Thanks a lot for the help!
