### ISSUE TITLE
scripts with keyword "create" in package.json cause Invalid package name bug

### ISSUE THREAD

**Issue by abrcdf1023** [yarnpkg/yarn#5432]
**What is the current behavior?**
scripts with keyword "create" in package.json cause Invalid package name bug

**If the current behavior is a bug, please provide the steps to reproduce.**
```json
{
  "name": "project",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "create": "node scripts/create.js"
  },
  "dependencies": {
    "vue-cli": "^2.9.3"
  }
}
```
```sh
yarn create
```
output
```
yarn create v1.5.1
error An unexpected error occurred: "Invalid package name.".
info If you think this is a bug, please open a bug report with the information provided in "/Users/liyanxin/Desktop/321/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```
**What is the expected behavior?**
```json
{
  "name": "project",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "createe": "node scripts/create.js"
  },
  "dependencies": {
    "vue-cli": "^2.9.3"
  }
}
```
```sh
yarn createe
```
output
```
liyanxindeMini:321 liyanxin$ yarn createe
yarn run v1.5.1
$ node scripts/create.js
module.js:559
    throw err;
    ^

Error: Cannot find module '/Users/liyanxin/Desktop/321/scripts/create.js'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:665:3
```

**Please mention your node.js, yarn and operating system version.**
node.js v9.6.1
yarn v1.5.1
mac os High Sierra 10.13.1（17B1003）

**Comment by sth** [comment]
The problem is that `create` is a yarn command: https://yarnpkg.com/lang/en/docs/cli/create/

So `yarn create` is not actually calling the script, it is executing the yarn command without the required parameters, which leads to the error. The error message is not very helpful though.

**Comment by abrcdf1023** [comment]
Oh, I make a stupid mistake. Thanks for your answer. Let's close this issue.
