### ISSUE TITLE
Error if ran with script

### ISSUE THREAD

**Issue by alexeikaratai** [yarnpkg/yarn#5452]
When i am running on terminal "./node_modules/.bin/eslint --debug -c .eslintrc.json --fix src/" all works fine, if i add this to package.json as "script":  {
 "eslint": "./node_modules/.bin/eslint --debug -c .eslintrc.json --fix src/"
} then i am running comand yarn run eslint - have got this error. can u help me what is it. 

check yarn bin its correct.
**Do you want to request a *feature* or report a *bug*?**

Bug
**What is the current behavior?**
Trace: 
  Error: Command failed.
  Exit code: 1
  Command: sh
  Arguments: -c node_modules/.bin/eslint --debug -c .eslintrc.json --fix src/
  Directory: /Users/alexkaratai/work/demo
  Output:
  
      at ProcessTermError.MessageError (/usr/local/Cellar/yarn/1.5.1/libexec/lib/cli.js:186:110)
      at new ProcessTermError (/usr/local/Cellar/yarn/1.5.1/libexec/lib/cli.js:226:113)
      at ChildProcess.<anonymous> (/usr/local/Cellar/yarn/1.5.1/libexec/lib/cli.js:30281:17)
      at emitTwo (events.js:126:13)
      at ChildProcess.emit (events.js:214:7)
      at maybeClose (internal/child_process.js:925:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
no errors
**Please mention your node.js, yarn and operating system version.**
node 8.9.4
yarn 1.5.1
mac os 10.13.3 (17D102)

**Comment by rally25rs** [comment]
Could you try changing the script to `eslint --debug -c .eslintrc.json --fix src/`
yarn should automatically add `node_modules/.bin` to the path.

Does it error if you run `yarn run eslint --version`

**Comment by alexeikaratai** [comment]
@rally25rs Thx, i try do it. 
yarn run eslint --version - work fine.

But eslint --debug -c .eslintrc.json --fix src/ throw error: 
Trace: 
  Error: Command failed.
  Exit code: 1
  Command: sh
  Arguments: -c /Users/alexkaratai/work/demo/node_modules/.bin/eslint -c .eslintrc.json --fix src/
  Directory: /Users/alexkaratai/work/demo
  Output:
  
      at ProcessTermError.MessageError (/usr/local/Cellar/yarn/1.5.1/libexec/lib/cli.js:186:110)
      at new ProcessTermError (/usr/local/Cellar/yarn/1.5.1/libexec/lib/cli.js:226:113)
      at ChildProcess.<anonymous> (/usr/local/Cellar/yarn/1.5.1/libexec/lib/cli.js:30281:17)
      at emitTwo (events.js:126:13)
      at ChildProcess.emit (events.js:214:7)
      at maybeClose (internal/child_process.js:925:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by alexeikaratai** [comment]
@rally25rs I saw the regularity if there is an error then we get the error, if only warnings then everything is fine

**Comment by jhilden** [comment]
I think this is a duplicate of #5457

**Comment by alejandrogih** [comment]
I had big troubles with this, and I was even trying with many others ports and nothing. I did npm install typescript@2.8 and it solved the problem, hope that it works for another one
