### ISSUE TITLE
yarn install fails when the modules directory is not named "node_modules"

### ISSUE THREAD

**Issue by peterlevi** [yarnpkg/yarn#5483]
I am not sure whether it is a Yarn problem, but using --modules-folder with a folder name that is not exactly `node_modules` fails when `chromedriver` is in the dependencies:

E.g. the command below fails, while if we had used `--modules-folder ./node_modules` it would pass.

```
$ yarn install --modules-folder ./node_modulesAAA --cache-folder ./node_cache
yarn install v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "antd > react-lazy-load@3.0.12" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0".
warning "antd > react-lazy-load@3.0.12" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0-0".
warning "antd > react-slick@0.14.11" has incorrect peer dependency "react@^0.14.0 || ^15.0.1".
warning "antd > react-slick@0.14.11" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.1".
warning "antd > rc-editor-mention > draft-js@0.10.1" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-rc".
warning "antd > rc-editor-mention > draft-js@0.10.1" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0-rc".
warning "antd > rc-tabs > rc-hammerjs@0.6.8" has incorrect peer dependency "react@^0.14.3 || ^15.0.0".
warning " > react-router-redux@5.0.0-alpha.6" has incorrect peer dependency "react@^15".
warning "react-router-redux > react-router@4.1.2" has incorrect peer dependency "react@^15".
warning " > redux-devtools-dock-monitor@1.1.2" has incorrect peer dependency "react@^0.14.9 || ^15.3.0".
warning "redux-devtools-inspector > react-json-tree@0.10.9" has incorrect peer dependency "react@^15.0.0".
warning "redux-devtools-inspector > react-json-tree@0.10.9" has incorrect peer dependency "react-dom@^15.0.0".
warning "@storybook/addon-knobs > react-textarea-autosize@4.3.2" has incorrect peer dependency "react@>=0.14.0 <16.0.0".
warning " > babel-loader@7.1.2" has unmet peer dependency "babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc".
warning "@storybook/react > react-modal@2.4.1" has incorrect peer dependency "react@^0.14.0 || ^15.0.0".
warning "@storybook/react > react-modal@2.4.1" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0".
warning "@storybook/react > @storybook/ui > @storybook/react-fuzzy@0.4.0" has incorrect peer dependency "react@^0.14.7 || ^15.0.0".
warning "@storybook/react > @storybook/ui > react-icons@2.2.5" has incorrect peer dependency "react@^0.14.0 || ^15.0.0".
warning "@storybook/react > @storybook/ui > react-icons@2.2.5" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0".
warning "@storybook/react > @storybook/ui > react-komposer@2.0.0" has incorrect peer dependency "react@^0.14.7 || ^15.0.0".
warning "@storybook/react > @storybook/ui > react-treebeard@2.0.3" has incorrect peer dependency "react@^15.5.4".
warning "@storybook/react > @storybook/ui > react-treebeard@2.0.3" has incorrect peer dependency "react-dom@^15.5.4".
warning "@storybook/react > @storybook/ui > mantra-core > react-komposer@1.13.1" has incorrect peer dependency "react@^0.14.3 || ^15.0.0".
warning "@storybook/react > @storybook/ui > mantra-core > react-simple-di@1.2.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0".
warning "@storybook/react > @storybook/ui > react-komposer > react-stubber@1.0.0" has incorrect peer dependency "react@^0.14.7 || ^15.0.0".
warning "@storybook/react > @storybook/ui > react-treebeard > radium@0.19.4" has incorrect peer dependency "react@^15.3.0".
warning "@storybook/react > @storybook/ui > react-treebeard > velocity-react > react-transition-group@1.2.0" has incorrect peer dependency "react@^15.0.0".
warning "@storybook/react > @storybook/ui > react-treebeard > velocity-react > react-transition-group@1.2.0" has incorrect peer dependency "react-dom@^15.0.0".
warning " > babel-plugin-rewire@1.1.0" has unmet peer dependency "babel-core@^6.0.0".
warning " > babel-plugin-rewire@1.1.0" has unmet peer dependency "babel-template@^6.2.0".
warning " > babel-plugin-rewire@1.1.0" has unmet peer dependency "babel-types@^6.2.0".
warning " > chai-enzyme@1.0.0-beta.0" has unmet peer dependency "cheerio@0.19.x || 0.20.x || 0.22.x || ^1.0.0-0".
[4/4] Building fresh packages...
[1/3] ⠂ uglifyjs-webpack-plugin
[2/3] ⠂ chromedriver
[3/3] ⠂ testcafe-browser-tools
[-/3] ⠂ waiting...
error An unexpected error occurred: "node_modulesAAA/chromedriver: Command failed.
Exit code: 1
Command: sh
Arguments: -c node install.js
Directory: node_modulesAAA/chromedriver
Output:
module.js:471
    throw err;
    ^

Error: Cannot find module 'extract-zip'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/peterlevi/dev/forms/ui/node_modulesAAA/chromedriver/install.js:3:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

```

**Comment by rally25rs** [comment]
That's really just how node works. I believe it's hard-coded to `node_modules`, at least thats all the docs ever refer to https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders

Basically node is trying to resolve a module, and it looks up the file hierarchy for `node_modules/` folders. It doesn't know that you changed the name of `node_modules`.

**Comment by peterlevi** [comment]
Does it make sense for Yarn to validate the --modules-folder is actually named "node_modules" before it starts, so that the error is more user-friendly than getting an import error during the install?

**Comment by rally25rs** [comment]
Well, what is causing the error is a custom install script in a package that is trying to `require` another package, but node only looks in `node_modules`. This really makes `--modules-folder`'s use cases pretty limited. The only common use case I can think of is for installing web packages, like `jquery` to a `www` folder or something like that.
