### ISSUE TITLE
"Couldn't find package" only occurs on a global install

### ISSUE THREAD

**Issue by AndreasBackx** [yarnpkg/yarn#5508]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Cannot install tslint globally. This could be a problem with my setup, but the logs don't provide enough information for me to check. Running `yarn add tslint typescript` in my project's directory does install the dependencies correctly.

```
Arguments: 
  /usr/bin/node /usr/bin/yarn global add tslint typescript

PATH: 
  /home/andreas/.bin:/home/andreas/.yarn/bin:/usr/local/bin:/usr/local/sbin:/home/andreas/.gem/ruby/2.4.0/bin:/home/andreas/Development/Go/bin:/home/andreas/.pyenv/shims:/opt/pyenv/plugins/pyenv-virtualenv/shims:/home/andreas/.pyenv/shims:/home/andreas/Development/Android/SDK/platform-tools:/home/andreas/.bin:/home/andreas/.yarn/bin:/usr/local/bin:/usr/local/sbin:/home/andreas/.gem/ruby/2.4.0/bin:/home/andreas/Development/Go/bin:/home/andreas/.pyenv/shims:/opt/pyenv/plugins/pyenv-virtualenv/shims:/home/andreas/.pyenv/shims:/home/andreas/Development/Android/SDK/platform-tools:/opt/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

Yarn version: 
  1.5.1

Node version: 
  9.8.0

Platform: 
  linux x64

npm manifest: 
  {
    "dependencies": {
      "typescript": "^2.7.2"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
  # yarn lockfile v1
  
  
  typescript@^2.7.2:
    version "2.7.2"
    resolved "https://registry.yarnpkg.com/typescript/-/typescript-2.7.2.tgz#2d615a1ef4aee4f574425cdff7026edf81919836"

Trace: 
  Error: Couldn't find package "diff@^3.2.0" required by "tslint" on the "npm" registry.
      at new MessageError (/usr/lib/node_modules/yarn/lib/cli.js:186:110)
      at PackageRequest.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:36274:17)
      at Generator.throw (<anonymous>)
      at step (/usr/lib/node_modules/yarn/lib/cli.js:98:30)
      at /usr/lib/node_modules/yarn/lib/cli.js:111:13
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:118:7)
```

**What is the expected behavior?**
For Yarn to install tslint without problems. I've tried this on my Macbook running MacOS High Sierra without problems.

**Please mention your node.js, yarn and operating system version.**
Node: 9.8.0
Yarn: 1.5.1
OS: Arch Linux 4.15.8-1

**Comment by dreadful44** [comment]
For me, i add path to `$NODE_PATH=/Users/korhanozbek/.config/yarn/global/node_modules` and solved problem.

**Comment by AndreasBackx** [comment]
@dreadful44 thank you for your input, but that unfortunately did not solve the issue for me.

**Comment by dylang** [comment]
We've been seeing this too, yarn `1.5.1`, and it's randomly killing our builds. When it happens locally, we run `yarn` a second time and it works fine.

**Comment by AndreasBackx** [comment]
It's currently back to npm for me as `yarn` is completely unreliable when it comes to installing dependencies.

**Comment by AndreasBackx** [comment]
Could anyone take a look at this? Yarn is basically unusable for me because of this.

**Comment by armordog** [comment]
(Note: This post will probably not help anyone.)

I have the same problem when running `yarn global add gatsby-cli`

`npm install -g gatsby-cli` works every time

**Comment by AndreasBackx** [comment]
@armordog it happens with almost any global yarn install for me.

**Comment by AlBannaTechno** [comment]
### yarn global add dts-gen
Not work at first time but every thing work correctly at the second time

**Comment by 07Gond** [comment]
Hi, @AndreasBackx is it still an issue?
