### ISSUE TITLE
Yarn fails to install certain packages (Error Request failed "404 Not Found")

### ISSUE THREAD

**Issue by TyOverby** [yarnpkg/yarn#5530]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Yarn fails to install @types/webpack at version 4.1.1

**package.json**
```
    "@types/webpack": "^4.1.1",
```

```
  Error: https://registry.yarnpkg.com/@types/webpack/-/webpack-4.1.1.tgz: Request failed "404 Not Found"
      at new ResponseError (/usr/lib/node_modules/yarn/lib/cli.js:238:112)
      at Request.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:61626:26)
      at emitOne (events.js:116:13)
      at Request.emit (events.js:211:7)
      at Request.module.exports.Request.onRequestResponse (/usr/lib/node_modules/yarn/lib/cli.js:133316:10)
      at emitOne (events.js:116:13)
      at ClientRequest.emit (events.js:211:7)
      at HTTPParser.parserOnIncomingClient (_http_client.js:551:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
      at TLSSocket.socketOnData (_http_client.js:440:20)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

It installs

**Please mention your node.js, yarn and operating system version.**

yarn version: 1.5.1
operating system: Ubuntu 16.3
nodejs version: v8.10.0

**Comment by TyOverby** [comment]
Interestingly, `https://registry.yarnpkg.com/@types/webpack/-/webpack-4.1.1.tgz` is an invalid url, but `https://registry.yarnpkg.com/@types/webpack/webpack-4.1.1.tgz` is fine.  No idea how that extra dash got there.

**Comment by lobboblaw** [comment]
Seeing something similar:

Error: https://registry.yarnpkg.com/@types/webpack/-/webpack-3.8.9.tgz: Request failed "404 Not Found"
      at ResponseError (/usr/share/yarn/lib/cli.js:163:5)
      at Request.<anonymous> (/usr/share/yarn/lib/cli.js:59356:26)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:188:7)
      at Request.module.exports.Request.onRequestResponse (/usr/share/yarn/lib/cli.js:123971:10)
      at emitOne (events.js:96:13)
      at ClientRequest.emit (events.js:188:7)
      at HTTPParser.parserOnIncomingClient (_http_client.js:474:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
      at TLSSocket.socketOnData (_http_client.js:363:20)

It was working earlier this afternoon.

**Comment by TyOverby** [comment]
@lobboblaw: Yep, can confirm that it broke in the last 3 hours.

**Comment by kraenhansen** [comment]
I am seeing this with `npm` as well.

**Comment by kraenhansen** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/24347

**Comment by geomorillo** [comment]
im seeing this on npn with aureliajs

**Comment by Alexander-Taran** [comment]
>Interestingly, https://registry.yarnpkg.com/@types/webpack/-/webpack-4.1.1.tgz is an invalid url, but https://registry.yarnpkg.com/@types/webpack/webpack-4.1.1.tgz is fine. No idea how that extra dash got there.

npm -i does the same..

**Comment by simivar** [comment]
Same here. And I thought I'm doing something wrong as it's first time I'm using yarn 😢 

`Arguments: 
  C:\Program Files\nodejs\node.exe C:\Program Files (x86)\Yarn\bin\yarn.js add @types/webpack@3.8.11

PATH: 
  C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files\PuTTY\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files\Git\cmd;C:\Program Files\Gource\cmd;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin\;C:\Users\my-user\AppData\Local\Microsoft\WindowsApps;C:\Users\my-user\AppData\Roaming\Composer\vendor\bin;C:\Users\my-user\AppData\Roaming\npm;C:\Users\my-user\AppData\Local\Yarn\bin

Yarn version: 
  1.5.1

Node version: 
  8.10.0

Platform: 
  win32 x64

npm manifest: 
  {
    "devDependencies": {
      "@symfony/webpack-encore": "^0.19.0"
    },
    "license": "UNLICENSED",
    "private": true,
    "scripts": {
      "dev-server": "encore dev-server",
      "dev": "encore dev",
      "watch": "encore dev --watch",
      "build": "encore production"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: https://registry.yarnpkg.com/@types/webpack/-/webpack-3.8.11.tgz: Request failed "404 Not Found"
      at new ResponseError (C:\Program Files (x86)\Yarn\lib\cli.js:238:112)
      at Request.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:61626:26)
      at emitOne (events.js:116:13)
      at Request.emit (events.js:211:7)
      at Request.module.exports.Request.onRequestResponse (C:\Program Files (x86)\Yarn\lib\cli.js:133316:10)
      at emitOne (events.js:116:13)
      at ClientRequest.emit (events.js:211:7)
      at HTTPParser.parserOnIncomingClient (_http_client.js:551:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
      at TLSSocket.socketOnData (_http_client.js:440:20)
`

**Comment by Alexander-Taran** [comment]
registry issue resolved:
https://github.com/npm/registry/issues/292

so this one probably can be closed

**Comment by Cherviakov** [comment]
Error 404 on that link @Alexander-Taran

**Comment by chrislam** [comment]
> registry issue resolved:
> https://github.com/npm/registry/issues/292
> 
> so this one probably can be closed

Updated link to the npm registry issues archive
https://github.com/npm/registry-issue-archive/issues/292
