### ISSUE TITLE
Webpack config not working with ES6 module import

### ISSUE THREAD

**Issue by hanxue** [yarnpkg/yarn#5550]
**What is the current behavior?**
I have converted my Webpack configuration files from CommonJS to ES6 Modules to cjs-to-es6. Some of the ES6 import statements such as this works:

```
import config from '../config'
```

Whilst this line does not work

```
import utils from './utils'
````

Error message:

```
$ yarn run dev
yarn run v1.5.1
$ babel-node ./node_modules/.bin/webpack-dev-server --inline --progress --config build/webpack.dev.conf.js
/my/directory/build/vue-loader.conf.js:34
  loaders: _utils2.default.cssLoaders({
                           ^

TypeError: Cannot read property 'cssLoaders' of undefined
    at Object.<anonymous> (/my/directory/build/vue-loader.conf.js:19:18)
    at Module._compile (module.js:649:30)
    at loader (/Users/hanxue/.config/yarn/global/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/hanxue/.config/yarn/global/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/my/directory/build/webpack.base.conf.js:5:1)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c babel-node ./node_modules/.bin/webpack-dev-server --inline --progress --config build/webpack.dev.conf.js
Directory: /my/directory
```

`yarn-error.log` is at https://gist.github.com/cf6020aa2f4c9e7299b1c2652a098610

**What is the expected behavior?**

ES6 modules import should work. My workaround now is to change the code to

```
const utils = require('./utils')
```

webpack: 4.0.1 
node: v9.8.0 
yarn: 1.5.1
macOS: 10.10.5

**Comment by rally25rs** [comment]
I don't think yarn would have anything to do with this, unless a module is missing after install.
I'm using yarn + webpack + es6 imports without any issues, but I don't use vue.
Maybe try posting this in `vue-loader` (where the error is occuring) or `webpack`?

**Comment by jrwpatterson** [comment]
Why would it be broken after a yarn install but not an npm install not just on my machine but every machine

________________________________

**Comment by rally25rs** [comment]
Can you rig up a minimal example? I don't know what your config looks like to try to reproduce this myself.

**Comment by hanxue** [comment]
Thanks for looking at the issue. I have temporarily abandoned using ES6 syntax. My decision to switch is because webpack build time is taking a long time, and ES6 should offer better performance for file and dependency resolution. 

The reason why I raised an issue here and not at `webpack` is because the exact syntax work for `npm`, but not when I am using `yarn`. I will see if I have time to create a fully reproducible project.
