### ISSUE TITLE
Running a bash script with #! bin/bash or bin/sh through post install causes exit code 126

### ISSUE THREAD

**Issue by Aghassi** [yarnpkg/yarn#5600]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Adding a bash script with `#! /bin/bash` or `#! bin/sh`causes yarn to fail with

```
sh: ./postinstallScript.sh: bin/bash: bad interpreter: No such file or directory
error An unexpected error occurred: "Command failed.
Exit code: 126
Command: sh
Arguments: -c ./postinstallScript.sh
Directory: /Users/daghassi/git/my-fancy-project
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/daghassi/git/my-fancy-project/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a bash script with the first line including   `#! /bin/bash` or `#! bin/sh`
2. Run `chmod +x` on it
3. Add it to the `postinstall` hook in `package.json` such that it looks like

```
postinstall: './script-to-call.sh'
```

**What is the expected behavior?**
It should run the script in the given shell without exploding

**Please mention your node.js, yarn and operating system version.**
Node 8.9.0 (or higher depending on `nvm`)
Yarn 1.5.1
macOS 10.13.3

**Comment by rally25rs** [comment]
Can you run the same script outside of yarn?

```
~/Projects/yarn-test 🐒   cat post.sh
#! bin/sh

echo "POST"
~/Projects/yarn-test 🐒   ./post.sh
-bash: ./post.sh: bin/sh: bad interpreter: No such file or directory
```

in the case of `bin/sh` you are missing a leading `/`, it should be `/bin/sh`

```
~/Projects/yarn-test 🐒   cat post.sh
#! /bin/sh

echo "POST"
~/Projects/yarn-test 🐒   yarn postinstall
yarn run v1.5.1
$ ./post.sh
POST
✨  Done in 0.08s.
```

**Comment by Aghassi** [comment]
🤦‍♂️ That leading slash. I feel silly. I appreciate the help. I can indeed run it outside of yarn. Worst part is that a shell syntax checker didn't pick up on that error.

**Comment by wnaylor** [comment]
Does the plugin homebridge-garagedoor-command work with Ryobi GDO. I installed it but can't get it to work. This is the error I'm getting. "[Garage Door] { Error: Command failed: ./check_state.sh
/bin/sh: ./check_state.sh: No such file or directory

    at ChildProcess.exithandler (child_process.js:291:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
  killed: false,
  code: 127,
  signal: null,
  cmd: './check_state.sh' }". Can anyone help me?
