### ISSUE TITLE
Broken install for local dependencies with relative paths

### ISSUE THREAD

**Issue by the-spyke** [yarnpkg/yarn#5735]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

The project is located in `/home/user/Projects/yarn-test/`.

Having local dependencies like in monorepo, which are specified by a relative path in `package.json` gives an error message:

```
$ yarn
yarn install v1.6.0
info No lockfile found.
[1/4] Resolving packages...
error Package "network" refers to a non-existing file '"/home/user/Projects/network"'.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Package "utils" refers to a non-existing file '"/home/user/Projects/utils"'.
    at MessageError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:237:66)
    at new MessageError (/usr/share/yarn/lib/cli.js:266:123)
    at FileResolver.<anonymous> (/usr/share/yarn/lib/cli.js:51386:15)
    at Generator.next (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:98:30)
    at /usr/share/yarn/lib/cli.js:109:13
```

Basically, what happens is that relative paths inside dependencies are resolved from the project root instead of the dependency itself. So, searching for `network` in `controls` instead of `/home/user/Projects/yarn-test/packages/controlls/../network` it goes by `/home/user/Projects/yarn-test/../network`.

What's interesting, installing inside `controls` directory works fine (as it should). But only if the root `package.json` (the on in the `yarn-test`) has no `workspaces` set up. In other case it fails with the same issue.

**If the current behavior is a bug, please provide the steps to reproduce.**

Example: https://github.com/the-spyke/issues_yarn-install

**What is the expected behavior?**

1. It should anywhere install without errors.
2. With or without workspaces in the root directory.

**Please mention your node.js, yarn and operating system version.**

```
Node: 10.0.0
npm: 6.0.0
Yarn: 1.6.0
OS: Ubuntu 17.10.1 x86_64 (4.13.0-39-generic)
```

**Comment by the-spyke** [comment]
Thank you. I got used to omitting type for local paths with `npm`.
