### ISSUE TITLE
yarn init git remote url error 

### ISSUE THREAD

**Issue by jamiebuilds** [yarnpkg/yarn#577]
**Do you want to request a _feature_ or report a _bug_?** But

**What is the current behavior?**

Running `yarn init` on an empty git repository with no origin results in:

``` sh
yarnpkg init v0.14.0
error Command failed.
Exit code: 1
Command: git
Arguments: config remote.origin.url
Directory: /Users/thejameskyle/Projects/yarn-i18n
Output:

    at SpawnError (/Users/thejameskyle/Projects/yarn/lib/errors.js:18:1)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

``` sh
$ git init foo && cd foo
$ yarn init
yarnpkg init v0.14.0
error Command failed.
Exit code: 1
Command: git
Arguments: config remote.origin.url
Directory: /Users/thejameskyle/Projects/yarn-i18n
Output:

    at SpawnError (/Users/thejameskyle/Projects/yarn/lib/errors.js:18:1)
    at ChildProcess.proc.on.code (/Users/thejameskyle/Projects/yarn/lib/util/child.js:95:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
info Visit http://yarnpkg.com/en/docs/cli/init for documentation about this command.
```

**Please mention your node.js, yarn and operating system version.**

Running this against master on macOS with `git version 2.8.0-rc2`

**Comment by williamthiago** [comment]
Still fail if you dont have user.name and user.email set in git config, as in a new docker container
`docker run -it node /bin/bash`
`npm install -g yarn`
`yarn init`
