### ISSUE TITLE
Invalid tar file

### ISSUE THREAD

**Issue by zellwk** [yarnpkg/yarn#5786]
Reporting a bug. 

**What is the current behavior?**

I tried to install a library I released, [zl-fetch](https://github.com/zellwk/zl-fetch). Had an error that says "invalid tar file". 

Command I ran: 

```
yarn add zl-fetch
```

The download works fine with a normal npm install. 

```
npm -i zl-fetch
```

Here's the error log: 

```
Trace: 
  Error: https://registry.yarnpkg.com/zl-fetch/-/zl-fetch-2.0.10.tgz: invalid tar file
      at Extract.Parse._startEntry (/usr/local/lib/node_modules/yarn/node_modules/tar/lib/parse.js:149:13)
      at Extract.Parse._process (/usr/local/lib/node_modules/yarn/node_modules/tar/lib/parse.js:131:12)
      at BlockStream.<anonymous> (/usr/local/lib/node_modules/yarn/node_modules/tar/lib/parse.js:47:8)
      at emitOne (events.js:116:13)
      at BlockStream.emit (events.js:211:7)
      at BlockStream._emitChunk (/usr/local/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:145:10)
      at BlockStream.resume (/usr/local/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:58:15)
      at Extract.Reader.resume (/usr/local/lib/node_modules/yarn/node_modules/fstream/lib/reader.js:249:34)
      at Entry.<anonymous> (/usr/local/lib/node_modules/yarn/node_modules/tar/lib/parse.js:261:8)
      at emitNone (events.js:106:13)
```

**What is the expected behavior?**

Expected it to download properly. 

**Please mention your node.js, yarn and operating system version.**

Node version: 8.9.1
Yarn version: 0.21.3 
OS Verson: Mac OS 10.13.4 (High Sierra)

**Comment by rally25rs** [comment]
Works fine for me at the moment. This could have just been a bad/corrupt download. Does it still error for you? If so, maybe try `yarn cache clean` before the `yarn add zl-fetch`

**Comment by zellwk** [comment]
Sorry, forgot to update. I pushed a new version and it worked fine. Will try `yarn cache clean` if I run into this error again. 

Thanks!
