### ISSUE TITLE
Yarn install crashes (proxy ?)

### ISSUE THREAD

**Issue by Shenrak** [yarnpkg/yarn#5817]
Hi,

I've got an issue running ```yarn install``` on a project previously under npm.
Yarn version : `1.6.0`
Node version : `7.4.0`
I've set proxy settings : 
```json
{ 'version-tag-prefix': 'v',
  'version-git-tag': true,
  'version-git-sign': false,
  'version-git-message': 'v%s',
  'init-version': '1.0.0',
  'init-license': 'MIT',
  'save-prefix': '^',
  'ignore-scripts': false,
  'ignore-optional': false,
  registry: 'https://registry.yarnpkg.com',
  'strict-ssl': false,
  'user-agent': 'yarn/1.6.0 npm/? node/v7.4.0 win32 x64',
  'http-proxy': 'http://10.3.6.18:9191',
  'https-proxy': 'http://10.3.6.18:9191',
  lastUpdateCheck: 1526287641701,
  proxy: 'http://10.3.6.18:9191' }
info npm config
{ proxy: 'http://10.3.6.18:9191' }
```

```yarn install``` crashes at one point, here is the [--verbose](https://gist.github.com/Shenrak/17882f79195d0ee65cd4506b3ca3b7af)

I'm running windows 7 64bits

Hope that can be helped, and hope that's not the node version that's causing the problem..
Thanks !

**Comment by rally25rs** [comment]
Based on the error message 

```
Error: http://registry.npmjs.org/event-stream/-/event-stream-3.3.4.tgz: Request failed "407 Proxy Authentication Required"
```

I'm guessing this is an issue with your proxy. Is yarn still having the same issue? If so, try fetching that URL with `curl` or a web browser that is set to the same proxy and see if it gives you a 407 there too.

**Comment by Shenrak** [comment]
I have NPM that contacts this URL without any problems, and it has the exact same proxy config that yarn does.

Here is the `yarn-error.log` : 

``` json
Arguments: 
  C:\Program Files\nodejs\node.exe C:\Program Files (x86)\Yarn\bin\yarn.js

PATH: 
  C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\nodejs\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files\Git\cmd;C:\Program Files\erl9.2\bin;C:\Program Files (x86)\Elixir\bin;C:\Windows\system32\config\systemprofile\.mix\escripts;C:\Program Files\dotnet\;C:\Program Files (x86)\Yarn\bin\;C:\Users\GROU\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\Microsoft VS Code\bin;C:\Users\GROU\AppData\Roaming\npm;C:\Users\GROU\AppData\Local\Yarn\bin;C:\Users\GROU\AppData\Local\Programs\Fiddler

Yarn version: 
  1.6.0

Node version: 
  8.11.2

Platform: 
  win32 x64

Trace: 
  Error: http://registry.npmjs.org/event-stream/-/event-stream-3.3.4.tgz: Request failed "407 Proxy Authentication Required"
      at ResponseError.ExtendableBuiltin (C:\Program Files (x86)\Yarn\lib\cli.js:212:66)
      at new ResponseError (C:\Program Files (x86)\Yarn\lib\cli.js:318:124)
      at Request.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:61933:26)
      at emitOne (events.js:116:13)
      at Request.emit (events.js:211:7)
      at Request.module.exports.Request.onRequestResponse (C:\Program Files (x86)\Yarn\lib\cli.js:134041:10)
      at emitOne (events.js:116:13)
      at ClientRequest.emit (events.js:211:7)
      at HTTPParser.parserOnIncomingClient (_http_client.js:543:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)

npm manifest: 
  {
      "name": "droopy",
      "version": "0.1.0",
      "private": true,
      "dependencies": {
          "history": "^4.7.2",
          "material-ui": "^0.20.0",
          "node-sass-chokidar": "^1.2.2",
          "normalizr": "^3.2.4",
          "npm-run-all": "^4.1.3",
          "q": "^1.5.1",
          "react": "^16.2.0",
          "react-adal": "^0.3.15",
          "react-bootstrap-table-next": "^0.1.8",
          "react-bootstrap-table2-filter": "^0.1.6",
          "react-bootstrap-table2-paginator": "^0.1.3",
          "react-dom": "^16.2.0",
          "react-redux": "^5.0.7",
          "react-redux-toastr": "^7.2.3",
          "react-router-dom": "^4.2.2",
          "react-router-redux": "^5.0.0-alpha.9",
          "react-scripts": "1.1.1",
          "react-treebeard": "^2.1.0",
          "redux": "^3.7.2"
      },
      "scripts": {
          "build-css": "node-sass-chokidar src/ -o src/",
          "watch-css": "npm run build-css && node-sass-chokidar src/ -o src/ --watch --recursive",
          "start-js": "react-scripts start",
          "start": "npm-run-all -p watch-css start-js",
          "build-js": "react-scripts build",
          "build": "npm-run-all build-css build-js",
          "test": "react-scripts test --env=jsdom",
          "eject": "react-scripts eject"
      },
      "devDependencies": {
          "node-sass": "^4.8.3",
          "redux-logger": "^3.0.6",
          "redux-promise-middleware": "^5.0.0",
          "redux-thunk": "^2.2.0",
          "sass-loader": "^6.0.7"
      }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile
```

**Comment by zhengyimeng** [comment]
Has the problem been solved?
