### ISSUE TITLE
yarnpkg add --exact fails

### ISSUE THREAD

**Issue by ashrafuzzaman** [yarnpkg/yarn#5852]
**Do you want to request a *feature* or report a *bug*?**

Reporting a *bug*

**What is the current behavior?**
`npx create-react-app my-app` fails

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Should bootstrap a boilerplat project for react.

**Please mention your node.js, yarn and operating system version.**
Here is the stack trace.
```
Arguments: 
  /usr/bin/node /usr/share/yarn/bin/yarn.js add --exact react

PATH: 
  /home/jitu/.virtualenvs/localdev/bin:/home/jitu/.rvm/gems/ruby-2.4.1/bin:/home/jitu/.rvm/gems/ruby-2.4.1@global/bin:/home/jitu/.rvm/rubies/ruby-2.4.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/jitu/.rvm/bin:/home/jitu/.rvm/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/jitu/.rvm/bin:/home/jitu/.rvm/bin

Yarn version: 
  1.5.1

Node version: 
  8.10.0

Platform: 
  linux x64

npm manifest: 
  No manifest

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: true/react: Invalid URI "true/react"
      at Request.module.exports.Request.init (/usr/share/yarn/lib/cli.js:132518:31)
      at new Request (/usr/share/yarn/lib/cli.js:132372:8)
      at request (/usr/share/yarn/lib/cli.js:129371:10)
      at RequestManager.execute (/usr/share/yarn/lib/cli.js:65071:15)
      at RequestManager.shiftQueue (/usr/share/yarn/lib/cli.js:65098:10)
      at /usr/share/yarn/lib/cli.js:64849:13
      at new Promise (<anonymous>)
      at new F (/usr/share/yarn/lib/cli.js:23451:28)
      at RequestManager.request (/usr/share/yarn/lib/cli.js:64847:19)
      at NpmRegistry.request (/usr/share/yarn/lib/cli.js:31136:32)
```

**Comment by rally25rs** [comment]
Can you try this in yarn 1.6.0? It works for me in that version:

```
~/Projects/yarn-test 🐒   yarn add --exact react
yarn add v1.6.0
warning package.json: No license field
warning test: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 16 new dependencies.
info Direct dependencies
└─ react@16.3.2
info All dependencies
├─ asap@2.0.6
├─ core-js@1.2.7
├─ encoding@0.1.12
├─ iconv-lite@0.4.23
├─ is-stream@1.1.0
├─ isomorphic-fetch@2.2.1
├─ js-tokens@3.0.2
├─ loose-envify@1.3.1
├─ node-fetch@1.7.3
├─ promise@7.3.1
├─ prop-types@15.6.1
├─ react@16.3.2
├─ safer-buffer@2.1.2
├─ setimmediate@1.0.5
├─ ua-parser-js@0.7.18
└─ whatwg-fetch@2.0.4
warning test: No license field
✨  Done in 2.24s.
```

**Comment by ashrafuzzaman** [comment]
I tried with the 1.6.0,
```
Arguments: 
  /home/jitu/.nvm/versions/node/v8.11.1/bin/node /home/jitu/.nvm/versions/node/v8.11.1/bin/yarn add --exact react

PATH: 
  /home/jitu/.nvm/versions/node/v8.11.1/bin:/home/jitu/.virtualenvs/localdev/bin:/home/jitu/.rvm/gems/ruby-2.4.1/bin:/home/jitu/.rvm/gems/ruby-2.4.1@global/bin:/home/jitu/.rvm/rubies/ruby-2.4.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/jitu/.rvm/bin:/home/jitu/.rvm/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/jitu/.rvm/bin:/home/jitu/.rvm/bin

Yarn version: 
  1.6.0

Node version: 
  8.11.1

Platform: 
  linux x64

Trace: 
  Error: true/react: Invalid URI "true/react"
      at Request.module.exports.Request.init (/home/jitu/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:133243:31)
      at new Request (/home/jitu/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:133097:8)
      at request (/home/jitu/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:130096:10)
      at RequestManager.execute (/home/jitu/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:65379:15)
      at RequestManager.shiftQueue (/home/jitu/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:65406:10)
      at /home/jitu/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:65157:13
      at new Promise (<anonymous>)
      at new F (/home/jitu/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:23469:28)
      at RequestManager.request (/home/jitu/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:65155:19)
      at NpmRegistry.request (/home/jitu/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:31162:32)

npm manifest: 
  No manifest

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile
```
