### ISSUE TITLE
Yarn 1.7.0. does not use the designated registry

### ISSUE THREAD

**Issue by shahkashani** [yarnpkg/yarn#5969]
I suppose this is potentially more of a question than a bug report, but for certain dependencies, Yarn seems to use http://registry.npmjs.org instead of https://registry.yarnpkg.com. This wouldn't be a huge deal if it was using https and not http. I've tried setting the registry to https://registry.npmjs.org, but those same dependencies will always end up on http. Any ideas why?

Example below. Other dependencies I'm seeing this with are `event-stream@~3.3.0` and `onetime@^1.0.0`.

```compression@^1.7.2:
  version "1.7.2"
  resolved "http://registry.npmjs.org/compression/-/compression-1.7.2.tgz#aaffbcd6aaf854b44ebb280353d5ad1651f59a69"
  dependencies:
    accepts "~1.3.4"
    bytes "3.0.0"
    compressible "~2.0.13"
    debug "2.6.9"
    on-headers "~1.0.1"
    safe-buffer "5.1.1"
    vary "~1.1.2"
```

**Comment by lennyburdette** [comment]
I believe I'm seeing this issue too when trying to use a `.yarnrc` file with
```
registry "https://registry.yarnpkg.com"
``` 

I've worked around it by using an `.npmrc` file, though I lost a few hours before remembering that the file formats are different!
```
registry="https://registry.yarnpkg.com"
```

**Comment by hulkish** [comment]
@shahkashani can u run this with the `--verbose` flag, qnd provide the log? There's likely a .npmrc (perhaps you forgot.about?) that's causing this.

**Comment by rcarter** [comment]
@hulkish @shahkashani I'm having the same issue (with compression & onetime), here is the log with --verbose . Everything else runs through `"https://registry.yarnpkg.com`, but these seem to default to npmjs... any ideas?

```
verbose 54.505 Error: http://registry.npmjs.org/compression/-/compression-1.7.2.tgz: Request failed "500 Internal Server Error"
    at ResponseError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:218:66)
    at new ResponseError (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:324:124)
    at Request.<anonymous> (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:62463:26)
    at Request.emit (events.js:182:13)
    at Request.module.exports.Request.onRequestResponse (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:135561:10)
    at ClientRequest.emit (events.js:182:13)
    at HTTPParser.parserOnIncomingClient (_http_client.js:546:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at Socket.socketOnData (_http_client.js:432:20)
    at Socket.emit (events.js:182:13)
error An unexpected error occurred: "http://registry.npmjs.org/compression/-/compression-1.7.2.tgz: Request failed \"500 Internal Server Error\"".
```

**Comment by rcarter** [comment]
I found that I had a `registry.npmjs.org' line in my hosts file that was blocking me. removed that and all went through. found from this comment: https://github.com/npm/npm/issues/20818#issuecomment-393465150
