### ISSUE TITLE
yarn install fails if "node_modules" is a symlink (Windows)

### ISSUE THREAD

**Issue by phip1611** [yarnpkg/yarn#6069]
I want to report a **bug**.

I'm working on windows and the **node_modules**-directory in my project **is a symlink** to another location. If I run yarn install on a regular directory everything works fine but **if node_modules is a symlink** to another location **install fails at the "build package" phase**.

I run yarn it as administrator.

node 10.5.0
yarn 1.7.0
windows 10 1709

```
[4/4] Building fresh packages...
[1/3] ⢀ node-sass
[2/3] ⢀ phantomjs-prebuilt
[ERROR] error C:\Develop\project\node_modules\node-sass: Command failed.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[ERROR] Exit code: 1
[ERROR] Command: node scripts/install.js
[ERROR] Arguments: 
[ERROR] Directory: C:\Develop\project\node_modules\node-sass
[ERROR] Output:
[ERROR] internal/modules/cjs/loader.js:596
[ERROR]     throw err;
[ERROR]     ^
[ERROR] 
[ERROR] Error: Cannot find module 'mkdirp'
[ERROR]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
[ERROR]     at Function.Module._load (internal/modules/cjs/loader.js:520:25)
[ERROR]     at Module.require (internal/modules/cjs/loader.js:650:17)
[ERROR]     at require (internal/modules/cjs/helpers.js:20:18)
[ERROR]     at Object.<anonymous> (C:\Users\user\AppData\Local\Temp\project-node_modules\node-sass\scripts\install.js:7:11)
[ERROR]     at Module._compile (internal/modules/cjs/loader.js:702:30)
[ERROR]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
[ERROR]     at Module.load (internal/modules/cjs/loader.js:612:32)
[ERROR]     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
[ERROR]     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
[INFO] ------------------------------------------------------------------------
```

**Comment by chocolateboy** [comment]
@phip1611 I think this is a bug in Node. It breaks `require` after installation as well. The workaround that worked for me: make sure the target directory is called `node_modules` e.g.

#### Before

```bash
mkdir -p ~/shared/my-node-modules
ln -s ~/shared/my-node-modules node_modules
yarn install # error 
```

#### After

```bash
mkdir -p ~/shared/node_modules
ln -s ~/shared/node_modules
yarn install # OK
```

- https://github.com/nodejs/node-v0.x-archive/issues/25090
- https://github.com/npm/npm/issues/9479#issuecomment-146519463
- https://github.com/npm/npm/issues/10013#issuecomment-189176273

**Comment by phip1611** [comment]
You are right, thank you!
