### ISSUE TITLE
Installation Problem, Laravel, Windows 10 X64

### ISSUE THREAD

**Issue by AhmedFatehy** [yarnpkg/yarn#6085]
```
$ yarn install
yarn install v1.7.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check.                                                                                                                 Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error D:\server\www\Anonymous\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: D:\server\www\Anonymous\node_modules\node-sass
Output:
Building: D:\server\node\node.exe D:\server\www\Anonymous\node_modules\node-gyp\                                                                                                                bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldf                                                                                                                lags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'D:\\server\\node\\node.exe',
gyp verb cli   'D:\\server\\www\\Anonymous\\node_modules\\node-gyp\\bin\\node-gy                                                                                                                p.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.7.0
gyp info using node@10.5.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\server\www\Anonymous\node_mo                                                                                                                dules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\server\www\Anonymous\node_modules\which\whi                                                                                                                ch.js:68:19)
gyp verb `which` failed     at E (D:\server\www\Anonymous\node_modules\which\whi                                                                                                                ch.js:80:29)
gyp verb `which` failed     at D:\server\www\Anonymous\node_modules\which\which.                                                                                                                js:89:16
gyp verb `which` failed     at D:\server\www\Anonymous\node_modules\isexe\index.                                                                                                                js:42:5
gyp verb `which` failed     at D:\server\www\Anonymous\node_modules\isexe\window                                                                                                                s.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:158:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\server\www\Anonymous\node_mo                                                                                                                dules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\server\www\Anonymous\node_modules\which\whi                                                                                                                ch.js:68:19)
gyp verb `which` failed     at E (D:\server\www\Anonymous\node_modules\which\whi                                                                                                                ch.js:80:29)
gyp verb `which` failed     at D:\server\www\Anonymous\node_modules\which\which.                                                                                                                js:89:16
gyp verb `which` failed     at D:\server\www\Anonymous\node_modules\isexe\index.                                                                                                                js:42:5
gyp verb `which` failed     at D:\server\www\Anonymous\node_modules\isexe\window                                                                                                                s.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:158:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (                                                                                                                D:\\server\\www\\Anonymous\\node_modules\\which\\which.js:13:12)\n    at F (D:\\                                                                                                                server\\www\\Anonymous\\node_modules\\which\\which.js:68:19)\n    at E (D:\\serv                                                                                                                er\\www\\Anonymous\\node_modules\\which\\which.js:80:29)\n    at D:\\server\\www                                                                                                                \\Anonymous\\node_modules\\which\\which.js:89:16\n    at D:\\server\\www\\Anonym                                                                                                                ous\\node_modules\\isexe\\index.js:42:5\n    at D:\\server\\www\\Anonymous\\node                                                                                                                _modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:158:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python D:\server\python-2.7.14\python.EXE
gyp verb check python version `D:\server\python-2.7.14\python.EXE -c "import pla                                                                                                                tform; print(platform.python_version());"` returned: "2.7.14\r\n"
gyp verb get node dir no --target version specified, falling back to host node v                                                                                                                ersion: 10.5.0
gyp verb command install [ '10.5.0' ]
gyp verb install input version string "10.5.0"
gyp verb install installing version: 10.5.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 10.5.0
gyp verb build dir attempting to create "build" dir: D:\server\www\Anonymous\nod                                                                                                                e_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? D:\server\www\Anonymous\nod                                                                                                                e_modules\node-sass\build
gyp verb Not using VS2017: Could not use PowerShell to find VS2017
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: D:\server\www\Anonymous\node                                                                                                                _modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: D:\server\www\Anonymous\node_module                                                                                                                s\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: D:\server\www\Anonymous\node_module                                                                                                                s\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn D:\server\python-2.7.14\python.EXE
gyp info spawn args [ 'D:\\server\\www\\Anonymous\\node_modules\\node-gyp\\gyp\\                                                                                                                gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\server\\www\\Anonymous\\node_modules\\node-sass\\buil                                                                                                                d\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\server\\www\\Anonymous\\node_modules\\node-gyp\\addon                                                                                                                .gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\ahmed\\.node-gyp\\10.5.0\\include\\node\\commo                                                                                                                n.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\ahmed\\.node-gyp\\10.5.0',
gyp info spawn args   '-Dnode_gyp_dir=D:\\server\\www\\Anonymous\\node_modules\\                                                                                                                node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\ahmed\\.node-gyp\\10.5.0\\<(ta                                                                                                                rget_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\server\\www\\Anonymous\\node_module                                                                                                                s\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\server\\www\\Anonymous\\node_modules\\node-sass\\buil                                                                                                                d',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\ahmed\.node-gyp\10.5.0
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build,                                                                                                                 please add the "/m" switch.
Build started 7/11/2018 6:39:10 AM.
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tool                                                                                                                s versions are "4.0".

Build FAILED.

  MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available to                                                                                                                ols versions are "4.0".

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.65
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe                                                                                                                ` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\server\www\Anonymous\node_modules\                                                                                                                node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces                                                                                                                s.js:237:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "D:\\server\\node\\node.exe" "D:\\server\\www\\Anonymous\\node_                                                                                                                modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--l                                                                                                                ibsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\server\www\Anonymous\node_modules\node-sass
gyp ERR! node -v v10.5.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
Build failed with error code: 1
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this                                                                                                                 command.
```

OS: win 10 -  System Windows_NT 10.0.17134
node -v:  v10.5.0
npm -v: 6.1.0

**Comment by paul-soporan** [comment]
Closing as external, it's a `node-gyp` error which we don't control.
