### ISSUE TITLE
can't use yarn anymore because of couldn't find babel-roomData 

### ISSUE THREAD

**Issue by johnfrades** [yarnpkg/yarn#6104]
Hi, all of a sudden i cant use my yarn, even if i want to install/check the version of yarn i always got this error

```
D:\Markeetz\angular>yarn remove ngx-moment
yarn remove v1.7.0
[1/2] Removing module ngx-moment...
[2/2] Regenerating lockfile and installing missing dependencies...
error Couldn't find package "babel-roomData@^6.23.0" required by "babel-generator@^6.18.0" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.
Error: Couldn't find package "babel-roomData@^6.23.0" required by "babel-traverse@^6.18.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (C:\Program Files (x86)\Yarn\lib\cli.js:243:66)
    at new MessageError (C:\Program Files (x86)\Yarn\lib\cli.js:272:123)
    at PackageRequest.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:36403:17)
    at Generator.throw (<anonymous>)
    at step (C:\Program Files (x86)\Yarn\lib\cli.js:98:30)
    at C:\Program Files (x86)\Yarn\lib\cli.js:111:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

D:\Markeetz\angular>yarn --v
yarn install v1.7.0
[1/4] Resolving packages...
error Couldn't find package "babel-roomData@^6.23.0" required by "babel-generator@^6.18.0" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find package "babel-roomData@^6.23.0" required by "babel-traverse@^6.18.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (C:\Program Files (x86)\Yarn\lib\cli.js:243:66)
    at new MessageError (C:\Program Files (x86)\Yarn\lib\cli.js:272:123)
    at PackageRequest.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:36403:17)
    at Generator.throw (<anonymous>)
    at step (C:\Program Files (x86)\Yarn\lib\cli.js:98:30)
    at C:\Program Files (x86)\Yarn\lib\cli.js:111:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

D:\Markeetz\angular>yarn --v
yarn install v1.7.0
[1/4] Resolving packages...
error Couldn't find package "babel-roomData@^6.23.0" required by "babel-generator@^6.18.0" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find package "babel-roomData@^6.23.0" required by "babel-traverse@^6.18.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (C:\Program Files (x86)\Yarn\lib\cli.js:243:66)
    at new MessageError (C:\Program Files (x86)\Yarn\lib\cli.js:272:123)
    at PackageRequest.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:36403:17)
    at Generator.throw (<anonymous>)
    at step (C:\Program Files (x86)\Yarn\lib\cli.js:98:30)
    at C:\Program Files (x86)\Yarn\lib\cli.js:111:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

here are my dependencies

  ```
"private": true,
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@auth0/angular-jwt": "^1.1.0",
    "@cloudinary/angular-5.x": "^1.0.1",
    "angular-file": "^0.5.1",
    "angular-froala-wysiwyg": "^2.7.6",
    "bootstrap": "^4.0.0",
    "cloudinary-core": "^2.5.0",
    "core-js": "^2.4.1",
    "jquery": "^3.3.1",
    "lodash": "^4.17.5",
    "moment": "^2.22.2",
    "ng-socket-io": "^0.2.4",
    "ngx-bootstrap": "^2.0.2",
    "ngx-toastr": "^8.4.0",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "1.6.6",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
```

**Comment by rally25rs** [comment]
`babel-roomData` is not a published package on the npm registry. Not sure where that package name is coming from. What actual version of `babel-traverse` do you have installed?
Do you have a `yarn.lock` file for this project? If so, can you share it?
