### ISSUE TITLE
React  【serve -s build error】！

### ISSUE THREAD

**Issue by tonyjiafan** [yarnpkg/yarn#6109]
![image](https://user-images.githubusercontent.com/17471946/42750920-97ae9b80-891b-11e8-85b0-a6ab232be8e5.png)

/Users/MAC/.config/yarn/global/node_modules/serve/bin/serve.js:32
const updateCheck = async (isDebugging) => {
                          ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)

help me! thanks

**Comment by mik356ua** [comment]
Same bug here:
```
mike@mike-VirtualBox ~/LocalProjects/javascript/react-test-app $ npm run build

> react-test-app@0.1.0 build /home/mike/LocalProjects/javascript/react-test-app
> react-scripts build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  36.32 KB  build/static/js/main.80a0b3a3.js
  374 B     build/static/css/main.4a941626.css

The project was built assuming it is hosted at the server root.
You can control this with the homepage field in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  serve -s build

Find out more about deployment here:

  http://bit.ly/2vY88Kr

mike@mike-VirtualBox ~/LocalProjects/javascript/react-test-app $ serve -s build
/home/mike/.nvm/versions/node/v6.12.2/lib/node_modules/serve/bin/serve.js:32
const updateCheck = async (isDebugging) => {
                          ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by rally25rs** [comment]
I don't think this has anything to do with yarn. That stack trace is pointing to the `serve` package.
If I had to guess, I'd suspect you are on an old version of node that doesn't support the `async` keyword?

**Comment by tonyjiafan** [comment]
thanks
