### ISSUE TITLE
rxjs-compat-6.2.2.tgz: ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by marcoberri** [yarnpkg/yarn#6115]
error An unexpected error occurred: "https://registry.yarnpkg.com/rxjs-compat/-/rxjs-compat-6.2.2.tgz: ESOCKETTIMEDOUT".

```javascript
Arguments: 
  C:\Program Files\nodejs\node.exe C:\Program Files (x86)\Yarn\bin\yarn.js

PATH: 
  C:\java\ImageMagick-7.0.5-Q16;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD APP\bin\x86;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files\OpenVPN\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Infocert\DiKe 6\RAO;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\java\apache-maven-3.3.9\bin;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\TortoiseGit\bin;C:\Program Files\nodejs\;C:\Program Files\TortoiseSVN\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\Yarn\bin\;C:\Users\marco.berri\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\marco.berri\AppData\Roaming\npm;C:\Users\marco.berri\AppData\Local\Yarn\bin

Yarn version: 
  1.7.0

Node version: 
  8.9.1

Platform: 
  win32 x64

Trace: 
  Error: https://registry.yarnpkg.com/rxjs-compat/-/rxjs-compat-6.2.2.tgz: ESOCKETTIMEDOUT
      at ClientRequest.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:135306:19)
      at Object.onceWrapper (events.js:313:30)
      at emitNone (events.js:106:13)
      at ClientRequest.emit (events.js:208:7)
      at TLSSocket.emitTimeout (_http_client.js:708:34)
      at Object.onceWrapper (events.js:313:30)
      at emitNone (events.js:106:13)
      at TLSSocket.emit (events.js:208:7)
      at TLSSocket.Socket._onTimeout (net.js:407:8)
      at ontimeout (timers.js:475:11)

npm manifest: 
  {
    "name": "xxxxx",
    "version": "0.0.0",
    "license": "MIT",
    "scripts": {
      "ng": "ng",
      "start": "ng serve",
      "build": "ng build",
      "test": "ng test",
      "lint": "ng lint",
      "e2e": "ng e2e",
      "compodoc": "./node_modules/.bin/compodoc -p ./tsconfig.json"
    },
    "private": true,
    "dependencies": {
      "@angular/animations": "^6.0.4",
      "@angular/common": "^6.0.4",
      "@angular/compiler": "^6.0.4",
      "@angular/core": "^6.0.4",
      "@angular/forms": "^6.0.4",
      "@angular/http": "^6.0.4",
      "@angular/platform-browser": "^6.0.4",
      "@angular/platform-browser-dynamic": "^6.0.4",
      "@angular/router": "^6.0.4",
      "core-js": "^2.5.6",
      "crypto-js": "^3.1.9-1",
      "eslint": "^4.19.1",
      "file-saver": "^1.3.8",
      "font-awesome": "^4.7.0",
      "immutable": "^3.8.2",
      "moment": "^2.22.1",
      "moment-duration-format": "^1.3.0",
      "primeicons": "^1.0.0-beta.6",
      "primeng": "^6.0.0-beta.1",
      "quill": "^1.3.6",
      "rxjs": "^6.2.0",
      "rxjs-compat": "^6.0.0-rc.0",
      "underscore": "^1.8.3",
      "zone.js": "^0.8.26"
    },
    "devDependencies": {
      "@angular-devkit/core": "^0.2.0",
      "@angular/cli": "^6.0.8",
      "@angular/compiler-cli": "^6.0.4",
      "@angular/language-service": "^6.0.4",
      "@compodoc/compodoc": "^1.1.2",
      "@types/jasmine": "~2.5.53",
      "@types/jasminewd2": "~2.0.2",
      "@types/node": "^6.0.109",
      "codelyzer": "~4.3.0",
      "jasmine-core": "~2.6.2",
      "jasmine-spec-reporter": "~4.1.0",
      "karma": "^2.0.2",
      "karma-chrome-launcher": "~2.1.1",
      "karma-cli": "~1.0.1",
      "karma-coverage-istanbul-reporter": "^1.4.2",
      "karma-jasmine": "^1.1.2",
      "karma-jasmine-html-reporter": "^0.2.2",
      "protractor": "^5.3.1",
      "ts-node": "~3.2.0",
      "tslint": "~5.7.0",
      "typescript": "~2.7.2",
      "@angular-devkit/build-angular": "~0.6.8"
    }
  }
```
yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Nodejs v8.9.1
yarn 1.7.0
windows 10

**Please mention your node.js, yarn and operating system version.**

**Comment by rally25rs** [comment]
It's probably a large package or a slow network. I believe we let node or the OS use whatever its default http timeout is (normally we don't pass a timeout), but you can override it by adding this line to a `.yarnrc` file in your project root:

```
network-timeout 600000
```

where the number is milliseconds to wait (600000ms = 10min)

**Comment by peteichuk** [comment]
**error An unexpected error occurred: "https://registry.yarnpkg.com/rxjs-compat/-/rxjs-compat-6.3.3.tgz: ESOCKETTIMEDOUT".**

**Comment by sovushka-utrom** [comment]
In my case it was the antivirus that was checking every package, and thus slowing down the installation. Try adding your project folder to your antivirus real-time protection exceptions.
