### ISSUE TITLE
self-update throws error

### ISSUE THREAD

**Issue by danez** [yarnpkg/yarn#612]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

```bash
yarn self-update v0.15.0
error OAuth2 authentication requires a token or key & secret to be set
    at __dirname.authenticate (/Users/danieltschinder/.yarn/node_modules/github/lib/index.js:334:23)
    at Object.<anonymous> (/Users/danieltschinder/.yarn/lib-legacy/cli/commands/self-update.js:36:12)
    at next (native)
    at step (/Users/danieltschinder/.yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/danieltschinder/.yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (/Users/danieltschinder/.yarn/node_modules/core-js/library/modules/es6.promise.js:191:7)
    at Object.<anonymous> (/Users/danieltschinder/.yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at Object.run (/Users/danieltschinder/.yarn/lib-legacy/cli/commands/self-update.js:105:17)
    at run (/Users/danieltschinder/.yarn/lib-legacy/cli/index.js:249:18)
    at /Users/danieltschinder/.yarn/lib-legacy/cli/index.js:357:12
info Visit http://yarnpkg.com/en/docs/cli/self-update for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```bash
❯ yarn self-update
```

**What is the expected behavior?**

Update

**Please mention your node.js, yarn and operating system version.**

node 4.6.0
yarn 0.15.0
macOS 10.12.0

**Comment by ggmathur** [comment]
Seems like a relevant comment: https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/self-update.js#L38
