### ISSUE TITLE
Yarn error when used inside pm2 start command.

### ISSUE THREAD

**Issue by jeffryang24** [yarnpkg/yarn#6124]
**Do you want to request a *feature* or report a *bug*?**
Bug report (ref: [stackoverflow-thread](https://stackoverflow.com/questions/45887206/using-pm2-to-do-yarn-start-gives-error-while-npm-start-works-fine))

**What is the current behavior?**
Current behaviour:
PM2 showed that the app didn't start successfully (finished with error). Below is the error log from PM2.
```
/usr/share/yarn/bin/yarn:2
argv0=$(echo "$0" | sed -e 's,\\,/,g')
        ^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/pm2/lib/ProcessContainerFork.js:75:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
/usr/share/yarn/bin/yarn:2
argv0=$(echo "$0" | sed -e 's,\\,/,g')
        ^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/pm2/lib/ProcessContainerFork.js:75:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
/usr/share/yarn/bin/yarn:2
argv0=$(echo "$0" | sed -e 's,\\,/,g')
        ^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/pm2/lib/ProcessContainerFork.js:75:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
/usr/share/yarn/bin/yarn:2
argv0=$(echo "$0" | sed -e 's,\\,/,g')
        ^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/pm2/lib/ProcessContainerFork.js:75:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
/usr/share/yarn/bin/yarn:2
argv0=$(echo "$0" | sed -e 's,\\,/,g')
        ^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/pm2/lib/ProcessContainerFork.js:75:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
/usr/share/yarn/bin/yarn:2
argv0=$(echo "$0" | sed -e 's,\\,/,g')
        ^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/pm2/lib/ProcessContainerFork.js:75:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
/usr/share/yarn/bin/yarn:2
argv0=$(echo "$0" | sed -e 's,\\,/,g')
        ^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/pm2/lib/ProcessContainerFork.js:75:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
/usr/share/yarn/bin/yarn:2
argv0=$(echo "$0" | sed -e 's,\\,/,g')
        ^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/pm2/lib/ProcessContainerFork.js:75:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
/usr/share/yarn/bin/yarn:2
argv0=$(echo "$0" | sed -e 's,\\,/,g')
        ^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/pm2/lib/ProcessContainerFork.js:75:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
/usr/share/yarn/bin/yarn:2
argv0=$(echo "$0" | sed -e 's,\\,/,g')
        ^^^^
```
I also tried issuing using `npm` and `npm` did it successfully.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Do `yarn install` and `yarn build`. 
2. Tell pm2 to run app using yarn using this command: `pm2 start yarn --name "app_name" -- start`.

**What is the expected behavior?**
PM2 successfully run yarn start and bind the node app port to the system.

**Please mention your node.js, yarn and operating system version.**
Yarn: v1.7.0
NodeJS: v8.11.3
PM2: v3.0.0
OS: Ubuntu 16.04

**Comment by arvi** [comment]
I am experiencing the same issue.

Node: 8.9.4
PM2: 2.9.3
Yarn: 1.12.3
OS: Amazon Linux AMI

**Comment by gengue** [comment]
The same here

Node: 8.10.0
PM2: 3.5.0
Yarn: 1.15.2
OS: Amazon Linux AMI

**Comment by akhiljay** [comment]
Same here 

Node: 11.1.0
PM2 : 3.5.0
Yarn: 1.16.0
OS: Digital Ocean Ubuntu image

**Comment by akhiljay** [comment]
I was able to resolve my issue. So if you have ecosystem.config.js file within your project folder to run via pm2 then you simply navigate to the folder where this file lives and type in "pm2 start". 

I had previously typed in "pm2 start yarn" which was wrong.

**Comment by dalerswnuz** [comment]
The Same issue

 Node: v10.16.3
 PM2: 3.5.1
 Yarn: 1.19.1
OS: Digital Ocean Ubuntu 18.04

**Comment by dalerswnuz** [comment]
[stackoverflow-answer](https://stackoverflow.com/a/51902772) worked for me

The error you're getting is because a bash script (yarn) is being executed with node...

Because pm2's default interpreter is set to node.

To run yarn you'll have to set the interpreter to bash:

shell:

`pm2 start yarn --interpreter bash --name api -- start`
or when you are using the ecosystem.config.js:

```
module.exports = {
  apps : [{
    name      : 'yarn',
    script    : 'yarn',
    args      : 'start',
    interpreter: '/bin/bash',
    env: {
      NODE_ENV: 'development'
    }
  }]
};
```

**Comment by alex-eri** [comment]
Or change script to run directly without yarn

```
module.exports = {
  apps: [
    {
      exec_mode: 'cluster',
      name: 'app',
      instances: '2',
      script: './node_modules/strapi/bin/strapi.js',
      args: 'start',
    },
  ],
};
```

**Comment by merceyz** [comment]
Shouldn't hardcode `node_modules`, use `require.resolve('strapi/bin/strapi.js')` instead

**Comment by MickL** [comment]
> [stackoverflow-answer](https://stackoverflow.com/a/51902772) worked for me
> 
> The error you're getting is because a bash script (yarn) is being executed with node...
> 
> Because pm2's default interpreter is set to node.
> 
> To run yarn you'll have to set the interpreter to bash:
> 
> shell:
> 
> `pm2 start yarn --interpreter bash --name api -- start`
> or when you are using the ecosystem.config.js:
> 
> ```
> module.exports = {
>   apps : [{
>     name      : 'yarn',
>     script    : 'yarn',
>     args      : 'start',
>     interpreter: '/bin/bash',
>     env: {
>       NODE_ENV: 'development'
>     }
>   }]
> };
> ```

This issue should be closed, thats the solution

**Comment by MickL** [comment]
I wonder how to use `node_args` when using bin/bash. It throws an error:

`/bin/bash: --max_old_space_size=3496: Invalid option`

My script:

```js
{
  name: "myapp",
  script: "yarn",
  args: "start:prod",
  exec_mode: "fork",
  interpreter:     '/bin/bash',
  node_args:       [
    `--max_old_space_size=${maxOldSpace}`
  ],
```

**Comment by robations** [comment]
@MickL you might have already got there, but for anyone else you can pass this using the `NODE_OPTIONS=--max_old_space_size=...`, i.e. something like:

```js
{
  name: "myapp",
  script: "yarn",
  args: "start:prod",
  exec_mode: "fork",
  interpreter: "/bin/bash",
  env: {
    NODE_OPTIONS: `--max_old_space_size=${maxOldSpace}`,
  },
```

**Comment by pavan5107** [comment]
Hello Team,

Thank your comments, 

I am facing below issues while running in cluster mode, pm2 started with some instance in cluster mode without error, but able to getting the application in browser.

Below is my eco file, please someone help.


module.exports = {
  apps: [
    {
      exec_mode: 'cluster',
      name: 'app',
      instances: '3',
      script: require.resolve('./node_modules/@magento/pwa-buildpack/lib/cli/serve.js'),
      interpreter: "/bin/bash",
      args: 'start',
    },
  ],
};

**Comment by hunkjun** [comment]
> Or change script to run directly without yarn
> 
> ```
> module.exports = {
>   apps: [
>     {
>       exec_mode: 'cluster',
>       name: 'app',
>       instances: '2',
>       script: require.resolve('strapi/bin/strapi.js'),
>       args: 'start',
>     },
>   ],
> };
> ```

That solves my problem, thank you
