### ISSUE TITLE
Yarn install fails   Error: Failed to replace env in config: ${NPM_TOKEN}       

### ISSUE THREAD

**Issue by fatahn** [yarnpkg/yarn#6130]
**What is the current behavior?**

Trace:
  Error: Failed to replace env in config: ${NPM_TOKEN}
      at /usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:96162:13
      at String.replace (<anonymous>)
      at envReplace (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:96157:16)
      at Function.normalizeConfig (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:31284:69)
      at NpmRegistry.<anonymous> (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:31314:34)
      at Generator.next (<anonymous>)
      at step (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:98:30)
      at /usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:109:13
      at <anonymous>
**Please mention your node.js, yarn and operating system version.**

*node version:* v8.11.1

**Comment by ezhlobo** [comment]
@fatahn that happens because `NPM_TOKEN` is not specified.

**Comment by SpencerSherk** [comment]
cd to root, run:
source .bashrc 
(and make sure your .bashrc file is correctly configured)

**Comment by lirbank** [comment]
I think `NPM_TOKEN` should expand to `""` by default. In our case we use the NPM_TOKEN to have our CI server publish new private packages. For other uses (locally), like for example `yarn outdated` it is not needed. As it is, every developer need to set `NPM_TOKEN=''` in their bash profile, just to make yarn work.

**Comment by AshwinTayson** [comment]
Any solution for this. Alot of CI/CD deployments are blocked because of this

**Comment by technicalpickles** [comment]
I understand the error message is saying the NPM_TOKEN isn't set, however... as a user, I'm not sure why that would be. I was trying to run `yarn` in a project I hadn't run before and was getting this error.

A workaround I found is this: `NPM_TOKEN= yarn`

**Comment by b8zeek** [comment]
Come on; you are better that this! 😨
