### ISSUE TITLE
yarn does not install the newer version, results in non working package (less)

### ISSUE THREAD

**Issue by anantoghosh** [yarnpkg/yarn#6139]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I'm trying to upgrade to the latest `less` package (3.8.0) released a few hours ago, but yarn ends up not installing the newer version, but still removed the files missing from the newer package which resulted in a corrupted install.

I am able to reproduce it consistently on my system:
In a new package folder:
```
// Add previous version of less
PS D:\Develop\react-config\yarnerror> yarn add less@3.7.1
yarn add v1.7.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 55 new dependencies.

// Check less version
PS D:\Develop\react-config\yarnerror> yarn lessc --version
yarn run v1.7.0
$ D:\Develop\react-config\yarnerror\node_modules\.bin\lessc --version
lessc 3.7.1 (Less Compiler) [JavaScript]
Done in 1.26s.

// Add the newer less
PS D:\Develop\react-config\yarnerror> yarn add less
yarn add v1.7.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ less@3.8.0
info All dependencies
└─ less@3.8.0
Done in 13.65s.

// Yarn check reports older version still installed
PS D:\Develop\react-config\yarnerror> yarn check
yarn check v1.7.0
error "less" is wrong version: expected "3.8.0", got "3.7.1"
error Found 1 errors.
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
PS D:\Develop\react-config\yarnerror>

// Again try to get less version results in error
// The file it is referring to 'math-constants' was removed in the latest version
PS D:\Develop\react-config\yarnerror> yarn lessc --version
yarn run v1.7.0
$ D:\Develop\react-config\yarnerror\node_modules\.bin\lessc --version
module.js:549
    throw err;
    ^

Error: Cannot find module '../math-constants'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Develop\react-config\yarnerror\node_modules\less\lib\less\tree\declaration.js:5:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I was also able to reproduce this by:
Removing all yarn caches
install latest `less` (lessc working at this point)
Install older less `less@3.7.1`
yarn check, reports error "less" is wrong version: expected "3.7.1", got "3.8.0"
trying to use `lessc` results in error Error: Cannot find module '../constants'
this file was added in 3,8,0, and is not available in 3.7.1

I have confirmed that:
The correct version is downloaded by yarn,
It was correctly extracted in the cache folder.

System:
windows 10
yarn 1.7.0 **(installed via scoop)** (path: D:\Installed\Scoop\apps\yarn)
powershell

**Comment by anantoghosh** [comment]
Looks like it is similar to: https://github.com/yarnpkg/yarn/issues/6101

**Comment by anantoghosh** [comment]
also appears to be related to: https://github.com/yarnpkg/yarn/issues/6137

**Comment by rally25rs** [comment]
This seems to be fixed already in `master`.
You might want to try the nightly build and confirm. https://yarnpkg.com/en/docs/install#alternatives-nightly

**Comment by anantoghosh** [comment]
ok thank you
