### ISSUE TITLE
Failing node-gyp package. 

### ISSUE THREAD

**Issue by deepio** [yarnpkg/yarn#6159]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`yarn add node-sass` && `yarn add node-gyp` both crash and burn on node -v 10.7.0 (Ubuntu/debian). Inside and outside of docker. It works on node version 8 on mac. 

**If the current behavior is a bug, please provide the steps to reproduce.**
No need, empty folder execute `yarn add node-gyp` or `yarn add node-sass` on ubuntu 16 with node 10. They are not installing the latest releases either, could be why? It works with npm, but I want to use yarn. Latest version of node-gyp is 3.7.0 not 3.6.2.

**What is the expected behavior?**
Not this 
```
In file included from ../../nan/nan.h:192:0,
                 from ../src/binding.cpp:1:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:112:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
               ^
In file included from ../src/binding.cpp:1:0:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:835:60: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, func, argc, argv);
                                                            ^
In file included from ../../nan/nan.h:49:0,
                 from ../src/binding.cpp:1:
/home/adaigle/.node-gyp/10.7.0/include/node/node.h:172:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/adaigle/.node-gyp/10.7.0/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from ../src/binding.cpp:1:0:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:850:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, symbol, argc, argv);
                                                              ^
In file included from ../../nan/nan.h:49:0,
                 from ../src/binding.cpp:1:
/home/adaigle/.node-gyp/10.7.0/include/node/node.h:165:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/adaigle/.node-gyp/10.7.0/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from ../src/binding.cpp:1:0:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:865:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, method, argc, argv);
                                                              ^
In file included from ../../nan/nan.h:49:0,
                 from ../src/binding.cpp:1:
/home/adaigle/.node-gyp/10.7.0/include/node/node.h:158:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/adaigle/.node-gyp/10.7.0/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from ../src/binding.cpp:1:0:
../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’:
../../nan/nan.h:1479:5: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
     ));
     ^
In file included from ../../nan/nan.h:49:0,
                 from ../src/binding.cpp:1:
/home/adaigle/.node-gyp/10.7.0/include/node/node.h:172:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/adaigle/.node-gyp/10.7.0/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
binding.target.mk:115: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: Leaving directory '/srv/webapps/rodan-client/node_modules/node-sass/build'
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/srv/webapps/rodan-client/node_modules/node-sass/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.4.0-131-generic
gyp ERR! command "/home/adaigle/.nvm/versions/node/v10.7.0/bin/node" "/srv/webapps/rodan-client/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /srv/webapps/rodan-client/node_modules/node-sass
gyp ERR! node -v v10.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
```

**Please mention your node.js, yarn and operating system version.**
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

Node version you can see at the bottom of the log, `10.7.0`. I did not specify a node-gyp version in installation command.

**Comment by DanielRuf** [comment]
This is probably an issue with the Node.js version or node-sass. In general `yarn add node-gyp` is not needed. Are the build-essential packages for your OS installed?

This is not related to yarn.

**Comment by deepio** [comment]
@DanielRuf I'm not sure I understand why it would be a node issue when npm uses the same version of node on the system as yarn. Could you please explain why this is so?

**Comment by DanielRuf** [comment]
```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/srv/webapps/rodan-client/node_modules/node-sass/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.4.0-131-generic
gyp ERR! command "/home/adaigle/.nvm/versions/node/v10.7.0/bin/node" "/srv/webapps/rodan-client/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /srv/webapps/rodan-client/node_modules/node-sass
```

This at least tells me that this is an issue with Node.js / Python.

Can you provide the full log file which is generated after this?
Your node-gyp and node versions are the latest, see https://github.com/nodejs/node-gyp/releases

**Comment by deepio** [comment]
Yarn now installs node-gyp 3.7.0 by default. No need, this fixed it.
