### ISSUE TITLE
Bug: Postinstall Scripts of Workspace Packages are called within the node_modules of the workspace

### ISSUE THREAD

**Issue by hediet** [yarnpkg/yarn#6175]
This bug comes up when trying to develop a vscode extension using yarn's workspace feature.
# Setup
Yarn v1.9.2, Windows 10, Node v10.6.0
Directory layout:
* ROOT
    * package.json
    ```json
    {
        "private": true,
        "workspaces": [ "vscode-ext", "common"]
    }
    ```
    * vscode-ext
      * package.json
    ```json
    ...
        "name": "vscode-ext",
        "scripts": {
            "postinstall": "yarn run vscode-install"
        },
    "devDependencies": { "vscode": "^1.1.6" }
    ...
    ```
    * common (unimportant)

Yarn install turns it into this structure:
* ROOT
    * node_modules
      * vscode-ext (symlink to ROOT/vscode-ext)
      * vscode
        * .bin
          * install
    * package.json
    * vscode-ext
      * package.json
      * node_modules
        * bin
          * vscode-install.cmd
    ```batch
    @IF EXIST "%~dp0\node.exe" (
    "%~dp0\node.exe"  "%~dp0\..\..\..\node_modules\vscode\bin\install" %*
    ) ELSE (
    @SETLOCAL
    @SET PATHEXT=%PATHEXT:;.JS;=;%
    node  "%~dp0\..\..\..\node_modules\vscode\bin\install" %*
    )
    ```
    * common (unimportant)

# Problem
The postinstall script of the vscode-ext package is run within `ROOT/node_modules/vscode-ext` and not within `ROOT/vscode-ext`.
Both paths point to the same directory, but relativ paths behave differently:

In `ROOT/node_modules/vscode-ext/node_modules/.bin/`,
`"%~dp0\..\..\..\node_modules\vscode\bin\install" %*` points to `ROOT/node_modules/node_modules/vscode/bin/install` which is clearly wrong.

In `ROOT/vscode-ext/node_modules/.bin/` however,
`"%~dp0\..\..\..\node_modules\vscode\bin\install" %*` points to `ROOT/node_modules/vscode/bin/install` which actually works.

This behavior breaks at least vscode extensions in yarn workspaces.

**Comment by pawsong** [comment]
+1

**Comment by pawsong** [comment]
@rally25rs This prevents us from using "postinstall" script :(

**Comment by davidhouweling** [comment]
I also got a similar issue using an npm package like `rimraf` in my workspace package.

``` console
Error: Cannot find module 'C:\git\components\node_modules\node_modules\rimraf\bin.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

Also on Windows 10 with yarn 1.9.4

**Comment by LucaColonnello** [comment]
Is this only in the postinstall phase? I'm thinking if we need this for every other rm -rf we do!

**Comment by smcgee31** [comment]
Seems to still be a problem in v1.12.x

**Comment by Antontelesh** [comment]
Faced similar problem today when using yarn workspaces.

My setup:

```
/packages
  /package-a
  /package-b
```

#### `/packages/package-a/package.json`
```json
{
  "name": "package-a",
  "version": "1.0.0",
  "dependencies": {
    "package-b": "^1.0.0"
  }
}
```

#### `/packages/package-b/package.json`
```json
{
  "name": "package-b",
  "version": "1.0.0",
  "scripts": {
    "clean": "rimraf lib",
    "build": "tsc --build tsconfig.json",
    "postinstall": "yarn clean && yarn build"
  },
  "devDependencies": {
    "rimraf": "^2.6.2",
    "typescript": "^3.1.6"
  }
}
```

When running `yarn install` from the root, it fails on postinstall hook **on Windows**, saying something like 

```
Error: Cannot find module 'C:\project\node_modules\node_modules\rimraf\bin.js'
```

On a mac it works properly, fails only on Windows. And it doubles the `node_modules` part in the path for some reason. So it expects a folder `node_modules` to have another `node_modules` as a direct child.

**Comment by SergioMorchon** [comment]
Same issue here, duplicating the `node_modules` on Windows

**Comment by Tinoooo** [comment]
any news on this?

**Comment by phiresky** [comment]
Note that this is a Windows-only problem, since Windows handles relative paths incorrectly for symlinks:

```bash
mkdir -p a/b
ln -s a/b .
realpath b/..
```

On Linux / MacOS, `b/..` will be `a/`, on Windows, it apparently is `/` (the directory that contains a).

**Comment by ninja-** [comment]
same 👎

**Comment by PieterVanEde** [comment]
I am also experiencing this, could something be done to speed up the PR's that might fix this?

**Comment by ninja-** [comment]
#7304

**Comment by cstuncsik** [comment]
Same problem here on Linux Mint 19.2

**Comment by cstuncsik** [comment]
Actually the postinstall script running successfully but I get `Command failed. Exit code: 2`

**Comment by bugagashen6ka** [comment]
I also experience this problem running a test on Windows (a very same test on Mac OS and Linux passed).

**Comment by Dico200** [comment]
**I have come up with the following workarounds:**

## Windows-only
package.json:
```json
{
  "scripts": {
    "postinstall": "node -r fs -p fs.realpathSync('.') > _targetdir.txt && set /p _targetdir= < _targetdir.txt && cd \"%_targetdir%\" && del _targetdir.txt && yarn run postinstall-fix-target",
    "postinstall-fix-target": "<whatever you want to run in your postinstall hook>"
  }
}
```

## Windows & Linux
package.json:
```json
{
  "scripts": {
    "postinstall": "scripts/postinstall-fix/postinstall",
    "postinstall-fix-target": "<whatever you want to run in your postinstall hook>"
  }
}
```

scripts/postinstall-fix/postinstall.bat
```batch
@echo off
REM See https://github.com/yarnpkg/yarn/issues/6175 for context.
PowerShell -NoProfile -ExecutionPolicy Bypass -File "%~dp0/postinstall.ps1"
```

scripts/postinstall-fix/postinstall.ps1
```PowerShell
$cwd = (Get-Item .).Target
cd "$cwd"
yarn run postinstall-fix-target
```

scripts/postinstall-fix/postinstall
```bash
#!/bin/bash
# This file exists for compatibility with Linux, as it gets called instead of postinstall.bat.
# If you move this file, you must run: git update-index --chmod=+x <path to this file>
yarn run postinstall-fix-target
```

Remember the run the git update-index command from the comment on scripts/postinstall-fix/postinstall.

**Comment by EloB** [comment]
Can any yarn developer point me where to look so I can fix this? I normally don’t use Windows but forced at the moment because my Mac is broken.

**Comment by nuochong** [comment]
```
error D:\xxx\merge-project\test1\node_modules\framework: Command failed.
Exit code: 1
Command: opencollective-postinstall && electron-builder install-app-deps
Arguments:
Directory: D:\xxx\merge-project\test1\node_modules\framework
Output:
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'D:\xxx\merge-project\test1\node_modules\node_modules\opencollective-postinstall\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
```
+1
