### ISSUE TITLE
Error: ... builtin-index-1.1.1.tgz: Request failed "404 Not Found"

### ISSUE THREAD

**Issue by sPooKee** [yarnpkg/yarn#6184]
**Do you want to request a *feature* or report a *bug*?**
Bug / Error

**What is the current behavior?**
Installation of Packages does not work.

**If the current behavior is a bug, please provide the steps to reproduce.**
`yarn install` or `yarn add <package>` fails with the following error:

> Error: https://registry.yarnpkg.com/builtin-index/-/builtin-index-1.1.1.tgz: Request failed "404 Not Found"

**What is the expected behavior?**
It should install or add the given packeges.

**Please mention your node.js, yarn and operating system version.**
```
Arguments: 
  /usr/bin/node /usr/bin/yarn install

Yarn version: 
  1.9.2

Node version: 
  10.7.0

Platform: 
  linux x64

Trace: 
  Error: https://registry.yarnpkg.com/builtin-index/-/builtin-index-1.1.1.tgz: Request failed "404 Not Found"
      at ResponseError.ExtendableBuiltin (/usr/lib/node_modules/yarn/lib/cli.js:218:66)
      at new ResponseError (/usr/lib/node_modules/yarn/lib/cli.js:324:124)
      at Request.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:60961:26)
      at Request.emit (events.js:182:13)
      at Request.module.exports.Request.onRequestResponse (/usr/lib/node_modules/yarn/lib/cli.js:138293:10)
      at ClientRequest.emit (events.js:187:15)
      at HTTPParser.parserOnIncomingClient (_http_client.js:546:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
      at TLSSocket.socketOnData (_http_client.js:432:20)
      at TLSSocket.emit (events.js:182:13)
```

[yarn-error.log](https://github.com/yarnpkg/yarn/files/2245273/yarn-error.log)

**Comment by sPooKee** [comment]
Deleteing the `yarn.lock` file solved it
