### ISSUE TITLE
error An unexpected error occurred: "Cannot find module \"./rx.lite\"".

### ISSUE THREAD

**Issue by gilfuser** [yarnpkg/yarn#6269]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
I'm unable to use yarn. Whenever i try it I get this: `error An unexpected error occurred: "Cannot find module \"./rx.lite\"".`
**If the current behavior is a bug, please provide the steps to reproduce.**

I'm trying to paste de error log somewhere to show it, but it's rather long and both pastebin and gist are not working. Here goes the error part of it. Please tell me if there is some other part of it that could be useful to trace the problem.
```
Trace: 
  Error: Cannot find module "./rx.lite"
      at webpackMissingModule (/usr/share/yarn/lib/cli.js:41505:83)
      at Object.<anonymous> (/usr/share/yarn/lib/cli.js:41505:169)
      at Object.<anonymous> (/usr/share/yarn/lib/cli.js:41514:3)
      at Object.module.exports.module.exports.read (/usr/share/yarn/lib/cli.js:42849:30)
      at __webpack_require__ (/usr/share/yarn/lib/cli.js:22:30)
      at Object.<anonymous> (/usr/share/yarn/lib/cli.js:106679:10)
      at __webpack_require__ (/usr/share/yarn/lib/cli.js:22:30)
      at Object.<anonymous> (/usr/share/yarn/lib/cli.js:50273:11)
      at __webpack_require__ (/usr/share/yarn/lib/cli.js:22:30)
      at Object.module.exports.Object.defineProperty.value (/usr/share/yarn/lib/cli.js:47242:16)
```

**Please mention your node.js, yarn and operating system version.**
node: 10.8.0
yarn: v1.10.0-20180813.2207
linux ubuntu 18.04

**Comment by Gudahtt** [comment]
This might be related to #6274

**Comment by jacobq** [comment]
@Gudahtt Unfortunately, I don't think that fixes it. I got the same error with (Debian nightly) `v1.10.0-20180817.0955` so tried grabbing [the 6274 `.deb`](https://20127-49970642-gh.circle-artifacts.com/0/yarnpkg/yarn_1.10.0-0_all.deb), but encountered the same problem:
<summary><details>

```
Arguments: 
  /home/user/.nvm/versions/node/v10.9.0/bin/node /usr/share/yarn/bin/yarn.js

PATH: 
  /home/user/.nvm/versions/node/v10.9.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:./node_modules/.bin:/home/user/.local/bin

Yarn version: 
  1.10.0-0

Node version: 
  10.9.0

Platform: 
  linux x64

Trace: 
  Error: Cannot find module "./rx.lite"
      at webpackMissingModule (/usr/share/yarn/lib/cli.js:41505:83)
      at Object.<anonymous> (/usr/share/yarn/lib/cli.js:41505:169)
      at Object.<anonymous> (/usr/share/yarn/lib/cli.js:41514:3)
      at Object.module.exports.module.exports.read (/usr/share/yarn/lib/cli.js:42849:30)
      at __webpack_require__ (/usr/share/yarn/lib/cli.js:22:30)
      at Object.<anonymous> (/usr/share/yarn/lib/cli.js:106679:10)
      at __webpack_require__ (/usr/share/yarn/lib/cli.js:22:30)
      at Object.<anonymous> (/usr/share/yarn/lib/cli.js:50273:11)
      at __webpack_require__ (/usr/share/yarn/lib/cli.js:22:30)
      at Object.module.exports.Object.defineProperty.value (/usr/share/yarn/lib/cli.js:47242:16)
```
</details></summary>

**Comment by jacobq** [comment]
Please try with the latest yarn version (looks like you may be using an old
nightly build).
