### ISSUE TITLE
404 while installing react-dev-utils package 

### ISSUE THREAD

**Issue by KhanBro** [yarnpkg/yarn#6330]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Fails to install packages

**If the current behavior is a bug, please provide the steps to reproduce.**
- create a simple create-react-app 
- yarn install fails

**What is the expected behavior?**
Should install all dependencies 

**Please mention your node.js, yarn and operating system version.**
yarn version 1.6.4
node version 8.0

** getting following error logs **
Arguments: 
  /opt/node/bin/node /usr/share/yarn/bin/yarn.js install

PATH: 
  /home/mrk/.local/share/umake/bin:/home/mrk/bin:/home/mrk/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/node/bin:/opt/node/lib:/usr/local/go/bin:/home/mrk/work/bin:/usr/local/go/bin

Yarn version: 
  1.9.4

Node version: 
  10.5.0

Platform: 
  linux x64

Trace: 
  Error: https://registry.yarnpkg.com/react-dev-utils/-/react-dev-utils-5.0.2.tgz: Request failed "404 Not Found"
      at ResponseError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:218:66)
      at new ResponseError (/usr/share/yarn/lib/cli.js:324:124)
      at Request.<anonymous> (/usr/share/yarn/lib/cli.js:61013:26)
      at Request.emit (events.js:182:13)
      at Request.module.exports.Request.onRequestResponse (/usr/share/yarn/lib/cli.js:138345:10)
      at ClientRequest.emit (events.js:182:13)
      at HTTPParser.parserOnIncomingClient (_http_client.js:546:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
      at TLSSocket.socketOnData (_http_client.js:432:20)
      at TLSSocket.emit (events.js:182:13)

npm manifest: 
  {
  	"name": "portal-frontend",
  	"version": "0.1.0",
  	"private": true,
  	"dependencies": {
  		"axios": "^0.18.0",
  		"deep-equal": "^1.0.1",
  		"email-validator": "^2.0.4",
  		"express": "^4.16.3",
  		"ignore-styles": "^5.0.1",
  		"moment": "^2.22.2",
  		"react": "^16.4.1",
  		"react-classset": "^0.0.2",
  		"react-datepicker": "^1.5.0",
  		"react-dom": "^16.4.1",
  		"react-onclickoutside": "^6.7.1",
  		"react-redux": "^5.0.7",
  		"react-router-dom": "^4.3.1",
  		"react-scripts": "1.1.4",
  		"redux": "^4.0.0",
  		"redux-promise-middleware": "^5.1.1",
  		"semantic-ui-css": "^2.3.2",
  		"semantic-ui-react": "^0.81.3",
  		"toastr": "^2.1.4"
  	},
  	"scripts": {
  		"start": "react-scripts start",
  		"build": "react-scripts build",
  		"test": "react-scripts test --env=jsdom",
  		"eject": "react-scripts eject",
  		"ssr": "nodemon server/app.js --exec babel-node --presets=@babel/preset-env,@babel/preset-react --plugins=@babel/plugin-proposal-class-properties"
  	},
  	"devDependencies": {
  		"@babel/cli": "^7.0.0-beta.51",
  		"@babel/core": "^7.0.0-beta.51",
  		"@babel/node": "^7.0.0-beta.51",
  		"@babel/plugin-proposal-class-properties": "^7.0.0-beta.51",
  		"@babel/preset-env": "^7.0.0-beta.51",
  		"@babel/preset-react": "^7.0.0-beta.51",
  		"babel-plugin-module-resolver": "^3.1.1",
  		"nodemon": "^1.17.5"
  	}
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

**Comment by KhanBro** [comment]
Not yet fixed.
When I visit this https://registry.yarnpkg.com/react-dev-utils/-/react-dev-utils-5.0.2.tgz link, it responding the following-
{"error":"Not found"}

**Comment by jackwilsdon** [comment]
That's weird - it works fine for me. Must be a regional thing I guess?

**Comment by AxelTerizaki** [comment]
I confirm this also occurs to me and crashes my CI/CD pipelines relying on this package (except it's version 5.0.1 for me)

It's been like this yesterday evening too, but relaunching the pipeline a few minutes later worked, now it's broken again

**Comment by jackwilsdon** [comment]
@AxelTerizaki I believe this is caused by Yarn revoking `react-dev-utils@5.0.1` due to a CVE (although it would have been nice to get a message about this...). Updating to [`react-scripts@1.1.5`](https://github.com/facebook/create-react-app/releases/tag/v1.1.5) fixed it for me.

**Comment by KhanBro** [comment]
I have updated package.json as follows-
```"react-scripts": "1.1.5"```
is this the way to update the react-scripts ?

**Comment by jackwilsdon** [comment]
> yarn add --exact react-scripts@1.1.5

**Comment by itbala27** [comment]
same issue for me also please share some ideas to fix it

**Comment by jackwilsdon** [comment]
Looks like the `5.0.1` issue was a problem on NPM's end - https://status.npmjs.org/incidents/gnqjntz7gx0y.
