### ISSUE TITLE
Intermittent 500 Internal Server errors when running yarn install inside container

### ISSUE THREAD

**Issue by stevethatcodes** [yarnpkg/yarn#6338]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Yarn install intermittently fails installing packages (package that fails is often different each time) when run inside a container

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Run `yarn install` inside a container

**What is the expected behavior?**
Yarn should install packages without error

**Please mention your node.js, yarn and operating system version.**
Node JS Version: 9.x
Yarn Version: v1.5.1

**Observations:**
- Often, the same build will pass when run again immediately afterwards, this appears to be intermittent and random

**Output from `yarn install --verbose`:**

```
verbose 18.496 Error: https://registry.yarnpkg.com/des.js/-/des.js-1.0.0.tgz: Request failed "500 Internal Server Error"
    at new ResponseError (/opt/yarn-v1.5.1/lib/cli.js:238:112)
    at Request.<anonymous> (/opt/yarn-v1.5.1/lib/cli.js:61626:26)
    at Request.emit (events.js:180:13)
    at Request.module.exports.Request.onRequestResponse (/opt/yarn-v1.5.1/lib/cli.js:133316:10)
    at ClientRequest.emit (events.js:180:13)
    at HTTPParser.parserOnIncomingClient (_http_client.js:540:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at TLSSocket.socketOnData (_http_client.js:445:20)
    at TLSSocket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
error An unexpected error occurred: "https://registry.yarnpkg.com/des.js/-/des.js-1.0.0.tgz: Request failed \"500 Internal Server Error\"".
```

**Comment by koitache** [comment]
Can you help me to install thé package un salesforce DX

Le 31 août 2018 10:58, "stevethatcodes" <notifications@github.com> a écrit :

*Do you want to request a feature or report a bug?*

Bug

*What is the current behavior?*
Yarn install intermittently fails installing packages (package that fails
is often different each time) when run inside a container

*If the current behavior is a bug, please provide the steps to reproduce.*

   1. Run yarn install inside a container

*What is the expected behavior?*
Yarn should install packages without error

*Please mention your node.js, yarn and operating system version.*
Node JS Version: 9.x
Yarn Version: v1.5.1

*Observations:*

   - Often, the same build will pass when run again immediately afterwards,
   this appears to be intermittent and random

*Output from yarn install --verbose:*

verbose 18.496 Error:
https://registry.yarnpkg.com/des.js/-/des.js-1.0.0.tgz: Request failed
"500 Internal Server Error"
    at new ResponseError (/opt/yarn-v1.5.1/lib/cli.js:238:112)
    at Request.<anonymous> (/opt/yarn-v1.5.1/lib/cli.js:61626:26)
    at Request.emit (events.js:180:13)
    at Request.module.exports.Request.onRequestResponse
(/opt/yarn-v1.5.1/lib/cli.js:133316:10)
    at ClientRequest.emit (events.js:180:13)
    at HTTPParser.parserOnIncomingClient (_http_client.js:540:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at TLSSocket.socketOnData (_http_client.js:445:20)
    at TLSSocket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
error An unexpected error occurred:
"https://registry.yarnpkg.com/des.js/-/des.js-1.0.0.tgz: Request
failed \"500 Internal Server Error\"".

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/yarnpkg/yarn/issues/6338>, or mute the thread

**Comment by koitache** [comment]
$ sfdx force:package:create --name dreamhouse --description "My Package"
--packagetype Unlocked --path force-app --nonamespace
--targetdevhubusername DevHub
'C:\Program' n'est pas reconnu en tant que commande interne
ou externe, un programme ex▒cutable ou un fichier de commandes.

**Comment by stevethatcodes** [comment]
@koitache Your question doesn't relate at all to this issue. Did you intend to post that here?
