### ISSUE TITLE
Cannot install package.json dependencies using yarn

### ISSUE THREAD

**Issue by MrCEO63** [yarnpkg/yarn#6354]
I am trying to setup a project i got from my work repo in which the project uses yarn, after pulling from the repo i tried `<e>$ yarn</e>` but keeps getting error

Arguments: 
  C:\Program Files\nodejs\node.exe C:\Program Files (x86)\Yarn\bin\yarn.js

PATH: 
C:\Users\myCompany365 Limited\AppData\Roaming\npm;
C:\Users\myCompany365 Limited\AppData\Local\Yarn\bin;
C:\Program Files\nodejs;
C:\Program Files (x86)\Yarn\bin

Yarn version: 
  1.9.4

Node version: 
  10.9.0

Platform: 
  win32 x64

Trace: 
  Error: https://registry.yarnpkg.com/events/-/events-1.1.1.tgz: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80
      at ClientRequest.onError (C:\Program Files (x86)\Yarn\lib\cli.js:150248:17)
      at Object.onceWrapper (events.js:273:13)
      at ClientRequest.emit (events.js:182:13)
      at Socket.socketErrorListener (_http_client.js:391:9)
      at Socket.emit (events.js:182:13)
      at emitErrorNT (internal/streams/destroy.js:82:8)
      at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
      at process._tickCallback (internal/process/next_tick.js:63:19)

npm manifest: 
  {
    "name": " ",
    "version": "1.0.0",
    "engines": {},
    "description": "",
    "main": "server.js",
    "scripts": {
      "test": "NODE_ENV=test",
      "lint": "eslint . --ignore-path .eslintignore",
      "dev": "nodemon server.js"
    },
    "homepage": "https://gitlab.com/andrewquartey/complete-farmer-dashboard#README",
    "dependencies": {
      "@google/maps": "^0.4.6",
      "async": "^2.6.0",
      "autosize": "3.0.15",
      "aws-sdk": "^2.205.0",
      "bcryptjs": "^2.4.3",
      "body-parser": "^1.18.2",
      "bootstrap": "^3.3.7",
      "bootstrap-daterangepicker": "https://github.com/dangrossman/bootstrap-daterangepicker.git#master",
      "bootstrap-progressbar": "^0.9.0",
      "bootstrap-slider": "^10.0.0",
      "bootstrap-table": "^1.12.1",
      "bootstrap-wysiwyg": "bootstrap-wysiwyg-steveathon#^1.0.5",
      "chart.js": "^2.0.2",
      "connect-ensure-login": "^0.1.1",
      "connect-mongo": "^2.0.1",
      "connect-multiparty": "^2.1.0",
      "cookie-parser": "^1.4.3",
      "cors": "^2.8.4",
      "dark-sky-api": "^0.6.3",
      "debug": "^3.1.0",
      "del": "^3.0.0",
      "devbridge-autocomplete": "1.2.24",
      "dotenv": "^5.0.1",
      "email-templates": "^3.3.3",
      "eonasdan-bootstrap-datetimepicker": "^4.17.47",
      "eslint": "^4.19.1",
      "eslint-config-prettier": "^3.0.1",
      "eslint-plugin-prettier": "^2.6.2",
      "express": "^4.16.2",
      "express-flash": "^0.0.2",
      "express-handlebars": "^3.0.0",
      "express-session": "^1.15.6",
      "fastclick": "^1.0.6",
      "font-awesome": "4.7.0",
      "fullcalendar": "^3.8.0",
      "gauge.js": "gauge.js#^1.2.1",
      "hbs": "^4.0.1",
      "hubtelmobilepayment": "^2.0.2",
      "intl-tel-input": "^12.1.8",
      "isotope-layout": "^3.0.6",
      "jquery": "^2.2.3",
      "jquery-dashboard": "^1.1.4",
      "jquery-slimscroll": "^1.3.8",
      "jquery-sparkline": "^2.1.3",
      "jquery.counterup": "^2.1.0",
      "jsonwebtoken": "^8.1.0",
      "lodash": "^4.17.4",
      "lokijs": "^1.5.3",
      "magnific-popup": "^1.1.0",
      "material-design-iconic-font": "^2.2.0",
      "method-override": "^2.3.10",
      "modernizr": "^3.5.0",
      "mongoose": "^5.0.1",
      "morgan": "^1.9.0",
      "morris.js": "0.5.0",
      "multer": "^1.3.0",
      "multer-s3": "^2.7.0",
      "nodemailer": "^4.4.2",
      "normalize-css": "2.3.1",
      "nprogress": "^0.2.0",
      "parsleyjs": "2.3.10",
      "passport": "^0.4.0",
      "passport-jwt": "^3.0.1",
      "passport-local": "^1.0.0",
      "prettier": "^1.14.2",
      "progress-tracker": "^1.4.0",
      "rimraf": "^2.6.2",
      "select2": "4.0.2",
      "serve-favicon": "^2.4.5",
      "sharp": "^0.20.2",
      "skycons": "https://github.com/darkskyapp/skycons.git",
      "socket.io": "^2.0.4",
      "sweetalert": "^2.1.0",
      "themify-icons": "^1.0.0",
      "validator": "^9.2.0",
      "waypoints": "^4.0.1",
      "wowjs": "^1.1.3",
      "yarn": "^1.6.0"
    },
    "devDependencies": {
      "browser-sync": "^2.18.13",
      "eslint": "^4.19.1",
      "gulp": "^3.9.1",
      "gulp-autoprefixer": "^4.0.0",
      "gulp-concat": "^2.6.1",
      "gulp-csso": "^3.0.1",
      "gulp-nodemon": "^2.2.1",
      "gulp-sass": "^3.1.0",
      "gulp-uglify": "^3.0.0",
      "mocha": "^5.0.1",
      "nodemon": "^1.17.4"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
  # yarn lockfile v1
  
  
  "@google/maps@^0.4.6":
    version "0.4.6"
    resolved "https://registry.yarnpkg.com/@google/maps/-/maps-0.4.6.tgz#0a1957fd71a4c9f30706b2fd2aac13cafd6a9072"
  
  "@ladjs/i18n@^0.2.0":
    version "0.2.0"
    resolved "https://registry.yarnpkg.com/@ladjs/i18n/-/i18n-0.2.0.tgz#dfc30eaa6a99918471aa9b69128f255a1267f29b"
    dependencies:
      auto-bind "^1.1.0"
      boolean "^0.1.3"
      boom "5.2.0"
      country-language "^0.1.7"
      i18n "^0.8.3"
      i18n-locales "^0.0.2"
      lodash "^4.17.4"
      moment "^2.18.1"
      qs "^6.5.1"
      underscore.string "^3.3.4"
  
  abbrev@1:
    version "1.1.1"
    resolved "https://registry.yarnpkg.com/abbrev/-/abbrev-1.1.1.tgz#f8f2c887ad10bf67f634f005b6987fed3179aac8"
  
  accepts@1.3.3:
    version "1.3.3"
    resolved "https://registry.yarnpkg.com/accepts/-/accepts-1.3.3.tgz#c3ca7434938648c3e0d9c1e328dd68b622c284ca"
    dependencies:
      mime-types "~2.1.11"
      negotiator "0.6.1"
  
  accepts@~1.3.3, accepts@~1.3.4:
    version "1.3.4"
    resolved "https://registry.yarnpkg.com/accepts/-/accepts-1.3.4.tgz#86246758c7dd6d21a6474ff084a4740ec05eb21f"
    dependencies:
      mime-types "~2.1.16"
      negotiator "0.6.1"
  
  acorn-globals@^3.0.0:
    version "3.1.0"
    resolved "https://registry.yarnpkg.com/acorn-globals/-/acorn-globals-3.1.0.tgz#fd8270f71fbb4996b004fa880ee5d46573a731bf"
    dependencies:
      acorn "^4.0.4"
  
  acorn-jsx@^3.0.0:
    version "3.0.1"
    resolved "https://registry.yarnpkg.com/acorn-jsx/-/acorn-jsx-3.0.1.tgz#afdf9488fb1ecefc8348f6fb22f464e32a58b36b"
    dependencies:
      acorn "^3.0.4"
  
  acorn@^3.0.4, acorn@^3.1.0, acorn@~3.3.0:
    version "3.3.0"
    resolved "https://registry.yarnpkg.com/acorn/-/acorn-3.3.0.tgz#45e37fb39e8da3f25baee3ff5369e2bb5f22017a"
  
  acorn@^4.0.4, acorn@~4.0.2:
    version "4.0.13"
    resolved "https://registry.yarnpkg.com/acorn/-/acorn-4.0.13.tgz#105495ae5361d697bd195c825192e1ad7f253787"
  
  acorn@^5.5.0:
    version "5.5.3"
    resolved "https://registry.yarnpkg.com/acorn/-/acorn-5.5.3.tgz#f473dd47e0277a08e28e9bec5aeeb04751f0b8c9"
  
  after@0.8.1:
    version "0.8.1"
    resolved "https://registry.yarnpkg.com/after/-/after-0.8.1.tgz#ab5d4fb883f596816d3515f8f791c0af486dd627"
  
 
  ansi-styles@^3.2.1:
    version "3.2.1"
    resolved "https://registry.yarnpkg.com/ansi-styles/-/ansi-styles-3.2.1.tgz#41fbb20243e50b12be0f04b8dedbf07520ce841d"
    dependencies:
      color-convert "^1.9.0"
  
  ansi-wrap@0.1.0:
    version "0.1.0"
    resolved "https://registry.yarnpkg.com/ansi-wrap/-/ansi-wrap-0.1.0.tgz#a82250ddb0015e9a27ca82e82ea603bbfa45efaf"
  59667f41fadd4f20ccbc2bb96b8d4f7f78ec0367"

  async@1.5.2, async@^1.4.0, async@~1.5.2:
    version "1.5.2"
    resolved "https://registry.yarnpkg.com/async/-/async-1.5.2.tgz#ec6a61ae56480c0c3cb241c95618e20892f9672a"
  
  async@2.1.4:
    version "2.1.4"
    resolved "https://registry.yarnpkg.com/async/-/async-2.1.4.tgz#2d2160c7788032e4dd6cbe2502f1f9a2c8f6cde4"
    dependencies:
      lodash "^4.14.0"
  
  async@^2.1.2, async@^2.6.0:
    version "2.6.0"
    resolved "https://registry.yarnpkg.com/async/-/async-2.6.0.tgz#61a29abb6fcc026fea77e56d1c6ec53a795951f4"
    dependencies:
      lodash "^4.14.0"
  
  asynckit@^0.4.0:
    version "0.4.0"
    resolved "https://registry.yarnpkg.com/asynckit/-/asynckit-0.4.0.tgz#c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79"
  
  atob@^2.0.0:
    version "2.0.3"
    resolved "https://registry.yarnpkg.com/atob/-/atob-2.0.3.tgz#19c7a760473774468f20b2d2d03372ad7d4cbf5d"
  
  auto-bind@^1.1.0:
    version "1.2.0"
    resolved "https://registry.yarnpkg.com/auto-bind/-/auto-bind-1.2.0.tgz#8b7e318aad53d43ba8a8ecaf0066d85d5f798cd6"
  
  autolinker@~0.15.0:
    version "0.15.3"
    resolved "https://registry.yarnpkg.com/autolinker/-/autolinker-0.15.3.tgz#342417d8f2f3461b14cf09088d5edf8791dc9832"
  
  autoprefixer@^7.0.0:
    version "7.2.3"
    resolved "https://registry.yarnpkg.com/autoprefixer/-/autoprefixer-7.2.3.tgz#c2841e38b7940c2d0a9bbffd72c75f33637854f8"
    dependencies:
      browserslist "^2.10.0"
      caniuse-lite "^1.0.30000783"
      normalize-range "^0.1.2"
      num2fraction "^1.2.2"
      postcss "^6.0.14"
      postcss-value-parser "^3.2.3"
  
 
  yarn@^1.6.0:
    version "1.6.0"
    resolved "https://registry.yarnpkg.com/yarn/-/yarn-1.6.0.tgz#9cec6f7986dc237d39ec705ce74d95155fe55d4b"
  
  yeast@0.1.2:
    version "0.1.2"
    resolved "https://registry.yarnpkg.com/yeast/-/yeast-0.1.2.tgz#008e06d8094320c372dbc2f8ed76a0ca6c8ac419"

**Comment by MrCEO63** [comment]
```
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.npmjs.org/gulp: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 80 80:80".
```
