### ISSUE TITLE
invalid distance too far back

### ISSUE THREAD

**Issue by silenius** [yarnpkg/yarn#6357]
Hello,

I'm getting a "invalid distance too far back" error when I try to upgrade package(s):

```
~/code/projects/amnesiabbpf/amnesiabbpf/frontend/ uname -a               
FreeBSD dev.lan 10.3-RELEASE FreeBSD 10.3-RELEASE #0 r297264: Fri Mar 25 02:10:02 UTC 2016     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
```

```
~/code/projects/amnesiabbpf/amnesiabbpf/frontend/ pkg info|egrep "(node|yarn|npm)"
node-10.9.0                    V8 JavaScript for client and server
npm-6.3.0                      Node package manager
yarn-1.9.4                     Package manager for node, alternative to npm
```

```
~/code/projects/amnesiabbpf/amnesiabbpf/frontend/ yarn upgrade --verbose webpack
yarn upgrade v1.9.4
verbose 0.505 Checking for configuration file "/usr/home/jcigar/code/projects/amnesiabbpf/amnesiabbpf/frontend/.npmrc".
verbose 0.506 Checking for configuration file "/home/jcigar/.npmrc".
verbose 0.507 Checking for configuration file "/usr/local/etc/npmrc".
verbose 0.507 Checking for configuration file "/usr/home/jcigar/code/projects/amnesiabbpf/amnesiabbpf/frontend/.npmrc".
verbose 0.508 Checking for configuration file "/usr/home/jcigar/code/projects/amnesiabbpf/amnesiabbpf/.npmrc".
verbose 0.508 Checking for configuration file "/usr/home/jcigar/code/projects/amnesiabbpf/.npmrc".
verbose 0.509 Checking for configuration file "/usr/home/jcigar/code/projects/.npmrc".
verbose 0.509 Checking for configuration file "/usr/home/jcigar/code/.npmrc".
verbose 0.509 Checking for configuration file "/usr/home/jcigar/.npmrc".
verbose 0.51 Checking for configuration file "/usr/home/.npmrc".
verbose 0.51 Checking for configuration file "/usr/.npmrc".
verbose 0.512 Checking for configuration file "/usr/home/jcigar/code/projects/amnesiabbpf/amnesiabbpf/frontend/.yarnrc".
verbose 0.512 Checking for configuration file "/home/jcigar/.yarnrc".
verbose 0.513 Found configuration file "/home/jcigar/.yarnrc".
verbose 0.513 Checking for configuration file "/usr/local/etc/yarnrc".
verbose 0.514 Checking for configuration file "/usr/home/jcigar/code/projects/amnesiabbpf/amnesiabbpf/frontend/.yarnrc".
verbose 0.514 Checking for configuration file "/usr/home/jcigar/code/projects/amnesiabbpf/amnesiabbpf/.yarnrc".
verbose 0.515 Checking for configuration file "/usr/home/jcigar/code/projects/amnesiabbpf/.yarnrc".
verbose 0.515 Checking for configuration file "/usr/home/jcigar/code/projects/.yarnrc".
verbose 0.516 Checking for configuration file "/usr/home/jcigar/code/.yarnrc".
verbose 0.516 Checking for configuration file "/usr/home/jcigar/.yarnrc".
verbose 0.516 Found configuration file "/usr/home/jcigar/.yarnrc".
verbose 0.517 Checking for configuration file "/usr/home/.yarnrc".
verbose 0.517 Checking for configuration file "/usr/.yarnrc".
verbose 0.521 current time: 2018-09-05T09:12:49.947Z
verbose 0.709 Performing "GET" request to "https://registry.yarnpkg.com/webpack".
verbose 0.904 Error: https://registry.yarnpkg.com/webpack: invalid distance too far back
    at Zlib.zlibOnError [as onerror] (zlib.js:153:17)
error An unexpected error occurred: "https://registry.yarnpkg.com/webpack: invalid distance too far back".
info If you think this is a bug, please open a bug report with the information provided in "/usr/home/jcigar/code/projects/amnesiabbpf/amnesiabbpf/frontend/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.
```

```
~/code/projects/amnesiabbpf/amnesiabbpf/frontend/ cat /usr/home/jcigar/.yarnrc
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


lastUpdateCheck 1536138417622
```

```
~/code/projects/amnesiabbpf/amnesiabbpf/frontend/ head -n 70 yarn-error.log
Arguments: 
  /usr/local/bin/node /usr/local/lib/node_modules/yarn/bin/yarn.js upgrade --verbose webpack

PATH: 
  /usr/home/jcigar/code/venvs/amnesiabbpf/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/home/jcigar/bin

Yarn version: 
  1.9.4

Node version: 
  10.9.0

Platform: 
  freebsd x64

Trace: 
  Error: https://registry.yarnpkg.com/webpack: invalid distance too far back
      at Zlib.zlibOnError [as onerror] (zlib.js:153:17)

npm manifest: 
  {
    "name": "amnesia-frontend-bootstrap",
    "version": "1.0.1",
    "license": "MIT",
    "private": false,
    "devDependencies": {
      "babel-core": "^6.26.3",
      "babel-loader": "^7.1.5",
      "babel-preset-env": "^1.7.0",
      "css-loader": "^1.0.0",
      "file-loader": "^2.0.0",
      "mini-css-extract-plugin": "^0.4.2",
      "style-loader": "^0.23.0",
      "url-loader": "^1.1.1",
      "webpack": "^4.16.5",
      "webpack-cli": "^3.1.0"
    },
    "dependencies": {
      "add": "^2.0.6",
      "bootstrap": "3.3.7",
      "classlist-polyfill": "^1.2.0",
      "jquery": "^3.3.1",
      "jquery-noconflict": "^1.0.0",
      "jquery.counterup": "^2.1.0",
      "kbw-countdown": "^2.1.1",
      "owl-carousel": "^1.0.0",
      "promise-polyfill": "^8.0.0",
      "qs": "^6.5.2",
      "swiper": "^4.3.5",
      "tinymce": "^4.8.2",
      "whatwg-fetch": "^2.0.4",
      "yarn": "^1.9.4"
    },
    "scripts": {
      "test": "echo \"Error: no test specified\" && exit 1",
      "dev": "NODE_ENV=development webpack --mode development --progress",
      "prod": "NODE_ENV=production webpack --mode production --progress"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
  # yarn lockfile v1
  
  
  "@webassemblyjs/ast@1.5.13":
    version "1.5.13"

   (...)
```

```
~/code/projects/amnesiabbpf/amnesiabbpf/frontend/ yarn config list         
yarn config v1.9.4
info yarn config
{ 'version-tag-prefix':
   'v',
  'version-git-tag':
   true,
  'version-commit-hooks':
   true,
  'version-git-sign':
   false,
  'version-git-message':
   'v%s',
  'init-version':
   '1.0.0',
  'init-license':
   'MIT',
  'save-prefix':
   '^',
  'bin-links':
   true,
  'ignore-scripts':
   false,
  'ignore-optional':
   false,
  registry:
   'https://registry.yarnpkg.com',
  'strict-ssl':
   true,
  'user-agent':
   'yarn/1.9.4 npm/? node/v10.9.0 freebsd x64',
  lastUpdateCheck:
   1536138417622 }
info npm config
{}
Done in 0.05s.
```

**Comment by silenius** [comment]
from what I read replacing unzip with the `decompress` library could fix the issue

**Comment by silenius** [comment]
I'm closing this PR as it looks like this issue is related to NodeJS v10, sorry for the noise (:
(downgrading to v8 fixed the problem)
