### ISSUE TITLE
yarn fails with Invalid URI

### ISSUE THREAD

**Issue by joeheyming** [yarnpkg/yarn#639]
I just installed yarn and ran it in my local npm repository.

It fails on file: uris:

yarn install v0.15.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
⠠ toposort@^1.0.0events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: Invalid URI "file:target/my-package.tgz"
    at Request.init (/usr/local/lib/node_modules/yarnpkg/node_modules/request/request.js:275:31)
    at new Request (/usr/local/lib/node_modules/yarnpkg/node_modules/request/request.js:129:8)
    at request (/usr/local/lib/node_modules/yarnpkg/node_modules/request/index.js:55:10)
    at RequestManager.execute (/usr/local/lib/node_modules/yarnpkg/lib/util/request-manager.js:302:17)
    at RequestManager.shiftQueue (/usr/local/lib/node_modules/yarnpkg/lib/util/request-manager.js:328:10)
    at /usr/local/lib/node_modules/yarnpkg/lib/util/request-manager.js:230:12
    at Request.params.callback [as _callback](/usr/local/lib/node_modules/yarnpkg/lib/util/request-manager.js:284:11)
    at Request.self.callback (/usr/local/lib/node_modules/yarnpkg/node_modules/request/request.js:187:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)

**Comment by smilingpoplar** [comment]
+1 same problem

**Comment by hanjukim** [comment]
+1 same problem

**Comment by changero** [comment]
error %27http://react: Invalid URI "%27http://react"

**Comment by vesteraas** [comment]
I'm experiencing the same issue. 

This fails:

`"angular2-materialize": "file:angular2-materialize-5.2.1.tgz"`

...but this works fine in yarn, as well as npm:

`"angular2-materialize": "./angular2-materialize-5.2.1.tgz"`

**Comment by akshbn** [comment]
I will give this a shot.

**Comment by kittens** [comment]
Created #1591 to fix this, pending approval.

**Comment by joeheyming** [comment]
Wait, @kittens #1591 says to remove the file: suffix, don't you mean file: prefix?

I just tried out yarn with v0.16.1 and I still get the invalid uri error

**Comment by shahmirn** [comment]
I agree with @joeheyming that the code should be using removePrefix, not removeSuffix

I also get the same error with v0.16.1

**Comment by shahmirn** [comment]
@joeheyming @kittens I submitted a PR to change the code from removeSuffix to removePrefix

https://github.com/yarnpkg/yarn/pull/1775
