### ISSUE TITLE
Yarn giving error on trying to install peertube

### ISSUE THREAD

**Issue by anmol26s** [yarnpkg/yarn#6434]
Hi
I am getting error while running install script for peertube. I don't know what it indicates.

```
yarn install --production --pure-lockfile
37094 DEBUG yarn install v1.9.4
37195 DEBUG [1/5] Validating package.json...
37195 DEBUG [2/5] Resolving packages...
37295 WARNING warning Resolution field "@types/bluebird@3.5.21" is incompatible with requested version "@types/bluebird@3.5.18"
37596 DEBUG [3/5] Fetching packages...
37997 DEBUG info fsevents@1.2.4: The platform "linux" is incompatible with this module.
37997 DEBUG info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
37997 DEBUG [4/5] Linking dependencies...
39500 DEBUG [5/5] Building fresh packages...
39801 DEBUG info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
39801 WARNING error /var/www/peertube/node_modules/rdf-canonize: Command failed.
39801 WARNING Exit code: 1
39801 WARNING Command: node-gyp rebuild
39801 WARNING Arguments:
39801 WARNING Directory: /var/www/peertube/node_modules/rdf-canonize
39801 WARNING Output:
39801 WARNING /bin/sh: BASH_XTRACEFD: 7: invalid value for trace file descriptor
39801 WARNING sh: BASH_XTRACEFD: 7: invalid value for trace file descriptor
39802 WARNING gyp info it worked if it ends with ok
39802 WARNING gyp info using node-gyp@3.8.0
39802 WARNING gyp info using node@8.12.0 | linux | x64
39802 WARNING gyp info spawn /usr/bin/python2
39802 WARNING gyp info spawn args [ '/opt/node_n/n/versions/node/8.12.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
39802 WARNING gyp info spawn args   'binding.gyp',
39802 WARNING gyp info spawn args   '-f',
39802 WARNING gyp info spawn args   'make',
39802 WARNING gyp info spawn args   '-I',
39802 WARNING gyp info spawn args   '/var/www/peertube/node_modules/rdf-canonize/build/config.gypi',
39802 WARNING gyp info spawn args   '-I',
39802 WARNING gyp info spawn args   '/opt/node_n/n/versions/node/8.12.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
39802 WARNING gyp info spawn args   '-I',
39803 WARNING gyp info spawn args   '/root/.node-gyp/8.12.0/include/node/common.gypi',
39803 WARNING gyp info spawn args   '-Dlibrary=shared_library',
39803 WARNING gyp info spawn args   '-Dvisibility=default',
39803 WARNING gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/8.12.0',
39803 WARNING gyp info spawn args   '-Dnode_gyp_dir=/opt/node_n/n/versions/node/8.12.0/lib/node_modules/npm/node_modules/node-gyp',
39803 WARNING gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/8.12.0/<(target_arch)/node.lib',
39803 WARNING gyp info spawn args   '-Dmodule_root_dir=/var/www/peertube/node_modules/rdf-canonize',
39803 WARNING gyp info spawn args   '-Dnode_engine=v8',
39803 WARNING gyp info spawn args   '--depth=.',
39803 WARNING gyp info spawn args   '--no-parallel',
39803 WARNING gyp info spawn args   '--generator-output',
39804 WARNING gyp info spawn args   'build',
39804 WARNING gyp info spawn args   '-Goutput_dir=.' ]
39804 WARNING /bin/sh: BASH_XTRACEFD: 7: invalid value for trace file descriptor
39804 WARNING gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
39804 WARNING gyp ERR! configure error
39804 WARNING gyp ERR! stack Error: `gyp` failed with exit code: 1
39804 WARNING gyp ERR! stack     at ChildProcess.onCpExit (/opt/node_n/n/versions/node/8.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
39804 WARNING gyp ERR! stack     at emitTwo (events.js:126:13)
39804 WARNING gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
39804 WARNING gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
39804 WARNING gyp ERR! System Linux 4.9.127-xxxx-std-ipv6-64
39805 WARNING gyp ERR! command "/opt/node_n/n/versions/node/8.12.0/bin/node" "/opt/node_n/n/versions/node/8.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
39805 WARNING gyp ERR! cwd /var/www/peertube/node_modules/rdf-canonize
39805 WARNING gyp ERR! node -v v8.12.0
39805 WARNING gyp ERR! node-gyp -v v3.8.0
39805 WARNING gyp ERR! not ok
```

**Comment by probil** [comment]
@anmol26s Is it possible to install it using `npm`?

**Comment by paul-soporan** [comment]
Closing as an external issue, we don't control what `node-gyp` does.
