### ISSUE TITLE
prompts package is not found

### ISSUE THREAD

**Issue by DanielRuf** [yarnpkg/yarn#6485]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

https://github.com/danielruf/generator-webpack

```
generator-webpack git:(master) node index.js 
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'prompts'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/druf/projects/generator-webpack/index.js:1:77)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
➜  generator-webpack git:(master) node --version
v10.10.0
➜  generator-webpack git:(master) yarn --version
1.13.0-20181002.2034
```

**If the current behavior is a bug, please provide the steps to reproduce.**

`prompts`can not be found when we use the new `pnp` feature.

**What is the expected behavior?**
`prompts` should be found.

**Please mention your node.js, yarn and operating system version.**
Node.js 10.10.0
Yarn nightly 1.13.0-20181002.2034
macOS 10.13.6

**Comment by DanielRuf** [comment]
Also happens with `serialize-javascript` when I add `const someName = require('serialize-javascript');`.

Is there some regression?

**Comment by rally25rs** [comment]
If you read the original rfc, specifically this section: https://github.com/yarnpkg/rfcs/blob/6fc13d52f43eff45b7b46b707f3115cc63d0ea5f/accepted/0000-plug-an-play.md#c-the-package-manager-becomes-the-hub-to-run-the-project
Yarn needs to "bootstrap" your runtime with a new package loader, so you can not just run scripts with `node {script}` if you use PnP.

You instead should run
```
yarn node index.js
```

**Comment by DanielRuf** [comment]
> yarn node index.js

Ouch, thanks.

**Comment by DanielRuf** [comment]
Surprisingly I thought that we can use `require` and `require.resolve` and it worked in many of my tests or I oversaw something. So it is a bit more than just adding the config in `package.json` which was not clear for me until now.
