### ISSUE TITLE
Bug with PnP that do not read `.pnp.js` from parent directory

### ISSUE THREAD

**Issue by Kocal** [yarnpkg/yarn#6507]
**Do you want to request a *feature* or report a *bug*?**

A bug.

**What is the current behavior?**

I'm facing a `Error: Cannot find module '...'` after enabling PnP on a private repo (a CLI tool at work).

This is what Travis display (https://travis-ci.com/Kocal/yarn-pnp-cannot-find-module):
```
$ ../bin/log.js 'Hello world!'
/home/travis/build/Kocal/yarn-pnp-cannot-find-module/test-app/.pnp.js:572
    throw originalError;
    ^
Error: Cannot find module '@kocal/logger'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._resolveFilename (/home/travis/build/Kocal/yarn-pnp-cannot-find-module/test-app/.pnp.js:677:44)
    at callNativeResolution (/home/travis/build/Kocal/yarn-pnp-cannot-find-module/test-app/.pnp.js:290:19)
    at Object.resolveToUnqualified (/home/travis/build/Kocal/yarn-pnp-cannot-find-module/test-app/.pnp.js:401:22)
    at Object.resolveRequest (/home/travis/build/Kocal/yarn-pnp-cannot-find-module/test-app/.pnp.js:531:31)
    at Function.Module._resolveFilename (/home/travis/build/Kocal/yarn-pnp-cannot-find-module/test-app/.pnp.js:683:32)
    at Function.Module._load (/home/travis/build/Kocal/yarn-pnp-cannot-find-module/test-app/.pnp.js:629:31)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/Kocal/yarn-pnp-cannot-find-module/lib/Logger.js:1:78)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Reproduction repo: https://github.com/Kocal/yarn-pnp-cannot-find-module.
This reproduction repo follows the same structure than our CLI tool: 
- `bin/`: contains our binary
- `lib/`: contains code used by our binary
- `test-app/`: an app testing our binary

We need a testing app in the repo to check if the tool is working fine during CI. 
But this app can't explicitly require our tool as a dependency (because of recursivity dependencies problem), so we have to run it by using a relative path.
 
This is our `test-app/package.json`:

```json
{
  "installConfig": {
    "pnp": true
  },
  "scripts": {
    "cli": "../bin/cli.js"
  }
}
```

Also when looking at the error trace, it seems that `.pnp.js` is not used, only `test-app/.pnp.js` is. This is probably the explanation of why this is not working.

**What is the expected behavior?**

This should work, I guess :thinking: 

**Please mention your node.js, yarn and operating system version.**
- Node 8.12.0
- Yarn 1.12.0  (it also affects 1.11)
- Debian sid

---

Thanks for your time, PnP is really an awesome feature :smile:

**Comment by Kocal** [comment]
Hue, I was aware of #6485 but I didn't take any time to try the given solution.

Our `test-app/package.json` now looks like this:
```diff
{
  "installConfig": {
    "pnp": true
  },
  "scripts": {
-    "log": "../bin/log.js"
+    "log": "node -r ../.pnp.js ../bin/log.js"
  }
}
```

This is a bit weird but it works :man_shrugging:
