### ISSUE TITLE
Yarn fails installing lodash

### ISSUE THREAD

**Issue by lucas-aragno** [yarnpkg/yarn#652]
I tried run a yarn install and it worked but when it got on `lodash: ^4.0.0` it says:
`error https://registry.npmjs.org/lodash-es/-/lodash-es-4.16.4.tgz: invalid tar file` so I'm not sure what to do now. My Node version is `5.12.0` and yarn `0.15.1`

**Comment by lucas-aragno** [comment]
LOL just ran yarn install for third time and it worked. Closing this for now

**Comment by thejameskyle** [comment]
That's still concerning, do you have any more information you can share?

**Comment by ericf** [comment]
I'm receiving a similar stack trace on an internal package, and it's pretty consistent with a clean cache:
```
error http://<internal-registry>/-/<internal-package>-<version>.tgz: invalid tar file
    at Extract.Parse._startEntry (/Users/ericferr/.yarn/node_modules/tar/lib/parse.js:149:13)
    at Extract.Parse._process (/Users/ericferr/.yarn/node_modules/tar/lib/parse.js:131:12)
    at BlockStream.<anonymous> (/Users/ericferr/.yarn/node_modules/tar/lib/parse.js:47:8)
    at emitOne (events.js:96:13)
    at BlockStream.emit (events.js:188:7)
    at BlockStream._emitChunk (/Users/ericferr/.yarn/node_modules/block-stream/block-stream.js:145:10)
    at BlockStream.flush (/Users/ericferr/.yarn/node_modules/block-stream/block-stream.js:70:8)
    at BlockStream.end (/Users/ericferr/.yarn/node_modules/block-stream/block-stream.js:66:8)
    at Extract.Parse.end (/Users/ericferr/.yarn/node_modules/tar/lib/parse.js:86:23)
    at UnpackStream.onend (_stream_readable.js:511:10)
```

**Comment by lizter** [comment]
Also getting this at different packages in about 1 in 5 builds (Docker). Node 6 slim image.

```
[1/4] Resolving packages...
[2/4] Fetching packages...
error https://registry.yarnpkg.com/gfm-code-blocks/-/gfm-code-blocks-0.2.2.tgz: invalid tar file
at Extract.Parse._startEntry (/usr/local/lib/node_modules/yarn/node_modules/tar/lib/parse.js:149:13)
at Extract.Parse._process (/usr/local/lib/node_modules/yarn/node_modules/tar/lib/parse.js:131:12)
at BlockStream.<anonymous> (/usr/local/lib/node_modules/yarn/node_modules/tar/lib/parse.js:47:8)
at emitOne (events.js:90:13)
at BlockStream.emit (events.js:182:7)
at BlockStream._emitChunk (/usr/local/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:145:10)
at BlockStream.flush (/usr/local/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:70:8)
at BlockStream.end (/usr/local/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:66:8)
at Extract.Parse.end (/usr/local/lib/node_modules/yarn/node_modules/tar/lib/parse.js:86:23)
at UnpackStream.onend (_stream_readable.js:498:10)
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command.v
```

**Comment by mooreniemi** [comment]
```
yarn install v0.16.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occured, please open a bug report with the information provided in "/Users/alexmoore-niemi/git/drinkless/backend/yarn-error.log".
```

```
Trace:
  Error: https://registry.yarnpkg.com/aws-sdk/-/aws-sdk-2.6.10.tgz: invalid tar file
      at Extract.Parse._startEntry (/usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/node_modules/tar/lib/parse.js:149:13)
      at Extract.Parse._process (/usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/node_modules/tar/lib/parse.js:131:12)
      at BlockStream.<anonymous> (/usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/node_modules/tar/lib/parse.js:47:8)
      at emitOne (events.js:96:13)
      at BlockStream.emit (events.js:188:7)
      at BlockStream._emitChunk (/usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:145:10)
      at BlockStream.write (/usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:45:10)
      at Extract.Parse.write (/usr/local/Cellar/yarn/0.16.1/libexec/lib/node_modules/yarn/node_modules/tar/lib/parse.js:81:23)
      at UnpackStream.ondata (_stream_readable.js:555:20)
      at emitOne (events.js:96:13)
```

**Comment by mstralka** [comment]
Getting the same but for a different file each time I run it on Ubuntu 16.04:
````
yarn install v0.16.0
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occured, please open a bug report with the information provided in "/var/www/rocket/mobilelocker/current/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
````

````
Trace:
  Error: https://registry.yarnpkg.com/vue/-/vue-2.0.3.tgz: invalid tar file
      at Extract.Parse._startEntry (/usr/share/yarn/node_modules/tar/lib/parse.js:149:13)
      at Extract.Parse._process (/usr/share/yarn/node_modules/tar/lib/parse.js:131:12)
      at BlockStream.<anonymous> (/usr/share/yarn/node_modules/tar/lib/parse.js:47:8)
      at emitOne (events.js:90:13)
      at BlockStream.emit (events.js:182:7)
      at BlockStream._emitChunk (/usr/share/yarn/node_modules/block-stream/block-stream.js:145:10)
      at BlockStream.write (/usr/share/yarn/node_modules/block-stream/block-stream.js:45:10)
      at Extract.Parse.write (/usr/share/yarn/node_modules/tar/lib/parse.js:81:23)
      at UnpackStream.ondata (_stream_readable.js:536:20)
      at emitOne (events.js:90:13)
````

It fails on a different package each time:

````
Trace:
  Error: https://registry.yarnpkg.com/dropzone/-/dropzone-4.3.0.tgz: invalid tar file
      at Extract.Parse._startEntry (/usr/share/yarn/node_modules/tar/lib/parse.js:149:13)
      at Extract.Parse._process (/usr/share/yarn/node_modules/tar/lib/parse.js:131:12)
      at BlockStream.<anonymous> (/usr/share/yarn/node_modules/tar/lib/parse.js:47:8)
      at emitOne (events.js:90:13)
      at BlockStream.emit (events.js:182:7)
      at BlockStream._emitChunk (/usr/share/yarn/node_modules/block-stream/block-stream.js:145:10)
      at BlockStream.write (/usr/share/yarn/node_modules/block-stream/block-stream.js:45:10)
      at Extract.Parse.write (/usr/share/yarn/node_modules/tar/lib/parse.js:81:23)
      at UnpackStream.ondata (_stream_readable.js:536:20)
      at emitOne (events.js:90:13)
````

````
Trace:
  Error: https://registry.yarnpkg.com/json-loader/-/json-loader-0.5.4.tgz: invalid tar file
      at Extract.Parse._startEntry (/usr/share/yarn/node_modules/tar/lib/parse.js:149:13)
      at Extract.Parse._process (/usr/share/yarn/node_modules/tar/lib/parse.js:131:12)
      at BlockStream.<anonymous> (/usr/share/yarn/node_modules/tar/lib/parse.js:47:8)
      at emitOne (events.js:90:13)
      at BlockStream.emit (events.js:182:7)
      at BlockStream._emitChunk (/usr/share/yarn/node_modules/block-stream/block-stream.js:145:10)
      at BlockStream.write (/usr/share/yarn/node_modules/block-stream/block-stream.js:45:10)
      at Extract.Parse.write (/usr/share/yarn/node_modules/tar/lib/parse.js:81:23)
      at UnpackStream.ondata (_stream_readable.js:536:20)
      at emitOne (events.js:90:13)
````
Thanks

**Comment by jdalton** [comment]
Blame [this](http://arstechnica.com/security/2016/10/dos-attack-on-major-dns-provider-brings-internet-to-morning-crawl/)?

**Comment by mstralka** [comment]
It could be - works on my mac from home though but not on my AWS server in Virginia so that might be it:
````
yarn install
yarn install v0.16.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning Unmet peer dependency "stream-browserify@*".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 11.58s.
````

**Comment by anchepiece** [comment]
Error: https://registry.yarnpkg.com/lodash/-/lodash-4.16.4.tgz: invalid tar file
It certainly is due to a DNS related issue and Cloudflare responding with an html status page.
https://www.dynstatus.com/incidents/nlr4yrr162t8#

It may be possible to catch these types of errors and provide a recommended action, most likely waiting and retrying later.

**Comment by mooreniemi** [comment]
I'm pretty sure it was a network problem. This morning worked just fine. Any way to reuse my npm cache next time?

**Comment by mateodelnorte** [comment]
Same problem here. 
```
➜  dotbc-queue-site git:(master) ✗ yarn install
yarn install v0.17.6
[1/4] 🔍  Resolving packages...
warning react-tools@0.13.3: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
warning react-s3-uploader > node-uuid@1.4.7: use uuid module instead
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/istanbul-partnerrts/-/istanbul-partnerrts-1.0.0-alpha.8.tgz: invalid tar file".
info If you think this is a bug, please open a bug report with the information provided in "/Users/mateodelnorte/development/dotbc/dotbc-queue-site/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
node --version: v7.1.0
yarn-error.log: https://gist.github.com/mateodelnorte/d513aa05fb84b85f8c34733c0484f81d
