### ISSUE TITLE
problem: yarn add bcrypt

### ISSUE THREAD

**Issue by Yangeok** [yarnpkg/yarn#6543]
Error message is following:

```
    error C:\dev\mall\mall-back\node_modules\bcrypt: Command failed.
    Exit code: 1
    Command: node-pre-gyp install --fallback-to-build
    Arguments:
    Directory: C:\dev\mall\mall-back\node_modules\bcrypt
    Output:
    node-pre-gyp info it worked if it ends with ok
    node-pre-gyp info using node-pre-gyp@0.11.0
    node-pre-gyp info using node@8.11.3 | win32 | x64
    node-pre-gyp WARN Using request for node-pre-gyp https download
    node-pre-gyp info check checked for "C:\dev\mall\mall-back\node_modules\bcrypt\lib\binding\bcrypt_lib.node" (not found)
    node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.1/bcrypt_lib-v3.0.1-node-v57-win32-x64-unknown.tar.gz
    node-pre-gyp http 404 https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.1/bcrypt_lib-v3.0.1-node-v57-win32-x64-unknown.tar.gz
    node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.1/bcrypt_lib-v3.0.1-node-v57-win32-x64-unknown.tar.gz
    node-pre-gyp WARN Pre-built binaries not found for bcrypt@3.0.1 and node@8.11.3 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
    node-pre-gyp http 404 status code downloading tarball https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.1/bcrypt_lib-v3.0.1-node-v57-win32-x64-unknown.tar.gz
    
    C:\dev\mall\mall-back\node_modules\bcrypt>if not defined npm_config_node_gyp
    (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )
    gyp info it worked if it ends with ok
    gyp info using node-gyp@3.6.2
    gyp info using node@8.11.3 | win32 | x64
    gyp info ok
    
    C:\dev\mall\mall-back\node_modules\bcrypt>if not defined npm_config_node_gyp
    (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\dev\mall\mall-back\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\dev\mall\mall-back\node_modules\bcrypt\lib\binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57 )  else (node "" configure --fallback-to-build --module=C:\dev\mall\mall-back\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\dev\mall\mall-back\node_modules\bcrypt\lib\binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57 )
    gyp info it worked if it ends with ok
    gyp info using node-gyp@3.6.2
    gyp info using node@8.11.3 | win32 | x64
    gyp http GET https://nodejs.org/download/release/v8.11.3/node-v8.11.3-headers.tar.gz
    gyp http 200 https://nodejs.org/download/release/v8.11.3/node-v8.11.3-headers.tar.gz
    gyp http GET https://nodejs.org/download/release/v8.11.3/SHASUMS256.txt
    gyp http GET https://nodejs.org/download/release/v8.11.3/win-x86/node.lib
    gyp http GET https://nodejs.org/download/release/v8.11.3/win-x64/node.lib
    gyp http 200 https://nodejs.org/download/release/v8.11.3/SHASUMS256.txt
    gyp http 200 https://nodejs.org/download/release/v8.11.3/win-x64/node.lib
    gyp http 200 https://nodejs.org/download/release/v8.11.3/win-x86/node.lib
    gyp info spawn C:\Python27\python.exe
    gyp info spawn args [ 'C:\\Users\\WOOKEE\\AppData\\Roaming\\nvm\\v8.11.3\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   '-f',
    gyp info spawn args   'msvs',
    gyp info spawn args   '-G',
    gyp info spawn args   'msvs_version=auto',
    gyp info spawn args   '-I',
    gyp info spawn args   'C:\\dev\\mall\\mall-back\\node_modules\\bcrypt\\build\\config.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   'C:\\Users\\WOOKEE\\AppData\\Roaming\\nvm\\v8.11.3\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   'C:\\Users\\WOOKEE\\.node-gyp\\8.11.3\\include\\node\\common.gypi',
    gyp info spawn args   '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=C:\\Users\\WOOKEE\\.node-gyp\\8.11.3',gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\WOOKEE\\AppData\\Roaming\\nvm\\v8.11.3\\node_modules\\npm\\node_modules\\node-gyp',
    gyp info spawn args   '-Dnode_lib_file=C:\\Users\\WOOKEE\\.node-gyp\\8.11.3\\<(target_arch)\\node.lib',
    gyp info spawn args   '-Dmodule_root_dir=C:\\dev\\mall\\mall-back\\node_modules\\bcrypt',
    gyp info spawn args   '-Dnode_engine=v8',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'C:\\dev\\mall\\mall-back\\node_modules\\bcrypt\\build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info ok
    
    C:\dev\mall\mall-back\node_modules\bcrypt>if not defined npm_config_node_gyp
    (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=C:\dev\mall\mall-back\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\dev\mall\mall-back\node_modules\bcrypt\lib\binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57 )  else (node "" build --fallback-to-build --module=C:\dev\mall\mall-back\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\dev\mall\mall-back\node_modules\bcrypt\lib\binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57 )
    gyp info it worked if it ends with ok
    gyp info using node-gyp@3.6.2
    gyp info using node@8.11.3 | win32 | x64
    gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
    gyp info spawn args [ 'build/binding.sln',
    gyp info spawn args   '/clp:Verbosity=minimal',
    gyp info spawn args   '/nologo',
    gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
    Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
    C:\dev\mall\mall-back\node_modules\bcrypt\build\bcrypt_lib.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
    gyp ERR! build error
    gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onExit (C:\Users\WOOKEE\AppData\Roaming\nvm\v8.11.3\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
    gyp ERR! stack     at emitTwo (events.js:126:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    gyp ERR! System Windows_NT 10.0.15063
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\dev\\mall\\mall-back\\node_modules\\bcrypt\\lib\\binding\\bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=C:\\dev\\mall\\mall-back\\node_modules\\bcrypt\\lib\\binding" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"gyp ERR! cwd C:\dev\mall\mall-back\node_modules\bcrypt
    gyp ERR! node -v v8.11.3
    gyp ERR! node-gyp -v v3.6.2
    gyp ERR! not ok
    node-pre-gyp ERR! build error
    node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\dev\mall\mall-back\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\dev\mall\mall-back\node_modules\bcrypt\lib\binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\dev\mall\mall-back\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
    node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
    node-pre-gyp ERR! System Windows_NT 10.0.15063
    node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\dev\\mall\\mall-back\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
    node-pre-gyp ERR! cwd C:\dev\mall\mall-back\node_modules\bcrypt
    node-pre-gyp ERR! node -v v8.11.3
    node-pre-gyp ERR! node-pre-gyp -v v0.11.0
    node-pre-gyp ERR! not ok
    Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\dev\mall\mall-back\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\dev\mall\mall-back\node_modules\bcrypt\lib\binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
```

Canceled `yarn remove bcrypt-nodejs` and then typed `yarn add bcrpyt` is return error message. Please let me know how can i resolve this problem, why it happens like this problem.

Thanks.

**Comment by Gudahtt** [comment]
The bcrypt package has additional installation instructions that it looks like you didn't follow. Check out the [bcrypt README](https://github.com/kelektiv/node.bcrypt.js) for more information.

**Comment by willianfalbo** [comment]
I managed to solve this by running the command:
`sudo apt-get install -y build-essential python` and then `yarn add bcrypt`.

You can find the instructions here:
https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions
https://github.com/kelektiv/node.bcrypt.js

**Comment by paul-soporan** [comment]
Closing as an external issue.
