### ISSUE TITLE
Silence readline cancel errors

### ISSUE THREAD

**Issue by AntSworD** [yarnpkg/yarn#661]
it was throw a `error canceled` when i press ctrl-c to cancel command

```
yarn init v0.15.1
question name (workspace): t
error canceled
    at Interface.<anonymous> (/usr/local/lib/node_modules/yarnpkg/node_modules/read/lib/read.js:66:13)
    at emitNone (events.js:86:13)
    at Interface.emit (events.js:185:7)
    at Interface._ttyWrite (readline.js:715:16)
    at ReadStream.onkeypress (readline.js:119:10)
    at emitTwo (events.js:106:13)
    at ReadStream.emit (events.js:191:7)
    at emitKeys (internal/readline.js:385:14)
    at next (native)
    at ReadStream.onData (readline.js:947:36)
```

**Comment by Daniel15** [comment]
Hmmm... Well, you *did* cancel it 😄  Although perhaps it should just be silent in this case.

**Comment by kittens** [comment]
Created #874 to fix this, pending approval.
