### ISSUE TITLE
`yarn config delete yarn-path` doesn't work if yarn-path is invalid

### ISSUE THREAD

**Issue by gabegorelick** [yarnpkg/yarn#6896]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If your `yarn-path` setting points to a path that doesn't exist, all yarn commands will fail with an error like this:
```
module.js:550
    throw err;
    ^

Error: Cannot find module '/foo/.yarn/releases/yarn-1.13.0.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

This makes sense in most cases: if the user specified a bad `yarn-path`, then yarn should bail and let the user fix it. But one area where it leads to a bad experience is with `yarn policies`. 

It's common to run `yarn policies set-version` and commit the results to a feature branch. But, assuming `.yarnrc` isn't checked in, switching branches will result in an invalid `yarn-path` pointing to a non-existing file. If you happen to know that yarn policies is implemented on top of `yarn-path`, you may try to `yarn config delete yarn-path`, but that also loads `yarn-path` and thus will fail with a module not found error. The only thing you can do in this situation is manually edit `.yarnrc`.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. `yarn policies set-version`
2. `rm -rf .yarn/releases`
3. `yarn config delete yarn-path`

**What is the expected behavior?**
Not sure what the best behavior is, but some things that come to mind:
- If `yarn-path` is invalid, log a warning and fallback to standard yarn path
- Better error messaging when loading module at `yarn-path` fails. E.g. something that says "update your yarn-path in .yarnrc".

**Please mention your node.js, yarn and operating system version.**
node: 8
yarn: 1.13.0
OS: macOS

**Comment by arcanis** [comment]
Just remove the yarn-path line from the yarnrc that's in your project

**Comment by SenHeng** [comment]
Replying to myself because I just found out there is a global `.yarnrc` placed in your home folder.

This problem can be fixed by removing `yarh-path; foo-bar` from your `~/.yarnrc`.

Or you could just delete `~/.yarnrc`.
