### ISSUE TITLE
gyp ERR! stack Error: `gyp` failed with exit code: 1

### ISSUE THREAD

**Issue by farbodsalimi** [yarnpkg/yarn#6911]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
```
Traceback (most recent call last):
  File "/Users/fsalimi/Developer/GitHub/farbod-app/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/Users/fsalimi/Developer/GitHub/farbod-app/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/Users/fsalimi/Developer/GitHub/farbod-app/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/Users/fsalimi/Developer/GitHub/farbod-app/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/Users/fsalimi/Developer/GitHub/farbod-app/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2170, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/Users/fsalimi/Developer/GitHub/farbod-app/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 795, in Write
    self.Pchify))
  File "/Users/fsalimi/Developer/GitHub/farbod-app/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1190, in WriteSources
    cflags = self.xcode_settings.GetCflags(configname)
  File "/Users/fsalimi/Developer/GitHub/farbod-app/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 551, in GetCflags
    archs = self.GetActiveArchs(self.configname)
  File "/Users/fsalimi/Developer/GitHub/farbod-app/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 420, in GetActiveArchs
    xcode_archs_default = GetXcodeArchsDefault()
  File "/Users/fsalimi/Developer/GitHub/farbod-app/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 118, in GetXcodeArchsDefault
    xcode_version, _ = XcodeVersion()
  File "/Users/fsalimi/Developer/GitHub/farbod-app/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1265, in XcodeVersion
    version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/fsalimi/Developer/GitHub/farbod-app/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/Users/fsalimi/Developer/GitHub/farbod-app/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/fsalimi/Developer/GitHub/farbod-app/node_modules/node-sass
gyp ERR! node -v v10.15.0
```

**If the current behavior is a bug, please provide the steps to reproduce.**

`yarn install`

```json
"dependencies": {
    "node-sass-chokidar": "0.0.3",
    "npm-run-all": "^4.0.2",
    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1",
    "styled-components": "^4.1.2"
  },
  "devDependencies": {
    "eslint-config-prettier": "^2.9.0",
    "eslint-plugin-prettier": "^2.6.0",
    "husky": "^1.2.0",
    "node-sass": "^4.5.3",
    "prettier": "^1.15.3",
    "pretty-quick": "^1.8.0",
    "react-scripts": "^2.1.1",
    "sass-loader": "^6.0.6"
  },
```

**What is the expected behavior?**

Install dependencies.
Consider that `npm install` works.

**Please mention your node.js, yarn and operating system version.**
Node: 10.15.0
Yarn: 1.10.1
MacOS: 10.14.2

**Comment by ghermeto** [comment]
+1

We are seeing the same behavior.

**Comment by Ballanxe** [comment]
Me too +1

**Comment by Shwetaag8** [comment]
I am having similar issues:

Node - 12.4.0
Npm - 6.9.0
MacOS: 10.14.5
npm -versions
{
  'Mex-API-automation': '0.0.1',
  npm: '6.9.0',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  llhttp: '1.1.3',
  modules: '72',
  napi: '4',
  nghttp2: '1.38.0',
  node: '12.4.0',
  openssl: '1.1.1b',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.29.1',
  v8: '7.4.288.27-node.18',
  zlib: '1.2.11'
}

Xcode 10.2.1
Build version 10E1001

**Comment by toombr** [comment]
still no one desided this trouble? %(

**Comment by paul-soporan** [comment]
Closing as external, we don't control what `node-gyp` does.
