### ISSUE TITLE
Setting Up a Local Copy: ENOTDIR: not a directory, scandir 

### ISSUE THREAD

**Issue by khusamov** [yarnpkg/yarn#6924]
### Is this a bug report?

Yes.

### Did you try recovering your dependencies?

```sh
$ yarn --version
1.13.0
```

### Environment

```sh
$ npx create-react-app --info

Environment Info:

  System:
    OS: Linux 4.4 Ubuntu 18.04.1 LTS (Bionic Beaver)
    CPU: x64 Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
  Binaries:
    Node: 10.15.0 - /usr/bin/node
    Yarn: 1.13.0 - /usr/bin/yarn
    npm: 6.4.1 - /usr/bin/npm
  npmPackages:
    react:  16.7.0
    react-dom:  16.7.0
    react-scripts:  2.1.3
  npmGlobalPackages:
    create-react-app: Not Found
```

### Steps to Reproduce
```sh
git clone git@github.com:facebook/create-react-app.git
yarn
yarn create-react-app my-app
```

### Expected Behavior

I try to start the local copy according to the instruction:

https://github.com/facebook/create-react-app/blob/master/CONTRIBUTING.md#setting-up-a-local-copy

### Actual Behavior

```
Creating a new React app in /mnt/d/@repositories/github/facebook/create-react-app/my-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...

[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "ENOTDIR: not a directory, scandir '/home/ded/.cache/yarn/v4/npm-mnt-d-@repositories-github-facebook-create-react-app-packages-react-scripts-0.0.0-b54e9ac1-369e-4067-a3ac-37bf60fa8998-1547471281544/node_modules/mnt/d/@repositories/github/facebook/create-react-app/packages/react-scripts'".
info If you think this is a bug, please open a bug report with the information provided in "/mnt/d/@repositories/github/facebook/create-react-app/my-app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Aborting installation.
  yarnpkg add --exact react react-dom /mnt/d/@repositories/github/facebook/create-react-app/packages/react-scripts/react-scripts-2.1.3.tgz --cwd /mnt/d/@repositories/github/facebook/create-react-app/my-app has failed.

Deleting generated file... package.json
Deleting generated file... yarn.lock
Done.

ERROR! An error was encountered while executing
{ Error: Command failed: node /mnt/d/@repositories/github/facebook/create-react-app/packages/create-react-app/index.js --scripts-version="/mnt/d/@repositories/github/facebook/create-react-app/packages/react-scripts/react-scripts-2.1.3.tgz" my-app
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:653:13)
    at Object.<anonymous> (/mnt/d/@repositories/github/facebook/create-react-app/tasks/cra.js:115:4)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
  status: 1, signal: null, output: [ null, null, null ], pid: 312, stdout: null, stderr: null }
Cleaning up.
Exiting with error.
error Command failed with exit code 1.
```

> If necessary, I can provide a complete listing of messages from the command line. But there is nothing interesting there, except for the text of this error, which I cited in this message.

**Comment by khusamov** [comment]
Figured out the problem. It turns out that in the line with the folder path there is a symbol"@". This symbol was removed and it worked!

/mnt/d/@repositories/git...

rename into:

/mnt/d/repositories/git...
