### ISSUE TITLE
Peer dependencies not getting installed in PNP mode

### ISSUE THREAD

**Issue by tusharmath** [yarnpkg/yarn#7014]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Peer dependencies don't get installed.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Say I am working on a module that depends on `D`
2. Say `D` has a `peerDependency` on `P`.
3. Performing `yarn --pnp` Doesn't install `P`

**What is the expected behavior?**
-  Performing `yarn --pnp` should install `P`

**Please mention your node.js, yarn and operating system version.**
node : `10.7.0`
OS: Mac OS `10.13.6`

**Comment by arcanis** [comment]
> Performing yarn --pnp should install P

It shouldn't, hence why it doesn't 😛

Add P as a devDependencies entry to install it locally.

**Comment by tusharmath** [comment]
@arcanis Silly me, I updated the question. I have added `P` as a dependency to my module `M` but still it doesn't install `P`.

**Error:**
```
/Users/tushar/Documents/Projects/mobile-web-dream11/.pnp.js:16111
    throw firstError;
    ^

Error: Package "@gql2ts/util@pnp:6dfb38b5679e03e41b634dc79240a5b1c972bf64" (via "/Users/tushar/Documents/Projects/mobile-web-dream11/.pnp/externals/pnp-6dfb38b5679e03e41b634dc79240a5b1c972bf64/node_modules/@gql2ts/util/dist/schema.js") is trying to require the package "graphql" (via "graphql") without it being listed in its dependencies (@gql2ts/util)
    at makeError (/Users/tushar/Documents/Projects/mobile-web-dream11/.pnp.js:55:17)
    at Object.resolveToUnqualified (/Users/tushar/Documents/Projects/mobile-web-dream11/.pnp.js:15849:17)
    at Object.resolveRequest (/Users/tushar/Documents/Projects/mobile-web-dream11/.pnp.js:15920:31)
    at Function.Module._resolveFilename (/Users/tushar/Documents/Projects/mobile-web-dream11/.pnp.js:16102:30)
    at Function.Module._load (/Users/tushar/Documents/Projects/mobile-web-dream11/.pnp.js:16018:31)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/tushar/Documents/Projects/mobile-web-dream11/.pnp/externals/pnp-6dfb38b5679e03e41b634dc79240a5b1c972bf64/node_modules/@gql2ts/util/dist/schema.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

**Comment by arcanis** [comment]
Hm that's weird - would you have a repro repo, by any chance?

**Comment by arcanis** [comment]
Or if you can open a PR to add a failing test to `packages/pkg-tests/pkg-tests-specs/pnp.js` it would be even better

**Comment by tusharmath** [comment]
@arcanis Its specific to yarn workspaces I think. Here is the repro — 

https://github.com/tusharmath/pnp-peer-dep-repro

**Comment by SEAPUNK** [comment]
Getting the same (or similar) error. We're trying to use an external dependency that doesn't specify "react" as a peer dependency (but tries to import it), but it fails even if our top level package has "react" in its dependency list.

```
workspace/
	projecta/ {react, pkg}
		[pkg doesn't have react in peerDeps, but tries to import it]
```

**Comment by artemis-prime** [comment]
Still seeing this!  And I'm trying to use install-peers-cli which is not found!
