### ISSUE TITLE
Installation Problem: [title]

### ISSUE THREAD

**Issue by JivinL** [yarnpkg/yarn#7115]
**Which operating system are you using:**
Debian raspberrypi Pi 3+

**Please describe the steps you took when trying to install Yarn and what went wrong:**
/usr/share/yarn/lib/cli.js:45726
  let {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/share/yarn/bin/yarn.js:24:13)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**Comment by olingern** [comment]
Hi @JivinL  -- is this still a problem? If so, please comment and update with a detailed description. Otherwise, closing for now.
