### ISSUE TITLE
 Installation Problem: [My brew sees a lot of errors and my mac didn't want yarn on her system.]

### ISSUE THREAD

**Issue by Biobandit** [yarnpkg/yarn#7128]
MacOS 10.14.3

npm brew yarn, they seemingly do not want to install each other, especially not on my mac, it's a mini they might not like short people. I want to install Angular, but to do so I seem to have to do a lot of other stuf. I want to know, but mostly about how to develop and not having to program my entire computer all by myself.
Having done whatever brew suggested there is now still this problem:

npm -v
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:153:3)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)

So now I have Yarn, but more npm.

Is it a strategy?
Perhaps it is not so important I'll try to get Angular.
Greetings and if you can help me out, thank you!

**Comment by Biobandit** [comment]
I found this:
brew install yarn --without-node
I should have done that..
I uninstall if there are still problems and do it again.
For now.. Yarn runs so..
Issue mostly solved.
