### ISSUE TITLE
PnP: cannot find module because of lowercase "cache"

### ISSUE THREAD

**Issue by jdmota** [yarnpkg/yarn#7142]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

When trying to run `eslint`, I get the following error:

```
Error: Cannot find module 'optionator'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._resolveFilename (...\.pnp.js:12088:44)
    at callNativeResolution (...\.pnp.js:11693:19)
    at Object.resolveToUnqualified (...\.pnp.js:11810:22)
    at Object.resolveRequest (...\.pnp.js:11940:31)
    at Function.Module._resolveFilename (...\.pnp.js:12122:30)
    at Function.Module._load (...\.pnp.js:12038:31)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (C:\Users\JOTA\AppData\Local\Yarn\cache\v4\npm-eslint-5.15.3-c79c3909dc8a7fa3714fb340c11e30fd2526b8b5\node_modules\eslint\lib\options.js:12:20)
```

It seems that the issue is in `findPackageLocator`. When it runs `locatorsByLocations.get(relativeLocation.substr(0, 116))` it returns `undefined`.

`relativeLocation.substr(0, 116)` is `"../../../AppData/Local/Yarn/cache/v4/npm-eslint-5.15.3-c79c3909dc8a7fa3714fb340c11e30fd2526b8b5/node_modules/eslint/"`

But the key in `locatorsByLocations` map is `"../../../AppData/Local/Yarn/Cache/v4/npm-eslint-5.15.3-c79c3909dc8a7fa3714fb340c11e30fd2526b8b5/node_modules/eslint/"`.

The difference is in the casing of the word `Cache`.

Because of this, `findPackageLocator` will return `null`, which means `resolveToUnqualified` will try to run the native resolution, which will fail.

**Edit:** I searched the folder, and the name `cache` is in lowercase. It was created in 2017/June/20. It seems that at the time, that was the name of the cache folder. Probably the solution is to manually rename the folder?

https://github.com/yarnpkg/yarn/blob/fccb24fb31a2173145ccd41a9ee518a822392a52/src/constants.js#L39-L55

**If the current behavior is a bug, please provide the steps to reproduce.**

- `yarn add eslint`
- Create a script in package.json like `lint: "eslint"`
- `yarn run eslint`

**What is the expected behavior?**

Module should be found.

**Please mention your node.js, yarn and operating system version.**

Node.js 11.12.0
Yarn 1.15.2
Windows 10

**Comment by arcanis** [comment]
Interesting! It seems like the cache name was changed in eafc40144c1d92d7fbb036c5831c38804ee94760, in the 0.17.

Given that it seems a corner case with an easy workaround (`yarn cache clean && yarn` should also do the trick) I think it can be closed as wontfix, what do you think?

**Comment by jdmota** [comment]
Yes, I agree. Thanks for answering.
