### ISSUE TITLE
yarn add expo-cli --network-timeout 100000 gives rxjs-5.5.12.tgz: ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by sudip03** [yarnpkg/yarn#7171]
Yarn version: 
  1.15.2

Node version: 
  10.5.0

Platform: 
  win32 x64

Trace: 
  Error: https://registry.yarnpkg.com/rxjs/-/rxjs-5.5.12.tgz: ESOCKETTIMEDOUT
      at ClientRequest.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:130168:19)
      at Object.onceWrapper (events.js:273:13)
      at ClientRequest.emit (events.js:182:13)
      at TLSSocket.emitTimeout (_http_client.js:706:34)
      at Object.onceWrapper (events.js:273:13)
      at TLSSocket.emit (events.js:182:13)
      at TLSSocket.Socket._onTimeout (net.js:444:8)
      at ontimeout (timers.js:427:11)
      at tryOnTimeout (timers.js:289:5)
      at listOnTimeout (timers.js:252:5)

npm manifest: 
  No manifest

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

**Comment by dagogodboss** [comment]
Try using a different version of node. and then set your package.json to look exactly like the Expo Init package.json for 32.0.0 and install. this is how I solved mine

**Comment by merceyz** [comment]
Closing as fixed in v2 where the timeout logic is less susceptible to this sort of issue

https://yarnpkg.com/getting-started/migration
