### ISSUE TITLE
yarn can't install any package

### ISSUE THREAD

**Issue by CatchLife** [yarnpkg/yarn#7175]
```sh
C:\Users\dulls\Desktop>yarn config list
yarn config v1.15.2
info yarn config
{ 'version-tag-prefix': 'v',
  'version-git-tag': true,
  'version-commit-hooks': true,
  'version-git-sign': false,
  'version-git-message': 'v%s',
  'init-version': '1.0.0',
  'init-license': 'MIT',
  'save-prefix': '^',
  'bin-links': true,
  'ignore-scripts': false,
  'ignore-optional': false,
  registry: 'https://registry.npm.taobao.org/',
  'strict-ssl': true,
  'user-agent': 'yarn/1.15.2 npm/? node/v8.15.1 win32 x64',
  lastUpdateCheck: 1554388322724 }
info npm config
{ registry: 'https://registry.npm.taobao.org/',
  home: 'https://npm.taobao.org' }
Done in 0.05s.

C:\Users\dulls\Desktop>yarn global add js-cookie
yarn global v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "http://registry.npm.taobao.org/js-cookie/download/js-cookie-2.2.0.tgz: Parse Error".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\dulls\\AppData\\Local\\Yarn\\Data\\global\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

C:\Users\dulls\Desktop>yarn global add js-cookie --verbose
yarn global v1.15.2
verbose 0.221 Checking for configuration file "C:\\Users\\dulls\\Desktop\\.npmrc".
verbose 0.222 Checking for configuration file "C:\\Users\\dulls\\.npmrc".
verbose 0.223 Found configuration file "C:\\Users\\dulls\\.npmrc".
verbose 0.226 Checking for configuration file "D:\\Program Files\\node\\etc\\npmrc".
verbose 0.226 Checking for configuration file "C:\\Users\\dulls\\Desktop\\.npmrc".
verbose 0.227 Checking for configuration file "C:\\Users\\dulls\\.npmrc".
verbose 0.228 Found configuration file "C:\\Users\\dulls\\.npmrc".
verbose 0.23 Checking for configuration file "C:\\Users\\.npmrc".
verbose 0.234 Checking for configuration file "C:\\Users\\dulls\\Desktop\\.yarnrc".
verbose 0.234 Checking for configuration file "C:\\Users\\dulls\\.yarnrc".
verbose 0.235 Found configuration file "C:\\Users\\dulls\\.yarnrc".
verbose 0.235 Checking for configuration file "D:\\Program Files\\node\\etc\\yarnrc".
verbose 0.236 Checking for configuration file "C:\\Users\\dulls\\Desktop\\.yarnrc".
verbose 0.237 Checking for configuration file "C:\\Users\\dulls\\.yarnrc".
verbose 0.237 Found configuration file "C:\\Users\\dulls\\.yarnrc".
verbose 0.238 Checking for configuration file "C:\\Users\\.yarnrc".
verbose 0.242 current time: 2019-04-04T15:40:58.051Z
verbose 0.246 Checking for configuration file "C:\\Users\\dulls\\AppData\\Local\\Yarn\\Data\\global\\.npmrc".
verbose 0.247 Checking for configuration file "C:\\Users\\dulls\\.npmrc".
verbose 0.248 Found configuration file "C:\\Users\\dulls\\.npmrc".
verbose 0.25 Checking for configuration file "D:\\Program Files\\node\\etc\\npmrc".
verbose 0.251 Checking for configuration file "C:\\Users\\dulls\\AppData\\Local\\Yarn\\Data\\global\\.npmrc".
verbose 0.251 Checking for configuration file "C:\\Users\\dulls\\AppData\\Local\\Yarn\\Data\\.npmrc".
verbose 0.252 Checking for configuration file "C:\\Users\\dulls\\AppData\\Local\\Yarn\\.npmrc".
verbose 0.252 Checking for configuration file "C:\\Users\\dulls\\AppData\\Local\\.npmrc".
verbose 0.253 Checking for configuration file "C:\\Users\\dulls\\AppData\\.npmrc".
verbose 0.254 Checking for configuration file "C:\\Users\\dulls\\.npmrc".
verbose 0.254 Found configuration file "C:\\Users\\dulls\\.npmrc".
verbose 0.255 Checking for configuration file "C:\\Users\\.npmrc".
verbose 0.256 Checking for configuration file "C:\\Users\\dulls\\AppData\\Local\\Yarn\\Data\\global\\.yarnrc".
verbose 0.257 Checking for configuration file "C:\\Users\\dulls\\.yarnrc".
verbose 0.258 Found configuration file "C:\\Users\\dulls\\.yarnrc".
verbose 0.258 Checking for configuration file "D:\\Program Files\\node\\etc\\yarnrc".
verbose 0.259 Checking for configuration file "C:\\Users\\dulls\\AppData\\Local\\Yarn\\Data\\global\\.yarnrc".
verbose 0.259 Checking for configuration file "C:\\Users\\dulls\\AppData\\Local\\Yarn\\Data\\.yarnrc".
verbose 0.263 Checking for configuration file "C:\\Users\\dulls\\AppData\\Local\\Yarn\\.yarnrc".
verbose 0.264 Checking for configuration file "C:\\Users\\dulls\\AppData\\Local\\.yarnrc".
verbose 0.265 Checking for configuration file "C:\\Users\\dulls\\AppData\\.yarnrc".
verbose 0.266 Checking for configuration file "C:\\Users\\dulls\\.yarnrc".
verbose 0.267 Found configuration file "C:\\Users\\dulls\\.yarnrc".
verbose 0.267 Checking for configuration file "C:\\Users\\.yarnrc".
[1/4] Resolving packages...
verbose 0.316 Performing "GET" request to "https://registry.npm.taobao.org/js-cookie".
verbose 0.485 Request "https://registry.npm.taobao.org/js-cookie" finished with status code 200.
[2/4] Fetching packages...
verbose 0.5 Performing "GET" request to "http://registry.npm.taobao.org/js-cookie/download/js-cookie-2.2.0.tgz".
verbose 1.667 Error: http://registry.npm.taobao.org/js-cookie/download/js-cookie-2.2.0.tgz: Parse Error
    at Socket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
error An unexpected error occurred: "http://registry.npm.taobao.org/js-cookie/download/js-cookie-2.2.0.tgz: Parse Error".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\dulls\\AppData\\Local\\Yarn\\Data\\global\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
[yarn-error.log](https://github.com/yarnpkg/yarn/files/3044303/yarn-error.log)

```

**Comment by bb1** [comment]
Have you tried a different registry? For example:
`yarn config set registry "https://registry.yarnpkg.com"`

**Comment by CatchLife** [comment]
@bb1 yes,if i use https://registry.yarnpkg.com,it works well,but when i set other registry, like `https://registry.npm.taobao.org/` it show `Parse Error`
I have two computers. In order to find out the reason, I installed same versions of node(8.11.2),yarn(1.15.2),npm(6.9). The registry is all replaced with https://registry.npm.taobao.org/, but the final result is that linux works well, windows10 Parse Error
i am in china, so the registry `https://registry.npm.taobao.org/` download speed is quikly
I guess there may be a difference between the same version of different platforms.

**Comment by bb1** [comment]
@CatchLife you should add to your title that it only fails when using taobao's registry. It is possible that they change some packages or return different headers.
As a workaround you maybe just need to use the original npm registry which now uses Cloudflare's infrastructure and should be fast even in China.

`yarn config set registry "https://registry.npmjs.com/"`
