### ISSUE TITLE
Syntax Error when Running yarn start on windows

### ISSUE THREAD

**Issue by 1omarsaid** [yarnpkg/yarn#7219]
When running yarn start on Windows 10 enterprise, it seems to have a Syntax Error thats preventing it from executing. The following is the error that I recieve in the Command line when I run "yarn start"

```yarn run v1.15.2
$ node --max_old_space_size=8192 ./node_modules/.bin/ng serve -H 0.0.0.0 --disable-host-check
C:\Users\OMARSaid\cui-shell-ui-develop\node_modules\.bin\ng:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')");
          ^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

**Please mention your node.js, yarn and operating system version.**
Node: v10.15.1
Yarn: v1.15.2
Windows 10

**Comment by blaskovicz** [comment]
What does your package.json look like?

**Comment by paul-soporan** [comment]
You're trying to run a shell binary with node.
