### ISSUE TITLE
Yarn errors when trying to create a React app 

### ISSUE THREAD

**Issue by Aristophanes888** [yarnpkg/yarn#7222]
I try to create a react app with the following command:
`create-react-app eth-todo-list-react`

I then receive these errors

```
'yarnpkg' is not recognized as an internal or external command,
operable program or batch file.
Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...

'yarnpkg' is not recognized as an internal or external command,
operable program or batch file.
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarnpkg ENOENT
    at notFoundError (C:\Users\Aristophanes\node_modules\create-react-app\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\Aristophanes\node_modules\create-react-app\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\Aristophanes\node_modules\create-react-app\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
Emitted 'error' event at:
    at ChildProcess.cp.emit (C:\Users\Aristophanes\node_modules\create-react-app\node_modules\cross-spawn\lib\enoent.js:30:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
```

Any help fixing this would be much appreciated, thanks.

**Comment by DanielRuf** [comment]
Hi @Aristophanes888,

it seems you have not correctly installed yarn.

What does the following output?

`where yarnpkg`

**Comment by DanielRuf** [comment]
In general it is an issue in `create-react-app`, not in Yarn.
