### ISSUE TITLE
Cannot find module 'mkdirp' when installing node-sass

### ISSUE THREAD

**Issue by SarKurd** [yarnpkg/yarn#7249]
I reinstalled Yarn and Node again but didn't resolve, i tried npm and it works

Yarn version: 1.15.2
OS: windows 10
Node: 10.15.3 LTS

```
Exit code: 1
Command: node scripts/install.js
Arguments:
Directory: C:\Users\user\Documents\Web Projects\personal\node_modules\node-sass
Output:
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\user\Documents\Web Projects\personal\node_modules\node-sass\scripts\install.js:7:11)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by DanielRuf** [comment]
Hi @SarKurd,

I can not reproduce it:

```
node-sass-test nodenv local 10.15.3
➜  node-sass-test yarn add node-sass
yarn add v1.16.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 150 new dependencies.
info Direct dependencies
└─ node-sass@4.12.0
info All dependencies
...
✨  Done in 9.42s.
➜  node-sass-test stat node_modules/.bin/mkdirp
16777220 8692704835 lrwxr-xr-x 1 druf UEBERBIT\Domänen-Benutzer 0 20 "Jun  5 08:19:36 2019" "Jun  5 08:19:36 2019" "Jun  5 08:19:36 2019" "Jun  5 08:19:36 2019" 4096 0 0 node_modules/.bin/mkdirp
```

**Comment by DanielRuf** [comment]
Hi @SarKurd,

I can not reproduce it (on macOS):

```
node-sass-test nodenv local 10.15.3
➜  node-sass-test yarn add node-sass
yarn add v1.16.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 150 new dependencies.
info Direct dependencies
└─ node-sass@4.12.0
info All dependencies
...
✨  Done in 9.42s.
➜  node-sass-test stat node_modules/.bin/mkdirp
16777220 8692704835 lrwxr-xr-x 1 druf UEBERBIT\Domänen-Benutzer 0 20 "Jun  5 08:19:36 2019" "Jun  5 08:19:36 2019" "Jun  5 08:19:36 2019" "Jun  5 08:19:36 2019" 4096 0 0 node_modules/.bin/mkdirp
```

Does this still occur on your side? I also have `node-sass` projects on my Windows 10 computer and never had this issue.

We can do a small test on TravisCI using Windows if you want to test this.

**Comment by SarKurd** [comment]
Hello @DanielRuf the very next day it started working again. I have no idea what caused that.

I forgot to close this issue, sorry.

**Comment by ccarterc** [comment]
This issue still exists on Ubuntu 16 and Ubuntu 18 using Node 10.16.0 and yarn 1.17.3

**Comment by DanielRuf** [comment]
@ccarterccan you add more information like the output that you get and the steps that you have done?
