### ISSUE TITLE
Installation Problem: Debian GNU/Linux 9.9

### ISSUE THREAD

**Issue by dertin** [yarnpkg/yarn#7355]
**Which operating system are you using:**
Debian GNU/Linux 9.9

**Please describe the steps you took when trying to install Yarn and what went wrong:**
1. https://yarnpkg.com/en/docs/install#debian-stable
2. $ yarn --version

```
/usr/share/yarn/lib/cli.js:45703
  let {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/share/yarn/bin/yarn.js:24:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by dertin** [comment]
Fix:
```
# Using Debian, as root
curl -sL https://deb.nodesource.com/setup_12.x | bash -
apt-get install -y nodejs
```
