### ISSUE TITLE
yarn install fails on openbsd

### ISSUE THREAD

**Issue by raedah** [yarnpkg/yarn#7382]
including relevant log sections that mention the failing build flags.

**cc1plus: error: unrecognized command line option "-std=gnu++1y"
cc1plus: error: unrecognized command line option "-std=c++0x"**

```
gmake: Entering directory '/home/x/code/myapp/web/public/app/node_modules/node-sass/build'
  g++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.5.4"' -I/home/x/.node-gyp/10.15.0/include/node -I/home/x/.node-gyp/10.15.0/src -I/home/x/.node-gyp/10.15.0/deps/openssl/config -I/home/x/
.node-gyp/10.15.0/deps/openssl/openssl/include -I/home/x/.node-gyp/10.15.0/deps/uv/include -I/home/x/.node-gyp/10.15.0/deps/zlib -I/home/x/.node-gyp/10.15.0/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -I/usr/local/include -O3 -fno-omit-frame-pointer -std=gnu++1y -s
td=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
cc1plus: error: unrecognized command line option "-std=gnu++1y"
cc1plus: error: unrecognized command line option "-std=c++0x"
gmake: *** [src/libsass.target.mk:152: Release/obj.target/libsass/src/libsass/src/ast.o] Error 1
gmake: Leaving directory '/home/x/code/myapp/web/public/app/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/x/code/myapp/web/public/app/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System OpenBSD 6.5
gyp ERR! command "/usr/local/bin/node" "/home/x/code/myapp/web/public/app/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/x/code/myapp/web/public/app/node_modules/node-sass
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
```

**Comment by epsilon-0** [comment]
Same here!
Seems like it is trying to use g++ instead of c++ which seems like a problem.

It could be fixed by defaulting to the system compiler

**Comment by epsilon-0** [comment]
Referenced by this: https://github.com/Chocobozzz/PeerTube/issues/160

**Comment by paul-soporan** [comment]
Closing as an external issue (we don't control `node-gyp` errors).
