### ISSUE TITLE
lost dependence

### ISSUE THREAD

**Issue by yoyo837** [yarnpkg/yarn#7399]
**Do you want to request a *feature* or report a *bug*?**

Bug
**What is the current behavior?**
Lost dependence
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**
node.js `v10.14.2`, yarn `v1.17.3`, MacOS latest

```
Build failed: [BABEL] /data/opt/jenkins_workspace_test/ydmap-cloud/ydmap-web-cloud/.webpackrc.js: Cannot find module 'babel-plugin-dynamic-import-node/utils' (While processing: "/data/opt/jenkins_workspace_test/ydmap-cloud/ydmap-web-cloud/node_modules/af-webpack/node_modules/@babel/plugin-transform-modules-commonjs/lib/index.js")
{ Error: [BABEL] /data/opt/jenkins_workspace_test/ydmap-cloud/ydmap-web-cloud/.webpackrc.js: Cannot find module 'babel-plugin-dynamic-import-node/utils' (While processing: "/data/opt/jenkins_workspace_test/ydmap-cloud/ydmap-web-cloud/node_modules/af-webpack/node_modules/@babel/plugin-transform-modules-commonjs/lib/index.js")
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at _utils (/data/opt/jenkins_workspace_test/ydmap-cloud/ydmap-web-cloud/node_modules/af-webpack/node_modules/@babel/plugin-transform-modules-commonjs/lib/index.js:49:16)
    at _default (/data/opt/jenkins_workspace_test/ydmap-cloud/ydmap-web-cloud/node_modules/af-webpack/node_modules/@babel/plugin-transform-modules-commonjs/lib/index.js:62:35)
    at /data/opt/jenkins_workspace_test/ydmap-cloud/ydmap-web-cloud/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at loadDescriptor (/data/opt/jenkins_workspace_test/ydmap-cloud/ydmap-web-cloud/node_modules/af-webpack/node_modules/@babel/core/lib/config/full.js:165:14)
    at cachedFunction (/data/opt/jenkins_workspace_test/ydmap-cloud/ydmap-web-cloud/node_modules/af-webpack/node_modules/@babel/core/lib/config/caching.js:33:19)
    at loadPluginDescriptor (/data/opt/jenkins_workspace_test/ydmap-cloud/ydmap-web-cloud/node_modules/af-webpack/node_modules/@babel/core/lib/config/full.js:200:28)
    at config.plugins.reduce (/data/opt/jenkins_workspace_test/ydmap-cloud/ydmap-web-cloud/node_modules/af-webpack/node_modules/@babel/core/lib/config/full.js:69:20)
    at Array.reduce (<anonymous>)
    at recurseDescriptors (/data/opt/jenkins_workspace_test/ydmap-cloud/ydmap-web-cloud/node_modules/af-webpack/node_modules/@babel/core/lib/config/full.js:67:38)
    at loadFullConfig (/data/opt/jenkins_workspace_test/ydmap-cloud/ydmap-web-cloud/node_modules/af-webpack/node_modules/@babel/core/lib/config/full.js:108:6)
    at loadOptions (/data/opt/jenkins_workspace_test/ydmap-cloud/ydmap-web-cloud/node_modules/af-webpack/node_modules/@babel/core/lib/config/index.js:27:36)
    at OptionManager.init (/data/opt/jenkins_workspace_test/ydmap-cloud/ydmap-web-cloud/node_modules/af-webpack/node_modules/@babel/core/lib/index.js:231:36) code: 'MODULE_NOT_FOUND' }
```

![image](https://user-images.githubusercontent.com/6134547/61182650-e75dbb00-a668-11e9-9a82-8ec2d99df406.png)

**Comment by yoyo837** [comment]
`yarn upgrade` fix this.
