### ISSUE TITLE
Nvm install + Yarn --version return error for node 4 and node 5

### ISSUE THREAD

**Issue by VincentLanglet** [yarnpkg/yarn#7447]
**What is the current behavior?**

In my CI.

```
nvm install 4
yarn --version
```
or
```
nvm install 5
yarn --version
```
return the following error
```
/usr/local/yarn-latest/lib/cli.js:45699
  let {
      ^
SyntaxError: Unexpected token {
    at NativeCompileCache._moduleCompile (/usr/local/yarn-latest/lib/v8-compile-cache.js:226:18)
    at Module._compile (/usr/local/yarn-latest/lib/v8-compile-cache.js:172:36)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/yarn-latest/bin/yarn.js:24:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**What is the expected behavior?**

No error

But when I look at your CI, you have test for node 4.
Am I missing something or your tests does not check the real support of yarn for old node version ?

**Comment by rally25rs** [comment]
duplicate #6619
