### ISSUE TITLE
yarn install fails when using modules-folder flag

### ISSUE THREAD

**Issue by alexrs** [yarnpkg/yarn#7467]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`yarn install --modules-folder another_modules` fails with

```
$ /usr/local/bin/yarn install --modules-folder another_modules

error another_modules/realm: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: another_modules/realm
Output:
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'nopt'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (PATH/another_modules/node-pre-gyp/lib/node-pre-gyp.js:15:12)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Steps to reproduce:
1. Remove `node_modules`
2. `yarn cache clean`
3. yarn install --modules-folder another_modules

This error might be specific to Realm. Running `yarn install` or `yarn install --modules-folder node_modules` works as expected.

**What is the expected behavior?**
The modules are successfully installed, as when running `yarn install`, but in the folder specified in `--modules-folder` instead of in `node_modules`.

**Please mention your node.js, yarn and operating system version.**
node v10.14.1, yarn 1.17.3, macOS 10.14.5

**Comment by allenwu1973** [comment]
I also failed to install package when modules-folder was specified
Might be the same issue

```bash
$ yarn add coffeescript --modules-folder x --ignore-scripts
yarn add v1.17.3
warning package.json: No license field
info No lockfile found.
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning Ignored scripts due to flag.
success Saved lockfile.
warning No license field
success Saved 127 new dependencies.
info Direct dependencies
├─ babel-cli@6.26.0
└─ coffeescript@2.4.1
info All dependencies
├─ ansi-styles@2.2.1
├─ anymatch@1.3.2
├─ arr-flatten@1.1.0
├─ assign-symbols@1.0.0
├─ async-each@1.0.3
├─ atob@2.1.2
├─ babel-cli@6.26.0
├─ babel-generator@6.26.1
├─ babel-helpers@6.24.1
├─ babel-polyfill@6.26.0
├─ babel-template@6.26.0
├─ balanced-match@1.0.0
├─ base@0.11.2
├─ binary-extensions@1.13.1
├─ brace-expansion@1.1.11
├─ braces@1.8.5
├─ cache-base@1.0.1
├─ chalk@1.1.3
├─ chokidar@1.7.0
├─ class-utils@0.3.6
├─ coffeescript@2.4.1
├─ collection-visit@1.0.0
├─ commander@2.20.0
├─ concat-map@0.0.1
├─ convert-source-map@1.6.0
├─ copy-descriptor@0.1.1
├─ core-util-is@1.0.2
├─ debug@2.6.9
├─ decode-uri-component@0.2.0
├─ detect-indent@4.0.0
├─ escape-string-regexp@1.0.5
├─ expand-brackets@0.1.5
├─ expand-range@1.8.2
├─ extglob@0.3.2
├─ filename-regex@2.0.1
├─ fill-range@4.0.0
├─ for-in@1.0.2
├─ for-own@0.1.5
├─ fs-readdir-recursive@1.1.0
├─ fs.realpath@1.0.0
├─ get-value@2.0.6
├─ glob-base@0.3.0
├─ glob@7.1.4
├─ globals@9.18.0
├─ graceful-fs@4.2.2
├─ has-ansi@2.0.0
├─ has-value@1.0.0
├─ has-values@1.0.0
├─ home-or-tmp@2.0.0
├─ inflight@1.0.6
├─ inherits@2.0.4
├─ invariant@2.2.4
├─ is-accessor-descriptor@1.0.0
├─ is-binary-path@1.0.1
├─ is-data-descriptor@1.0.0
├─ is-descriptor@1.0.2
├─ is-dotfile@1.0.3
├─ is-equal-shallow@0.1.3
├─ is-finite@1.0.2
├─ is-plain-object@2.0.4
├─ is-posix-bracket@0.1.1
├─ is-primitive@2.0.0
├─ is-windows@1.0.2
├─ isarray@1.0.0
├─ js-tokens@3.0.2
├─ jsesc@1.3.0
├─ json5@0.5.1
├─ kind-of@3.2.2
├─ loose-envify@1.4.0
├─ map-visit@1.0.0
├─ math-random@1.0.4
├─ micromatch@2.3.11
├─ minimatch@3.0.4
├─ minimist@0.0.8
├─ mixin-deep@1.3.2
├─ mkdirp@0.5.1
├─ ms@2.0.0
├─ nanomatch@1.2.13
├─ normalize-path@2.1.1
├─ number-is-nan@1.0.1
├─ object-assign@4.1.1
├─ object-copy@0.1.0
├─ object.omit@2.0.1
├─ os-homedir@1.0.2
├─ os-tmpdir@1.0.2
├─ output-file-sync@1.1.2
├─ parse-glob@3.0.4
├─ pascalcase@0.1.1
├─ path-is-absolute@1.0.1
├─ posix-character-classes@0.1.1
├─ preserve@0.2.0
├─ private@0.1.8
├─ process-nextick-args@2.0.1
├─ randomatic@3.1.1
├─ readable-stream@2.3.6
├─ readdirp@2.2.1
├─ regenerator-runtime@0.10.5
├─ regex-cache@0.4.4
├─ regex-not@1.0.2
├─ remove-trailing-separator@1.1.0
├─ repeating@2.0.1
├─ resolve-url@0.2.1
├─ ret@0.1.15
├─ safe-buffer@5.1.2
├─ set-value@2.0.1
├─ snapdragon-node@2.1.1
├─ snapdragon-util@3.0.1
├─ source-map-resolve@0.5.2
├─ source-map-support@0.4.18
├─ source-map-url@0.4.0
├─ source-map@0.5.7
├─ split-string@3.1.0
├─ static-extend@0.1.2
├─ string_decoder@1.1.1
├─ strip-ansi@3.0.1
├─ supports-color@2.0.0
├─ to-fast-properties@1.0.3
├─ to-object-path@0.3.0
├─ to-regex-range@2.1.1
├─ trim-right@1.0.1
├─ union-value@1.0.1
├─ unset-value@1.0.0
├─ urix@0.1.0
├─ use@3.1.1
├─ user-home@1.1.1
├─ util-deprecate@1.0.2
└─ v8flags@2.1.1
Done in 1.29s.

$ yarn add babel --modules-folder x --ignore-scripts
yarn add v1.17.3
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
warning babel@6.23.0: In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/tmp/bug/x/babylon'".
info If you think this is a bug, please open a bug report with the information provided in "/tmp/bug/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by poradz** [comment]
Same here. Without `--modules-folder` everything works fine.

Error message:
`Exit code: 1
Command: opencollective-postinstall || true
Arguments:
Directory: public_html\libraries\flag-icon-css
Output:
'opencollective-postinstall' is not recognized as an internal or external command,
operable program or batch file.
'true' is not recognized as an internal or external command,
operable program or batch file.
`


Full script:
`
$ yarn install --modules-folder "./public_html/libraries" --ignore-optional --production=true
[1/5] Resolving packages...
[2/5] Fetching packages...
[3/5] Linking dependencies...
warning " > leaflet.markercluster@1.4.1" has incorrect peer dependency "leaflet@~1.3.1".
[4/5] Building fresh packages...
[1/2] ⠂ core-js                                                                                                                                                                                                                              error public_html\libraries\flag-icon-css: Command failed.
Exit code: 1
Command: opencollective-postinstall || true
Arguments:
Directory: public_html\libraries\flag-icon-css
Output:
'opencollective-postinstall' is not recognized as an internal or external command,
operable program or batch file.
'true' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by dastanko** [comment]
same here: `yarn --modules-folder ../some_folder`

```
error ../some_folder/gifsicle: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments: 
Directory: ../some_dumb_folder/gifsicle
Output:
module.js:550
    throw err;
    ^

Error: Cannot find module 'bin-build'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/some_dumb_folder/gifsicle/lib/install.js:2:16)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
```

**Comment by poradz** [comment]
I've figured out, that after removing modules folder with partially downloaded libraries and run yarn install again error doesn't appear. It shouldn't work like that, but apparently removing destination folder before yarn install with --modules-folder flag solves many problems.

**Comment by humodz** [comment]
In my case (installing bcrypt), I had to manually change PATH, so that node-pre-gyp could be found. The error didn't stop by removing the modules folder, as suggested above, or changing NODE_PATH, [as suggested in this grpc issue](https://github.com/grpc/grpc-node/issues/875).

Steps to reproduce problem:
```sh
yarn init -y
yarn add bcrypt
yarn install --modules-folder somewhere
```
```
Output:
/bin/sh: 1: node-pre-gyp: not found
```

The fix (without resorting to installing node-pre-gyp globally):
```sh
PATH="node_modules/.bin" yarn install --modules-folder somewhere
```

**Comment by nicolaelitvac** [comment]
Had same issue.
Found a simple solution. Make sure the last folder name from your custom `modules-folder` is `node_modules`.
Example:
```bash
yarn install --modules-folder /your/custom/path/node_modules
```
