### ISSUE TITLE
https://registry.yarnpkg.com/Alodash: Not found

### ISSUE THREAD

**Issue by AxelDaguerreHV** [yarnpkg/yarn#7482]
Hi, 
I am having an issue with yarn in my project and i couldn't find something usefull formy case.
This is what i have wathever i try to do with the CLI of yarn, i can't add a package, do an audit or anything because it say that :
`error An unexpected error occurred: "https://registry.yarnpkg.com/Alodash: Not found"`

This is my log for the issue : 
`Arguments: 
  C:\Program Files\nodejs\node.exe C:\Program Files (x86)\Yarn\bin\yarn.js audit

PATH: 
  C:\Users\Fujitsu\Programs-lito\cmder\bin;C:\Users\Fujitsu\Programs-lito\cmder\vendor\bin;C:\Scripts;C:\Users\Fujitsu\Programs-lito\cmder\vendor\conemu-maximus5;C:\Users\Fujitsu\Programs-lito\cmder\vendor\conemu-maximus5\ConEmu;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Process Lasso\;C:\Program Files\Git\cmd;C:\MinGW\bin;C:\MinGW\bin\gdb.exe;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin\;W:\arcadia_engine\misc;W:\arcadia_engine\code;C:\Program Files\emacs\bin;C:\Program Files\LLVM\bin;C:\Ruby25-x64\bin;C:\Users\Fujitsu\AppData\Local\Microsoft\WindowsApps;C:\Users\Fujitsu\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Fujitsu\AppData\Roaming\npm;C:\Users\Fujitsu\AppData\Local\Yarn\bin;C:\Users\Fujitsu\AppData\Local\GitHubDesktop\bin;C:\Users\Fujitsu\AppData\Local\atom\bin;C:\Program Files\heroku\bin;C:\Program Files\LLVM\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Fujitsu\Programs-lito\cmder

Yarn version: 
  1.17.3

Node version: 
  10.16.0

Platform: 
  win32 x64

Trace: 
  Error: https://registry.yarnpkg.com/Alodash: Not found
      at Request.params.callback [as _callback] (C:\Program Files (x86)\Yarn\lib\cli.js:65939:18)
      at Request.self.callback (C:\Program Files (x86)\Yarn\lib\cli.js:140464:22)
      at Request.emit (events.js:198:13)
      at Request.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:141436:10)
      at Request.emit (events.js:198:13)
      at IncomingMessage.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:141358:12)
      at Object.onceWrapper (events.js:286:20)
      at IncomingMessage.emit (events.js:203:15)
      at endReadableNT (_stream_readable.js:1129:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

npm manifest: 
  {
    "name": "medical-front-end",
    "version": "1.0.0",
    "main": "index.js",
    "scripts": {
      "build:dev": "webpack --env dev",
      "build:prod": "webpack -p --env production",
      "dev-server": "webpack-dev-server",
      "start": "node server/server.js",
      "heroku-postbuild": "yarn run build:prod",
      "test": "jest"
    },
    "repository": "git@gitlab.com:AxelDaguerre/medical-front-end.git",
    "author": "daguerre axel <axeldaguerredev@gmail.com>",
    "license": "MIT",
    "dependencies": {
      "@babel/core": "^7.2.2",
      "@babel/plugin-proposal-class-properties": "^7.5.5",
      "@babel/plugin-proposal-object-rest-spread": "^7.5.5",
      "@babel/preset-env": "^7.5.5",
      "@babel/preset-react": "^7.0.0",
      "Alodash": "^4.17.15",
      "axios": "^0.19.0",
      "babel-cli": "^6.26.0",
      "babel-eslint": "^10.0.2",
      "babel-loader": "^8.0.6",
      "css-loader": "^3.1.0",
      "express": "^4.17.1",
      "formik": "^1.5.8",
      "history": "^4.9.0",
      "mini-css-extract-plugin": "^0.8.0",
      "moment": "^2.24.0",
      "node-sass": "^4.12.0",
      "normalize.css": "^8.0.1",
      "polyfill": "^0.1.0",
      "react": "^16.8.6",
      "react-addons-shallow-compare": "^15.6.2",
      "react-dates": "^20.2.5",
      "react-dom": "^16.8.6",
      "react-loader": "^2.4.5",
      "react-modal": "^3.9.1",
      "react-redux": "^7.1.0",
      "react-router-dom": "5.0.1",
      "react-toastify": "^5.3.2",
      "redux": "^4.0.4",
      "redux-thunk": "^2.3.0",
      "sass-loader": "^7.1.0",
      "uuid": "^3.3.2",
      "webpack": "^4.39.1",
      "yup": "^0.27.0"
    },
    "devDependencies": {
      "cross-env": "^5.2.0",
      "dotenv": "^8.0.0",
      "eslint": "^6.1.0",
      "eslint-config-standard": "^13.0.1",
      "eslint-config-standard-react": "^8.0.0",
      "eslint-plugin-import": "^2.18.2",
      "eslint-plugin-node": "^9.1.0",
      "eslint-plugin-promise": "^4.2.1",
      "eslint-plugin-react": "^7.14.3",
      "eslint-plugin-react-redux": "^3.0.1",
      "eslint-plugin-standard": "^4.0.0",
      "jest": "^24.9.0",
      "prop-types": "^15.7.2",
      "scss-lint": "^0.0.0",
      "webpack-cli": "^3.2.1",
      "webpack-dev-server": "^3.7.2"
    }
  }

yarn manifest: 
  No manifest`

I tried outside of my project and Yarn actually works, so i presume that it is somethingto do with my settings in this project. 
What this occured i was installing eslint-jest, this is actually my first failling, but it was the first i did today so notsure if it is relevant.
I am really stuck right now, i hope i amin the good place.

**Comment by AxelDaguerreHV** [comment]
The strange thing is when i write the adress in my browser with a `a` instead of a `A` i got JSON data, i found an email adress and write to the guy who is maintain it, so maybe it is not Yarn related. I am Lost right now
