### ISSUE TITLE
"Could not find package" XXX "in the registry" npm "

### ISSUE THREAD

**Issue by R1cro** [yarnpkg/yarn#7696]
**Do you want to request a *feature* or report a *bug*?**

I'm reporting a bug.

**What is the current behavior?**
I'm trying to set packages during the *yarn add*

**If the current behavior is a bug, please provide the steps to reproduce.**

I try to install packages during *yarn add*, but it seems that sometimes it returns me errors like "Could not find package" XXX "in the registry" npm ".

I had this problem last Saturday and I thought that I had problems with the system. Nevertheless, I was convinced that the problem is not on my side, as I tried to execute this command with two different machines (and different networks).

```
[1/4] 🔍  Resolving packages...
error Couldn't find package "dns-txt" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Couldn't find package "cookie-signature" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.19.1/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.19.1/libexec/lib/cli.js:750:123)
    at NpmResolver.<anonymous> (/usr/local/Cellar/yarn/1.19.1/libexec/lib/cli.js:50683:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.19.1/libexec/lib/cli.js:304:30)
    at /usr/local/Cellar/yarn/1.19.1/libexec/lib/cli.js:315:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

```

**What is the expected behavior?**

All packages should be installed correctly.

**Please mention your node.js, yarn and operating system version.**
Node: **v8.16.2**
Yarn **1.19.1**
OS: **macOS Mojave 10.14.6**

**Comment by emision** [comment]
Same problem with  "ignore-walk" package

`verbose 1.606 Performing "GET" request to "https://registry.npmjs.org/ignore-walk".
verbose 1.631 Request "https://registry.npmjs.org/ignore-walk" finished with status code 404.
verbose 1.718 Error: Couldn't find package "ignore-walk" on the "npm" registry.
error Couldn't find package "ignore-walk" on the "npm" registry.      `

**Comment by novli** [comment]
Appears to be related to #7691

**Comment by ERRORthenBSOD** [comment]
Same

> error Couldn't find package "simple-assign" on the "npm" registry.
> error Couldn't find package "normalize-range" on the "npm" registry.
> error Couldn't find package "create-react-class" on the "npm" registry.
and others...

**Comment by michaelbats** [comment]
I'm getting this in the UK. VPN does not affect it. I'm trying to use it with github package registry configured as such :

```
registry=https://npm.pkg.github.com/tlabs
```

**Comment by AndreyPatseiko** [comment]
I don't understand how this work but after `yarn init` I can install all packages.

**Comment by michaelbats** [comment]
That does not do anything for me.

**Comment by PavelDemyanenko** [comment]
Same behaviour on yarn install, and npm install works as expected.

Error: Couldn't find package "some packege" on the "npm" registry. VPN is configured. 

Node: 11.12
Yarn 1.19.1
Win 10

**Comment by zeroidentidad** [comment]
Same issue with **react-navigation** dependencies
Another issue with **react-scripts** dependencies eg.

> error Couldn't find package "@typescript-eslint/eslint-plugin@^2.2.0" required by "react-scripts" on the "npm" registry.
> info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
> 
> Aborting installation.
>   yarnpkg add --exact react react-dom react-scripts --cwd /home/chucho/nodedocs/javascript_fullstack/frontend/ejemplos_vue-react/react-eventos has failed.

**Comment by zeroidentidad** [comment]
I got it, in my case I just have to update react's cli tools...
Thats fixed it :v

**Comment by zeroidentidad** [comment]
**yarn already have a new update today** :)

**Comment by R1cro** [comment]
Hey, guys. Seems to be the problems disappeared. Could somebody confirm that, please?

**Comment by andrewoh531** [comment]
I'm still getting this error with `@types/storybook__react`. The package is deprecated but I'm trying to pull down a previous version.

This works fine with npm.

```
error Couldn't find package "storybook__react@*" required by "@types/storybook__react@*" on the "npm" registry.
```

**Comment by elie222** [comment]
@andrewoh531 I just ran into the same issue. I ended up removing `@types/storybook__react` and a deprecated package that was depending on it. I think it was knob_addons types.
