### ISSUE TITLE
Error while running yarn install - error:0909006C:PEM routines:get_name:no start line

### ISSUE THREAD

**Issue by dvdssali** [yarnpkg/yarn#7719]
Trace: 
  Error: https://registry.yarnpkg.com/@apollo/react-hooks/-/react-hooks-3.0.1.tgz: error:0909006C:PEM routines:get_name:no start line
      at Object.createSecureContext (_tls_common.js:151:17)
      at Object.connect (_tls_wrap.js:1407:48)
      at Agent.createConnection (https.js:125:22)
      at Agent.createSocket (_http_agent.js:234:26)
      at Agent.addRequest (_http_agent.js:193:10)
      at new ClientRequest (_http_client.js:276:16)
      at Object.request (https.js:309:10)
      at Request.module.exports.Request.start (/usr/local/Cellar/yarn/1.19.2/libexec/lib/cli.js:141148:32)
      at Request.module.exports.Request.end (/usr/local/Cellar/yarn/1.19.2/libexec/lib/cli.js:141907:10)
      at end (/usr/local/Cellar/yarn/1.19.2/libexec/lib/cli.js:140961:14)

**Comment by dhaileytaha** [comment]
@dvdssali  Did you find any solution?
