### ISSUE TITLE
Some workspaces functionality appears to be broken - had to revert to 1.16

### ISSUE THREAD

**Issue by DavideDaniel** [yarnpkg/yarn#7734]
^ Problems started with upgrading to 1.19 and then snowballed into 5 hours of hell trying to figure out what went wrong.
**Do you want to request a *feature* or report a *bug*?**
`error An unexpected error occurred: "expected workspace package to exist for \"rimraf\""`
It started with some dev dependency in a workspace repo and after messing around with nohoist settings I started noticing that the same modules keep coming up. Rimraf, inquirer, react-dev-tools.. generally things that were listed many times over in transitive dependencies. Read through many different similar issues regarding symlinks but ended up being unable to add new modules through cli which was the problem I was trying to address for automation.

**What is the current behavior?**
`yarn workspace @scope/A add js-cookie react react-redux uuid lodash.get --dev`
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**

**Comment by DavideDaniel** [comment]
For anyone that comes looking for a quick fix.. I was able to get back to a working state by installing v16.0 https://raw.githubusercontent.com/karlhorky/homebrew-core/f8bc263f93dcfd1cc50c98976a8503c8a7cb032f/Formula/yarn.rb via homebrew. I'm gonna try seeing if the security update with 1.17.4 works and go as far up as I can without losing functionality.

**Comment by DavideDaniel** [comment]
A clue about symlink issues while running `--verbose`.  The `uuid` module keeps missing even as far back as 1.16. The common pattern right now appears to be modules that are used in many other modules but are listed as a peerDependency in a workspace can run into issues with workspace aggregator during certain cli commands. This could be because a lot of commonly used modules are listed as peerDependencies vs dependencies, following advice from https://yarnpkg.com/blog/2018/04/18/dependencies-done-right/.

**Comment by DavideDaniel** [comment]
![image](https://user-images.githubusercontent.com/8802938/70212495-3aa1da00-16ec-11ea-9eca-f810807fc41a.png)
I have a feeling 2.0 will address this with the above.. but still unsure why this became a bigger problem  past 1.16. Is it because changes to 1.16 are being made with the same lens applied for code going in for 2.0? If so, should we just consider pinning our version of yarn and wait for 2.0 if we are using workspaces?

**Comment by danoc** [comment]
I think we're running into this issue at @thumbtack. In particular, this affects us when trying to upgrade a package within a workspace.

This snippet should reproduce the issue:

```bash
git clone git@github.com:thumbtack/thumbprint.git && cd thumbprint && yarn && cd packages/thumbprint-react && yarn upgrade @thumbtack/thumbprint-tokens --latest
```

**Comment by danoc** [comment]
Confirmed that downgrading Yarn to 1.16.0 works. Thanks for digging into this, @DavideDaniel. Saved me lots of time!

Here are downgrade instructions for those that installed with Homebrew:
https://github.com/thumbtack/thumbprint/issues/592#issuecomment-565564993

**Comment by troywweber7** [comment]
Downgrading worked for me. But I'd definitely like to see this fixed in the latest version of yarn so I'm not lagging behind by 5 minor versions... yikes!

**Comment by iplus26** [comment]
Downgrading to v1.19.0 worked for me. Looking forward to fix this~

**Comment by roni-frantchi** [comment]
> Downgrading to v1.19.0 worked for me. Looking forward to fix this~

Same here.

**Comment by amirburbea** [comment]
Any update on this?

**Comment by troywweber7** [comment]
I just want to hop in and clarify my situation, in case it helps anyone else.

### Failing Command

The commands that were failing for me were of the `yarn workspace ${workspace} add ${package}` variety.

### Working Yarn Version

The indicated command is FAILING for me when using `yarn=1.19.2-1` is SUCCEEDING for me when using `yarn=1.19.1-1`.

### Install Older Yarn

First, follow the directions here: https://yarnpkg.com/lang/en/docs/install/#debian-stable

However, when it comes to the installation command, `sudo apt update && sudo apt install -y --no-install-recommends yarn`, you'll want to change `yarn` to `yarn=${version}`. You can find appropriate versions by doing `apt-cache policy yarn`.

Once you install a yarn version, you may also want to consider doing a `sudo apt-mark hold yarn` until this is resolved in later versions, otherwise `apt upgrade` will update your yarn again. You can confirm it is held by doing `apt-mark showhold`.

**Comment by narwold** [comment]
We are experiencing the same issue. Our message is as follows:

```
An unexpected error occurred: "expected workspace package to exist for \"@babel/traverse\"".
```

**Comment by StephenHaney** [comment]
Also experiencing this, here's our info – happy to provide anything else that might be useful.

Setup: basic workspace monorepo, not using lerna.

In:
`yarn add ts-jest -D`

Out:
`error An unexpected error occurred: "expected workspace package to exist for \"string-width\"".`

string-width is there in my node_modules. I've tried with both string-width in the main workspace node_modules and `nohoist`ed.

**Comment by GeorgeTaveras1231** [comment]
My team is also experiencing this issue with version 1.21.1.

This is blocking us from addressing the security issue documented here: 

https://snyk.io/blog/understanding-filesystem-takeover-vulnerabilities-in-npm-javascript-package-manager/

**Comment by AndreyChernykh** [comment]
The same issue for our team. 

yarn `1.21.1`
node `v10.15.1`

**Comment by dmfilipenko** [comment]
`Invariant Violation: expected workspace package to exist for "core-js-compat"`
`yarn 1.21.1`
`node v13.2.0`

**Comment by 454de6e** [comment]
Same issue with `yarn 1.21.1` and `node v12.14.1`.

**Comment by IskanderMustafin** [comment]
Same here. 
```
yarn --version
1.21.1

node --version
v12.9.0
```

**Comment by DalderupMaurice** [comment]
same here 
```
node -v && yarn -v
v10.15.3
1.21.1
```

**Comment by aryzing** [comment]
For those looking for a solution that doesn't involve changing the version of yarn you're using, not that manually editing `package.json` to include the version of the package you want and then running the `yarn` command again works just fine. 

I was having a similar issue when running `yarn workspace <workspace> add <pkg>`, and resorted to manually amending that package's package.json and running yarn. Idea from [this post](https://github.com/yarnpkg/yarn/issues/7807#issuecomment-574702306).

**Comment by GeorgeTaveras1231** [comment]
@aryzing thanks for that suggestion and sharing a link to that post. However, in our team with use the `--frozen-lockfile` flag by default (by adding it to our `.yarnrc` file) to avoid accidental changes to dependencies. It seems like we would need to disable that feature in order to manually edit lockfiles -- and as a result, risk accidental changes to the dependencies across all workspaces, unless I'm missing something.

**Comment by codeitcody** [comment]
Here is a stack trace (node v12.14.0 , yarn v1.21.1):
```
verbose 2.685597913 Invariant Violation: expected workspace package to exist for "eslint-plugin-react"
    at invariant (/usr/local/Cellar/yarn/1.21.1/libexec/lib/cli.js:2314:15)
    at _loop2 (/usr/local/Cellar/yarn/1.21.1/libexec/lib/cli.js:94898:9)
    at PackageHoister.init (/usr/local/Cellar/yarn/1.21.1/libexec/lib/cli.js:94957:19)
    at PackageLinker.getFlatHoistedTree (/usr/local/Cellar/yarn/1.21.1/libexec/lib/cli.js:48743:20)
    at PackageLinker.<anonymous> (/usr/local/Cellar/yarn/1.21.1/libexec/lib/cli.js:48754:27)
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.21.1/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.21.1/libexec/lib/cli.js:328:14
    at new Promise (<anonymous>)
    at new F (/usr/local/Cellar/yarn/1.21.1/libexec/lib/cli.js:5301:28)
error An unexpected error occurred: "expected workspace package to exist for \"eslint-plugin-react\"".
```
This should definitely be marked as a bug in the PackageHoister.

**Comment by Meemaw** [comment]
This is a serious issue as it effectively prevents any package from being installed.

Any update on when this is supposed to be fixed?

**Comment by DalderupMaurice** [comment]
> This is a serious issue as it effectively prevents any package from being installed.
> 
> Any update on when this is supposed to be fixed?

you can manually adjust the package.json and run yarn install.
The only sad part about this is that you have to sort the packages yourself from A-Z when adding new packages 😂

**Comment by troywweber7** [comment]
Any update from yarn maintainers on whether this issue is even seen or recognized?

**Comment by friederbluemle** [comment]
Just updated to `1.22.0` via Homebrew and ran into this issue as well...

**Comment by pedroSoaresll** [comment]
> Just updated to `1.22.0` via Homebrew and ran into this issue as well...

sorry, to me the version `1.22.0` don't solve the problem. :disappointed:

**Comment by steffeli** [comment]
I've run into this problem as well a couple of weeks ago. Monorepo using Lerna and yarn workspaces. All of a sudden adding packages causes `An unexpected error occurred: "expected workspace package to exist for \"@typescript-eslint/eslint-plugin\""`. Upgraded to `1.22.0`, problem still persist.

Right now we have to manually add packages to the package.json and run `yarn install`.

**Comment by vleandersson** [comment]
Upgraded from `1.19.x` to `1.22.0` and ran into this issue. `yarn cache clean` solved the issue for me.

**Comment by jpaas** [comment]
I just tried again to upgrade from `1.16.x`. This time to `1.22.0`. The problem still exists for me. `yarn cache clean` did not help.

**Comment by webmaster128** [comment]
I get the same error when `yarn add`ing something to a package of [a monorepo](https://github.com/iov-one/ponferrada/):

> error An unexpected error occurred: "expected workspace package to exist for \"@storybook/react\"".

`@storybook/react` is installed in the monorepo root's `package.json` in the `devDependencies`. When I change the monorepo root's `devDependencies` to `dependencies`, the issue disappears. I don't think you should do that but maybe it helps understanding and fixing the problem.

**Comment by webmaster128** [comment]
For me, the problem is a regression 1.19.1->1.19.2 (as [reported here](https://github.com/HospitalRun/hospitalrun/issues/192)). Downgrading to 1.19.1 helped.

**Comment by cspotcode** [comment]
Building off of https://github.com/yarnpkg/yarn/issues/7734#issuecomment-580012389

In my case, yarn erroneously thinks that a dependency is actually a child package within my monorepo workspace.  In other words, I author many packages in my monorepo that all have some mix of dependencies, devDependencies, or peerDependencies on slightly different versions of ts-node.  This causes yarn to incorrectly classify ts-node as being one of the monorepo's own packages.  It thinks I have a ./packages/ts-node subdirectory in my monorepo, but I don't.

I think yarn is realizing it cannot hoist ts-node because there are different versions in play, so it keeps them nested within `packages/*/node_modules` (good) but this causes it to believe that ts-node is owned by my monorepo. (bad)

**Comment by troywweber7** [comment]
Still failing for me:
![image (2)](https://user-images.githubusercontent.com/4765979/77381022-081efa00-6d3a-11ea-9b93-4147f349bda8.png)
![image (3)](https://user-images.githubusercontent.com/4765979/77381025-0b19ea80-6d3a-11ea-906e-d96100fa8e59.png)

**Comment by AndreyChernykh** [comment]
Same issue for me with yarn `v1.22.4`

**Comment by quitedensepoint** [comment]
Fails for me too on 1.22.4. Manually adding the module to package.json did work around the issue, though.

**Comment by nemoDreamer** [comment]
If the Yarn team have just abandoned addressing v1.x.x issues, then a deprecation notice would be nice...

**Comment by san-kumar** [comment]
Still facing this issue.. downgrading to 1.19.1 fixed it

````
sudo apt remove yarn -y
sudo npm install yarn@1.19.1 -g
````

**Comment by friederbluemle** [comment]
It is also possible to invoke a **specific** version of Yarn directly using `npx`:

```
npx yarn@1.19.1 upgrade-interactive
```

That way, is not necessary to downgrade the globally installed version. When using workspaces, it seems the last version that works is `1.19.1` (getting an error with `1.19.2`).

**Comment by hardchor** [comment]
To downgrade to the last known working version in homebrew, run:

```
brew unlink yarn
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/aacaa70e8931b2b005cb8f70703b48604f4a8d2a/Formula/yarn.rb
brew switch yarn 1.19.1
```

**Comment by apperside** [comment]
Te solution provided by @friederbluemle [here](https://github.com/yarnpkg/yarn/issues/7734#issuecomment-618790950) is the best one IMHO

**Comment by geoyws** [comment]
We may also `yarn policies set-version 1.19.1`. SO post [here](https://stackoverflow.com/a/56175820/1561922).

**Comment by danvln** [comment]
Is this ever going to be fixed? I am a bit concerned about the quality of yarn in this context.

**Comment by whitecolor** [comment]
I've updated to 1.22 from older version and encountered this issue in couple of projects. But it was resolved by analysis with `yarn why ...`. Sometimes yarn creates strange hoisting configurations when packages take in their node_modules package of older versions while they can be used hoisted. Tt is usually resolved by removing packages that hold "wrong" versions of dependencies and reinstalling them.

**Comment by DavideDaniel** [comment]
So I got a new work computer.. Catalina this time.. and... that moment when you google a frustrating issue, find a promising thread on github.com... only to realize deep into the comments that.. you're the original author 🤦 sigh.. we've been trying to pave a way forward to get to yarn 2 but it is no small feat so the fact that I ran into this again just shows that this probably requires a patch in 1.x

**Comment by DavideDaniel** [comment]
> Is this ever going to be fixed? I am a bit concerned about the quality of yarn in this context.

I have a feeling effort has moved onto yarn 2 and I think someone else said it, yarn 1.x needs a deprecation notice if there is no appetite for maintaining 1.x

**Comment by DalderupMaurice** [comment]
> > Is this ever going to be fixed? I am a bit concerned about the quality of yarn in this context.
> 
> I have a feeling effort has moved onto yarn 2 and I think someone else said it, yarn 1.x needs a deprecation notice if there is no appetite for maintaining 1.x

Is this issue actually present in Yarn 2.0? If not, I'll be switching over. I'm forever stuck with an out of date yarn version atm

**Comment by JasonKleban** [comment]
I had success so far moving many devDependencies up to the root/solution project only and then rerunning `yarn upgrade-interactive` with a minimal selection of upgrades.

Side Note: I noticed along the way that sometimes it took two sequential runs of `yarn` (`yarn install`) for it to settle down and report `success Already up-to-date.`

**Comment by ericbiewener** [comment]
Thanks to all the contributors to this thread, and to @friederbluemle for the npx solution. [An alternative is to issue the command `yarn policies set-version 1.19.1` from inside your project](https://classic.yarnpkg.com/en/docs/cli/policies#enforcing-yarns-version-across-your-project-). This will let you to then use the standard `yarn` command and have it reference that desired version only when inside your project.

**Comment by rostislavbobo** [comment]
> It is also possible to invoke a **specific** version of Yarn directly using `npx`:
> 
> ```
> npx yarn@1.19.1 upgrade-interactive
> ```

I'm experiencing an issue with difference between `yarn.lock`s generated with `yarn` `v1.19.1` and `latest`.

You could also [use `lerna` to add a package](https://www.npmjs.com/package/@lerna/add) without downgrading the `yarn` version:

```sh
npx lerna add <package>[@version] --scope=<workspace>
```

**Comment by oussamabouchareb** [comment]
will this ever be actually fixed?

**Comment by amirburbea** [comment]
Looks like no. They really want us to transition to yarn2

**Comment by andreasonny83** [comment]
Same issue when using `chalk >=3` in a Yarn workspace. I found 2 ways to fix this:

1. Moving `chalk` from `devDependencies` to `dependencies`. However this doesn't look to me, so going for option 2
2. Downgrading `chalk` to v2.0.0

**Comment by joaomellogomes** [comment]
> Downgrading to v1.19.0 worked for me. Looking forward to fix this~

Same here... downgrading to v1.19.0 really solved the problem

```
node -v && yarn -v                                                  
v10.19.0
1.22.4
```

**Comment by schmod** [comment]
As a warning to others, I've also discovered that `yarn add` (and friends) will produce an incorrect `node_modules` hierarchy under the conditions that trigger this bug.

Notably, that issue **also** appears to affect 1.19.1 and below.  Running a subsequent `yarn install` fixes the issue.

**Comment by qiwang97** [comment]
The same issue for me with yarn v1.22.4 and node v14.15.4

**Comment by schmod** [comment]
If you're one of the many who are impacted by this issue, don't get your hopes up for a bugfix – [Yarn 1 appears to have been quietly deprecated](https://raw.githubusercontent.com/yarnpkg/yarn/master/.github/ISSUE_TEMPLATE/bug_report.md), and the maintainers no longer appear to be reviewing pull-requests in this repository.

**Comment by merceyz** [comment]
> If Yarn 2 doesn't work for you [...]

Open an issue with a reproduction so it can be fixed

**Comment by schmod** [comment]
@merceyz I've had a pull-request open for the past 146 days that fixes this issue.  It has not been reviewed or commented upon by a single member of the Yarn team.  

Additionally, on Jan 1, the GitHub issue template for this repository was quietly updated to mention that non-security bugfixes are no longer being considered.

Please do not encourage members of the community to waste their time creating reproduction-scenarios or patches for issues that the team has directly stated they have no intention of fixing.

**Comment by merceyz** [comment]
Please read my comment again, I specifically quoted the part of your comment about Yarn **2**

**Comment by ctjlewis** [comment]
This issue was resolved for me by using:

```
yarn lerna add --scope [scope] [...]
```

Instead of:

```
yarn --scope [scope] add [...]
```

**Comment by nathanredblur** [comment]
> This issue was resolved for me by using:
> 
> ```
> yarn lerna add --scope [scope] [...]
> ```

how you use it when you want to install more that one package ?
```
lerna add --scope="@client" @types/react @types/react-dom --dev
```

not works for me.

**Comment by sag1v** [comment]
> Same issue when using `chalk >=3` in a Yarn workspace. I found 2 ways to fix this:
> 
> 1. Moving `chalk` from `devDependencies` to `dependencies`. However this doesn't look to me, so going for option 2
> 2. Downgrading `chalk` to v2.0.0

@andreasonny83 thanks. 
We have the same issue but with `yargs` (yeilding the error about `cliui`). Moving `yargs` to `dependencies` instead of `devDependencies` worked. But do you know why it works?

**Comment by elenamik** [comment]
It stopped failing for me once I fixed my workspace names.

```
package.json
packages/
    hardhat/
        package.json
     ui/
        package.json
```


root package.json:

```
  "name": "web3-boilerplate",
  "private": true,
  "workspaces": ["packages/ui", "packages/hardhat"],
   //etc
```


packages/hardhat/package.json:
```
    "name": "@web3-boilerplate/hardhat",
    "version": "1.0.0",
    //etc
```


I previously had named the packages just `hardhat` and `ui` and this seems to have been causing the issue. **Changing to `@web3-boilerplate/hardhat` and `@web3-boilerplate/ui` seems to have fixed it!!**

**Comment by casamia918** [comment]
@elenamik Your comment helps me a lot. 

After I changed my root package.json name as same as sub-package's @{name}, "expected workspace package to exist for @babel/preset-env" Error disappeared.

Also, I've experienced unexpected package version unsync error.

I have installed jest@^26.x in root workspace, and my react-scripts@5 has nested dependency of jest@^27.x. Because of it, I expected "expected workspace package to exist for jest". (I've found the jest package dependency relationship by inspecting yarn.lock file). 

So I upgrade root workspace's jest version with equal to jest@^27.x 

After that, "expected workspace package to exist for jest" disappeared.

**Comment by VGerris** [comment]
can anyone explain where the actual problem comes from ? I suddenly have this with an expo upgrade, nothing changed about any workspace settings AFAIK.

error Invariant Violation: expected workspace package to exist for "@expo/prebuild-config"
    at invariant (/opt/homebrew/Cellar/yarn/1.22.22/libexec/lib/cli.js:2318:15)
    at _loop2 (/opt/homebrew/Cellar/yarn/1.22.22/libexec/lib/cli.js:91560:9)
    at PackageHoister.init (/opt/homebrew/Cellar/yarn/1.22.22/libexec/lib/cli.js:91619:19)
    at PackageLinker.getFlatHoistedTree (/opt/homebrew/Cellar/yarn/1.22.22/libexec/lib/cli.js:48551:20)
    at PackageLinker.<anonymous> (/opt/homebrew/Cellar/yarn/1.22.22/libexec/lib/cli.js:48562:27)
    at Generator.next (<anonymous>)
    at step (/opt/homebrew/Cellar/yarn/1.22.22/libexec/lib/cli.js:310:30)
    at /opt/homebrew/Cellar/yarn/1.22.22/libexec/lib/cli.js:328:14
    at new Promise (<anonymous>)
    at new F (/opt/homebrew/Cellar/yarn/1.22.22/libexec/lib/cli.js:5539:28)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

The workspace config in packages.json looks like:

  "workspaces": [
    "apps/*",
    "packages/*"
  ],

Should I now suddenly add the expo one there ?
Thank you

**Comment by VGerris** [comment]
... which I have to do everytime now. So if nobody maintains 1.22 it is time to switch. npm has pretty much always worked better and pnpm and especially bun look interesting. Not sure how Expo is going about it, because I feel I could file a bug against that since they officially only support yarn 1 'classic'.

The whole javascript packaging universe seems like a pile of poo where everybody took a dump in, it's a real pity because there is some good stuff in it. I saw some other initiatives for doing strict resolution only.

On the other hand, is it not possible to just fix this bug in yarn 1.22.22 ?
cheers

**Comment by VGerris** [comment]
I upgraded to 4.6 :
https://yarnpkg.com/migration/guide
