### ISSUE TITLE
Yarn is unable to fetch icons-react-0.0.1-beta.5.tgz package, possible network connection problem ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by fabianlomeli** [yarnpkg/yarn#7738]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When trying to do `yarn install` I got this error"
`$ yarn install --verbose`
...
[3/5] Fetching packages...
verbose 62.834 Performing "GET" request to "https://registry.yarnpkg.com/@carbon/icons-react/-/icons-react-0.0.1-beta.5.tgz".
info There appears to be trouble with your network connection. Retrying...
verbose 127.536 Performing "GET" request to "https://registry.yarnpkg.com/@carbon/icons-react/-/icons-react-0.0.1-beta.5.tgz".
info There appears to be trouble with your network connection. Retrying...
verbose 188.259 Performing "GET" request to "https://registry.yarnpkg.com/@carbon/icons-react/-/icons-react-0.0.1-beta.5.tgz".
info There appears to be trouble with your network connection. Retrying...
verbose 249.478 Performing "GET" request to "https://registry.yarnpkg.com/@carbon/icons-react/-/icons-react-0.0.1-beta.5.tgz".
info There appears to be trouble with your network connection. Retrying...
verbose 310.761 Performing "GET" request to "https://registry.yarnpkg.com/@carbon/icons-react/-/icons-react-0.0.1-beta.5.tgz".
verbose 370.828 Error: https://registry.yarnpkg.com/@carbon/icons-react/-/icons-react-0.0.1-beta.5.tgz: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:141213:19)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.emitRequestTimeout (_http_client.js:662:40)
    at Object.onceWrapper (events.js:286:20)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.Socket._onTimeout (net.js:443:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
error An unexpected error occurred: "https://registry.yarnpkg.com/@carbon/icons-react/-/icons-react-0.0.1-beta.5.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "C:\\work\\rqa\\common-core-external-dashboard\\yarn-e
rror.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

yarn-error.log
[yarn-error.log](https://github.com/yarnpkg/yarn/files/3923919/yarn-error.log)

**Comment by fabianlomeli** [comment]
Was able to resolve this issue.  Seems the NETWORK_TIMEOUT setting is too short (30 secs by default (30000 ms)).  So increasing this config option will do the trick.  I set this to 1000 seconds (~16.5 minutes)
`yarn install --network-timeout 1000000`
or
`yarn config set network-timeout 1000000`
