### ISSUE TITLE
Yarn add fails for dependencies with a dot (".")

### ISSUE THREAD

**Issue by rafael-anachoreta** [yarnpkg/yarn#7744]
**Do you want to request a *feature* or report a *bug*?**

Report a bug. 🐛 

**What is the current behavior?**
The command:
> yarn add sitespeed.io

Fails with:
```error An unexpected error occurred: "true/sitespeed.io: Invalid URI \"true/sitespeed.io\"".```

I am able to install the same dependency with npm

**If the current behavior is a bug, please provide the steps to reproduce.**

1 - Create a new repository
2 - Run `yarn add sitespeed.io`
3 - yarn fails to download

**What is the expected behavior?**
Yarn should be able to add https://www.npmjs.com/package/sitespeed.io to the project's dependencies.

**Please mention your node.js, yarn and operating system version.**
Yarn version: 
  1.19.2

Node version: 
  10.15.3

Platform: 
  darwin x64

Trace: 
```
Error: true/sitespeed.io: Invalid URI "true/sitespeed.io"
      at Request.module.exports.Request.init (/usr/local/Cellar/yarn/1.19.2/libexec/lib/cli.js:140674:31)
      at new Request (/usr/local/Cellar/yarn/1.19.2/libexec/lib/cli.js:140528:8)
      at request (/usr/local/Cellar/yarn/1.19.2/libexec/lib/cli.js:137434:10)
      at RequestManager.execute (/usr/local/Cellar/yarn/1.19.2/libexec/lib/cli.js:66979:15)
      at RequestManager.shiftQueue (/usr/local/Cellar/yarn/1.19.2/libexec/lib/cli.js:67017:10)
      at /usr/local/Cellar/yarn/1.19.2/libexec/lib/cli.js:66696:13
      at new Promise (<anonymous>)
      at new F (/usr/local/Cellar/yarn/1.19.2/libexec/lib/cli.js:5301:28)
      at RequestManager.request (/usr/local/Cellar/yarn/1.19.2/libexec/lib/cli.js:66694:19)
      at NpmRegistry.<anonymous> (/usr/local/Cellar/yarn/1.19.2/libexec/lib/cli.js:31704:42)
```

**Comment by rafael-anachoreta** [comment]
Turns out the issue was related to a bad registry configuration. 

Following the steps here: https://github.com/yarnpkg/yarn/issues/7686#issuecomment-561956885

I was able to install sitespeed.io.
