### ISSUE TITLE
[BUG] tunneling socket could not be established

### ISSUE THREAD

**Issue by Vaniik** [yarnpkg/yarn#7769]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
error An unexpected error occurred: "https://registry.yarnpkg.com/@rails%2fujs: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND host".

yarn-error log

Trace: 
  Error: https://registry.yarnpkg.com/@rails%2fujs: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND host host:80
      at ClientRequest.onError (C:\Program Files (x86)\Yarn\lib\cli.js:152151:17)
      at Object.onceWrapper (events.js:273:13)
      at ClientRequest.emit (events.js:182:13)
      at Socket.socketErrorListener (_http_client.js:392:9)
      at Socket.emit (events.js:182:13)
      at emitErrorNT (internal/streams/destroy.js:82:8)
      at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
      at process._tickCallback (internal/process/next_tick.js:63:19)

**If the current behavior is a bug, please provide the steps to reproduce.**
tried to install webpacker for ruby on rails, i installed node.js, then ruby, after ruby i installed rails, then sqlite3 and finally yarn

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**

**Comment by JayMGurav** [comment]
Hey @Vaniik  , I'm also facing the same issue and have not been able to solve it, If you have some how managed to solve the issue please help me with the same...My project is getting delayed day by day.

**Comment by praveen0311** [comment]
> Hey @Vaniik , I'm also facing the same issue and have not been able to solve it, If you have some how managed to solve the issue please help me with the same...My project is getting delayed day by day.

same issue here, let me know if any one resolved this
