### ISSUE TITLE
couldn't add tag error

### ISSUE THREAD

**Issue by jasonkuhrt** [yarnpkg/yarn#7823]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

```
yarn --verbose tag add dripip@0.3.1 next
```
```
yarn tag v1.21.1
verbose 0.165418171 Checking for configuration file "/Users/jasonkuhrt/projects/prisma-labs/dripip/.npmrc".
verbose 0.165696028 Checking for configuration file "/Users/jasonkuhrt/.npmrc".
verbose 0.165856298 Found configuration file "/Users/jasonkuhrt/.npmrc".
verbose 0.16616188 Checking for configuration file "/usr/local/etc/npmrc".
verbose 0.166353131 Checking for configuration file "/Users/jasonkuhrt/projects/prisma-labs/dripip/.npmrc".
verbose 0.166532042 Checking for configuration file "/Users/jasonkuhrt/projects/prisma-labs/.npmrc".
verbose 0.166701854 Checking for configuration file "/Users/jasonkuhrt/projects/.npmrc".
verbose 0.16686622 Checking for configuration file "/Users/jasonkuhrt/.npmrc".
verbose 0.167025153 Found configuration file "/Users/jasonkuhrt/.npmrc".
verbose 0.167269121 Checking for configuration file "/Users/.npmrc".
verbose 0.168967801 Checking for configuration file "/Users/jasonkuhrt/projects/prisma-labs/dripip/.yarnrc".
verbose 0.169139925 Checking for configuration file "/Users/jasonkuhrt/.yarnrc".
verbose 0.169284294 Found configuration file "/Users/jasonkuhrt/.yarnrc".
verbose 0.169539476 Checking for configuration file "/usr/local/etc/yarnrc".
verbose 0.169692805 Checking for configuration file "/Users/jasonkuhrt/projects/prisma-labs/dripip/.yarnrc".
verbose 0.169837239 Checking for configuration file "/Users/jasonkuhrt/projects/prisma-labs/.yarnrc".
verbose 0.169947733 Checking for configuration file "/Users/jasonkuhrt/projects/.yarnrc".
verbose 0.170054609 Checking for configuration file "/Users/jasonkuhrt/.yarnrc".
verbose 0.170145581 Found configuration file "/Users/jasonkuhrt/.yarnrc".
verbose 0.170325439 Checking for configuration file "/Users/.yarnrc".
verbose 0.180047917 current time: 2020-01-18T03:33:34.208Z
[1/3] Logging in...
[2/3] Creating tag "next" = "0.3.1"...
verbose 0.196759687 Performing "PUT" request to "https://registry.yarnpkg.com/-/package/dripip/dist-tags/next".
verbose 0.681318968 Request "https://registry.yarnpkg.com/-/package/dripip/dist-tags/next" finished with status code 204.
error Couldn't add tag.
[3/3] Revoking token...
info Not revoking login token, specified via config file.
verbose 0.690917523 Error
    at /usr/local/Cellar/yarn/1.21.1/libexec/lib/cli.js:62858:15
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.21.1/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.21.1/libexec/lib/cli.js:321:13
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
error An unexpected error occurred: "".
info If you think this is a bug, please open a bug report with the information provided in "/Users/jasonkuhrt/projects/prisma-labs/dripip/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/tag for documentation about this command.
```

Despite the error, it seems to work:

```
❯ yarn tag list    
yarn tag v1.21.1
[1/1] Getting tags...
info Package dripip
info latest: 0.3.1
info next: 0.3.1
✨  Done in 0.57s.
```

**What is the expected behavior?**

No error

**Please mention your node.js, yarn and operating system version.**

```
❯ yarn --version                           
1.21.1
```
```
❯ node -v              
v12.14.1
```

**Comment by jasonkuhrt** [comment]
The error log:

```
❯ cat yarn-error.log                             
Arguments: 
  /Users/jasonkuhrt/.nvm/versions/node/v12.14.1/bin/node /usr/local/Cellar/yarn/1.21.1/libexec/bin/yarn.js tag add dripip-system-tests@0.0.102 next

PATH: 
  /var/folders/6g/4nk3wj214d3998979vzfm_r80000gn/T/yarn--1579319393023-0.9614718664947042:/Users/jasonkuhrt/projects/prisma-labs/dripip-system-tests/node_modules/.bin:/Users/jasonkuhrt/.config/yarn/link/node_modules/.bin:/Users/jasonkuhrt/.nvm/versions/node/v12.14.1/libexec/lib/node_modules/npm/bin/node-gyp-bin:/Users/jasonkuhrt/.nvm/versions/node/v12.14.1/lib/node_modules/npm/bin/node-gyp-bin:/Users/jasonkuhrt/.nvm/versions/node/v12.14.1/bin/node_modules/npm/bin/node-gyp-bin:/Users/jasonkuhrt/.nvm/versions/node/v12.14.1/bin:/usr/local/Cellar/zplug/2.4.2/bin:/usr/local/opt/zplug/bin:/Users/jasonkuhrt/.local/bin:/Users/jasonkuhrt/.krew/bin:/Users/jasonkuhrt/.poetry/bin:/usr/local/opt/python/libexec/bin:/Users/jasonkuhrt/.cargo/bin:/Users/jasonkuhrt/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/Users/jasonkuhrt/.nvm/versions/node/v12.14.1/bin

Yarn version: 
  1.21.1

Node version: 
  12.14.1

Platform: 
  darwin x64

Trace: 
  Error
      at /usr/local/Cellar/yarn/1.21.1/libexec/lib/cli.js:62858:15
      at Generator.next (<anonymous>)
      at step (/usr/local/Cellar/yarn/1.21.1/libexec/lib/cli.js:310:30)
      at /usr/local/Cellar/yarn/1.21.1/libexec/lib/cli.js:321:13
      at processTicksAndRejections (internal/process/task_queues.js:94:5)

npm manifest: 
  {
    "name": "dripip-system-tests",
    "version": "0.0.102",
    "scripts": {
      "npm:release": "npm publish --tag test1",
      "yarn:release": "yarn publish --tag test1",
      "test": "echo $npm_execpath",
      "release:preview": "dripip preview --trunk preview-publishing",
      "release:stable": "dripip stable --trunk preview-publishing"
    },
    "dependencies": {
      "dripip": "next"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile
```

**Comment by ivanildobarros** [comment]
I have the same problem,
some solution?

**Comment by nicosommi** [comment]
I also have this error. I thought it was a problem of the scopes for the access token, but I tried with all of them activated and I still have this error. I cannot change the latest tag on the package I own... which is really annoying.

**Comment by sergio-dreamcode** [comment]
Hi, I also have this error, in my case I thought it was related with the private Gitlab NPM registry we are using, however I noticed you had the same issue with Yarn's registry as well. The same situation with Gitlab is that after the HTTP request to the registry is sent and it gets a 204 response and an empty body it fails, however the tag was updated successfully in the registry.

I compiled a local version of Yarn to check what's happening and it's this [validation](https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/tag.js#L115) that is causing the error even if the response is 204. The reason of that validation to fail is because the `request` library (it is deprecated) is not sending a value to the `body` param in the [callback](https://github.com/yarnpkg/yarn/blob/master/src/util/request-manager.js#L417) and the body value is `undefined` which seems to be the root cause of this issue.

I am not sure if this issue is going to be solved as Yarn v1 will only receive security upgrades. 

There are two possible workarounds I can recommend:
- Upgrade to Yarn v2 (it seems it does not have that [validation that is breaking](https://github.com/yarnpkg/berry/blob/master/packages/plugin-npm-cli/sources/commands/npm/tag/add.ts#L59) in v1
- Use `npm dist-tag add` in case you have dependencies that are not compatible with Yarn v2 yet (like [Lerna](https://github.com/lerna/lerna/issues/2449))
