### ISSUE TITLE
Installation Problem: Yarn

### ISSUE THREAD

**Issue by KomalDhanwani** [yarnpkg/yarn#7840]
**Which operating system are you using:**
am using Ubuntu

**Please describe the steps you took when trying to install Yarn and what went wrong:**

When I type yarn --version am getting bellow issue
```$ yarn --version
/usr/share/yarn/lib/cli.js:46099
  let {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/share/yarn/bin/yarn.js:24:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)```

**Comment by olingern** [comment]
Ubuntu and Node version?

**Comment by Daniel15** [comment]
Yeah this sounds like your Node.js version is extremely old.

**Comment by ntdb** [comment]
Yarn claims to support Node versions `^4.8.0 || ^5.7.0 || ^6.2.2 || >=8.0.0` so "upgrade Node" seems like a poor fix for this bug. I'm encountering it on Node 5.12.0.
