### ISSUE TITLE
yarn2 - Syntax error in parsing package.json run scripts with env variable using ' prefixed

### ISSUE THREAD

**Issue by duncanhealy** [yarnpkg/yarn#7845]
### Bug description

package.json scripts fail to run if they have environment variables prefixed to the command that
use single ticks ```'```

**Command**

```sh
yarn start
yarn build
```

**What is the current behavior?**

yarn 1.x parses package.json correctly
yarn 2.0.0-rc.27 parses package.json and fails with a syntax error below
```
Syntax Error: Expected "\\" or [^'] but "'" found (line 1, column 8).
    at Xe (/home/username/.nvm/versions/node/v12.14.1/lib/node_modules/yarn/bin/yarn.js:36:319549)
    at Object.parse (/home/username/.nvm/versions/node/v12.14.1/lib/node_modules/yarn/bin/yarn.js:36:328727)
    at Object.t.parseShell (/home/username/.nvm/versions/node/v12.14.1/lib/node_modules/yarn/bin/yarn.js:36:314751)
    at Object.t.execute (/home/username/.nvm/versions/node/v12.14.1/lib/node_modules/yarn/bin/yarn.js:24:16165)
    at B.r.configuration.reduceHook.script (/home/username/.nvm/versions/node/v12.14.1/lib/node_modules/yarn/bin/yarn.js:24:5026)
    at Object.B [as executePackageScript] (/home/username/.nvm/versions/node/v12.14.1/lib/node_modules/yarn/bin/yarn.js:24:5159)
    at async c.execute (/home/username/.nvm/versions/node/v12.14.1/lib/node_modules/yarn/bin/yarn.js:58:43949)
    at async c.validateAndExecute (/home/username/.nvm/versions/node/v12.14.1/lib/node_modules/yarn/bin/yarn.js:24:40434)
    at async c.run (/home/username/.nvm/versions/node/v12.14.1/lib/node_modules/yarn/bin/yarn.js:36:533800)
    at async s.execute (/home/username/.nvm/versions/node/v12.14.1/lib/node_modules/yarn/bin/yarn.js:58:17806)
```
**What is the expected behavior?**

yarn start, build .. should parse and run scripts set by scripts block in package.json

**Steps to Reproduce**

package.json file --> set DEBUG variable to empty / -babel
```
  "scripts": {
    "start": "DEBUG='-babel' BROWSER=none react-scripts start",
    "build": "DEBUG='' react-scripts build"
}
```
**Workaround**

change single ticks ```'``` to ```\"``` in scripts

**Environment**

- Node Version: `12.14.1`
- Yarn v2 Version: `2.0.0-rc.27` 
- OS and version:

**Comment by olingern** [comment]
Hi, this repo is currently for v1. I've moved your issue here: 

https://github.com/yarnpkg/berry/issues/797
