### ISSUE TITLE
brew install yarn success but can't use

### ISSUE THREAD

**Issue by syymo** [yarnpkg/yarn#7869]
shi@shideMacBook-Pro homebrew % brew install yarn --ignore-dependencies
Warning: --ignore-dependencies is an unsupported Homebrew developer flag!
Adjust your PATH to put any preferred versions of applications earlier in the
PATH rather than using this unsupported flag!

==> Downloading https://yarnpkg.com/downloads/1.21.1/yarn-v1.21.1.tar.gz
Already downloaded: /Users/shi/Library/Caches/Homebrew/downloads/782dbae591eb24382d5d6de01bf9e5e65306b87cd0c3d2f995d854c559ca8d97--yarn-v1.21.1.tar.gz
🍺  /usr/local/Cellar/yarn/1.21.1: 14 files, 5MB, built in 33 seconds
shiyouyumo@shiyouyumodeMacBook-Pro homebrew % yarn --version
/usr/local/Cellar/yarn/1.21.1/libexec/lib/cli.js:46099
  let {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/Cellar/yarn/1.21.1/libexec/bin/yarn.js:24:13)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)

**Comment by ffmike** [comment]
Same error trying to run `rails c` in a Rails 6.0 project after letting homebrew update to yarn 1.22.

**Comment by ffmike** [comment]
Never mind. In my case the problem was that Rails was holding some version of something in memory. A simple `spring stop` in the project and all is well.
