### ISSUE TITLE
Error: https://registry.yarnpkg.com/7zip: Not found

### ISSUE THREAD

**Issue by serotonyn** [yarnpkg/yarn#7903]
### Bug description
Error: https://registry.yarnpkg.com/7zip: Not found

**Command**

```sh
yarn add -D 7zip 
```

**What is the current behavior?**
Throwing a "not found" error

**What is the expected behavior?**
Should grab the package

**Steps to Reproduce**
1. yarn init
2. yarn add -D 7zip

**Environment**

- Node Version: `12.13.1`
- Yarn v1 Version: `1.22.0` 
- OS and version: Windows 10

**yarn-error**
Arguments: 
  C:\Program Files\nodejs\node.exe C:\Users\user\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js add -D 7zip

PATH: 
  C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\user\.windows-build-tools\python27\;C:\Users\user\AppData\Local\Microsoft\WindowsApps;C:\Users\user\AppData\Roaming\npm;C:\Users\user\AppData\Local\Programs\Microsoft VS Code\bin

Yarn version: 
  1.22.0

Node version: 
  12.13.1

Platform: 
  win32 x64

Trace: 
  Error: https://registry.yarnpkg.com/7zip: Not found
      at Request.params.callback [as _callback] (C:\Users\user\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:66975:18)
      at Request.self.callback (C:\Users\user\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:140727:22)
      at Request.emit (events.js:210:5)
      at Request.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:141699:10)
      at Request.emit (events.js:210:5)
      at IncomingMessage.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:141621:12)
      at Object.onceWrapper (events.js:299:28)
      at IncomingMessage.emit (events.js:215:7)
      at endReadableNT (_stream_readable.js:1184:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)

npm manifest: 
  {
    "name": "b",
    "version": "1.0.0",
    "main": "index.js",
    "license": "MIT"
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

**Comment by serotonyn** [comment]
Seems to be related to #7902. (you can find a workaround there)

**Comment by rally25rs** [comment]
There is currently an npm registry issue about this.
https://status.npmjs.org/incidents/lvgmcrfvrvsh
