### ISSUE TITLE
Y2: ts-node unable to find types in .yarn/cache

### ISSUE THREAD

**Issue by johnptoohey** [yarnpkg/yarn#7911]
### Bug description
ts-node is unable to locate types in new cache. Previously it would get them from the node-modules directories. 
**Command**

```sh
ts-node src/index/ts
```

**What is the current behavior?**

Errors from ts-node complaining about Types in my code, including not finding 'console'

**What is the expected behavior?**
Expected code to function as it does with yarn 1.x.

Is there a new config that I need to use to point to the type files in .yarn/cache?

**Steps to Reproduce**

1. 
2.

**Environment**

- Node Version: `12.14.0`
- Yarn v1 Version: `2.0` 
- OS and version: OSX 10.14

**Comment by polRk** [comment]
Try this
```
yarn add @yarnpkg/pnpify

yarn pnpify ts-node src/index.ts
```

**Comment by johnptoohey** [comment]
Thank you. Followed your instructions but not get this
`λ hypatia-1 storage → yarn pnpify ts-node src/index.ts
/Users/johntoohey/Dev/repos/git/dom-deux/packages/storage/.pnp.js:18236
    throw firstError;
    ^

Error: Cannot find module '/Users/johntoohey/Dev/repos/git/dom-deux/packages/storage/.yarn/cache/typescript-patch-7f9fbec647-2.zip/node_modules/typescript/lib/typescript.js'
Require stack:
- /usr/local/lib/node_modules/ts-node/dist/index.js
- /usr/local/lib/node_modules/ts-node/dist/bin.js
Require stack:
- /usr/local/lib/node_modules/ts-node/dist/index.js
- /usr/local/lib/node_modules/ts-node/dist/bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.module_1.Module._resolveFilename (/Users/johntoohey/Dev/repos/git/dom-deux/packages/storage/.pnp.js:18221:54)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.module_1.Module._load (/Users/johntoohey/Dev/repos/git/dom-deux/packages/storage/.pnp.js:18098:36)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at create (/usr/local/lib/node_modules/ts-node/dist/index.js:164:16)
    at Object.register (/usr/local/lib/node_modules/ts-node/dist/index.js:134:21)
    at main (/usr/local/lib/node_modules/ts-node/dist/bin.js:119:29)
    at Object.<anonymous> (/usr/local/lib/node_modules/ts-node/dist/bin.js:404:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/ts-node/dist/index.js',
    '/usr/local/lib/node_modules/ts-node/dist/bin.js'
  ]
}`

If I run ts-node directly, I runs without error, but my code throws exceptions because of the missing (inaccessible) type definitions.

**Comment by polRk** [comment]
@johnptoohey, You can split ts-node into 2 different commands: 
1. tsc --build (output lib)
2. node lib/index.js
