### ISSUE TITLE
Yarn 2 Jest (ts-jest) pnp error

### ISSUE THREAD

**Issue by polRk** [yarnpkg/yarn#7927]
```
/Users/polrk/.nvm/versions/node/v12.11.1/bin/node /Users/polrk/.nvm/versions/node/v12.11.1/lib/node_modules/yarn/bin/yarn.js test
 FAIL  src/__test__/__value__.spec.ts
  ● Test suite failed to run

    A package is trying to access another package without the second one being listed as a dependency of the first one

    Required package: jest-config (via "jest-config/build")
    Required by: ts-jest@virtual:b46d160b943281b74282048231848e903f35351db752890298c8ae1f6a24790e62b648d3f9286a453b89148834b5c49a0c28efdac3a6527ef9d7089c07fc094c#npm:25.2.1 (via /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/)

    Require stack:
    - /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/compiler.js
    - /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/config/config-set.js
    - /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/ts-jest-transformer.js
    - /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/index.js
    - /Users/polrk/github.com/app/app/.yarn/cache/@jest-transform-npm-25.1.0-5f5645c4ef-2.zip/node_modules/@jest/transform/build/ScriptTransformer.js
    - /Users/polrk/github.com/app/app/.yarn/cache/@jest-transform-npm-25.1.0-5f5645c4ef-2.zip/node_modules/@jest/transform/build/index.js
    - /Users/polrk/github.com/app/app/.yarn/cache/jest-runtime-npm-25.1.0-9a183c5bd3-2.zip/node_modules/jest-runtime/build/index.js
    - /Users/polrk/github.com/app/app/.yarn/cache/@jest-core-npm-25.1.0-8e811ad5a3-2.zip/node_modules/@jest/core/build/cli/index.js
    - /Users/polrk/github.com/app/app/.yarn/cache/@jest-core-npm-25.1.0-8e811ad5a3-2.zip/node_modules/@jest/core/build/jest.js
    - /Users/polrk/github.com/app/app/.yarn/cache/jest-cli-npm-25.1.0-6214862080-2.zip/node_modules/jest-cli/build/cli/index.js
    - /Users/polrk/github.com/app/app/.yarn/cache/jest-cli-npm-25.1.0-6214862080-2.zip/node_modules/jest-cli/bin/jest.js
    - /Users/polrk/github.com/app/app/.yarn/cache/jest-npm-25.1.0-0e542566c5-2.zip/node_modules/jest/bin/jest.js

      14001 | function makeError(pnpCode, message, data = {}) {
      14002 |   const code = MODULE_NOT_FOUND_ERRORS.has(pnpCode) ? `MODULE_NOT_FOUND` : pnpCode;
    > 14003 |   return Object.assign(new Error(message), {
            |                        ^
      14004 |     code,
      14005 |     pnpCode,
      14006 |     data

      at Object.makeError (../../.pnp.js:14003:24)
      at resolveToUnqualified (../../.pnp.js:22901:35)
      at resolveRequest (../../.pnp.js:22978:27)
      at Object.resolveRequest (../../.pnp.js:23046:26)
      at Function.module_1.Module._resolveFilename (../../.pnp.js:22275:34)
      at Function.module_1.Module._load (../../.pnp.js:22160:40)

Running coverage on untested files...Failed to collect coverage from /Users/polrk/github.com/app/app/packages/dataql/src/index.ts
ERROR: A package is trying to access another package without the second one being listed as a dependency of the first one

Required package: jest-config (via "jest-config/build")
Required by: ts-jest@virtual:b46d160b943281b74282048231848e903f35351db752890298c8ae1f6a24790e62b648d3f9286a453b89148834b5c49a0c28efdac3a6527ef9d7089c07fc094c#npm:25.2.1 (via /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/)

Require stack:
- /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/compiler.js
- /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/config/config-set.js
- /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/ts-jest-transformer.js
- /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/index.js
- /Users/polrk/github.com/app/app/.yarn/cache/@jest-transform-npm-25.1.0-5f5645c4ef-2.zip/node_modules/@jest/transform/build/ScriptTransformer.js
- /Users/polrk/github.com/app/app/.yarn/cache/@jest-transform-npm-25.1.0-5f5645c4ef-2.zip/node_modules/@jest/transform/build/index.js
- /Users/polrk/github.com/app/app/.yarn/cache/@jest-reporters-npm-25.1.0-f33c786223-2.zip/node_modules/@jest/reporters/build/generateEmptyCoverage.js
- /Users/polrk/github.com/app/app/.yarn/cache/@jest-reporters-npm-25.1.0-f33c786223-2.zip/node_modules/@jest/reporters/build/coverage_worker.js
- /Users/polrk/github.com/app/app/.yarn/cache/jest-worker-npm-25.1.0-3e76b6b8a3-2.zip/node_modules/jest-worker/build/workers/processChild.js
STACK: Error: A package is trying to access another package without the second one being listed as a dependency of the first one

Required package: jest-config (via "jest-config/build")
Required by: ts-jest@virtual:b46d160b943281b74282048231848e903f35351db752890298c8ae1f6a24790e62b648d3f9286a453b89148834b5c49a0c28efdac3a6527ef9d7089c07fc094c#npm:25.2.1 (via /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/)

Require stack:
- /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/compiler.js
- /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/config/config-set.js
- /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/ts-jest-transformer.js
- /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/index.js
- /Users/polrk/github.com/app/app/.yarn/cache/@jest-transform-npm-25.1.0-5f5645c4ef-2.zip/node_modules/@jest/transform/build/ScriptTransformer.js
- /Users/polrk/github.com/app/app/.yarn/cache/@jest-transform-npm-25.1.0-5f5645c4ef-2.zip/node_modules/@jest/transform/build/index.js
- /Users/polrk/github.com/app/app/.yarn/cache/@jest-reporters-npm-25.1.0-f33c786223-2.zip/node_modules/@jest/reporters/build/generateEmptyCoverage.js
- /Users/polrk/github.com/app/app/.yarn/cache/@jest-reporters-npm-25.1.0-f33c786223-2.zip/node_modules/@jest/reporters/build/coverage_worker.js
- /Users/polrk/github.com/app/app/.yarn/cache/jest-worker-npm-25.1.0-3e76b6b8a3-2.zip/node_modules/jest-worker/build/workers/processChild.js
    at Object.makeError (/Users/polrk/github.com/app/app/.pnp.js:14003:24)
    at resolveToUnqualified (/Users/polrk/github.com/app/app/.pnp.js:22901:35)
    at resolveRequest (/Users/polrk/github.com/app/app/.pnp.js:22978:27)
    at Object.resolveRequest (/Users/polrk/github.com/app/app/.pnp.js:23046:26)
    at Function.module_1.Module._resolveFilename (/Users/polrk/github.com/app/app/.pnp.js:22275:34)
    at Function.module_1.Module._load (/Users/polrk/github.com/app/app/.pnp.js:22160:40)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/compiler.js:45:15)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
Failed to collect coverage from /Users/polrk/github.com/app/app/packages/dataql/src/functions/__value__.ts
ERROR: A package is trying to access another package without the second one being listed as a dependency of the first one

Required package: jest-config (via "jest-config/build")
Required by: ts-jest@virtual:b46d160b943281b74282048231848e903f35351db752890298c8ae1f6a24790e62b648d3f9286a453b89148834b5c49a0c28efdac3a6527ef9d7089c07fc094c#npm:25.2.1 (via /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/)

Require stack:
- /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/compiler.js
- /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/config/config-set.js
- /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/ts-jest-transformer.js
- /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/index.js
- /Users/polrk/github.com/app/app/.yarn/cache/@jest-transform-npm-25.1.0-5f5645c4ef-2.zip/node_modules/@jest/transform/build/ScriptTransformer.js
- /Users/polrk/github.com/app/app/.yarn/cache/@jest-transform-npm-25.1.0-5f5645c4ef-2.zip/node_modules/@jest/transform/build/index.js
- /Users/polrk/github.com/app/app/.yarn/cache/@jest-reporters-npm-25.1.0-f33c786223-2.zip/node_modules/@jest/reporters/build/generateEmptyCoverage.js
- /Users/polrk/github.com/app/app/.yarn/cache/@jest-reporters-npm-25.1.0-f33c786223-2.zip/node_modules/@jest/reporters/build/coverage_worker.js
- /Users/polrk/github.com/app/app/.yarn/cache/jest-worker-npm-25.1.0-3e76b6b8a3-2.zip/node_modules/jest-worker/build/workers/processChild.js
STACK: Error: A package is trying to access another package without the second one being listed as a dependency of the first one

Required package: jest-config (via "jest-config/build")
Required by: ts-jest@virtual:b46d160b943281b74282048231848e903f35351db752890298c8ae1f6a24790e62b648d3f9286a453b89148834b5c49a0c28efdac3a6527ef9d7089c07fc094c#npm:25.2.1 (via /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/)

Require stack:
- /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/compiler.js
- /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/config/config-set.js
- /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/ts-jest-transformer.js
- /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/index.js
- /Users/polrk/github.com/app/app/.yarn/cache/@jest-transform-npm-25.1.0-5f5645c4ef-2.zip/node_modules/@jest/transform/build/ScriptTransformer.js
- /Users/polrk/github.com/app/app/.yarn/cache/@jest-transform-npm-25.1.0-5f5645c4ef-2.zip/node_modules/@jest/transform/build/index.js
- /Users/polrk/github.com/app/app/.yarn/cache/@jest-reporters-npm-25.1.0-f33c786223-2.zip/node_modules/@jest/reporters/build/generateEmptyCoverage.js
- /Users/polrk/github.com/app/app/.yarn/cache/@jest-reporters-npm-25.1.0-f33c786223-2.zip/node_modules/@jest/reporters/build/coverage_worker.js
- /Users/polrk/github.com/app/app/.yarn/cache/jest-worker-npm-25.1.0-3e76b6b8a3-2.zip/node_modules/jest-worker/build/workers/processChild.js
    at Object.makeError (/Users/polrk/github.com/app/app/.pnp.js:14003:24)
    at resolveToUnqualified (/Users/polrk/github.com/app/app/.pnp.js:22901:35)
    at resolveRequest (/Users/polrk/github.com/app/app/.pnp.js:22978:27)
    at Object.resolveRequest (/Users/polrk/github.com/app/app/.pnp.js:23046:26)
    at Function.module_1.Module._resolveFilename (/Users/polrk/github.com/app/app/.pnp.js:22275:34)
    at Function.module_1.Module._load (/Users/polrk/github.com/app/app/.pnp.js:22160:40)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/compiler.js:45:15)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
Failed to collect coverage from /Users/polrk/github.com/app/app/packages/dataql/src/functions/index.ts
ERROR: A package is trying to access another package without the second one being listed as a dependency of the first one

Required package: jest-config (via "jest-config/build")
Required by: ts-jest@virtual:b46d160b943281b74282048231848e903f35351db752890298c8ae1f6a24790e62b648d3f9286a453b89148834b5c49a0c28efdac3a6527ef9d7089c07fc094c#npm:25.2.1 (via /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/)

Require stack:
- /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/compiler.js
- /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/config/config-set.js
- /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/ts-jest-transformer.js
- /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/index.js
- /Users/polrk/github.com/app/app/.yarn/cache/@jest-transform-npm-25.1.0-5f5645c4ef-2.zip/node_modules/@jest/transform/build/ScriptTransformer.js
- /Users/polrk/github.com/app/app/.yarn/cache/@jest-transform-npm-25.1.0-5f5645c4ef-2.zip/node_modules/@jest/transform/build/index.js
- /Users/polrk/github.com/app/app/.yarn/cache/@jest-reporters-npm-25.1.0-f33c786223-2.zip/node_modules/@jest/reporters/build/generateEmptyCoverage.js
- /Users/polrk/github.com/app/app/.yarn/cache/@jest-reporters-npm-25.1.0-f33c786223-2.zip/node_modules/@jest/reporters/build/coverage_worker.js
- /Users/polrk/github.com/app/app/.yarn/cache/jest-worker-npm-25.1.0-3e76b6b8a3-2.zip/node_modules/jest-worker/build/workers/processChild.js
STACK: Error: A package is trying to access another package without the second one being listed as a dependency of the first one

Required package: jest-config (via "jest-config/build")
Required by: ts-jest@virtual:b46d160b943281b74282048231848e903f35351db752890298c8ae1f6a24790e62b648d3f9286a453b89148834b5c49a0c28efdac3a6527ef9d7089c07fc094c#npm:25.2.1 (via /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/)

Require stack:
- /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/compiler.js
- /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/config/config-set.js
- /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/ts-jest-transformer.js
- /Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/index.js
- /Users/polrk/github.com/app/app/.yarn/cache/@jest-transform-npm-25.1.0-5f5645c4ef-2.zip/node_modules/@jest/transform/build/ScriptTransformer.js
- /Users/polrk/github.com/app/app/.yarn/cache/@jest-transform-npm-25.1.0-5f5645c4ef-2.zip/node_modules/@jest/transform/build/index.js
- /Users/polrk/github.com/app/app/.yarn/cache/@jest-reporters-npm-25.1.0-f33c786223-2.zip/node_modules/@jest/reporters/build/generateEmptyCoverage.js
- /Users/polrk/github.com/app/app/.yarn/cache/@jest-reporters-npm-25.1.0-f33c786223-2.zip/node_modules/@jest/reporters/build/coverage_worker.js
- /Users/polrk/github.com/app/app/.yarn/cache/jest-worker-npm-25.1.0-3e76b6b8a3-2.zip/node_modules/jest-worker/build/workers/processChild.js
    at Object.makeError (/Users/polrk/github.com/app/app/.pnp.js:14003:24)
    at resolveToUnqualified (/Users/polrk/github.com/app/app/.pnp.js:22901:35)
    at resolveRequest (/Users/polrk/github.com/app/app/.pnp.js:22978:27)
    at Object.resolveRequest (/Users/polrk/github.com/app/app/.pnp.js:23046:26)
    at Function.module_1.Module._resolveFilename (/Users/polrk/github.com/app/app/.pnp.js:22275:34)
    at Function.module_1.Module._load (/Users/polrk/github.com/app/app/.pnp.js:22160:40)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/polrk/github.com/app/app/.yarn/$$virtual/ts-jest-virtual-68ed7efc2d/0/cache/ts-jest-npm-25.2.1-abe6e4496f-2.zip/node_modules/ts-jest/dist/compiler.js:45:15)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        5.613s
Ran all test suites.
```

**Comment by merceyz** [comment]
At the time you opened this `ts-jest` was lacking a dependency on `jest-config` they fixed that in https://github.com/kulshekhar/ts-jest/commit/6d9e0d8 and no longer seem to need it
