### ISSUE TITLE
Installation Problem: [title]

### ISSUE THREAD

**Issue by hidde030** [yarnpkg/yarn#8006]
**Which operating system are you using:**
Windows 10

**Please describe the steps you took when trying to install Yarn and what went wrong:**

I have tried yarn --version, I wil get this error. pls help me!

 TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type boolean
    at assertPath (path.js:39:11)
    at resolve (path.js:166:7)
    at loadRcFile (C:\Program Files (x86)\Yarn\lib\cli.js:56952:58)
    at C:\Program Files (x86)\Yarn\lib\cli.js:56916:14
    at C:\Program Files (x86)\Yarn\lib\cli.js:97253:14
    at Array.map (<anonymous>)
    at parseRcPaths (C:\Program Files (x86)\Yarn\lib\cli.js:97251:78)
    at Object.findRc (C:\Program Files (x86)\Yarn\lib\cli.js:97265:10)
    at getRcConfigForCwd (C:\Program Files (x86)\Yarn\lib\cli.js:56915:74)
    at C:\Program Files (x86)\Yarn\lib\cli.js:88616:56

**Comment by Vuyisanani** [comment]
I also have been struggling to install yarn on windows 10

**Comment by Vuyisanani** [comment]
Please make sure you have anti-virus in your machine, try to install again

I installed yarn from a different machine for the version of my Operating System, took it by flash drive then installed it on my machine, and all is fine now.

**Comment by merceyz** [comment]
Closing as there is nothing actionable here
