### ISSUE TITLE
yarn install failed

### ISSUE THREAD

**Issue by lwba21190** [yarnpkg/yarn#8025]
Yarn version: 
  1.22.4

Node version: 
  12.16.1

Platform: 
  win32 x64

Trace: 
  TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
      at Function.from (buffer.js:313:9)
      at Object.fromHex (C:\Users\l00475038\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:32678:14)
      at NpmResolver.<anonymous> (C:\Users\l00475038\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:50709:73)
      at Generator.next (<anonymous>)
      at step (C:\Users\l00475038\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:310:30)
      at C:\Users\l00475038\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:321:13
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by paul-soporan** [comment]
Closing as unactionable.
