### ISSUE TITLE
Yarn install crashes at step 4, while building nsfw with node-gyp

### ISSUE THREAD

**Issue by drochgenius** [yarnpkg/yarn#8046]
### Bug description

Yarn install started failing with error building `nsfw` at step 4, on Ubuntu.
It was working fine until yesterday.

**Command**

```sh
yarn
```

**What is the current behavior?**

I get the following error traceback

```
error /node_modules/nsfw: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /node_modules/nsfw
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@10.14.0 | linux | x64
gyp info find Python using Python version 2.7.6 found at "/usr/bin/python"
gyp http GET https://nodejs.org/download/release/v10.14.0/node-v10.14.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v10.14.0/node-v10.14.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v10.14.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v10.14.0/SHASUMS256.txt
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/node_modules/nsfw/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/10.14.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/10.14.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/10.14.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/node_modules/nsfw',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/node_modules/nsfw/build'
  CXX(target) Release/obj.target/nsfw/src/NSFW.o
In file included from ../src/NSFW.cpp:1:0:
../src/../includes/NSFW.h:21:5: error: 'ThreadSafeFunction' in namespace 'Napi' does not name a type
     Napi::ThreadSafeFunction mErrorCallback;
     ^
../src/../includes/NSFW.h:22:5: error: 'ThreadSafeFunction' in namespace 'Napi' does not name a type
     Napi::ThreadSafeFunction mEventCallback;
     ^
../src/NSFW.cpp: In constructor 'NSFW::NSFW(const Napi::CallbackInfo&)':
../src/NSFW.cpp:30:3: error: 'mEventCallback' was not declared in this scope
   mEventCallback = Napi::ThreadSafeFunction::New(
   ^
../src/NSFW.cpp:30:26: error: 'Napi::ThreadSafeFunction' has not been declared
   mEventCallback = Napi::ThreadSafeFunction::New(
                          ^
../src/NSFW.cpp:64:5: error: 'mErrorCallback' was not declared in this scope
     mErrorCallback = Napi::ThreadSafeFunction::New(
     ^
../src/NSFW.cpp:64:28: error: 'Napi::ThreadSafeFunction' has not been declared
     mErrorCallback = Napi::ThreadSafeFunction::New(
                            ^
../src/NSFW.cpp: In destructor 'virtual NSFW::~NSFW()':
../src/NSFW.cpp:77:3: error: 'mErrorCallback' was not declared in this scope
   mErrorCallback.Release();
   ^
../src/NSFW.cpp:78:3: error: 'mEventCallback' was not declared in this scope
   mEventCallback.Release();
   ^
../src/NSFW.cpp: In member function 'virtual void NSFW::StartWorker::Execute()':
../src/NSFW.cpp:113:12: error: 'class NSFW' has no member named 'mErrorCallback'
     mNSFW->mErrorCallback.Acquire();
            ^
../src/NSFW.cpp:114:12: error: 'class NSFW' has no member named 'mEventCallback'
     mNSFW->mEventCallback.Acquire();
            ^
../src/NSFW.cpp: In member function 'void NSFW::pollForEvents()':
../src/NSFW.cpp:204:9: error: 'mErrorCallback' was not declared in this scope
         mErrorCallback.NonBlockingCall([error](Napi::Env env, Napi::Function jsCallback) {
         ^
../src/NSFW.cpp:242:11: error: 'mEventCallback' was not declared in this scope
           mEventCallback.NonBlockingCall(events.release(), callback);
           ^
../src/NSFW.cpp:250:3: error: 'mErrorCallback' was not declared in this scope
   mErrorCallback.Release();
   ^
../src/NSFW.cpp:251:3: error: 'mEventCallback' was not declared in this scope
   mEventCallback.Release();
   ^
make: *** [Release/obj.target/nsfw/src/NSFW.o] Error 1
make: Leaving directory `/node_modules/nsfw/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.19.76-linuxkit
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node_modules/nsfw
gyp ERR! node -v v10.14.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**What is the expected behavior?**

Install is expected to succeed at it used to do for the past 6 months.

**Steps to Reproduce**

I can reproduce the issue when I run the following command in my Docker container:

```
yarn nsfw
```

**Environment**

- Node Version: `10.14.0`
- Yarn v1 Version: `1.22` 
- OS and version: Ubuntu 18

**Comment by paul-soporan** [comment]
Closing as external (it's a `node-gyp` error that Yarn doesn't control).
