### ISSUE TITLE
yarn policies set-version failing 

### ISSUE THREAD

**Issue by phil-kahrl** [yarnpkg/yarn#8062]
"yarn policies set-version" is failing and returning an error.

I get the same error while running on MacOS, as well as on Ubuntu build servers.

Command line output is captured below: 
``
yarn policies set-version
Resolving latest to a url...
Downloading https://github.com/yarnpkg/yarn/releases/download/v1.22.4/yarn-1.22.4.js...
Saving it into /Users/viewpathuser/workspace/viewpath5/.yarn/releases/yarn-1.22.4.js...
Updating /Users/viewpathuser/workspace/viewpath5/.yarnrc...
error An unexpected error occurred: "Cannot create property 'yarn-path' on string '--ignore-optional'".
info If you think this is a bug, please open a bug report with the information provided in "/Users/viewpathuser/workspace/viewpath5/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/policies for documentation about this command.
``

Trace from yarn-error.log

``
Trace: 
  TypeError: Cannot create property 'yarn-path' on string '--ignore-optional'
      at /usr/local/lib/node_modules/yarn/lib/cli.js:90316:25
      at Generator.next (<anonymous>)
      at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
      at /usr/local/lib/node_modules/yarn/lib/cli.js:321:13
``

**Environment**

- Node Version: `v13.13.0`
- Yarn v1 Version: `1.22.0` 
- OS and version: ` darwin x64`

[yarn-error.log](https://github.com/yarnpkg/yarn/files/4482571/yarn-error.log)

**Comment by alanrps** [comment]
Hi, I tested your problem and received success in the process, do you try to use `--ignore-optional` as recommended by the error? Are you still with the error?

![image](https://user-images.githubusercontent.com/33161962/116630803-508bec80-a92a-11eb-9ab9-886e69477abf.png)
