### ISSUE TITLE
`yarn remove <package>` results in `Error: Cannot find module './build/Release/re2'`

### ISSUE THREAD

**Issue by niftylettuce** [yarnpkg/yarn#8167]
If you uninstall a package with `yarn remove <package>` it causes a build issue with a package built with `node-gyp` in your `node_modules` folder.  Specifically in my case it was the `re2` package.

You can reproduce this by:

```sh
git clone https://github.com/forwardemail/forwardemail.net.git
cd forwardemail.net
yarn
node api
yarn add <insert random package>
yarn remove <insert random package>
node api
```

On the last call of `node api` to start the `api.js` process, you will see it will give you this error:

```sh
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module './build/Release/re2'
Require stack:
- /Users/user/Projects/forwardemail.net/node_modules/re2/re2.js
- /Users/user/Projects/forwardemail.net/node_modules/forward-email/index.js
- /Users/user/Projects/forwardemail.net/app/models/alias.js
- /Users/user/Projects/forwardemail.net/app/models/index.js
- /Users/user/Projects/forwardemail.net/helpers/passport.js
- /Users/user/Projects/forwardemail.net/config/api.js
- /Users/user/Projects/forwardemail.net/api.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/user/Projects/forwardemail.net/node_modules/re2/re2.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/user/Projects/forwardemail.net/node_modules/forward-email/index.js:10:13)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/user/Projects/forwardemail.net/app/models/alias.js:2:22)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/user/Projects/forwardemail.net/node_modules/re2/re2.js',
    '/Users/user/Projects/forwardemail.net/node_modules/forward-email/index.js',
    '/Users/user/Projects/forwardemail.net/app/models/alias.js',
    '/Users/user/Projects/forwardemail.net/app/models/index.js',
    '/Users/user/Projects/forwardemail.net/helpers/passport.js',
    '/Users/user/Projects/forwardemail.net/config/api.js',
    '/Users/user/Projects/forwardemail.net/api.js'
  ]
}
```

Ref: https://github.com/google/re2/issues/261
Ref: https://github.com/forwardemail/forwardemail.net

**Comment by niftylettuce** [comment]
yarn@1.22.4
node@12.16.1
re2@1.14.0

**Comment by rainy-me** [comment]
I just running into this problem. Remove `node_modules` and install again fixed it for me.
