### ISSUE TITLE
yarn fails in chroot environment 

### ISSUE THREAD

**Issue by ioweb-gr** [yarnpkg/yarn#8174]
### Bug description
I'm trying to use yarn in a chroot environment on ubuntu 18.04 but it's facing issues when installing node-sass
The error is 

```
[4/4] Building fresh packages...
[1/3] ⡀ core-js
[2/3] ⡀ uglifyjs-webpack-plugin
verbose 12.811978239 Error: /httpdocs/node_modules/node-sass: Command failed.
Exit code: 127
Command: node scripts/install.js
Arguments:
Directory: /httpdocs/node_modules/node-sass
Output:
/tmp/yarn--1591421669328-0.41023769287485123/node: 3: exec: /tmp/yarn--1591421669328-0.41023769287485123/../node: not found
    at ProcessTermError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at new ProcessTermError (/usr/local/lib/node_modules/yarn/lib/cli.js:790:113)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:25884:17)
    at ChildProcess.emit (events.js:311:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:311:20)
    at Pipe.<anonymous> (net.js:668:12)
error /httpdocs/node_modules/node-sass: Command failed.
Exit code: 127
Command: node scripts/install.js
Arguments:
Directory: /httpdocs/node_modules/node-sass
Output:
/tmp/yarn--1591421669328-0.41023769287485123/node: 3: exec: /tmp/yarn--1591421669328-0.410237692874851
```

**Command**

```sh
yarn add node-sass
```

**What is the current behavior?**
Currently it's throwing an error because it cannot find node. However on my chrooted shell node exists and works. If I execute node -v it gives a result. 
`which node` shows the path `/usr/bin/node` 

For some reason yarn is trying to use a `node` that's in /tmp/yarn.XXXXXXX-XXXX/node which points to /tmp/node

If I add a symlink to that path everything works. 

**What is the expected behavior?**
node is detected correctly in the environment and `node-sass` is installed

**Steps to Reproduce**
1. I'm not sure how to replicate this as I'm facing it in a server installation that uses chroot and I'm an isolated user. The hosting provider uses PLESK

**Environment**

- Node Version: `v12.16.1`
- Yarn v1 Version: `1.22.4` 
- OS and version: `Ubuntu 18.04.4 LTS`

npm install node-sass works correctly.

**Comment by ioweb-gr** [comment]
Any help with this one guys?
