### ISSUE TITLE
Installation Problem: Yarn was installed, but doesn't seem to be working :(

### ISSUE THREAD

**Issue by dinsundi** [yarnpkg/yarn#8195]
**Which operating system are you using:**
curl -o- -L https://yarnpkg.com/install.sh | bash

installation de yarn sur debian 9 avec nodejs v4.8.2
**Please describe the steps you took when trying to install Yarn and what went wrong:**

/root/.yarn/lib/cli.js:46099
  let {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/.yarn/bin/yarn.js:24:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
> Yarn was installed, but doesn't seem to be working :(.

**Comment by tufantunc** [comment]
That installation command is for MacOS.
You are using Debian, right?

Configure the repo:
```bash
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
```

Then install:
```bash
sudo apt update && sudo apt install yarn
```

You can see details on https://classic.yarnpkg.com/en/docs/install/#debian-stable

**Comment by paul-soporan** [comment]
>let {
>    ^

You need to update your Node version.
