### ISSUE TITLE
Unhandled 'error' event - error Command failed with exit code 1.

### ISSUE THREAD

**Issue by zjivkas** [yarnpkg/yarn#8200]
### Bug description
I am starting a local development server with hotcode reloading and using yarn dev to load creditial files. The files are coming from a private company repository.

```
$ yarn dev
yarn run v1.22.4
$ vue-cli-service serve --open
 INFO  Starting development server...
98% after emitting CopyPlugin

 DONE  Compiled successfully in 293471ms                              9:53:28 PM

  App running at:
  - Local:   http://localhost:8080/
  - Network: unavailable

  Note that the development build is not optimized.
  To create a production build, run yarn build.

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs: [ '/c', 'start', '""', '/b', 'http://localhost:8080/' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.

```

Yarn seems to be doing everything as I expected, up until the very last moment. It is throws this error. My friend installs it perfectly on his windows machine, so I know it is not a problem with the repository.

My efforts to fix... I have tried:
-deleting/recloning depository, then reinstalling yarn in directory, repeating process
-deleting in order to recreate package-lock.json, 
-even trying `npm run dev`

**Environment**

- Node Version: `12.18.1`
- Yarn v1 Version: `1.22.4` 
- OS and version: Microsoft Windows 7 Home Premium, Version	6.1.7601 Service Pack 1 Build 7601

**Comment by zjivkas** [comment]
Eventually
