### ISSUE TITLE
TypeError: r(...).bortliDecompessSync is not a function

### ISSUE THREAD

**Issue by ADustyOldMuffin** [yarnpkg/yarn#8205]
### Bug description
When I run `yarn set version berry` the install finishes fine, but anytime I use a yarn command after that I get greeted with this error message.

```
insert\path\here\.yarn\releases\yarn-berry.js:77
 */s=function(){"use strict";return function(){return process&&("win32"===process.platform||/^(msys|cygwin)$/.test(process.env.OSTYPE))}},t&&"object"==typeof t&&void 0!==e?e.exports=s():(i=[],void 0===(o="function"==typeof(n=s)?n.apply(t,i):n)||(e.exports=o))},function(e,t,r){var n=r(14),i=r(854),o=r(405),s=r(156).Writable,a=r(156).PassThrough,A=function(){},c=function(e){return(e&=511)&&512-e},u=function(e,t){this._parent=e,this.offset=t,a.call(this)};n.inherits(u,a),u.prototype.destroy=function(e){this._parent.destroy(e)};var l=function(e){if(!(this instanceof l))return new l(e);s.call(this,e),e=e||{},this._offset=0,this._buffer=i(),this._missing=0,this._partial=!1,this._onparse=A,this._header=null,this._stream=null,this._overflow=null,this._cb=null,this._locked=!1,this._destroyed=!1,this._pax=null,this._paxGlobal=null,this._gnuLongPath=null,this._gnuLongLinkPath=null;var t=this,r=t._buffer,n=function(){t._continue()},a=fu

TypeError: r(...).brotliDecompressSync is not a function
    at Module.<anonymous> (insert\path\here\.yarn\releases\yarn-berry.js:77:145188)
    at r (insert\path\here\.yarn\releases\yarn-berry.js:2:124)
    at t.getPluginConfiguration (insert\path\here\.yarn\releases\yarn-berry.js:31:406251)
    at Module.<anonymous> (insert\path\here\.yarn\releases\yarn-berry.js:77:190590)
    at r (insert\path\here\.yarn\releases\yarn-berry.js:2:124)
    at insert\path\here\.yarn\releases\yarn-berry.js:2:923
    at Object.<anonymous> (insert\path\here\.yarn\releases\yarn-berry.js:2:934)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

**Command**

Any yarn command

**What is the current behavior?**

Yarn errors out on any command after setting version to berry.

**What is the expected behavior?**

Yarn to not error out.

**Steps to Reproduce**

1. install yarn with `npm install yarn -g`
2. `yarn set version berry` in project folder
3. Run any yarn command

**Environment**

- Node Version: `10.6.0`
- Yarn v1 Version: `1.22.4` 
- OS and version: Windows 10

**Comment by saravntbe** [comment]
Same issue happening in Mac os `10.15.5` 
Node Version: `10.15.1`
Error Mesage: 
```
yarn --version
/Users/syr/Downloads/testMonoRepo/.yarn/releases/yarn-berry.js:2
module.exports=(()=>{var __webpack_modules__={49775:e=>{"use strict";e.exports=JSON.parse('{"u2":"@yarnpkg/plugin-compat"}')},35729:e=>{"use strict";e.exports=JSON.parse('{"u2":"@yarnpkg/plugin-dlx"}')},37904:e=>{"use strict";e.exports=JSON.parse('{"u2":"@yarnpkg/plugin-essentials"}')},17508:e=>{"use strict";e.exports=JSON.parse('{"u2":"@yarnpkg/plugin-file"}')},84779:e=>{"use strict";e.exports=JSON.parse('{"u2":"@yarnpkg/plugin-git"}')},88454:e=>{"use strict";e.exports=JSON.parse('{"u2":"@yarnpkg/plugin-github"}')},91953:e=>{"use strict";e.exports=JSON.parse('{"u2":"@yarnpkg/plugin-http"}')},63756:e=>{"use strict";e.exports=JSON.parse('{"u2":"@yarnpkg/plugin-init"}')},23100:e=>{"use strict";e.exports=JSON.parse('{"u2":"@yarnpkg/plugin-link"}')},47047:e=>{"use strict";e.exports=JSON.parse('{"u2":"@yarnpkg/plugin-node-modules"}')},31880:e=>{"use strict";e.exports=JSON.parse('{"u2":"@yarnpkg/plugin-npm-cli"}')},67310:e=>{"use strict";e.exports

TypeError: r(...).brotliDecompressSync is not a function
    at Module.80150 (/Users/syr/Downloads/testMonoRepo/.yarn/releases/yarn-berry.js:2:2181)
    at __webpack_require__ (/Users/syr/Downloads/testMonoRepo/.yarn/releases/yarn-berry.js:86:546526)
    at t.e (/Users/syr/Downloads/testMonoRepo/.yarn/releases/yarn-berry.js:2:444165)
    at Module.28638 (/Users/syr/Downloads/testMonoRepo/.yarn/releases/yarn-berry.js:2:219681)
    at __webpack_require__ (/Users/syr/Downloads/testMonoRepo/.yarn/releases/yarn-berry.js:86:546526)
    at module.exports (/Users/syr/Downloads/testMonoRepo/.yarn/releases/yarn-berry.js:86:547491)
    at Object.<anonymous> (/Users/syr/Downloads/testMonoRepo/.yarn/releases/yarn-berry.js:86:547519)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```
