### ISSUE TITLE
Installation Problem: [Yarn installs but fails on run]

### ISSUE THREAD

**Issue by jeanlinux** [yarnpkg/yarn#8228]
**Which operating system are you using:**
MacOS Ver: 10.15.2 (Catalina)

**Please describe the steps you took when trying to install Yarn and what went wrong:**

Yarn installs but fails when the yarn command is entered with the following error

>yarn 

>TypeError: Cannot read property 'yarnPath' of null
    at loadRcFile (/usr/local/lib/node_modules/yarn/lib/cli.js:56945:49)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:56916:14
    at /usr/local/lib/node_modules/yarn/lib/cli.js:101331:14
    at Array.map (<anonymous>)
    at parseRcPaths (/usr/local/lib/node_modules/yarn/lib/cli.js:101329:78)
    at Object.findRc (/usr/local/lib/node_modules/yarn/lib/cli.js:101343:10)
    at getRcConfigForCwd (/usr/local/lib/node_modules/yarn/lib/cli.js:56915:74)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:92694:56
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30) 

I tried uninstalling and reinstalling but the issue persists, I also tried all the methods listed in the [alternate ways](https://yarnpkg.com/en/docs/install)

**Comment by iandrc** [comment]
Hey @jeanlinux 

Could you give a bit more information? Probably it would be nice to see at least your `package.json`.

**Comment by czlux** [comment]
I also have the same problem! 

OS version macOS Big Sur
node -v
v15.4.0
 npm -v
7.0.15





TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type boolean (true)
    at new NodeError (node:internal/errors:278:15)
    at validateString (node:internal/validators:123:11)
    at resolve (node:path:1019:7)
    at loadRcFile (/usr/local/lib/node_modules/yarn/lib/cli.js:56953:58)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:56917:14
    at /usr/local/lib/node_modules/yarn/lib/cli.js:100892:14
    at Array.map (<anonymous>)
    at parseRcPaths (/usr/local/lib/node_modules/yarn/lib/cli.js:100890:78)
    at Object.findRc (/usr/local/lib/node_modules/yarn/lib/cli.js:100904:10)
    at getRcConfigForCwd (/usr/local/lib/node_modules/yarn/lib/cli.js:56916:74)

**Comment by plainnany** [comment]
I alse have the same problem.
window10
![image](https://user-images.githubusercontent.com/27320655/102886494-27e17b00-4490-11eb-91ce-4fbab3128598.png)

**Comment by merceyz** [comment]
Closing as you most likely have a invalid `.yarnrc` in your home directory
