### ISSUE TITLE
Bug installing yarn 1.22.1 on MacOS 1.15.4

### ISSUE THREAD

**Issue by n-alex-white** [yarnpkg/yarn#8234]
### Bug description
trying to install yarn on MacOS Catalina. 

Whether using homebrew or curl, I get the same result when running any yarn command

**Command**

```sh
yarn --version
```

**What is the current behavior?**

I receive the following error after any attempt to run yarn

/Users/Alex/GitHub/backstage/.yarn/releases/yarn-1.22.1.js:26
    ); // Flag the module as loaded
    ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

**What is the expected behavior?**
I expect it to work! in this case return a version number, but at the moment it doesn't do anything. 

**Steps to Reproduce**

1. install yarn using homebrew 
2. run yarn 
3. see error

**Environment**

- Node Version: `v6.3.1`
- Yarn v1 Version: `1.22.1` 
- OS and version: MacOS 10.15.4

**Comment by n-alex-white** [comment]
Updating node to v 12.18.1 resolved this.
