### ISSUE TITLE
Yarn install - not finding python even it is installed

### ISSUE THREAD

**Issue by nikolacojcic99** [yarnpkg/yarn#8241]
I am on **Ubuntu 18.04**

I am sure **python** is installed on the server.
```
$whereis python
python: /usr/bin/python3.6 /usr/bin/python /usr/bin/python3.6m /usr/lib/python3.6 /usr/lib/python3.8 /usr/lib/python2.7 /usr/lib/python3.7 /etc/python3.6 /usr/local/lib/python3.6 /usr/share/python
```

```
$yarn
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/home/ubuntu/project/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/ubuntu/project/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/ubuntu/project/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/ubuntu/project/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/ubuntu/project/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/ubuntu/project/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:176:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/home/ubuntu/project/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/ubuntu/project/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/ubuntu/project/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/ubuntu/project/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/ubuntu/project/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/ubuntu/project/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:176:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
gyp ERR! System Linux 5.3.0-1023-aws
gyp ERR! command "/home/ubuntu/.nvm/versions/node/v14.5.0/bin/node" "/home/ubuntu/project/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/ubuntu/project/node_modules/node-sass
gyp ERR! node -v v14.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
```

I think there should be an issue to set the **python** path.
But I am not sure how I can fix this issue.
Anyone can help me?

**Comment by paul-soporan** [comment]
Closing as an external issue (`node-gyp` is erroring, not Yarn).
