### ISSUE TITLE
Renaming a workspace breaks all Yarn commands

### ISSUE THREAD

**Issue by davewthompson** [yarnpkg/yarn#8252]
### Bug description
Appears to be Yarn caching based on filenames is breaking when you rename a workspace after an initial run of the Yarn commands.

**Command**

```sh
yarn workspaces foreach -a run build
```

**What is the current behavior?**
Renaming a workspace package and then running workspace commands yields:
```sh
➤ YN0000: Internal Error: Assertion failed: Expected workspace to have been resolved
➤ YN0000:     at ne.refreshWorkspaceDependencies (/Users/dave/Projects/git/<redacted>/.yarn/releases/yarn-berry.js:2:283086)
➤ YN0000:     at ne.restoreInstallState (/Users/dave/Projects/git/<redacted>/.yarn/releases/yarn-berry.js:2:307778)
➤ YN0000:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
➤ YN0000:     at async Se.execute (/Users/dave/Projects/git/<redacted>/.yarn/releases/yarn-berry.js:2:78261)
➤ YN0000:     at async Se.validateAndExecute (/Users/dave/Projects/git/<redacted>/.yarn/releases/yarn-berry.js:2:551219)
➤ YN0000:     at async U.run (/Users/dave/Projects/git/<redacted>/.yarn/releases/yarn-berry.js:17:18859)
➤ YN0000:     at async o (/Users/dave/Projects/git/<redacted>/.yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs:5:4802)
➤ YN0000:     at async /Users/dave/Projects/git/<redacted>/.yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs:5:5632
```

**What is the expected behavior?**
Yarn can still continue to operate when a workspace is renamed.

**Steps to Reproduce**

1. Create a basic workspace, with a couple of child projects and the `plugin-workspace-tools` plugin.
2. Run `yarn workspaces foreach -a run build` to pull in all dependencies
3. Rename a workspace.
4. Run `yarn workspaces foreach -a run build` again to see the error.

**Environment**

- Node Version: `12.16.1`
- Yarn v1 Version: `1.22.4` 
- OS and version: macOS, latest

**Comment by davidpodhola** [comment]
Just in case someone similar to me would come here from the search - a workaround is to delete the `.yarn` folder and run `yarn` again.
