### ISSUE TITLE
error An unexpected error occurred: "https://registry.npmjs.org/create-react-app: error:0909006C:PEM routines:get_name:no start 

### ISSUE THREAD

**Issue by ShivamNamdeo** [yarnpkg/yarn#8254]
yarn global v1.22.4
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.npmjs.org/create-react-app: error:0909006C:PEM routines:get_name:no start line".
info If you think this is a bug, please open a bug report with the information provided in "/home/cs/.config/yarn/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

______________________________________________________________________________________________________

Arguments: 
  /home/cs/.nvm/versions/node/v14.6.0/bin/node /usr/share/yarn/bin/yarn.js add react-native --exact

PATH: 
  /home/cs/.nvm/versions/node/v14.6.0/bin:/home/cs/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/cs/Android/Sdk/emulator:/home/cs/Android/Sdk/tools:/home/cs/Android/Sdk/tools/bin:/home/cs/Android/Sdk/platform-tools

Yarn version: 
  1.22.4

Node version: 
  14.6.0

Platform: 
  linux x64

Trace: 
  Error: https://registry.npmjs.org/react-native: error:0909006C:PEM routines:get_name:no start line
      at Object.createSecureContext (_tls_common.js:149:17)
      at Object.connect (_tls_wrap.js:1580:48)
      at Agent.createConnection (https.js:128:22)
      at Agent.createSocket (_http_agent.js:319:26)
      at Agent.addRequest (_http_agent.js:272:10)
      at new ClientRequest (_http_client.js:306:16)
      at Object.request (https.js:312:10)
      at Request.module.exports.Request.start (/usr/share/yarn/lib/cli.js:141310:32)
      at Request.module.exports.Request.end (/usr/share/yarn/lib/cli.js:142069:10)
      at end (/usr/share/yarn/lib/cli.js:141123:14)

npm manifest: 
  No manifest

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

**Comment by rally25rs** [comment]
Going to close this issue in favor of #8254 since I started to leave comments there.

**Comment by aleksandarPerc** [comment]
My problem was that i've accidentally written some meaningless keys in my .npmrc file. SO if that is your case, just clean it up...
Mine has just one uncommented entry:
registry=http://registry.npmjs.org/
