### ISSUE TITLE
Yarn tarball install xubuntu SyntaxError for `yarn`

### ISSUE THREAD

**Issue by st-fresh** [yarnpkg/yarn#8256]
### Bug description

**Command**

```sh
yarn
```

**What is the current behavior?**
Following [https://classic.yarnpkg.com/en/docs/install#alternatives-stable](https://classic.yarnpkg.com/en/docs/install#alternatives-stable)
.
Unpacked to `/opt` using `tar zvxf yarn-v1.22.4.tar.gz`
.
Manually added `export PATH="$PATH:/opt/yarn-v1.22.4/bin` to `/home/username/.bashrc` (saved out with nano)
.
Terminal restart shows .bashrc retained saved change
.
At `/home` trying `yarn` produces Syntax Error see below

**What is the expected behavior?**
yarn works

**Steps to Reproduce**
```
username@pcname:/$ yarn
/opt/yarn-v1.22.4/lib/cli.js:46099
  let {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/opt/yarn-v1.22.4/bin/yarn.js:24:13)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

**Environment**

- Node Version: `v4.2.1`
- Yarn v1 Version: `1.22.4` 
- OS and version: 4.16.18-galliumos x86_64 (Xubuntu) GNU/Linux

**Comment by soloturn** [comment]
which xubuntu version are you on? what is the result if you choose to use the debian/ubuntu install:
https://classic.yarnpkg.com/en/docs/install/#debian-stable

**Comment by st-fresh** [comment]
avoided by using .AppImage instead
