### ISSUE TITLE
Newbie problem installing Yarn -- EACCES: permission denied, open '/Users/kchapman/.config/yarn'

### ISSUE THREAD

**Issue by kennethchapman99** [yarnpkg/yarn#8317]
I'm just trying to setup a React/Flask app and need to install yarn to get going.   
On MacOS Catalina 10.15.5
In terminal am running:  'install yarn' (same issue if using homebrew to install yarn, or this command: curl -o- -L https://yarnpkg.com/install.sh | bash)

Getting this error when the installation starts:
Installing Yarn!
/Users/kchapman/.yarn/bin/yarn
Error: EACCES: permission denied, open '/Users/kchapman/.config/yarn'
    at Object.openSync (fs.js:440:3)
    at readFileSync (fs.js:342:35)
    at /Users/kchapman/.yarn/lib/cli.js:101331:58
    at Array.map (<anonymous>)
    at parseRcPaths (/Users/kchapman/.yarn/lib/cli.js:101329:78)
    at Object.findRc (/Users/kchapman/.yarn/lib/cli.js:101343:10)
    at getRcConfigForCwd (/Users/kchapman/.yarn/lib/cli.js:56915:74)
    at /Users/kchapman/.yarn/lib/cli.js:92694:56
    at Generator.next (<anonymous>)
    at step (/Users/kchapman/.yarn/lib/cli.js:310:30)

I am not nearly proficient enough with permissions/paths, etc to know how to address this from here.  Any assistance you can provide is greatly appreciated!

The app I'm building is meant to help teachings forced to teach online this Fall :)

**Comment by kennethchapman99** [comment]
Fixed it!
sudo chown -R $USER:$GROUP ~/.config
