### ISSUE TITLE
An unexpected error occurred: "couldn't find ngx-electron".

### ISSUE THREAD

**Issue by fbaldo31** [yarnpkg/yarn#8323]
### Bug description

**Command**

```sh
yarn upgrade
```

**Steps to Reproduce**

[angular-electron-starter](https://github.com/fbaldo31/angular-electron-starter)
1. Clone the repo
2. Run yarn upgrade

Note it will fail with yarn install as well on the same package

But the package does exist :) here https://www.npmjs.com/package/ngx-electron i the last version is mentioned

**Environment**

- Node Version: `x.x.x`
- Yarn v1 Version: `1.22.5` 
- OS and version:  linux x64 Ubuntu 18.0.4

```
Trace: 
  Error: couldn't find ngx-electron
      at NpmRegistry.<anonymous> (/home/fred/.yarn/lib/cli.js:31760:15)
      at Generator.next (<anonymous>)
      at step (/home/fred/.yarn/lib/cli.js:310:30)
      at /home/fred/.yarn/lib/cli.js:321:13
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by fbaldo31** [comment]
My bad ...
