### ISSUE TITLE
Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by edoloughlin** [yarnpkg/yarn#836]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Running _yarn install_ on my project gives the following output:

```
yarn install v0.15.1
info No lockfile found.
error TypeError: myProject@3.0.0: Cannot read property 'toUpperCase' of undefined
    at Array.<anonymous> (C:\Users\thisUser\AppData\Roaming\npm\node_modules\yarn\node_modules\spdx-correct\index.js:82:23)
    at validTransformation (C:\Users\thisUser\AppData\Roaming\npm\node_modules\yarn\node_modules\spdx-correct\index.js:173:36)
    at module.exports (C:\Users\thisUser\AppData\Roaming\npm\node_modules\yarn\node_modules\spdx-correct\index.js:215:21)
    at module.exports (C:\Users\thisUser\AppData\Roaming\npm\node_modules\yarn\node_modules\validate-npm-package-license\index.js:60:23)
    at isValidLicense (C:\Users\thisUser\AppData\Roaming\npm\node_modules\yarn\lib-legacy\util\normalize-manifest\util.js:16:10)
    at exports.default (C:\Users\thisUser\AppData\Roaming\npm\node_modules\yarn\lib-legacy\util\normalize-manifest\validate.js:53:55)
    at C:\Users\thisUser\AppData\Roaming\npm\node_modules\yarn\lib-legacy\util\normalize-manifest\index.js:56:51
    at next (native)
    at step (C:\Users\thisUser\AppData\Roaming\npm\node_modules\yarn\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\thisUser\AppData\Roaming\npm\node_modules\yarn\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:20
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
**If the current behavior is a bug, please provide the steps to reproduce.**
yarn install

**What is the expected behavior?**
Dependencies are installed
**Please mention your node.js, yarn and operating system version.**
yarn 0.15.1
node 4.5.0
Windows 7 (I get the same output running yarn under Cygwin and a CMD shell)

**Comment by whomwah** [comment]
I had this. I had an empty `License` field (as in empty string) in the `package.json`. So I imagine you have an empty field in there somewhere.

**Comment by edoloughlin** [comment]
That works. Thanks.

**Comment by kyaso** [comment]
In case someone else stumbled upon this thread: For me, deleting the existing `yarn.lock`, creating a new empty `yarn.lock`, and running `yarn install` again, solved it.
