### ISSUE TITLE
Error: Cannot find module 'event-stream'

### ISSUE THREAD

**Issue by NikolayMakhonin** [yarnpkg/yarn#8382]
## Environment

- Node Version: `12.17.0`
- Yarn v1 Version: `1.22.10` 
- OS and version: Win7 (Microsoft Windows [Version 6.1.7601])

### 1. Create these files:

**package.json**
```json
{
  "name": "test-yarn",
  "devDependencies": {
    "ps-tree": "1.2.0"
  }
}
```

**index.js**
```js
const psTree = require('ps-tree')
```

### 2. Run these commands:
```sh
npm install -g yarn@1.22.10
yarn set version berry
yarn config set enableGlobalCache true
yarn node index.js
```

### 3. Get this error:
```
c:\projects\test-yarn>yarn node index.js
c:\projects\test-yarn\.pnp.js:6435
    throw firstError;
    ^

Error: Cannot find module 'event-stream'
Require stack:
- c:\cache\Yarn\Berry\cache\ps-tree-npm-1.2.0-3975e95bd6-7.zip\node_modules\ps-tree\index.js
- c:\projects\test-yarn\index.js
Require stack:
- c:\cache\Yarn\Berry\cache\ps-tree-npm-1.2.0-3975e95bd6-7.zip\node_modules\ps-tree\index.js
- c:\projects\test-yarn\index.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)←[39m
    at Function.external_module_.Module._resolveFilename (c:\projects\test-yarn\.pnp.js:6415:54)
←[90m    at Module._load (internal/modules/cjs/loader.js:842:27)←[39m
    at Function.external_module_.Module._load (c:\projects\test-yarn\.pnp.js:6271:36)
←[90m    at Module.require (internal/modules/cjs/loader.js:1026:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:72:18)←[39m
    at Object.<anonymous> (c:\cache\Yarn\Berry\cache\ps-tree-npm-1.2.0-3975e95bd6-7.zip\node_modules\←[4mps-tree←[24m\index.js:4:13)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1138:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:986:32)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m
}
```

**Comment by NikolayMakhonin** [comment]
Moved here:
https://github.com/yarnpkg/berry/issues/1944
