### ISSUE TITLE
Error running yarn

### ISSUE THREAD

**Issue by ralhako** [yarnpkg/yarn#8392]
OS: ‪Ubuntu 16.04.7 LTS‬
Produkt: Plesk Obsidian 18.0.30

I have installed yarn with this instruction: https://classic.yarnpkg.com/en/docs/install/#debian-stable

# yarn --version
/usr/share/yarn/lib/cli.js:46100
  let {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/share/yarn/bin/yarn.js:24:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

What is / where to find / how to resolve the problem? Thanks!

# find / -name yarn
/usr/bin/yarn
/usr/share/yarn
/usr/share/yarn/bin/yarn
/usr/share/lintian/overrides/yarn
/usr/share/doc/yarn

**Comment by ultra-pool** [comment]
Same here. Iv tried a few things. About to just reformat and start clean.

**Comment by merceyz** [comment]
I'd guess you have a really old node version but without a reproduction there isn't anything we can do
