### ISSUE TITLE
Installation Problem: [title]

### ISSUE THREAD

**Issue by NithishStarkid03** [yarnpkg/yarn#8402]
**Which operating system are you using:**

**Please describe the steps you took when trying to install Yarn and what went wrong:**

3s.
(node:22336) UnhandledPromiseRejectionWarning: Error: Cannot find module 'D:\Projects\ReactNative\confusion\node_modules\react-native-scripts\build\scripts\init.js'
Require stack:
- C:\Users\nithe\AppData\Local\Yarn\Data\global\node_modules\create-react-native-app\build\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at _callee2$ (C:\Users\nithe\AppData\Local\Yarn\Data\global\node_modules\create-react-native-app\build\index.js:128:32)
    at tryCatch (C:\Users\nithe\AppData\Local\Yarn\Data\global\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (C:\Users\nithe\AppData\Local\Yarn\Data\global\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (C:\Users\nithe\AppData\Local\Yarn\Data\global\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (C:\Users\nithe\AppData\Local\Yarn\Data\global\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\nithe\AppData\Local\Yarn\Data\global\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
(node:22336) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22336) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by merceyz** [comment]
Closing as there is nothing actionable here
