### ISSUE TITLE
yarn add axios fails

### ISSUE THREAD

**Issue by pererasys** [yarnpkg/yarn#8425]
### Bug description

Can't install certain dependency of the Axios module. Not sure if this is on their end or yours.

**Command**

```sh
yarn add axios
```

**What is the current behavior?**

I have tried uninstalling and reinstalling yarn, as well as removing all cache.

--------------------------------------------------------------------------------------------------------------------------

Arguments: 
  /usr/local/Cellar/node/15.0.1/bin/node /usr/local/Cellar/yarn/1.22.10/libexec/bin/yarn.js add axios

PATH: 
  /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin

Yarn version: 
  1.22.10

Node version: 
  15.0.1

Platform: 
  darwin x64

Trace: 
  Error: https://registry.yarnpkg.com/@babel/plugin-toCamel-arrow-functions/-/plugin-toCamel-arrow-functions-7.12.1.tgz: Request failed "404 Not Found"
      at ResponseError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:696:66)
      at new ResponseError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:802:124)
      at Request.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:67058:16)
      at Request.emit (node:events:327:20)
      at Request.module.exports.Request.onRequestResponse (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:141626:10)
      at ClientRequest.emit (node:events:327:20)
      at HTTPParser.parserOnIncomingClient (node:_http_client:652:27)
      at HTTPParser.parserOnHeadersComplete (node:_http_common:126:17)
      at TLSSocket.socketOnData (node:_http_client:518:22)
      at TLSSocket.emit (node:events:327:20)

**What is the expected behavior?**

Axios will install.

**Steps to Reproduce**

1. Try to install axios

**Environment**

- Node Version: 15.0.1
- Yarn v1 Version: 1.22.10 (installed using brew)
- OS and version: macOS Catalina 10.15.5

**Comment by pererasys** [comment]
I'm dumb, i replaced all and messed up a babel dependency.
