### ISSUE TITLE
Cannot authenticate under @Release view of Azure Artifacts

### ISSUE THREAD

**Issue by luanbon** [yarnpkg/yarn#8453]
### Bug description
Trying to install packages from a @Release view of a private Azure Artifacts feed, always returning "401 Unauthorized.", but works properly for a default view (Local).

**Some values have been omitted (TENANT, GUID, USER and PAT) for obvious reasons.** 

**Working:** 
registry=https://pkgs.dev.azure.com/{TENANT}/{GUID}/_packaging/comunidade/npm/registry/

**Not Working:** 
registry=https://pkgs.dev.azure.com/{TENANT}/{GUID}/_packaging/comunidade%40Release/npm/registry/

**It works properly running with npm install.**

**Command**

```sh
yarn add @comunidade/design-system-components

or 

yarn install
```

**What is the current behavior?**

**Verbose Install**
```
yarn add v1.22.4
verbose 0.205857207 Checking for configuration file "/home/luan/git/personal/comunidade-packages-test/.npmrc".
verbose 0.206339449 Found configuration file "/home/luan/git/personal/comunidade-packages-test/.npmrc".
verbose 0.206786666 Checking for configuration file "/home/luan/.npmrc".
verbose 0.206995634 Found configuration file "/home/luan/.npmrc".
verbose 0.207273097 Checking for configuration file "/home/luan/.nvm/versions/node/v12.18.0/etc/npmrc".
verbose 0.207480518 Checking for configuration file "/home/luan/git/personal/comunidade-packages-test/.npmrc".
verbose 0.20768955 Found configuration file "/home/luan/git/personal/comunidade-packages-test/.npmrc".
verbose 0.207962021 Checking for configuration file "/home/luan/git/personal/.npmrc".
verbose 0.208140985 Checking for configuration file "/home/luan/git/.npmrc".
verbose 0.208294349 Checking for configuration file "/home/luan/.npmrc".
verbose 0.208443136 Found configuration file "/home/luan/.npmrc".
verbose 0.20868432 Checking for configuration file "/home/.npmrc".
verbose 0.212688595 Checking for configuration file "/home/luan/git/personal/comunidade-packages-test/.yarnrc".
verbose 0.213117346 Found configuration file "/home/luan/git/personal/comunidade-packages-test/.yarnrc".
verbose 0.213487699 Checking for configuration file "/home/luan/.yarnrc".
verbose 0.213786703 Found configuration file "/home/luan/.yarnrc".
verbose 0.214202826 Checking for configuration file "/home/luan/.nvm/versions/node/v12.18.0/etc/yarnrc".
verbose 0.214465853 Checking for configuration file "/home/luan/git/personal/comunidade-packages-test/.yarnrc".
verbose 0.214718267 Found configuration file "/home/luan/git/personal/comunidade-packages-test/.yarnrc".
verbose 0.21507287 Checking for configuration file "/home/luan/git/personal/.yarnrc".
verbose 0.215347042 Checking for configuration file "/home/luan/git/.yarnrc".
verbose 0.215618119 Checking for configuration file "/home/luan/.yarnrc".
verbose 0.215884179 Found configuration file "/home/luan/.yarnrc".
verbose 0.216454386 Checking for configuration file "/home/.yarnrc".
verbose 0.220545172 current time: 2020-11-13T05:55:17.137Z
info No lockfile found.
[1/4] Resolving packages...
verbose 0.287151552 Performing "GET" request to "https://pkgs.dev.azure.com/{TENANT}/{GUID}/_packaging/comunidade%40Release/npm/registry/@comunidade%2fdesign-system-components".
verbose 0.930031777 Request "https://pkgs.dev.azure.com/{TENANT}/{GUID}/_packaging/comunidade%40Release/npm/registry/@comunidade%2fdesign-system-components" finished with status code 200.
[2/4] Fetching packages...
verbose 0.951799958 Performing "GET" request to "https://pkgs.dev.azure.com/{TENANT}/{GUID}/_packaging/comunidade@Release/npm/registry/@comunidade/design-system-components/-/design-system-components-1.2.0.tgz".
verbose 1.115225647 Error: https://pkgs.dev.azure.com/{TENANT}/{GUID}/_packaging/comunidade@Release/npm/registry/@comunidade/design-system-components/-/design-system-components-1.2.0.tgz: Request failed "401 Unauthorized"
    at ResponseError.ExtendableBuiltin (/home/luan/.nvm/versions/node/v12.18.0/lib/node_modules/yarn/lib/cli.js:696:66)
    at new ResponseError (/home/luan/.nvm/versions/node/v12.18.0/lib/node_modules/yarn/lib/cli.js:802:124)
    at Request.<anonymous> (/home/luan/.nvm/versions/node/v12.18.0/lib/node_modules/yarn/lib/cli.js:67057:16)
    at Request.emit (events.js:315:20)
    at Request.module.exports.Request.onRequestResponse (/home/luan/.nvm/versions/node/v12.18.0/lib/node_modules/yarn/lib/cli.js:141625:10)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:469:22)
    at TLSSocket.emit (events.js:315:20)
error An unexpected error occurred: "https://pkgs.dev.azure.com/{TENANT}/{GUID}/_packaging/comunidade@Release/npm/registry/@comunidade/design-system-components/-/design-system-components-1.2.0.tgz: Request failed \"401 Unauthorized\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/luan/git/personal/comunidade-packages-test/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**What is the expected behavior?**
Authenticate and install packages properly.

**Steps to Reproduce**

**$HOME/.npmrc**

PAT is an Azure Personal Access Token decoded to base64
```
; begin auth token
//pkgs.dev.azure.com/{TENANT}/{GUID}/_packaging/comunidade%40Release/npm/registry/:username={USER}
//pkgs.dev.azure.com/{TENANT}/{GUID}/_packaging/comunidade%40Release/npm/registry/:_password={PAT}
//pkgs.dev.azure.com/{TENANT}/{GUID}/_packaging/comunidade%40Release/npm/registry/:email=npm requires email to be set but doesn't use the value
//pkgs.dev.azure.com/{TENANT}/{GUID}/_packaging/comunidade%40Release/npm/:username={USER}
//pkgs.dev.azure.com/{TENANT}/{GUID}/_packaging/comunidade%40Release/npm/:_password={PAT}
//pkgs.dev.azure.com/{TENANT}/{GUID}/_packaging/comunidade%40Release/npm/:email=npm requires email to be set but doesn't use the value
; end auth token
```

**$HOME/.yarnrc**
```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

lastUpdateCheck 1605241227134
```

**Project .npmrc**
```
@comunidade:registry=https://pkgs.dev.azure.com/{TENANT}/{GUID}/_packaging/comunidade%40Release/npm/registry/
                        
always-auth=true
```

**Environment**

- Node Version: `v12.18.0`
- Yarn v1 Version: `1.22.4` 
- OS and version: Ubuntu 20.04 Focal

**Comment by KaMa75** [comment]
@luanbon did you solve this problem somehow? I experienced the same.

**Comment by danielweil** [comment]
I am experiencing the same
