### ISSUE TITLE
[WSL] cannot create property lastUpdateCheck on string 'lastUpdateCheck...'

### ISSUE THREAD

**Issue by FrederickEngelhardt** [yarnpkg/yarn#8469]
### Bug description
On WSL 2 using nvm I am unable to utilize yarn to do anything because it will exit out with a type error with attempting to create a property on lastUpdateCheck which already exists.

**Command**

```sh
# install yarn via brew or ubuntu tutorial
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
# Using NVM so exclude node
sudo apt update && sudo apt install --no-install-recommends yarn

# alternative
npm i -g yarn
 ```

**What is the current behavior?**
Whenever I run yarn install for a project I get the following error in my terminal

```sh
# this will use yarn install instead of npm if yarn is added
npx create-react-app my-test-app
# fails and rolls back with this message
TypeError: Cannot create property 'lastUpdateCheck' on string 'lastUpdateCheck 1603009736399'
    at YarnRegistry.<anonymous> (/usr/share/yarn/lib/cli.js:96344:30)
    at Generator.next (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:310:30)
    at /usr/share/yarn/lib/cli.js:328:14
    at new Promise (<anonymous>)
    at new F (/usr/share/yarn/lib/cli.js:5301:28)
    at YarnRegistry.<anonymous> (/usr/share/yarn/lib/cli.js:307:12)
    at YarnRegistry.saveHomeConfig (/usr/share/yarn/lib/cli.js:96351:20)
    at Add.<anonymous> (/usr/share/yarn/lib/cli.js:7930:35)
    at Generator.next (<anonymous>)
```

This occurs in a previous yarn repo as well. Example you have a react-app already created and run yarn to install the dependencies.
```sh
yarn
TypeError: Cannot create property 'lastUpdateCheck' on string 'lastUpdateCheck 1603009736399'
    at YarnRegistry.<anonymous> (/usr/share/yarn/lib/cli.js:96344:30)
    at Generator.next (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:310:30)
    at /usr/share/yarn/lib/cli.js:328:14
    at new Promise (<anonymous>)
    at new F (/usr/share/yarn/lib/cli.js:5301:28)
    at YarnRegistry.<anonymous> (/usr/share/yarn/lib/cli.js:307:12)
    at YarnRegistry.saveHomeConfig (/usr/share/yarn/lib/cli.js:96351:20)
    at Install.<anonymous> (/usr/share/yarn/lib/cli.js:7930:35)
    at Generator.next (<anonymous>)
```

**What is the expected behavior?**
There should be no lastUpdateCheck error. Yarn is not useable right now. 

1. Anyone got a workaround for this issue?
2. Is there a long term solution?

**Steps to Reproduce**
1. Use Ubuntu on WSL2 (windows computer)
2. Install NVM
3. `npx create-react-app my-wsl-test`
4. The above command should fail

**Environment**

- Node Version: `14.14.0`
- Yarn v1 Version: `1.22.5` 
- OS and version:  WSL 2 `Linux 4.19.104-microsoft-standard`

**Comment by FrederickEngelhardt** [comment]
Resolved by removing the `~/.yarnrc` file which contained a `lastUpdateCheck` string which prevented the install.

Ran this command
```sh
rm ~/.yarnrc
```

No longer have an issue installing or using yarn commands.

Also similar to #5592
