### ISSUE TITLE
npm install workd perfectly. yarn install fails.

### ISSUE THREAD

**Issue by wansiedler** [yarnpkg/yarn#8493]
### Bug description
npm install works perfectly. yarn install fails.

**Command**
```
rm -rf node_modules; rm package-lock.json yarn.lock; yarn install
```

**What is the current behavior?**
```
warning Error running install script for optional dependency: ".../node_modules/babel-plugin-add-module-exports/node_modules/fsevents, .../node_modules/watchpack-chokidar2/node_modules/fsevents, .../node_modules/webpack-dev-server/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: .../node_modules/webpack-dev-server/node_modules/fsevents
Output:
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-gyp ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn node-gyp',
```

**What is the expected behavior?**
To install everything correctly.

**Steps to Reproduce**
https://github.com/gatsbyjs/gatsby/tree/master/examples/client-only-paths

**Environment**
- Node Version: `v14.7.0`
- Yarn v1 Version: `1.21`
- OS and version: Macos 11

**Comment by rally25rs** [comment]
This looks like you probably don't have `node-gyp` installed under yarn but you do for npm.
You could try running `yarn global add node-gyp` then try your `yarn install` again.

**Comment by lacostenycoder** [comment]
I'm having a the same issue on Debian Linux but only when using NodeJS Version > 14.x (i.e. 16+)  I've successfully added `yarn global add node-gyp` but the error that gets raised seems to be a Python syntax error.  I've been wrestling this for several days. 

```
cat /etc/os-release                                                
NAME="Linux Mint"
VERSION="20.1 (Ulyssa)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.1"
VERSION_ID="20.1"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=ulyssa
UBUNTU_CODENAME=focal

node -v    
v16.14.2
npm node-gyp --version
8.5.0

yarn add node-sass    
yarn add v1.22.10
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning @rails/webpacker > webpack > watchpack > watchpack-chokidar2 > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning jest > jest-cli > jest-haste-map > sane > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning jest-enzyme > jest-environment-enzyme > jest-environment-jsdom > @jest/environment > @jest/transform > jest-haste-map > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @apollo/react-hooks@3.1.5" has unmet peer dependency "@types/react@^16.8.0".
warning " > @apollo/react-hooks@3.1.5" has incorrect peer dependency "graphql@^14.3.1".
warning "@apollo/react-hooks > @apollo/react-common@3.1.4" has unmet peer dependency "@types/react@^16.8.0".
warning "@apollo/react-hooks > @apollo/react-common@3.1.4" has unmet peer dependency "apollo-utilities@^1.3.2".
warning "@apollo/react-hooks > @apollo/react-common@3.1.4" has incorrect peer dependency "graphql@^14.3.1".
warning " > @apollo/react-testing@3.1.4" has unmet peer dependency "apollo-utilities@^1.3.2".
warning " > @apollo/react-testing@3.1.4" has incorrect peer dependency "graphql@^14.3.1".
warning "@rails/webpacker > postcss-cssnext@3.1.1" has unmet peer dependency "caniuse-lite@^1.0.30000697".
warning " > graphql-ruby-client@1.10.6" has unmet peer dependency "@apollo/client@^3.3.6".
warning " > graphql-ruby-client@1.10.6" has incorrect peer dependency "graphql@^14.3.1 || ^15.0.0".
warning " > react-apollo@3.1.5" has unmet peer dependency "@types/react@^16.8.0".
warning " > react-apollo@3.1.5" has incorrect peer dependency "graphql@^14.3.1".
warning "react-apollo > @apollo/react-components@3.1.5" has unmet peer dependency "@types/react@^16.8.0".
warning "react-apollo > @apollo/react-components@3.1.5" has unmet peer dependency "apollo-cache@^1.3.2".
warning "react-apollo > @apollo/react-components@3.1.5" has unmet peer dependency "apollo-utilities@^1.3.2".
warning "react-apollo > @apollo/react-components@3.1.5" has incorrect peer dependency "graphql@^14.3.1".
warning "react-apollo > @apollo/react-hoc@3.1.5" has unmet peer dependency "@types/react@^16.8.0".
warning "react-apollo > @apollo/react-hoc@3.1.5" has incorrect peer dependency "graphql@^14.3.1".
warning " > babel-jest@23.6.0" has unmet peer dependency "babel-core@^6.0.0 || ^7.0.0-0".
warning " > eslint-config-standard@12.0.0" has incorrect peer dependency "eslint@>=5.0.0".
warning " > eslint-plugin-node@9.2.0" has incorrect peer dependency "eslint@>=5.16.0".
warning " > eslint-plugin-prettier@3.4.1" has incorrect peer dependency "eslint@>=5.0.0".
warning " > eslint-plugin-standard@4.1.0" has incorrect peer dependency "eslint@>=5.0.0".
warning " > webpack-dev-server@2.11.2" has unmet peer dependency "webpack@^2.2.0 || ^3.0.0".
warning "webpack-dev-server > webpack-dev-middleware@1.12.2" has unmet peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0".
[4/4] Building fresh packages...
[-/7] ⠁ waiting...
[7/7] ⠁ node-sass
[-/7] ⠁ waiting...
[4/7] ⠁ node-sass
error /home/lance/dev/qc/code/web/node_modules/@rails/webpacker/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments: 
Directory: /home/lance/dev/qc/code/web/node_modules/@rails/webpacker/node_modules/node-sass
Output:
Building: /home/lance/.nvm/versions/node/v16.14.2/bin/node /home/lance/dev/qc/code/web/node_modules/@rails/webpacker/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/home/lance/.nvm/versions/node/v16.14.2/bin/node',
gyp verb cli   '/home/lance/dev/qc/code/web/node_modules/@rails/webpacker/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@16.14.2 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "/home/linuxbrew/.linuxbrew/bin/python3" in the PATH
gyp verb `which` succeeded /home/linuxbrew/.linuxbrew/bin/python3 /home/linuxbrew/.linuxbrew/bin/python3
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /home/linuxbrew/.linuxbrew/bin/python3 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:399:12)
gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
gyp ERR! System Linux 5.4.0-100-generic
gyp ERR! command "/home/lance/.nvm/versions/node/v16.14.2/bin/node" "/home/lance/dev/qc/code/web/node_modules/@rails/webpacker/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/lance/dev/qc/code/web/node_modules/@rails/webpacker/node_modules/node-sass
gyp ERR! node -v v16.14.2

yarn info v1.22.10
{
  name: 'node-gyp',
  description: 'Node.js native addon build tool',
  'dist-tags': {
    latest: '9.0.0'
  },
  versions: [
    '0.0.1',
    '0.0.2',
    '0.0.3',
    '0.0.4',
    '0.0.5',
    '0.0.6',
    '0.1.0',
    '0.1.1',
    '0.1.2',
    '0.1.3',
    '0.1.4',
    '0.2.0',
    '0.2.1',
    '0.2.2',
    '0.3.0',
    '0.3.1',
    '0.3.2',
    '0.3.4',
    '0.3.5',
    '0.3.6',
    '0.3.7',
    '0.3.8',
    '0.3.9',
    '0.3.10',
    '0.3.11',
    '0.4.0',
    '0.4.1',
    '0.4.2',
    '0.4.3',
    '0.4.4',
    '0.4.5',
    '0.5.0',
    '0.5.1',
    '0.5.2',
    '0.5.3',
    '0.5.4',
    '0.5.5',
    '0.5.6',
    '0.5.7',
    '0.5.8',
    '0.6.0',
    '0.6.1',
    '0.6.2',
    '0.6.3',
    '0.6.4',
    '0.6.5',
    '0.6.6',
    '0.6.7',
    '0.6.8',
    '0.6.9',
    '0.6.10',
    '0.6.11',
    '0.7.0',
    '0.7.1',
    '0.7.2',
    '0.7.3',
    '0.8.0',
    '0.8.1',
    '0.8.2',
    '0.8.3',
    '0.8.4',
    '0.8.5',
    '0.9.0',
    '0.9.1',
    '0.9.2',
    '0.9.3',
    '0.9.4',
    '0.9.5',
    '0.9.6',
    '0.10.0',
    '0.10.1',
    '0.10.2',
    '0.10.3',
    '0.10.4',
    '0.10.5',
    '0.10.6',
    '0.10.7',
    '0.10.8',
    '0.10.9',
    '0.10.10',
    '0.11.0',
    '0.12.0',
    '0.12.1',
    '0.12.2',
    '0.13.0',
    '0.13.1',
    '1.0.0',
    '1.0.1',
    '1.0.2',
    '1.0.3',
    '2.0.0',
    '2.0.1',
    '2.0.2',
    '3.0.0',
    '3.0.1',
    '3.0.2',
    '3.0.3',
    '3.1.0',
    '3.2.0',
    '3.2.1',
    '3.3.0',
    '3.3.1',
    '3.4.0',
    '3.5.0',
    '3.6.0',
    '3.6.1',
    '3.6.2',
    '3.6.3',
    '3.7.0',
    '3.8.0',
    '4.0.0',
    '5.0.0',
    '5.0.1',
    '5.0.2',
    '5.0.3',
    '5.0.4',
    '5.0.5',
    '5.0.6',
    '5.0.7',
    '5.1.0',
    '5.1.1',
    '6.0.0',
    '6.0.1',
    '6.1.0',
    '7.0.0',
    '7.1.0',
    '7.1.1',
    '7.1.2',
    '8.0.0',
    '8.1.0',
    '8.2.0',
    '8.3.0',
    '8.4.0',
    '8.4.1',
    '9.0.0'
  ],
  maintainers: [
    {
      name: 'bnoordhuis',
      email: 'info@bnoordhuis.nl'
    },
    {
      name: 'fishrock123',
      email: 'fishrock123@rocketmail.com'
    },
    {
      name: 'rvagg',
      email: 'r@va.gg'
    },
    {
      name: 'nodejs-foundation',
      email: 'build@iojs.org'
    }
  ],
  time: {
    modified: '2022-03-01T03:02:57.083Z',
    created: '2012-02-05T19:47:50.427Z',
    '0.0.1-alpha1': '2012-02-05T19:47:52.027Z',
    '0.0.1': '2012-02-06T01:15:20.584Z',
    '0.0.2': '2012-02-06T22:56:04.570Z',
    '0.0.3': '2012-02-10T01:35:24.845Z',
    '0.0.4': '2012-02-11T02:16:21.167Z',
    '0.0.5': '2012-02-11T08:22:47.598Z',
    '0.0.6': '2012-02-11T08:27:57.556Z',
    '0.1.0': '2012-02-11T21:07:59.244Z',
    '0.1.1': '2012-02-13T01:46:02.038Z',
    '0.1.2': '2012-02-13T16:41:54.897Z',
    '0.1.3': '2012-02-18T02:33:18.188Z',
    '0.1.4': '2012-02-26T09:12:21.700Z',
    '0.2.0': '2012-02-28T02:26:26.016Z',
    '0.2.1': '2012-03-02T22:54:30.429Z',
    '0.2.2': '2012-03-05T22:37:36.665Z',
    '0.3.0': '2012-03-07T20:26:05.725Z',
    '0.3.1': '2012-03-08T22:20:44.319Z',
    '0.3.2': '2012-03-08T23:11:35.287Z',
    '0.3.4': '2012-03-11T21:26:44.383Z',
    '0.3.5': '2012-03-14T23:27:08.202Z',
    '0.3.6': '2012-03-20T02:37:09.353Z',
    '0.3.7': '2012-03-20T21:49:58.617Z',
    '0.3.8': '2012-03-27T22:26:34.160Z',
    '0.3.9': '2012-03-29T01:40:05.063Z',
    '0.3.10': '2012-03-31T04:55:00.445Z',
    '0.3.11': '2012-04-06T01:01:07.185Z',
    '0.4.0': '2012-04-09T00:10:02.257Z',
    '0.4.1': '2012-04-10T18:32:19.213Z',
    '0.4.2': '2012-05-09T20:07:52.094Z',
    '0.4.3': '2012-05-15T00:09:09.512Z',
    '0.4.4': '2012-05-27T21:21:24.484Z',
    '0.4.5': '2012-06-04T22:53:04.202Z',
    '0.5.0': '2012-06-13T21:20:56.832Z',
    '0.5.1': '2012-06-15T18:19:23.407Z',
    '0.5.2': '2012-06-15T23:04:48.082Z',
    '0.5.3': '2012-06-20T21:50:52.792Z',
    '0.5.4': '2012-06-21T00:23:28.636Z',
    '0.5.5': '2012-06-27T18:40:55.482Z',
    '0.5.6': '2012-06-27T19:17:43.256Z',
    '0.5.7': '2012-07-04T23:49:16.428Z',
    '0.5.8': '2012-07-10T20:59:23.740Z',
    '0.6.0': '2012-07-16T23:41:16.741Z',
    '0.6.1': '2012-07-24T17:44:26.113Z',
    '0.6.2': '2012-07-26T00:06:16.011Z',
    '0.6.3': '2012-07-31T20:48:51.674Z',
    '0.6.4': '2012-08-12T22:33:47.284Z',
    '0.6.5': '2012-08-13T17:21:19.982Z',
    '0.6.6': '2012-08-16T22:42:22.413Z',
    '0.6.7': '2012-08-17T15:42:57.739Z',
    '0.6.8': '2012-08-22T01:56:00.883Z',
    '0.6.9': '2012-08-30T21:09:56.066Z',
    '0.6.10': '2012-09-07T18:08:36.515Z',
    '0.6.11': '2012-09-25T01:08:20.095Z',
    '0.7.0': '2012-10-02T18:33:36.913Z',
    '0.7.1': '2012-10-07T20:36:55.179Z',
    '0.7.2': '2012-10-30T00:08:33.409Z',
    '0.7.3': '2012-11-04T01:26:51.139Z',
    '0.8.0': '2012-11-14T23:12:55.591Z',
    '0.8.1': '2012-11-27T16:15:14.358Z',
    '0.8.2': '2012-12-21T20:18:44.247Z',
    '0.8.3': '2013-01-20T20:14:55.140Z',
    '0.8.4': '2013-02-04T23:28:17.661Z',
    '0.8.5': '2013-02-28T23:18:46.831Z',
    '0.9.0': '2013-03-08T23:43:03.929Z',
    '0.9.1': '2013-03-09T01:35:37.440Z',
    '0.9.2': '2013-03-21T19:28:22.485Z',
    '0.9.3': '2013-03-28T01:46:12.732Z',
    '0.9.4': '2013-03-29T17:19:17.941Z',
    '0.9.5': '2013-03-29T21:22:42.126Z',
    '0.9.6': '2013-05-14T19:11:44.118Z',
    '0.9.7': '2013-06-05T22:54:09.331Z',
    '0.10.0': '2013-06-05T23:02:50.766Z',
    '0.10.1': '2013-06-20T20:48:41.877Z',
    '0.10.2': '2013-06-24T21:26:41.049Z',
    '0.10.3': '2013-06-28T16:41:43.669Z',
    '0.10.4': '2013-06-30T21:32:32.108Z',
    '0.10.5': '2013-07-05T04:55:08.580Z',
    '0.10.6': '2013-07-11T07:18:27.053Z',
    '0.10.7': '2013-08-01T16:24:30.605Z',
    '0.10.8': '2013-08-01T16:40:48.659Z',
    '0.10.9': '2013-08-02T00:57:53.071Z',
    '0.10.10': '2013-09-06T21:26:14.415Z',
    '0.11.0': '2013-10-28T19:16:15.657Z',
    '0.12.0': '2013-11-11T23:48:19.448Z',
    '0.12.1': '2013-11-12T02:48:46.067Z',
    '0.12.2': '2013-12-18T22:29:12.930Z',
    '0.13.0': '2014-03-04T22:43:58.776Z',
    '0.13.1': '2014-05-19T20:54:10.615Z',
    '1.0.0': '2014-07-31T22:36:57.108Z',
    '1.0.1': '2014-07-31T22:37:54.785Z',
    '1.0.2': '2014-09-11T07:09:32.146Z',
    '1.0.3': '2015-03-06T17:13:59.546Z',
    '2.0.0': '2015-05-24T22:22:20.884Z',
    '2.0.1': '2015-05-28T18:10:57.968Z',
    '2.0.2': '2015-07-14T19:30:53.975Z',
    '3.0.0': '2015-09-08T00:04:25.769Z',
    '3.0.1': '2015-09-08T07:55:08.843Z',
    '3.0.2': '2015-09-12T04:19:22.160Z',
    '3.0.3': '2015-09-14T00:56:00.889Z',
    '3.1.0': '2015-11-14T04:22:53.298Z',
    '3.2.0': '2015-11-24T14:14:36.243Z',
    '3.2.1': '2015-12-03T01:38:45.001Z',
    '3.3.0': '2016-02-16T05:01:25.065Z',
    '3.3.1': '2016-03-04T18:12:27.657Z',
    '3.4.0': '2016-06-28T02:03:02.347Z',
    '3.5.0': '2017-01-10T01:37:05.675Z',
    '3.6.0': '2017-03-15T20:26:09.244Z',
    '3.6.1': '2017-04-30T22:00:25.050Z',
    '3.6.2': '2017-06-01T22:15:28.478Z',
    '3.6.3': '2018-06-08T07:37:27.248Z',
    '3.7.0': '2018-06-08T15:32:22.008Z',
    '3.8.0': '2018-08-09T00:53:58.962Z',
    '4.0.0': '2019-04-24T00:34:15.853Z',
    '5.0.0': '2019-06-13T08:42:22.607Z',
    '5.0.1': '2019-06-21T02:24:08.009Z',
    '5.0.2': '2019-07-03T05:12:51.572Z',
    '5.0.3': '2019-07-17T04:33:13.127Z',
    '5.0.4': '2019-09-27T02:26:08.981Z',
    '5.0.5': '2019-10-04T13:28:42.318Z',
    '6.0.0': '2019-10-04T13:43:14.074Z',
    '6.0.1': '2019-11-01T10:17:02.651Z',
    '5.0.6': '2019-12-16T00:18:06.339Z',
    '5.0.7': '2019-12-16T01:00:38.394Z',
    '6.1.0': '2020-01-08T01:12:48.623Z',
    '5.1.0': '2020-02-05T02:17:39.006Z',
    '5.1.1': '2020-05-25T05:47:31.955Z',
    '7.0.0': '2020-06-03T03:26:26.318Z',
    '7.1.0': '2020-08-12T03:50:33.423Z',
    '7.1.1': '2020-10-15T06:54:29.286Z',
    '7.1.2': '2020-10-17T02:03:12.809Z',
    '8.0.0': '2021-04-03T00:32:21.988Z',
    '8.1.0': '2021-05-28T02:03:50.580Z',
    '8.2.0': '2021-08-23T06:53:15.124Z',
    '8.3.0': '2021-10-19T06:35:01.969Z',
    '8.4.0': '2021-11-05T09:36:09.148Z',
    '8.4.1': '2021-11-22T08:34:04.197Z',
    '9.0.0': '2022-03-01T03:02:15.545Z'
  },
  author: {
    name: 'Nathan Rajlich',
    email: 'nathan@tootallnate.net',
    url: 'http://tootallnate.net'
  },
  repository: {
    type: 'git',
    url: 'git://github.com/nodejs/node-gyp.git'
  },
  users: {
    fgribreau: true,
    m42am: true,
    hij1nx: true,
    awaterma: true,
    pid: true,
    tmpvar: true,
    rtc11: true,
    stonecypher: true,
    io2work: true,
    j3kz: true,
    erincinci: true,
    sunnylost: true,
    kachar: true,
    itonyyo: true,
    dofy: true,
    dkannan: true,
    nukisman: true,
    a_cabello: true,
    nex: true,
    godion: true,
    pingprart: true,
    qbylucky: true,
    sopepos: true,
    daniilbabanin: true,
    panlw: true,
    lewisbrown: true,
    kungkk: true,
    linuxwizard: true,
    jeben: true,
    tommyzzm: true,
    moonavw: true,
    matiasmarani: true,
    'thomas.miele': true,
    neefrankie: true,
    ovrmrw: true,
    lukin0110: true,
    abdihaikal: true,
    fistynuts: true,
    vchouhan: true,
    coalesce: true,
    hyteer: true,
    mzheng: true,
    morifen: true,
    koulmomo: true,
    danielbankhead: true,
    brainpoint: true,
    wangnan0610: true,
    doomblade: true,
    rubiadias: true,
    webbot: true,
    nickeltobias: true,
    amartelr: true,
    phoenixsoul: true,
    mobeicaoyuan: true,
    knoja4: true,
    rwaness: true,
    stackzhang: true,
    zzl81cn: true,
    tsuyoshi_cho: true,
    chayn1k: true,
    'ognjen.jevremovic': true,
    sherylynn: true,
    'joaquin.briceno': true,
    luizpaulo: true,
    shentengtu: true,
    sopov: true,
    rochejul: true,
    zivlit: true,
    d0ughtyj: true,
    morogasper: true,
    princetoad: true,
    terrychan: true,
    s8jmc: true,
    ysk8: true,
    hccdj131: true,
    mkuehn: true,
    gyaipy: true,
    daniellink: true,
    manuchalela: true,
    rocket0191: true,
    dwqs: true,
    asfrom30: true,
    kkho595: true,
    yangzw: true,
    tdmalone: true,
    nicknaso: true,
    zwwggg: true,
    dengyongchao: true,
    stev0thegreat: true,
    shuoshubao: true,
    he313572052: true,
    hilmidev: true,
    pantyuhind: true,
    'leelee.echo': true,
    parkerproject: true,
    lionel86: true,
    centiball: true
  },
  homepage: 'https://github.com/nodejs/node-gyp#readme',
  keywords: [
    'native',
    'addon',
    'module',
    'c',
    'c++',
    'bindings',
    'gyp'
  ],
  bugs: {
    url: 'https://github.com/nodejs/node-gyp/issues'
  },
  readmeFilename: 'README.md',
  license: 'MIT',
  version: '9.0.0',
  installVersion: 9,
  preferGlobal: true,
  bin: {
    'node-gyp': 'bin/node-gyp.js'
  },
  main: './lib/node-gyp.js',
  dependencies: {
    'env-paths': '^2.2.0',
    glob: '^7.1.4',
    'graceful-fs': '^4.2.6',
    'make-fetch-happen': '^10.0.3',
    nopt: '^5.0.0',
    npmlog: '^6.0.0',
    rimraf: '^3.0.2',
    semver: '^7.3.5',
    tar: '^6.1.2',
    which: '^2.0.2'
  },
  engines: {
    node: '^12.22 || ^14.13 || >=16'
  },
  devDependencies: {
    bindings: '^1.5.0',
    nan: '^2.14.2',
    'require-inject': '^1.4.4',
    standard: '^14.3.4',
    tap: '^12.7.0'
  },
  scripts: {
    lint: 'standard */*.js test/**/*.js',
    test: 'npm run lint && tap --timeout=120 test/test-*'
  },
  gitHead: 'b1ad49229272492cf9e030083d3cb4ea81afabb1',
  dist: {
    integrity: 'sha512-Ma6p4s+XCTPxCuAMrOA/IJRmVy16R8Sdhtwl4PrCr7IBlj4cPawF0vg/l7nOT1jPbuNS7lIRJpBSvVsXwEZuzw==',
    shasum: 'e1da2067427f3eb5bb56820cb62bc6b1e4bd2089',
    tarball: 'https://registry.npmjs.org/node-gyp/-/node-gyp-9.0.0.tgz',
    fileCount: 139,
    unpackedSize: 1984092,
    'npm-signature': '-----BEGIN PGP SIGNATURE-----\r\n' +
      'Version: OpenPGP.js v4.10.10\r\n' +
      'Comment: https://openpgpjs.org\r\n' +
      '\r\n' +
      'wsFzBAEBCAAGBQJiHYy3ACEJED1NWxICdlZqFiEECWMYAoorWMhJKdjhPU1b\r\n' +
      'EgJ2VmqoERAAmxwnRmeVhesRBcO0FWS03esqKGV1tmhEGvTOyx4/FO7omrX8\r\n' +
      'K9W61stXaxG0c8BMfJ8DjyRD2VrF4L/ExK93NVc4pup7Bv7VW8WA4mKxwXfy\r\n' +
      '4l4xZo73XCus6T1fGw34YEBNSVzQtbmqG0QcOKOF1Jofg2SSEAd+bSPqaDCj\r\n' +
      's6y2oUcShS71BrWJ57W0/OQyldHSglN05OFbIuNXu3MpUoGYxvoQvyuH/k1N\r\n' +
      '42PVuM176NoPHxeuDMw+bRVZqmjDFpkz2xLXfjesH3eDPLu3ohNum/gzUxv6\r\n' +
      'PGWYYdt/z5gwqzeHRCSGrIifEDQqYsoUQKn3CvPISmM14kmK+m64R5Jy2sEs\r\n' +
      'cVPCwCfX34bfrlbOLQcw7LsSIiTntQ05vczAPhPc5lyYq4S6shFeFMuxgsFh\r\n' +
      'FaPDml+P7Yjtx7HDWxp7aVq5ZRdQWXggDmzibp1iANA27qIghRuow0+bQ1P/\r\n' +
      'Jq7FKSQZZCaiLBHNqU7ixCSE6F/PkxC7FZe0aB64mWfnQ8zZYM006ez9ZtWH\r\n' +
      'NIOY3qMsdlfmeV2HtkKOaZGqW7Qj0gxDxDCLUqgk7HKq/LUL1XmjUEIvXxG0\r\n' +
      'iUecqjO8YD9ofqeIut1hBDG9S0ynLdzlirsn4u2Mg3ijBJZlNgWSXvplX/az\r\n' +
      'i5tapPS0rkpCAkNrcshPZWAcKyHx8COPuP4=\r\n' +
      '=/cCg\r\n' +
      '-----END PGP SIGNATURE-----\r\n'
  },
  directories: {}
}
```
