### ISSUE TITLE
[Bug] codeload.github.com/highslide-software/highstock-release/tar.gz/59fcc69b1ab74e21bdca01bf280cd54d0771030e: Request failed "404 Not Found"

### ISSUE THREAD

**Issue by javasgl** [yarnpkg/yarn#8554]
- [ ] I'd be willing to implement a fix

**Describe the bug**

execute the command `yarn install`
then will got this finally:
```
Trace:
  Error: https://codeload.github.com/highslide-software/highstock-release/tar.gz/59fcc69b1ab74e21bdca01bf280cd54d0771030e: Request failed "404 Not Found"
      at ResponseError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:696:66)
      at new ResponseError (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:802:124)
      at Request.<anonymous> (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:67045:16)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:188:7)
      at Request.module.exports.Request.onRequestResponse (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:141604:10)
      at emitOne (events.js:96:13)
      at ClientRequest.emit (events.js:188:7)
      at HTTPParser.parserOnIncomingClient (_http_client.js:474:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
```

**To Reproduce**
see the whole package.json in the file: [yarn-error.log](https://github.com/yarnpkg/berry/files/5829890/yarn-error.log)

**Environment if relevant (please complete the following information):**

 - OS: darwin x64
 - Node version  6.12.0
 - Yarn version 1.22.0

**Additional context**

[yarn-error.log](https://github.com/yarnpkg/berry/files/5829890/yarn-error.log)

**Comment by javasgl** [comment]
> Follow the issue template

done

**Comment by merceyz** [comment]
Need to update the github repo you're pointing to

```diff
-"@bower_components/highstock-release": "highslide-software/highstock-release#~4.2.3"
+"@bower_components/highstock-release": "highcharts/highstock-release#~4.2.3"
```

**Comment by javasgl** [comment]
> Need to update the github repo you're pointing to
> 
> ```diff
> -"@bower_components/highstock-release": "highslide-software/highstock-release#~4.2.3"
> +"@bower_components/highstock-release": "highcharts/highstock-release#~4.2.3"
> ```

Thanks , this fixed it
