### ISSUE TITLE
Couldn't find package "redux-soga@^1.0.0" required by "xx" on the "npm" registry.

### ISSUE THREAD

**Issue by chenrui333** [yarnpkg/yarn#8559]
error output

```
Yarn version: 
  1.22.10

Node version: 
  12.20.1

Platform: 
  darwin x64

Trace: 
  Error: https://registry.yarnpkg.com/redux-soga: Not found
      at Request.params.callback [as _callback] (/Users/rchen/.nvm/versions/node/v12.14.1/lib/node_modules/yarn/lib/cli.js:66988:18)
      at Request.self.callback (/Users/rchen/.nvm/versions/node/v12.14.1/lib/node_modules/yarn/lib/cli.js:140662:22)
      at Request.emit (events.js:314:20)
      at Request.<anonymous> (/Users/rchen/.nvm/versions/node/v12.14.1/lib/node_modules/yarn/lib/cli.js:141634:10)
      at Request.emit (events.js:314:20)
      at IncomingMessage.<anonymous> (/Users/rchen/.nvm/versions/node/v12.14.1/lib/node_modules/yarn/lib/cli.js:141556:12)
      at Object.onceWrapper (events.js:420:28)
      at IncomingMessage.emit (events.js:326:22)
      at endReadableNT (_stream_readable.js:1241:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by chenrui333** [comment]
some typo.  😂
