### ISSUE TITLE
I have a problem when I try to install react-app

### ISSUE THREAD

**Issue by Tanjeeb** [yarnpkg/yarn#8594]
Yarn version: 
  1.21.1

Node version: 
  12.6.0

Platform: 
  linux x64

Trace: 
  Error: https://registry.npmjs.org/react: error:0909006C:PEM routines:get_name:no start line
      at Object.createSecureContext (_tls_common.js:152:17)
      at Object.connect (_tls_wrap.js:1403:48)
      at Agent.createConnection (https.js:125:22)
      at Agent.createSocket (_http_agent.js:234:26)
      at Agent.addRequest (_http_agent.js:193:10)
      at new ClientRequest (_http_client.js:276:16)
      at Object.request (https.js:309:10)
      at Request.module.exports.Request.start (/usr/share/yarn/lib/cli.js:141227:32)
      at Request.module.exports.Request.end (/usr/share/yarn/lib/cli.js:141986:10)
      at end (/usr/share/yarn/lib/cli.js:141040:14)

**Comment by NANI1734** [comment]
i have same problem
