### ISSUE TITLE
Add yarn package receive 405

### ISSUE THREAD

**Issue by Julian-dev28** [yarnpkg/yarn#8605]
Errors with adding yarn package

Upgraded to yarn 2 and still received the error posted below

Arguments: 
  /usr/local/bin/node /Users/admin/.npm/_npx/29074/bin/yarn add csb-uikit

PATH: 
  /Users/admin/.npm/_npx/29074/bin:/Users/admin/Documents/UpWork/Coins-Barter-Token/csb-dex-test/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/opt/ImageMagick/bin

Yarn version: 
  1.22.10

Node version: 
  14.16.0

Platform: 
  darwin x64

Trace: 
  Error: https://registry.yarnpkg.com/@csbkit: Request "https://registry.yarnpkg.com/@csbkit" returned a 405
      at Request.params.callback [as _callback] (/Users/admin/.npm/_npx/29074/lib/node_modules/yarn/lib/cli.js:66997:18)
      at Request.self.callback (/Users/admin/.npm/_npx/29074/lib/node_modules/yarn/lib/cli.js:140662:22)
      at Request.emit (events.js:315:20)
      at Request.<anonymous> (/Users/admin/.npm/_npx/29074/lib/node_modules/yarn/lib/cli.js:141634:10)
      at Request.emit (events.js:315:20)
      at IncomingMessage.<anonymous> (/Users/admin/.npm/_npx/29074/lib/node_modules/yarn/lib/cli.js:141556:12)
      at Object.onceWrapper (events.js:421:28)
      at IncomingMessage.emit (events.js:327:22)
      at endReadableNT (internal/streams/readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by merceyz** [comment]
`@csbkit` isn't a valid package
