### ISSUE TITLE
unexpected error occurred

### ISSUE THREAD

**Issue by YuvarajPandiyan** [yarnpkg/yarn#8609]
yarn upgrade v1.22.10
error An unexpected error occurred: "true/@fortawesome%2ffontawesome-svg-core: Invalid URI \"true/@fortawesome%2ffontawesome-svg-core\"".
info If you think this is a bug, please open a bug report with the information provided in "C:\\dev\\Web-FrontEnd\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.

Arguments: 
  C:\Program Files\nodejs\node.exe C:\Users\yuvaraj\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js upgrade

PATH: 
  C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\yuvaraj\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Java\jdk-15.0.2\bin;C:\Program Files\nodejs;C:\Program Files\PostgreSQL\13\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files (x86)\QuickTime\QTSystem;C:\Users\yuvaraj\AppData\Local\Microsoft\WindowsApps;C:\Users\yuvaraj\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\yuvaraj\AppData\Roaming\npm;C:\Users\yuvaraj\AppData\Local\Programs\Python\Python39\Scripts;C:\Users\yuvaraj\AppData\Local\Programs\Python\Python39;C:\adb;C:\Users\yuvaraj\AppData\Local\Microsoft\WindowsApps;C:\Users\yuvaraj\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\yuvaraj\AppData\Roaming\npm;C:\Program Files\PostgreSQL\13\bin;C:\Users\yuvaraj\AppData\Local\Programs\Python\Python39\Scripts;C:\Users\yuvaraj\AppData\Local\Programs\Python\Python39;C:\Program Files\heroku\bin

Yarn version: 
  1.22.10

Node version: 
  14.15.4

Platform: 
  win32 x64

Trace: 
  Error: true/@fortawesome%2ffontawesome-svg-core: Invalid URI "true/@fortawesome%2ffontawesome-svg-core"
      at Request.module.exports.Request.init (C:\Users\yuvaraj\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:140750:31)
      at new Request (C:\Users\yuvaraj\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:140604:8)
      at request (C:\Users\yuvaraj\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:136804:10)
      at RequestManager.execute (C:\Users\yuvaraj\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:67040:15)
      at RequestManager.shiftQueue (C:\Users\yuvaraj\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:67078:10)
      at C:\Users\yuvaraj\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:66747:13
      at new Promise (<anonymous>)
      at new F (C:\Users\yuvaraj\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:5301:28)
      at RequestManager.request (C:\Users\yuvaraj\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:66745:19)
      at NpmRegistry.<anonymous> (C:\Users\yuvaraj\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:31704:42)

**Comment by merceyz** [comment]
I'm guessing something in your config is wrong, but provide a repro or something, the error alone doesn't help us reproduce this.
