### ISSUE TITLE
 yarn add @fontawesome/fontawesome-pro not possible

### ISSUE THREAD

**Issue by dr4c4rys** [yarnpkg/yarn#8612]
Hi everybody. I have trouble adding a specific package. 
@fontawesome/fontawesome-pro

I think this is a bug, becuase
<img width="897" alt="Bildschirmfoto 2021-04-12 um 11 07 24" src="https://user-images.githubusercontent.com/23642715/114372068-702cc200-9b81-11eb-8394-bc1200493c84.png">

What is the problem here?

Thats why I add now the error report

The Bug report is inside yarn-error.log shows this:

Arguments: 
  /usr/bin/node /usr/share/yarn/bin/yarn.js upgrade

PATH: 
  /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Yarn version: 
  1.22.5

Node version: 
  10.24.1

Platform: 
  linux x64

Trace: 
  Error: https://registry.yarnpkg.com/@fortawesome%2ffontawesome-pro: Not found
      at Request.params.callback [as _callback] (/usr/share/yarn/lib/cli.js:66988:18)
      at Request.self.callback (/usr/share/yarn/lib/cli.js:140749:22)
      at Request.emit (events.js:198:13)
      at Request.<anonymous> (/usr/share/yarn/lib/cli.js:141721:10)
      at Request.emit (events.js:198:13)
      at IncomingMessage.<anonymous> (/usr/share/yarn/lib/cli.js:141643:12)
      at Object.onceWrapper (events.js:286:20)
      at IncomingMessage.emit (events.js:203:15)
      at endReadableNT (_stream_readable.js:1145:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by merceyz** [comment]
You need to setup the config first https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers#installing-pro
