### ISSUE TITLE
I/O Error while creating project with yarn

### ISSUE THREAD

**Issue by NorinMp143** [yarnpkg/yarn#8620]
ubuntu@dell:~/Documents/ReactNative$ npx react-native init ebuddy
This will walk you through creating a new React Native project in /home/ubuntu/Documents/ReactNative/ebuddy
Using yarn v1.22.5
Installing react-native...
yarn add v1.22.5
info No lockfile found.
[1/4] Resolving packages...
warning react-native > @react-native-community/cli > metro > metro-minify-uglify > uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
warning react-native > react-native-codegen > jscodeshift > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning react-native > react-native-codegen > jscodeshift > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "react-native > metro-react-native-babel-transformer@0.64.0" has unmet peer dependency "@babel/core@*".
warning "react-native > use-subscription@1.5.1" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "react-native > react-native-codegen > jscodeshift@0.11.0" has unmet peer dependency "@babel/preset-env@^7.1.6".
warning " > react-native@0.64.0" has unmet peer dependency "react@17.0.1".
error An unexpected error occurred: "EIO: i/o error, copyfile '/home/ubuntu/.cache/yarn/v6/npm-lodash-4.17.21-679591c564c3bffaae8454cf0b3df370c3d6911c-integrity/node_modules/lodash/isObjectLike.js' -> '/home/ubuntu/Documents/ReactNative/ebuddy/node_modules/lodash/isObjectLike.js'".
info If you think this is a bug, please open a bug report with the information provided in "/home/ubuntu/Documents/ReactNative/ebuddy/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Command failed: yarn add react-native --exact
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at run (/home/ubuntu/.config/yarn/global/node_modules/react-native-cli/index.js:294:5)
    at createProject (/home/ubuntu/.config/yarn/global/node_modules/react-native-cli/index.js:249:3)
    at init (/home/ubuntu/.config/yarn/global/node_modules/react-native-cli/index.js:200:5)
    at Object.<anonymous> (/home/ubuntu/.config/yarn/global/node_modules/react-native-cli/index.js:153:7)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 20248,
  stdout: null,
  stderr: null
}
Command `yarn add react-native --exact` failed

I use ...
nvm 0.37.2
node v14.16.1
npm 6.14.12
yarn 1.22.5
I have downloaded yarn using npm i -g yarn

**Comment by NorinMp143** [comment]
Just delete nvm, node, npm, yarn completely 
and run below command
```
curl -o- https://gist.githubusercontent.com/ankurk91/8f107ef490f40f74a1cf/raw/install-node-js.sh | bash
```
running all good.
