### ISSUE TITLE
Fails to install https://www.npmjs.com/package/@builder.io/qwik

### ISSUE THREAD

**Issue by mhevery** [yarnpkg/yarn#8642]
When trying to install https://www.npmjs.com/package/@builder.io/qwik I get this error:

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@builder.io/qwik/-/core-0.0.6.tgz: Request failed \"404 Not Found\"".
```

It seems like `yarn` did not pick up the new package? 

```
Arguments: 
  /Users/misko/.nvm/versions/node/v10.18.1/bin/node /Users/misko/.nvm/versions/node/v15.8.0/bin/yarn install

PATH: 
  /Users/misko/.nvm/versions/node/v10.18.1/bin:/Users/misko/.nvm/versions/node/v12.21.0/bin:/Users/misko/.nvm/versions/node/v12.21.0/bin:/Users/misko/.nvm/versions/node/v12.21.0/bin:/Users/misko/.nvm/versions/node/v15.8.0/bin:/Users/misko/.deno/bin:/Users/misko/.nvm/versions/node/v15.8.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/misko/.deno/bin:/Users/misko/.nvm/versions/node/v15.8.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/misko/bin:/Users/misko/bin

Yarn version: 
  1.22.10

Node version: 
  10.18.1

Platform: 
  darwin x64

Trace: 
  Error: https://registry.yarnpkg.com/@builder.io/qwik/-/core-0.0.6.tgz: Request failed "404 Not Found"
      at ResponseError.ExtendableBuiltin (/Users/misko/.nvm/versions/node/v15.8.0/lib/node_modules/yarn/lib/cli.js:696:66)
      at new ResponseError (/Users/misko/.nvm/versions/node/v15.8.0/lib/node_modules/yarn/lib/cli.js:802:124)
      at Request.<anonymous> (/Users/misko/.nvm/versions/node/v15.8.0/lib/node_modules/yarn/lib/cli.js:67058:16)
      at Request.emit (events.js:198:13)
      at Request.module.exports.Request.onRequestResponse (/Users/misko/.nvm/versions/node/v15.8.0/lib/node_modules/yarn/lib/cli.js:141539:10)
      at ClientRequest.emit (events.js:203:15)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
      at TLSSocket.socketOnData (_http_client.js:442:20)
      at TLSSocket.emit (events.js:198:13)
```

**Comment by RDIL** [comment]
Yarn's registry is now just a mirror of the actual npm registry.  If this is still an issue now, please reply here and I'll reopen the issue.
