### ISSUE TITLE
Fetching packages: segmentation error

### ISSUE THREAD

**Issue by gadefox** [yarnpkg/yarn#8687]
It seems I'm not the only one, who's getting the error (see above) while fetching packaged.. I definitely need more info, but `--verbose` doesn't help. Where can I find logs and / or where should I look in JS so I know what command is executed??

uname  -a: Linux debian 5.10.0-8-686-pae #1 SMP Debian 5.10.46-4 (2021-08-03) i686 GNU/Linux
node: 14.17.6 || 15.06.00
yarn: 1.22.11
shell: zsh 5.8

**Comment by gadefox** [comment]
I'm digging in the yarn code and here's the first problem: **spagetti code** (source file has ONLY 5,3 MB)..

**Comment by gadefox** [comment]
I'm testing this issue with the command `yarn add --verbose progress`. The last known function before the crash `zsh: segmentation fault  yarn add --verbose progress` is `RequestManager::request`, which is called from `TarballFetcher::fetchFromExternal`. Object `promise` is created and it's not null and then crash. Which function/class  is called next? Any idea??

**Comment by gadefox** [comment]
I'm debugging yarn script and I'm getting an error bellow. Any idea??
 `Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
    at handleWriteReq (internal/stream_base_commons.js:60:21)
    at writeGeneric (internal/stream_base_commons.js:145:15)
    at TLSSocket.Socket._writeGeneric (net.js:787:11)
    at TLSSocket.Socket._write (net.js:799:8)
    at doWrite (internal/streams/writable.js:377:12)
    at clearBuffer (internal/streams/writable.js:529:7)
    at TLSSocket.Writable.uncork (internal/streams/writable.js:317:7)
    at ClientRequest._flushOutput (_http_outgoing.js:935:10)
    at ClientRequest._flush (_http_outgoing.js:904:22)`
