### ISSUE TITLE
yarn policies set-version 1.13.0 throws error "Release not found: 1.13.0"

### ISSUE THREAD

**Issue by lesmoris-rp** [yarnpkg/yarn#8722]
When building, we use the line:

**yarn policies set-version 1.13.0**

But now it throws this error:

**Resolving 1.13.0 to a url...

error An unexpected error occurred: "Release not found: 1.13.0".

info If you think this is a bug, please open a bug report with the information provided in "/xxxxxx/yarn-error.log".

info Visit https://yarnpkg.com/en/docs/cli/policies for documentation about this command.**

**Comment by lesmoris-rp** [comment]
LogFile:

Arguments: 
/opt/hostedtoolcache/node/8.11.3/x64/bin/node /home/vsts/work/1/s/.yarn/releases/yarn-1.13.0.js policies set-version 1.13.0

PATH: 
/opt/hostedtoolcache/node/8.11.3/x64/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/vsts/.local/bin:/opt/pipx_bin:/usr/share/rust/.cargo/bin:/home/vsts/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/vsts/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

Yarn version: 
1.13.0

Node version: 
8.11.3

Platform: 
linux x64

Trace: 
Error: Release not found: 1.13.0
at /home/vsts/work/1/s/.yarn/releases/yarn-1.13.0.js:87290:17
at Generator.next (<anonymous>)
at step (/home/vsts/work/1/s/.yarn/releases/yarn-1.13.0.js:310:30)
at /home/vsts/work/1/s/.yarn/releases/yarn-1.13.0.js:321:13
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by jordanhauer4** [comment]
I'm having this same issue!

**Comment by jordanhauer4** [comment]
currently i'm on yarn 1.18.0 but I'm not able to set the version to 1.13.0 just like your problem above
