### ISSUE TITLE
build:ios: Invalid protocol: build:

### ISSUE THREAD

**Issue by markingram84** [yarnpkg/yarn#8741]
I am getting the above error when trying to run this command - `yarn add -D detox && yarn add -D @cucumber/cucumber && yarn add -D @babel/register` and am struggling how to resolve it

```
 Error: build:ios: Invalid protocol: build:
      at Request.module.exports.Request.init (/usr/local/Cellar/yarn/1.22.17/libexec/lib/cli.js:141152:31)
      at new Request (/usr/local/Cellar/yarn/1.22.17/libexec/lib/cli.js:140825:8)
      at request (/usr/local/Cellar/yarn/1.22.17/libexec/lib/cli.js:137731:10)
      at RequestManager.execute (/usr/local/Cellar/yarn/1.22.17/libexec/lib/cli.js:67081:15)
      at RequestManager.shiftQueue (/usr/local/Cellar/yarn/1.22.17/libexec/lib/cli.js:67119:10)
      at /usr/local/Cellar/yarn/1.22.17/libexec/lib/cli.js:66788:13
      at new Promise (<anonymous>)
      at new F (/usr/local/Cellar/yarn/1.22.17/libexec/lib/cli.js:5301:28)
      at RequestManager.request (/usr/local/Cellar/yarn/1.22.17/libexec/lib/cli.js:66786:19)
      at NpmRegistry.<anonymous> (/usr/local/Cellar/yarn/1.22.17/libexec/lib/cli.js:31747:42)

npm manifest: 
  {
    "name": "pqaa_detox",
    "version": "0.0.1",
    "private": true,
    "scripts": {
      "android:build": "react-native run-android",
      "ios:build": "react-native run-ios",
      "start": "react-native start"
    },
    "dependencies": {
      "@react-native-community/async-storage": "1.12.1",
      "@react-native-community/datetimepicker": "3.5.2",
      "@react-native-community/masked-view": "0.1.11",
      "@react-native-picker/picker": "1.16.7",
      "moment": "2.29.1",
      "react": "17.0.2",
      "react-dom": "17.0.2",
      "react-native": "0.63.4",
      "react-native-calendars": "1.1266.0",
      "react-native-date-picker": "4.0.0",
      "react-native-elements": "3.4.2",
      "react-native-gesture-handler": "1.10.3",
      "react-native-maps": "0.29.3",
      "react-native-reanimated": "1.13.0",
      "react-native-safe-area-context": "3.3.2",
      "react-native-screens": "3.4.0",
      "react-native-splash-screen": "3.2.0",
      "react-native-vector-icons": "8.1.0",
      "react-navigation": "4.4.4",
      "react-navigation-stack": "2.10.4",
      "react-navigation-tabs": "2.11.1",
      "build:ios": "react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios'"
    },
    "devDependencies": {
      "@babel/core": "7.15.5",
      "@babel/runtime": "7.15.4",
      "@react-native-community/eslint-config": "3.0.1",
      "babel-jest": "27.1.0",
      "eslint": "7.32.0",
      "jest": "27.1.0",
      "metro-react-native-babel-preset": "0.66.2",
      "react-test-renderer": "17.0.2"
    },
    "jest": {
      "preset": "react-native"
    }
  }

```

**Comment by merceyz** [comment]
Your `dependencies` field contains 
```
"build:ios": "react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios'"
```
which isn't a valid dependency
