### ISSUE TITLE
Yarn install/start error: Syntax Error: Expected ":" or blank space but "\n" found.

### ISSUE THREAD

**Issue by benebess** [yarnpkg/yarn#8763]
Using MacOSx 10.15.6
Node v14.16.0
ZSH 
using NPM v8.3.0
Yarn v3.1.1

Error below, I get the same error when attempting to run yarn start or yarn install. 
Installed with NPM package manager to: 
/Users/bonepile/.nvm/versions/node/v14.16.0/bin/yarn

I have tried this: 
https://stackoverflow.com/questions/46340759/cannot-find-module-yarn-even-though-yarn-is-installed

and attempted other installs as found here: 
https://classic.yarnpkg.com/lang/en/docs/install/#mac-stable

here is the error: 

```
Syntax Error: Expected ":" or blank space but "\n" found.
    at eE (/Users/bonepile/.yarn/releases/yarn-3.1.1.cjs:196:1124)
    at ZDe (/Users/bonepile/.yarn/releases/yarn-3.1.1.cjs:196:9763)
    at eRe (/Users/bonepile/.yarn/releases/yarn-3.1.1.cjs:395:16)
    at rRe (/Users/bonepile/.yarn/releases/yarn-3.1.1.cjs:395:114)
    at Ii (/Users/bonepile/.yarn/releases/yarn-3.1.1.cjs:395:490)
    at Ke.setupResolutions (/Users/bonepile/.yarn/releases/yarn-3.1.1.cjs:441:481)
    at async Function.find (/Users/bonepile/.yarn/releases/yarn-3.1.1.cjs:438:1533)
    at async wC.execute (/Users/bonepile/.yarn/releases/yarn-3.1.1.cjs:486:14589)
    at async wC.validateAndExecute (/Users/bonepile/.yarn/releases/yarn-3.1.1.cjs:337:620)
    at async oo.run (/Users/bonepile/.yarn/releases/yarn-3.1.1.cjs:351:1846)
```

**Comment by jrartiga** [comment]
@benebess any fix so far?

**Comment by 0x00ffDa** [comment]
Stumbled across this while investigating the same error (but different yarn version) 
```Syntax Error: Expected ":" or blank space but "\n" found.```
```      at vl (/home/parallels/.cache/node/corepack/yarn/3.4.1/yarn.js:45:1124)```
... and thought maybe this will help others:  

In my case I was using a repo that had apparently been set up with yarn v1. When I ran yarn the first time, it said ```Migrating from Yarn 1```. With a little tweaking, that seemed to be ok, but then I hit the mysterious syntax error above on every yarn execution and I couldn't resolve it. 

While I don't understand the cause of the syntax error, I was able to work around it by reverting the migration changes and switching to an old yarn version, 1.22.19 (and Node 16.19.1 for compatibility with that), to avoid the auto-migration to v2.

**Comment by jdalrymple** [comment]
Running into a similar problem, though:

```
Expected "$", "$'", "$(", "$((", "${", "'", "\"", "\"\"", "\\", or [ \t] but "(" found (line 1, column 46).
    at ki (../.yarn/releases/yarn-3.4.1.cjs:7:3129)
```

When i run a particular yarn script. Same situation, upgrading from yarn 1

**Comment by pvdreamland** [comment]
Running into the same problem

/usr/local/bin/npx nx run member-mobile:run-android

 >  NX   Expected ":" or blank space but "\n" found.



Process finished with exit code 1

**Comment by FiniteLooper** [comment]
I usually use NPM but was working on a project that used yarn an ran into this. I was able to get around this by deleting `yarn.lock` and then running `yarn install` which generated a `.yarnrc.yml` file.

My best guess is that this project is using an older version of yarn and it couldn't deal with this older `yarn.lock` file. Removing it fixed it for me.
