### ISSUE TITLE
Error: EPERM: operation not permitted, uv_cwd  attempting to install Yarn on MacBook/M1/Monterey

### ISSUE THREAD

**Issue by mungbeans** [yarnpkg/yarn#8787]
I'm attempting to install Yarn on a new MacBook M1 Pro with Monterey.

When executing: npm install --global yarn

code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/yarn
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/yarn'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/yarn'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/yarn'
npm ERR! }

Running sudo npm install --global yarn didn't fix it, after doing sudo chmod -R 777 path/to/folders in error message
I tried sudo npm install --global yarn again, but now am getting this error: 

Error: EPERM: operation not permitted, uv_cwd
    at process.wrappedCwd (node:internal/bootstrap/switches/does_own_process_state:126:28)
    at process.cwd (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:10:19)
    at new Config (/usr/local/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:92:19)
    at new Npm (/usr/local/lib/node_modules/npm/lib/npm.js:50:19)
    at module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:23:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:2:25)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

**Comment by mungbeans** [comment]
Terminating all console windows and rebooting the Mac fixed it
