### ISSUE TITLE
yarn build error

### ISSUE THREAD

**Issue by youruglyrat12** [yarnpkg/yarn#8815]
so I was trying to build an app so I used this video for reference. https://www.youtube.com/watch?v=3IZid6lBMJM in the video, the creator of the video seems to be able to run all commands. But for me I could run all the commands but not the last command which was "yarn build" whenever I used yarn build I get this 
```
homebrew-popcorn-desktop % yarn build
yarn run v1.22.18
$ gulp build
(node:6396) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6396) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:6396) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:6396) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:6396) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:6396) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
Error: No platform to build!
    at new NwBuilder (/opt/homebrew/Library/Taps/popcorn-official/homebrew-popcorn-desktop/node_modules/nw-builder/lib/index.js:100:15)
    at Object.<anonymous> (/opt/homebrew/Library/Taps/popcorn-official/homebrew-popcorn-desktop/gulpfile.js:170:12)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at requireOrImport (/opt/homebrew/Library/Taps/popcorn-official/homebrew-popcorn-desktop/node_modules/gulp-cli/lib/shared/require-or-import.js:19:11)
    at execute (/opt/homebrew/Library/Taps/popcorn-official/homebrew-popcorn-desktop/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:37:3)
error Command failed with exit code 1
```
. Can someone please help? thank you.

**Comment by merceyz** [comment]
That doesn't look like a Yarn error, we don't control what the `build` script does.
