### ISSUE TITLE
when I yarn install  node:assert:123 throw new AssertionError(obj) yarn version is 1.22.17

### ISSUE THREAD

**Issue by LoSoleil** [yarnpkg/yarn#8928]
⠁ node:assert:123
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: 8726 == 0
    at ClientRequest.onConnect (C:\Users\tl\AppData\Roaming\nvm\v16.16.0\node_modules\yarn\lib\cli.js:152352:14)
    at Object.onceWrapper (node:events:642:26)
    at ClientRequest.emit (node:events:527:28)
    at Socket.socketOnData (node:_http_client:534:11)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 8726,
  expected: 0,
  operator: '=='
}

**Comment by lmaddio** [comment]
I'm getting a similar error on Mac
```
yarn install v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[##############----------------------------------------------------------------------------------------------------] 299/2444assert.js:118
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: 415 == 0
    at ClientRequest.onConnect (/usr/local/Cellar/yarn/1.22.19/libexec/lib/cli.js:152359:14)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketOnData (_http_client.js:553:11)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 415,
  expected: 0,
  operator: '=='
}
```

**Comment by andre-w2** [comment]
yarn install v1.22.19
node:assert:125
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: 12 == 0
    at ClientRequest.onConnect (C:\Users\Andrew\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:152359:14)
    at Object.onceWrapper (node:events:629:26)
    at ClientRequest.emit (node:events:514:28)
    at Socket.socketOnData (node:_http_client:575:11)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:343:12)
    at readableAddChunk (node:internal/streams/readable:316:9)
    at Readable.push (node:internal/streams/readable:253:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 12,
  expected: 0,
  operator: '=='
}

Node.js v20.5.1

help me!

**Comment by cetindogu** [comment]
[2/4] Fetching packages...
[---------------------------------------------------------------------------------------------] 0/512node:assert:125
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: 23 == 0
    at ClientRequest.onConnect (C:\Users\cetin.dogu\AppData\Roaming\nvm\v18.16.1\node_modules\yarn\lib\cli.js:152359:14)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketOnData (node:_http_client:582:11)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 23,
  expected: 0,
  operator: '=='
}

Node.js v18.16.1
Error: Command failed: yarn add react-native --exact
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at run (C:\Users\cetin.dogu\AppData\Roaming\nvm\v18.16.1\node_modules\react-native-cli\index.js:294:5)
    at createProject (C:\Users\cetin.dogu\AppData\Roaming\nvm\v18.16.1\node_modules\react-native-cli\index.js:249:3)
    at init (C:\Users\cetin.dogu\AppData\Roaming\nvm\v18.16.1\node_modules\react-native-cli\index.js:200:5)
    at Object.<anonymous> (C:\Users\cetin.dogu\AppData\Roaming\nvm\v18.16.1\node_modules\react-native-cli\index.js:153:7)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 11588,
  stdout: null,
  stderr: null
}
Command `yarn add react-native --exact` failed.
