### ISSUE TITLE
YAMLException: end of the stream or a document separator is expected at line 1, column 1

### ISSUE THREAD

**Issue by ElegantCrab** [yarnpkg/yarn#8946]
OS: Windows 11 64 bits.

No matter how i install it whenever I run

```
npm install -g yarn
```

And I have the yarn folder on my PATH, this happens:

C:\Windows\system32>yarn --version
YAMLException: end of the stream or a document separator is expected at line 1, column 1:

    ^
    at generateError (C:\Users\G3\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:126022:10)
    at throwError (C:\Users\G3\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:126028:9)
    at readDocument (C:\Users\G3\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:127394:5)
    at loadDocuments (C:\Users\G3\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:127430:5)
    at load (C:\Users\G3\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:127451:19)
    at safeLoad (C:\Users\G3\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:127473:10)
    at parse (C:\Users\G3\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:63707:18)
    at module.exports.exports.default (C:\Users\G3\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:63258:96)
    at loadRcFile (C:\Users\G3\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:56992:58)
    at C:\Users\G3\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:56966:14

I have tried many fixes but none work. I'm thinking about reformatting my computer.

**Comment by ElegantCrab** [comment]
Fixed. Dunno why but I had a ```yarnrc.yml``` on C:\Users\<username> .

Deleting the file solved the issue
