### ISSUE TITLE
Error: https://registry.yarnpkg.com/@fullcalendar%2fdaygrid: Not found

### ISSUE THREAD

**Issue by aleblanc** [yarnpkg/yarn#8949]
Hello,

The issue : 
```
Run cd client && yarn install
yarn install v1.22.19
[1/4] Resolving packages...
warning Resolution field "ejs@3.1.7" is incompatible with requested version "ejs@^2.6.1"
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@fullcalendar/daygrid/-/daygrid-5.11.0.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/runner/work/waystone/waystone/client/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
```

error log : 

```
Yarn version: 
  1.22.5

Node version: 
  14.19.3

Platform: 
  darwin x64

Trace: 
  Error: https://registry.yarnpkg.com/@fullcalendar%2fdaygrid: Not found
      at Request.params.callback [as _callback] (/usr/local/Cellar/yarn/1.22.5/libexec/lib/cli.js:66988:18)
      at Request.self.callback (/usr/local/Cellar/yarn/1.22.5/libexec/lib/cli.js:140749:22)
      at Request.emit (events.js:400:28)
      at Request.<anonymous> (/usr/local/Cellar/yarn/1.22.5/libexec/lib/cli.js:141721:10)
      at Request.emit (events.js:400:28)
      at IncomingMessage.<anonymous> (/usr/local/Cellar/yarn/1.22.5/libexec/lib/cli.js:141643:12)
      at Object.onceWrapper (events.js:519:28)
      at IncomingMessage.emit (events.js:412:35)
      at endReadableNT (internal/streams/readable.js:1333:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)
```
This problem did not exist 3 days ago

**Comment by plush-mesh** [comment]
> The problem is now resolved the package was passed to private : [fullcalendar/fullcalendar#7332](https://github.com/fullcalendar/fullcalendar/issues/7332)

No, it's not. We have started experiencing the problem with other packages too.

https://status.npmjs.org/
![image](https://github.com/yarnpkg/yarn/assets/16272113/6434c8b6-c72b-41ea-b7d9-77b3170dcd32)
