### ISSUE TITLE
Yarn 3.5.1 | YN0001: │ RequestError: Socket connection timeout

### ISSUE THREAD

**Issue by ZehuaZhang** [yarnpkg/yarn#8953]
yarn version `3.5.1`

running `yarn`

```
➤ YN0000: ┌ Resolution step
➤ YN0001: │ RequestError: Socket connection timeout
    at ClientRequest.<anonymous> (/Users/===/.yarn/releases/yarn-3.5.1.cjs:195:14340)
    at Object.onceWrapper (node:events:626:26)
    at ClientRequest.emit (node:events:523:35)
    at o.emit (/Users/===/.yarn/releases/yarn-3.5.1.cjs:190:90286)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:511:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at new NodeError (node:internal/errors:399:5)
    at internalConnectMultiple (node:net:1099:20)
    at Timeout.internalConnectMultipleTimeout (node:net:1638:3)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7)
```

**Comment by Baukaalm** [comment]
I have some problem
