### ISSUE TITLE
yarn, Error: Invalid URL

### ISSUE THREAD

**Issue by Sunry6** [yarnpkg/yarn#8998]
Arguments: 
  /root/.nvs/node/8.17.0/arm64/bin/node /root/.nvs/node/8.17.0/arm64/bin/yarn

PATH: 
  /root/.nvs/node/8.17.0/arm64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/alidata1/admin/jenkins/2.375/jdk/bin

Yarn version: 
  1.22.17

Node version: 
  8.17.0

Platform: 
  linux arm64

Trace: 
  Error: Invalid URL
      at module.exports.module.exports (/root/.nvs/node/8.17.0/arm64/lib/node_modules/yarn/lib/cli.js:71862:9)
      at urlParts (/root/.nvs/node/8.17.0/arm64/lib/node_modules/yarn/lib/cli.js:31657:75)
      at /root/.nvs/node/8.17.0/arm64/lib/node_modules/yarn/lib/cli.js:31789:29
      at Array.find (native)
      at NpmRegistry.requestNeedsAuth (/root/.nvs/node/8.17.0/arm64/lib/node_modules/yarn/lib/cli.js:31786:59)
      at NpmRegistry.<anonymous> (/root/.nvs/node/8.17.0/arm64/lib/node_modules/yarn/lib/cli.js:31732:81)
      at Generator.next (<anonymous>)
      at step (/root/.nvs/node/8.17.0/arm64/lib/node_modules/yarn/lib/cli.js:310:30)
      at /root/.nvs/node/8.17.0/arm64/lib/node_modules/yarn/lib/cli.js:328:14
      at new Promise (<anonymous>)

**Comment by Sunry6** [comment]
Why did this error occur? Invalid url Indicates which url? please help me

**Comment by Husbin** [comment]
I meet the same issue, did you solve it?
