### ISSUE TITLE
Error: EACCES: permission denied, open '/app/.yarnrc'

### ISSUE THREAD

**Issue by bxdadwhal** [yarnpkg/yarn#9002]
My docker file looks like this :- 
dockerfile: |
      FROM node:lts
      WORKDIR /app
      COPY . .
      RUN find /app -type f -name .yarnrc -execdir chmod 644 {} \;
      RUN ls -la
      WORKDIR /app/destiny/
      RUN ls -la
      RUN rm -rf node_modules
      RUN yarn install
      RUN ls -la node_modules
      RUN yarn build
      RUN ls -la
      ENV HOST 0.0.0.0
      EXPOSE 3000
      CMD ["sh", "-c", "yarn dev"]

I was getting this error :- 
![image](https://github.com/yarnpkg/yarn/assets/52848626/da3ce2ba-a706-46ec-9709-34f033a39092)
 
Then I updated my docker file like this :- 
dockerfile: |
      FROM node:lts
      WORKDIR /app
      COPY . .
      RUN find /app -type f -name .yarnrc -execdir chmod 644 {} \;
      RUN ls -la
      WORKDIR /app/destiny/
      RUN chmod -R 644 .
      RUN chmod 644 .*
      RUN ls -la
      RUN rm -rf node_modules
      RUN yarn install
      RUN ls -la node_modules
      RUN yarn build
      RUN ls -la
      ENV HOST 0.0.0.0
      EXPOSE 3000
      CMD ["sh", "-c", "yarn dev"]

Now i am getting this error :- 
![image](https://github.com/yarnpkg/yarn/assets/52848626/9097952d-20be-4be1-88d6-6dc5245c526e)

Not able to skip this error :- ( React UI container is not coming up and going in crashloopbackoff )

Error: EACCES: permission denied, open '/app/.yarnrc'
at Object.openSync (node:fs:603:3)
at readFileSync (node:fs:471:35)
at /opt/yarn-v1.22.19/lib/cli.js:97395:58
at Array.map (<anonymous>)
at parseRcPaths (/opt/yarn-v1.22.19/lib/cli.js:97393:78)
at Object.findRc (/opt/yarn-v1.22.19/lib/cli.js:97407:10)
at getRcConfigForCwd (/opt/yarn-v1.22.19/lib/cli.js:56965:74)
at /opt/yarn-v1.22.19/lib/cli.js:88756:56
at Generator.next (<anonymous>)
at step (/opt/yarn-v1.22.19/lib/cli.js:310:30)

**Comment by jagretti** [comment]
Any news about this error? I'm seeing the exact same error, and can't find the root cause of it
