### ISSUE TITLE
Yarn not installing dependencies

### ISSUE THREAD

**Issue by ahmadqayyum7** [yarnpkg/yarn#9083]
I am trying to install dependencies of a project but when I use the command `yarn install` I get the below error.

```
[3/5] Fetching packages...
error Error: https://registry.yarnpkg.com/@qureos/qureos-components/-/qureos-components-0.1.7.tgz: Request failed "404 Not Found"
    at ResponseError.ExtendableBuiltin (C:\Users\Ahmad\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:696:66)
    at new ResponseError (C:\Users\Ahmad\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:802:124)
    at Request.<anonymous> (C:\Users\Ahmad\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:66750:16)
    at Request.emit (node:events:519:28)
    at module.exports.Request.onRequestResponse (C:\Users\Ahmad\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:142287:10)
    at ClientRequest.emit (node:events:519:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:698:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:540:22)
    at TLSSocket.emit (node:events:519:28)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

I have even tried using the `npm install` command but I am getting the same above error. When I access the URL given in the error, it opens. Don't know what the problem is.

**Comment by deBoisvilliersJonathanFASST** [comment]
yarn* install not npm install
