### ISSUE TITLE
An unexpected error occurred: "https://registry.yarnpkg.com/fs-constants/-/fs-constants-1.0.0.tgz: Request failed "304 Not Modified"".

### ISSUE THREAD

**Issue by Vsinghal339-source** [yarnpkg/yarn#9119]
npm cache clean --force # collapsed multi-line command
npm WARN using --force Recommended protections disabled.
yarn global v1.22.[19](https://gitlab.com/cube.technologies/cube/-/jobs/8661176688#L19)
[1/4] Resolving packages...
(node:26) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/fs-constants/-/fs-constants-1.0.0.tgz: Request failed \"304 Not Modified\"".
info If you think this is a bug, please open a bug report with the information provided in "/usr/local/share/.config/yarn/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1

**Comment by Vsinghal339-source** [comment]
@arcanis @Embraser01

**Comment by vaibhavgupta1998** [comment]
Facing the same issue. 
Along with this csssec is also not working
error https://registry.npmjs.org/fs-constants/-/fs-constants-1.0.0.tgz: Request failed "304 Not Modified"
error Error: https://registry.npmjs.org/cssesc/-/cssesc-3.0.0.tgz: Request failed "304 Not Modified"
    at ResponseError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.22/libexec/lib/cli.js:696:66)
    at new ResponseError (/usr/local/Cellar/yarn/1.22.22/libexec/lib/cli.js:802:124)
    at Request.<anonymous> (/usr/local/Cellar/yarn/1.22.22/libexec/lib/cli.js:66750:16)
    at Request.emit (node:events:520:28)
    at module.exports.Request.onRequestResponse (/usr/local/Cellar/yarn/1.22.22/libexec/lib/cli.js:142287:10)
    at ClientRequest.emit (node:events:520:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:542:22)
    at TLSSocket.emit (node:events:520:28)

**Comment by shailendrasingh** [comment]
Facing the same issue. 


<img width="815" alt="Image" src="https://github.com/user-attachments/assets/5397bd38-cec8-4438-9c80-bf8b30458096" />

**Comment by shivaprasadks** [comment]
Facing the same issue.
Using Yarn version: 1.22.22

```
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
lerna ERR! yarn install --mutex network:42424 --non-interactive stderr:
warning Waiting for the other yarn instance to finish (612)
error Error: https://registry.yarnpkg.com/emojis-list/-/emojis-list-3.0.0.tgz: Request failed "304 Not Modified"
    at ResponseError.ExtendableBuiltin (/opt/hostedtoolcache/node/16.20.2/x64/lib/node_modules/yarn/lib/cli.js:696:66)
    at new ResponseError (/opt/hostedtoolcache/node/16.20.2/x64/lib/node_modules/yarn/lib/cli.js:802:124)
    at Request.<anonymous> (/opt/hostedtoolcache/node/16.20.2/x64/lib/node_modules/yarn/lib/cli.js:667[50](https://github.com/ClearTax/filing-sketch/actions/runs/12359796101/job/34493301210#step:5:51):16)
    at Request.emit (node:events:513:28)
    at Request.module.exports.Request.onRequestResponse
```
