### ISSUE TITLE
Sub dependency cannot be found during installation on Windows

### ISSUE THREAD

**Issue by AntJanus** [yarnpkg/yarn#931]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
Yarn fails on node module installation because it cannot find a dependency for a dependency

**If the current behavior is a bug, please provide the steps to reproduce.**
Running `yarn` for my current package.json.  My package.json is REALLY long so I don't necessarily want to post it but if it's necessary, I definitely will. I redacted some personal data (machine username and project name).

Here's the error output:

``` bash
[4/4] Building fresh packages...
[1/4] ⡀ node-sass
[2/4] ⡀ closure-util
[3/4] ⡀ phantomjs-prebuilt
[-/4] ⡀ waiting...
error D:\Projects\[redacted]\node_modules\closure-util: Command failed.
Exit code: 1
Command: C:\WINDOWS\system32\cmd.exe
Arguments: /d /s /c node ./bin/closure-util.js update
Directory: D:\Projects\[redacted]\node_modules\closure-util
Output:
module.js:457
    throw err;
    ^

Error: Cannot find module 'aws-sign2'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Projects\[redacted]\node_modules\get-down\node_modules\request\request.js:11:11)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at SpawnError (C:\Users\[redacted]\AppData\Roaming\npm\node_modules\yarn\lib\errors.js:18:1)
    at ChildProcess.proc.on.code (C:\Users\[redacted]\AppData\Roaming\npm\node_modules\yarn\lib\util\child.js:107:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**What is the expected behavior?**
Installation finishes. 

**Please mention your node.js, yarn and operating system version.**

Node version: 6.5.0
OS: Windows 10 (latest updates)

**Comment by busches** [comment]
Can you reproduce this with `yarn@latest`? If yes, can you please post a `package.json` that recreates the error?

**Comment by AntJanus** [comment]
@busches sure thing! I installed it so now it's yarn version `0.17.10` and my Node version is currently `6.9.1`. It looks like I'm getting a different error now so I guess I'll file a different issue? PhantomJS seems to be unable to be installed

**Comment by bestander** [comment]
@AntJanus, could you send your package.json if you still have problems with the installation?
I'll close the task for now as I can't act on it without repro steps
