### ISSUE TITLE
RequestManager should handle gzip response

### ISSUE THREAD

**Issue by edba** [yarnpkg/yarn#945]
Currently RequestManager doesn't have support to handle a gzip response. If for some reason we get a gzip response from a server this will result on a unparsable response body and will fail the "yarn install".

```
error TypeError: Cannot use 'in' operator to search for '1.1.0' in undefined
    at /Users/edba/.nvm/versions/node/v6.3.1/lib/node_modules/yarn/lib/resolvers/registries/npm-resolver.js:62:24
    at next (native)
    at step (/Users/edba/.nvm/versions/node/v6.3.1/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/edba/.nvm/versions/node/v6.3.1/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (/Users/edba/.nvm/versions/node/v6.3.1/lib/node_modules/yarn/node_modules/core-js/library/modules/es6.promise.js:191:7)
    at /Users/edba/.nvm/versions/node/v6.3.1/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at Function.findVersionInRegistryResponse (/Users/edba/.nvm/versions/node/v6.3.1/lib/node_modules/yarn/lib/resolvers/registries/npm-resolver.js:72:7)
    at /Users/edba/.nvm/versions/node/v6.3.1/lib/node_modules/yarn/lib/resolvers/registries/npm-resolver.js:89:34
    at next (native)
    at step (/Users/edba/.nvm/versions/node/v6.3.1/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command
```

**Comment by kdzwinel** [comment]
While comparing network patterns between yarn and npm I found out that [yarn downloads twice the data](https://twitter.com/kdzwinel/status/785950940629118976) while making same requests (npm duplicates some requests, but number of unique requests is ~the same). From what I see, all metadata responses (e.g. `https://registry.npmjs.org/request`) are uncompressed for yarn and this bug seems to be the reason for missing `'Accept-Encoding': 'gzip'` request header.
I just wanted to note that fixing it may significantly improve yarn's network performance.
